/* embedded/block-4-mcu-esp32/manifest.js — per-module маніфест Модуля 4. Складає scripts/bookbuild.js
   (histories[]/extras[] ВИВОДЯТЬСЯ з topics[]). Нумерація — М.Р.Т. */
(window.__MODREG__ = window.__MODREG__ || []).push({
  n: 4, slug: "block-4-mcu-esp32", title: "Мікроконтролер і прошивка: ESP32",
  chapters: [
    { n: 1, title: "Анатомія мікроконтролера й архітектура ESP32", dir: "block-4-mcu-esp32/mcu-esp32", main: "mcu-esp32.md", status: "done",
      scope: "Ядро + пам'ять + периферія на одному чіпі; регістри периферії як «вікна» керування залізом; двоядерність і вбудоване радіо ESP32; чим відрізняється від простого 8-біт МК.",
      topics: [
        { mrt: "4.1.1", title: "Мікроконтролер: комп'ютер на одному чіпі (проти мікропроцесора)", status: "done" },
        { mrt: "4.1.2", title: "Складові МК: ядро, пам'ять (Flash/SRAM), периферія", status: "done" },
        { mrt: "4.1.3", title: "Регістри периферії: як код «торкається» заліза (memory-mapped IO)", status: "done" },
        { mrt: "4.1.4", title: "Тактування й живлення МК (джерела такту; режими сну)", status: "done" },
        { mrt: "4.1.5", title: "Архітектура ESP32: два ядра, радіо, багата периферія", status: "done" },
        { mrt: "4.1.6", title: "ESP32 проти простого 8-біт МК (коли більша потужність важлива)", status: "done" },
        { mrt: "4.1.7", title: "Сімейство ESP32 (S2/S3/C3/C6): що обирати", status: "done" },
        { mrt: "4.1.8", title: "Причини reset: power-on, brownout, watchdog, вихід із deep-sleep", status: "done" },
        { kind: "hist", file: "hist-first-mcu.md", at: "chapter", status: "done", title: "Перший мікроконтролер: TMS1000 / Intel, 1971" },
        { kind: "hist", file: "hist-esp.md", at: "4.1.5", status: "done", title: "Як дешевий Wi-Fi чип підкорив аматорів: ESP8266 → ESP32" },
        { kind: "hist", file: "hist-8051.md", at: "4.1.6", status: "done", title: "Intel 8051: архітектура 1980 року, яка досі всюди" },
        { kind: "hist", file: "hist-riscv.md", at: "4.1.7", status: "done", title: "Чому виробники МК мігрують на RISC-V" },
        { kind: "comp", file: "../../../components/comms/esp32-antenna/esp32-antenna.md", at: "4.1.2", status: "done", title: "Антена: PCB-доріжка, керамічна, IPEX-роз'єм" },
        { kind: "comp", file: "../../../components/comms/wroom-module/wroom-module.md", at: "4.1.2", status: "done", title: "Модуль WROOM/WROVER-класу: чому чип ховають під екран" },
        { kind: "proj", file: "proj-reg-access.md", at: "4.1.3", status: "done", title: "Доступ до регістрів: read-modify-write, set/clear-регістри, бітові поля" },
        { kind: "comp", file: "comp-crystal.md", at: "4.1.4", status: "done", title: "Кварц на платі: навантажувальні конденсатори, ppm, чому 40 МГц" },
        { kind: "math", file: "math-clock-tree.md", at: "4.1.4", status: "done", title: "Дерево тактування: PLL і дільники, з 40 МГц у 240 МГц" },
        { kind: "comp", file: "comp-devkit.md", at: "4.1.5", status: "done", title: "DevKit-плата ESP32 зсередини: USB-UART міст, LDO, кнопки EN/BOOT" },
        { kind: "math", file: "math-benchmarks.md", at: "4.1.6", status: "done", title: "Мегагерци проти DMIPS: як чесно порівнювати продуктивність" },
        { kind: "comp", file: "comp-brownout.md", at: "4.1.8", status: "done", title: "Супервізор живлення і brownout-детектор" }
      ] },
    { n: 2, title: "Тулчейн: як код стає прошивкою", dir: "block-4-mcu-esp32/toolchain", main: "toolchain.md", status: "done",
      scope: "Компіляція → лінкування → образ → прошивка у Flash; bootloader і послідовність скидання; що виконується до твоєї точки входу; «голе залізо» проти фреймворку.",
      topics: [
        { mrt: "4.2.1", title: "Від тексту до машинного коду: що таке компіляція", status: "done" },
        { mrt: "4.2.2", title: "Препроцесор, компілятор, асемблер (стадії)", status: "done" },
        { mrt: "4.2.3", title: "Лінкування: збираємо все докупи (об'єктні файли, бібліотеки, адреси)", status: "done" },
        { mrt: "4.2.4", title: "Образ прошивки й карта пам'яті (секції .text/.data/.bss)", status: "done" },
        { mrt: "4.2.5", title: "Прошивка у Flash: як код потрапляє в чіп (по USB/UART)", status: "done" },
        { mrt: "4.2.6", title: "Завантажувач (bootloader) і reset-послідовність (що до main())", status: "done" },
        { mrt: "4.2.7", title: "«Голе залізо» vs фреймворк (Arduino/IDF): ціна абстракції", status: "done" },
        { mrt: "4.2.8", title: "Відлагодження: Serial, JTAG/SWD (інструменти)", status: "done" },
        { mrt: "4.2.9", title: "Тестування прошивки: юніт-тести на хості, симуляція периферії, тест на залізі", status: "done" },
        { mrt: "4.2.10", title: "Ворнінги й статичний аналіз: небезпечні кути C", status: "done" },
        { mrt: "4.2.11", title: "C-рантайм на голому залізі: що виконується до main(), newlib", status: "done" },
        { kind: "hist", file: "hist-grace-hopper.md", at: "chapter", status: "done", title: "Грейс Гоппер: перший компілятор і перший «баг»" },
        { kind: "hist", file: "hist-gcc.md", at: "4.2.2", status: "done", title: "Річард Столмен і GCC: вільний компілятор для вбудованої розробки" },
        { kind: "hist", file: "hist-arduino.md", at: "4.2.7", status: "done", title: "Arduino: Іврея, викладачі IDII і Wiring" },
        { kind: "proj", file: "proj-optimizer.md", at: "4.2.2", status: "done", title: "Що робить оптимізатор: -O0 проти -O2, інлайн" },
        { kind: "math", file: "math-image-checksums.md", at: "4.2.4", status: "done", title: "Контрольні суми образу: від байтової суми до хешів" },
        { kind: "proj", file: "proj-firmware-version.md", at: "4.2.4", status: "done", title: "Версія всередині прошивки: git-хеш у образі" },
        { kind: "proj", file: "proj-map-file.md", at: "4.2.4", status: "done", title: "Читання map-файлу: хто з'їв Flash і RAM" },
        { kind: "proj", file: "proj-size-opt.md", at: "4.2.4", status: "done", title: "-Os, gc-sections і LTO: стиснути образ, не зламавши" },
        { kind: "comp", file: "../../../components/interfaces/usb-uart-bridge/usb-uart-bridge.md", at: "4.2.5", status: "done", title: "USB-UART адаптер (CP210x/CH340/FT232-класи)" },
        { kind: "proj", file: "proj-flash-protocol.md", at: "4.2.5", status: "done", title: "Як esptool розмовляє з ROM-завантажувачем: SLIP-кадри, stub" },
        { kind: "comp", file: "comp-strapping.md", at: "4.2.6", status: "done", title: "Strapping-піни і схема авто-прошивки: GPIO0, EN, DTR/RTS" },
        { kind: "comp", file: "comp-debug-probes.md", at: "4.2.8", status: "done", title: "Відлагоджувальні зонди (J-Link/ST-Link/ESP-Prog-класи)" },
        { kind: "proj", file: "proj-binary-logging.md", at: "4.2.8", status: "done", title: "Бінарне логування (defmt-клас): у чип летять самі байти" },
        { kind: "proj", file: "proj-logging.md", at: "4.2.8", status: "done", title: "Логування як інженерна система: рівні, мітки часу, кільцевий лог" },
        { kind: "proj", file: "proj-emulators.md", at: "4.2.9", status: "done", title: "Емулятори МК: QEMU, Renode і Wokwi" }
      ] },
    { n: 3, title: "Постійні дані: Flash-розділи, NVS і файлові системи", dir: "block-4-mcu-esp32/persistent-storage", main: "persistent-storage.md", status: "done",
      scope: "Flash зсередини (сторінки, сектори, стирання); зношування і wear leveling; таблиця розділів ESP32; NVS «ключ–значення»; файлові системи LittleFS/SD; цілісність при втраті живлення; два OTA-слоти.",
      topics: [
        { mrt: "4.3.1", title: "Навіщо зберігати: конфігурація, калібрування, логи", status: "done" },
        { mrt: "4.3.2", title: "Flash зсередини: сторінки, сектори, стирання перед записом", status: "done" },
        { mrt: "4.3.3", title: "Зношування комірок і wear leveling", status: "done" },
        { mrt: "4.3.4", title: "Таблиця розділів (partition table) ESP32", status: "done" },
        { mrt: "4.3.5", title: "NVS: сховище «ключ–значення»", status: "done" },
        { mrt: "4.3.6", title: "Файлові системи на Flash: LittleFS/SPIFFS; SD-картка", status: "done" },
        { mrt: "4.3.7", title: "Цілісність: втрата живлення посеред запису", status: "done" },
        { mrt: "4.3.8", title: "Два OTA-слоти: механіка подвійного образу", status: "done" },
        { mrt: "4.3.9", title: "Secure boot і шифрування Flash: захист прошивки й даних", status: "done" },
        { kind: "hist", file: "hist-flash.md", at: "chapter", status: "done", title: "Фудзіо Масуока і Flash: пам'ять, названа за спалахом" },
        { kind: "hist", file: "hist-fat.md", at: "4.3.6", status: "done", title: "FAT: файлова система 1977 року, що живе в кожній картці" },
        { kind: "proj", file: "proj-flash-ring-log.md", at: "4.3.1", status: "done", title: "Кільцевий лог у Flash: писати логи, не вбиваючи сектори" },
        { kind: "comp", file: "../../../components/memory/fram/fram.md", at: "4.3.3", status: "done", title: "FRAM (MB85-клас): пам'ять без зношування" },
        { kind: "math", file: "math-endurance.md", at: "4.3.3", status: "done", title: "Арифметика ресурсу: цикли стирання × wear leveling" },
        { kind: "proj", file: "proj-partition-table.md", at: "4.3.4", status: "done", title: "Власна таблиця розділів: CSV, зміщення, вирівнювання на 4 КіБ" },
        { kind: "proj", file: "proj-nvs-internals.md", at: "4.3.5", status: "done", title: "NVS зсередини: журнал записів, сторінки, збирання сміття" },
        { kind: "comp", file: "../../../components/memory/sd-card-module/sd-card-module.md", at: "4.3.6", status: "done", title: "SD-модуль: тримач картки, зсув рівнів, підключення по SPI" },
        { kind: "proj", file: "proj-atomic-config.md", at: "4.3.7", status: "done", title: "Атомарне оновлення конфігурації: два слоти + лічильник + сума" },
        { kind: "math", file: "math-hash-signature.md", at: "4.3.9", status: "done", title: "Хеш і цифровий підпис: математика ланцюга довіри" }
      ] },
    { n: 4, title: "GPIO глибоко", dir: "block-4-mcu-esp32/gpio", main: "gpio.md", status: "done",
      scope: "Push-pull і open-drain; логічні пороги входу; підтяжки й вибір номіналу; дребезг і його придушення; навантажувальна здатність і захист ніжки.",
      topics: [
        { mrt: "4.4.1", title: "Ніжка на рівні заліза: вихід push-pull (два транзистори)", status: "done" },
        { mrt: "4.4.2", title: "Open-drain і навіщо він (wired-AND; зсув рівнів)", status: "done" },
        { mrt: "4.4.3", title: "Логічні пороги входу", status: "done" },
        { mrt: "4.4.4", title: "Плаваючий пін і підтяжки", status: "done" },
        { mrt: "4.4.5", title: "Дребезг контактів і його придушення (апаратно/програмно)", status: "done" },
        { mrt: "4.4.6", title: "Навантажувальна здатність і захист ніжки (source/sink ліміти)", status: "done" },
        { mrt: "4.4.7", title: "GPIO у прошивці: регістри й маски (швидкодія)", status: "done" },
        { mrt: "4.4.8", title: "Абстрактна модель «модуля»: підключення дискретного давача", status: "done" },
        { kind: "hist", file: "hist-relay-bounce.md", at: "4.4.5", status: "done", title: "Дребезг старший за електроніку: реле, АТС Строуджера" },
        { kind: "math", file: "math-pullup-value.md", at: "4.4.4", status: "done", title: "Чому підтяжка саме 10 кОм: струм витоку, шум, споживання" },
        { kind: "comp", file: "comp-tact-button.md", at: "4.4.5", status: "done", title: "Тактова кнопка зсередини: мембрана, дребезг, RC-придушення" },
        { kind: "proj", file: "proj-debounce.md", at: "4.4.5", status: "done", title: "Антидребезг у коді: лічильник, мітка часу, автомат" },
        { kind: "math", file: "math-pin-budget.md", at: "4.4.6", status: "done", title: "Бюджет ніжки й порту: сумарний струм, резистор світлодіода, запас" },
        { kind: "proj", file: "proj-bitbang.md", at: "4.4.7", status: "done", title: "Біт-бенгінг: протокол на голих регістрах і ціна тактів" },
        { kind: "comp", file: "../../../components/interfaces/gpio-expander/gpio-expander.md", at: "4.4.8", status: "done", title: "Розширювачі GPIO (PCF8574/MCP23017-класи)" },
        { kind: "proj", file: "proj-key-matrix.md", at: "4.4.8", status: "done", title: "Матриця кнопок 4×4: сканування, ghost-натискання, діоди" }
      ] },
    { n: 5, title: "Переривання", dir: "block-4-mcu-esp32/interrupts", main: "interrupts.md", status: "done",
      scope: "Подія → контролер переривань → обробник; пріоритети, вектор, латентність; чому ISR коротка; volatile, атомарність, гонки даних, критичні секції.",
      topics: [
        { mrt: "4.5.1", title: "Переривання: реагувати на подію вмить (проти опитування)", status: "done" },
        { mrt: "4.5.2", title: "Як це працює: контролер переривань і вектор (збереження контексту)", status: "done" },
        { mrt: "4.5.3", title: "Обробник (ISR): чому коротко (що можна й не можна)", status: "done" },
        { mrt: "4.5.4", title: "Пріоритети й вкладеність (витіснення)", status: "done" },
        { mrt: "4.5.5", title: "volatile: чому компілятор не має «оптимізувати»", status: "done" },
        { mrt: "4.5.6", title: "Атомарність і гонки даних (критичні секції)", status: "done" },
        { mrt: "4.5.7", title: "Polling vs переривання: коли що", status: "done" },
        { kind: "hist", file: "hist-interrupt.md", at: "chapter", status: "done", title: "Винахід переривання: як машини навчилися «відволікатися»" },
        { kind: "hist", file: "hist-apollo.md", at: "4.5.4", status: "done", title: "Apollo 11: аларми 1201/1202, пріоритети, що дозволили посадку" },
        { kind: "hist", file: "hist-therac25.md", at: "4.5.6", status: "done", title: "Therac-25: гонки даних, які вбивали" },
        { kind: "comp", file: "comp-int-pin.md", at: "4.5.1", status: "done", title: "Ніжка INT у периферії (LIS/MPU/BME-класи)" },
        { kind: "proj", file: "proj-spsc-ring.md", at: "4.5.1", status: "done", title: "Кільце «ISR пише — main читає»: SPSC-буфер без блокувань" },
        { kind: "comp", file: "comp-int-controllers.md", at: "4.5.2", status: "done", title: "Контролери переривань: NVIC у Cortex-M проти матриці ESP32" },
        { kind: "proj", file: "proj-deferred-work.md", at: "4.5.3", status: "done", title: "Відкладена робота: прапорець, черга подій, «нижня половина»" },
        { kind: "proj", file: "proj-reentrancy.md", at: "4.5.3", status: "done", title: "Реентерабельність: чому printf, malloc, strtok небезпечні в ISR" },
        { kind: "math", file: "math-latency.md", at: "4.5.4", status: "done", title: "Латентність переривання: такти контексту, джитер, worst case" },
        { kind: "proj", file: "proj-volatile-asm.md", at: "4.5.5", status: "done", title: "Дивимось асемблер: цикл очікування з volatile і без" },
        { kind: "proj", file: "proj-atomics-barriers.md", at: "4.5.6", status: "done", title: "Атомарні типи й бар'єри пам'яті: спільні дані на двох ядрах" },
        { kind: "proj", file: "proj-critical-sections.md", at: "4.5.6", status: "done", title: "Критичні секції: вимкнути переривання чи взяти м'ютекс" },
        { kind: "math", file: "math-isr-budget.md", at: "4.5.7", status: "done", title: "Бюджет переривань: частота × тривалість ISR = частка CPU" }
      ] },
    { n: 6, title: "Таймери й керування часом", dir: "block-4-mcu-esp32/timers", main: "timers.md", status: "done",
      scope: "Лічильники й переповнення; режими захоплення/порівняння; точний час; періодичні події без блокування; чому delay() руйнує чуйність.",
      topics: [
        { mrt: "4.6.1", title: "Таймер-лічильник: апаратний рахівник тактів", status: "done" },
        { mrt: "4.6.2", title: "Період і переповнення (авто-перезавантаження)", status: "done" },
        { mrt: "4.6.3", title: "Режими захоплення й порівняння (input capture / output compare)", status: "done" },
        { mrt: "4.6.4", title: "Точний час: мілі- й мікросекунди (millis/micros зсередини)", status: "done" },
        { mrt: "4.6.5", title: "Чому delay() — зло; неблокуючий час (патерн millis)", status: "done" },
        { mrt: "4.6.6", title: "Періодичні події й планування (фундамент реального часу)", status: "done" },
        { mrt: "4.6.7", title: "Watchdog: таймер, що рятує від зависання", status: "done" },
        { mrt: "4.6.8", title: "RTC і реальний час: годинник, що йде уві сні (epoch, дрейф)", status: "done" },
        { kind: "hist", file: "hist-quartz.md", at: "chapter", status: "done", title: "Кварцовий резонатор: точний час для машин (Маррісон, 1927)" },
        { kind: "hist", file: "hist-y2k-2038.md", at: "4.6.8", status: "done", title: "Y2K і проблема 2038 року: коли переповнюється сам час" },
        { kind: "math", file: "math-prescaler.md", at: "4.6.1", status: "done", title: "Прескалер і дільники: з 80 МГц зробити рівно 1 кГц" },
        { kind: "math", file: "math-unsigned-wrap.md", at: "4.6.2", status: "done", title: "Чому millis() переживає переповнення: модульна арифметика" },
        { kind: "proj", file: "proj-input-capture.md", at: "4.6.3", status: "done", title: "Виміряти імпульс і частоту: input capture на практиці" },
        { kind: "proj", file: "proj-coop-scheduler.md", at: "4.6.5", status: "done", title: "Кооперативний планувальник на millis: список задач із періодами" },
        { kind: "proj", file: "proj-timer-wheel.md", at: "4.6.6", status: "done", title: "Колесо таймерів: тисячі відкладених подій" },
        { kind: "comp", file: "comp-esp32-watchdogs.md", at: "4.6.7", status: "done", title: "Три watchdog-и ESP32: TWDT, RTC WDT, віконний режим" },
        { kind: "proj", file: "proj-watchdog-feed.md", at: "4.6.7", status: "done", title: "Як «годувати» watchdog правильно: чекпойнти задач" },
        { kind: "comp", file: "../../../components/interfaces/rtc-module/rtc-module.md", at: "4.6.8", status: "done", title: "RTC-модуль DS3231-класу: батарейка, термокомпенсація, alarm" },
        { kind: "math", file: "math-calendar-math.md", at: "4.6.8", status: "done", title: "Unix-час і календар: високосні роки, пояси, чому зберігають UTC" }
      ] },
    { n: 7, title: "PWM і ЦАП", dir: "block-4-mcu-esp32/pwm-dac", main: "pwm-dac.md", status: "done",
      scope: "Апаратна генерація PWM таймером; період/шпаруватість/роздільність; частота й наслідки; відновлення аналогу RC-фільтром; справжній ЦАП.",
      topics: [
        { mrt: "4.7.1", title: "ШІМ (PWM): «вдавати» аналог цифровою ніжкою (середнє значення)", status: "done" },
        { mrt: "4.7.2", title: "Як таймер генерує PWM апаратно (період/порівняння)", status: "done" },
        { mrt: "4.7.3", title: "Шпаруватість, роздільність, частота (компроміси)", status: "done" },
        { mrt: "4.7.4", title: "Відновлення аналогу з PWM: RC-фільтр", status: "done" },
        { mrt: "4.7.5", title: "Застосування: яскравість, швидкість, керування потужністю", status: "done" },
        { mrt: "4.7.6", title: "Справжній ЦАП (DAC): пряме аналогове значення (проти PWM)", status: "done" },
        { mrt: "4.7.7", title: "Адресні світлодіоди: ШІМ усередині кожного пікселя", status: "done" },
        { kind: "hist", file: "hist-dimmer.md", at: "chapter", status: "done", title: "Як приборкали яскравість: від реостата до тиристорного диммера й ШІМ" },
        { kind: "comp", file: "comp-buzzer.md", at: "4.7.1", status: "done", title: "Бузер активний і пасивний: ШІМ стає звуком" },
        { kind: "math", file: "math-pwm-spectrum.md", at: "4.7.1", status: "done", title: "Спектр ШІМ: чому «середнє» працює і звідки писк" },
        { kind: "proj", file: "proj-pwm-alignment.md", at: "4.7.2", status: "done", title: "Edge- і center-aligned ШІМ, мертвий час" },
        { kind: "math", file: "math-freq-resolution.md", at: "4.7.3", status: "done", title: "Частота × роздільність = константа: біти з тактів таймера" },
        { kind: "math", file: "math-rc-design.md", at: "4.7.4", status: "done", title: "Проєктування RC-фільтра для ШІМ: зріз, пульсації, час встановлення" },
        { kind: "comp", file: "comp-mosfet-module.md", at: "4.7.5", status: "done", title: "MOSFET-модуль для ШІМ-навантажень: затвор, частота, нагрів" },
        { kind: "proj", file: "proj-gamma.md", at: "4.7.5", status: "done", title: "Гамма-корекція: чому лінійний ШІМ виглядає нелінійно для ока" },
        { kind: "comp", file: "comp-external-dac.md", at: "4.7.6", status: "done", title: "Зовнішній ЦАП (MCP4725-клас, I²C): коли вбудованого бракує" },
        { kind: "comp", file: "comp-ws2812-strip.md", at: "4.7.7", status: "done", title: "Стрічка WS2812-класу: живлення, інжекція, конденсатор і резистор" },
        { kind: "proj", file: "proj-ws2812-timing.md", at: "4.7.7", status: "done", title: "Протокол одного дроту на 800 кГц: біти таймінгами, скидання, кадр" }
      ] },
    { n: 8, title: "Аналого-цифрове перетворення (АЦП)", dir: "block-4-mcu-esp32/adc", main: "adc.md", status: "done",
      scope: "Дискретизація й квантування; біти ↔ мілівольти; опорна напруга; похибки/нелінійність і калібрування; Найквіст і аліасинг.",
      topics: [
        { mrt: "4.8.1", title: "АЦП: перетворити напругу в число (міст аналог→цифра)", status: "done" },
        { mrt: "4.8.2", title: "Дискретизація й квантування (два окремі кроки)", status: "done" },
        { mrt: "4.8.3", title: "Біти й роздільність: скільки мВ в одному кроці (LSB)", status: "done" },
        { mrt: "4.8.4", title: "Опорна напруга (reference): проти чого міряє АЦП", status: "done" },
        { mrt: "4.8.5", title: "Частота дискретизації, Найквіст, аліасинг (класична пастка)", status: "done" },
        { mrt: "4.8.6", title: "Похибки реального АЦП і калібрування (нелінійність АЦП ESP32)", status: "done" },
        { mrt: "4.8.7", title: "Як правильно зчитати сигнал (усереднення; антиаліас; імпеданс)", status: "done" },
        { mrt: "4.8.8", title: "Типи АЦП: SAR, дельта-сигма", status: "done" },
        { kind: "hist", file: "hist-sampling.md", at: "chapter", status: "done", title: "Теорема дискретизації: Найквіст і Шеннон" },
        { kind: "hist", file: "hist-delta-sigma.md", at: "4.8.8", status: "done", title: "Дельта-сигма: від дельта-модуляції через noise shaping до Іносе й Ясуди" },
        { kind: "comp", file: "../../../components/passive/potentiometer/potentiometer.md", at: "4.8.1", status: "done", title: "Потенціометр: перший аналоговий вхід" },
        { kind: "math", file: "math-quantization-noise.md", at: "4.8.2", status: "done", title: "Шум квантування: ±½ LSB і формула SNR = 6.02·N + 1.76 дБ" },
        { kind: "math", file: "math-dithering.md", at: "4.8.3", status: "done", title: "Дизеринг і oversampling: чому дрібка шуму додає бітів" },
        { kind: "math", file: "math-enob.md", at: "4.8.3", status: "done", title: "ENOB: скільки біт «справжні» і що дає усереднення √N" },
        { kind: "comp", file: "comp-voltage-reference.md", at: "4.8.4", status: "done", title: "Джерела опорної напруги (TL431/REF-класи)" },
        { kind: "math", file: "math-alias-folding.md", at: "4.8.5", status: "done", title: "Аліасинг у числах: як 51 Гц стає 1 Гц (згортання частот)" },
        { kind: "comp", file: "comp-ads1115.md", at: "4.8.6", status: "done", title: "Зовнішній АЦП ADS1115-класу: 16 біт, PGA, диференційні входи" },
        { kind: "proj", file: "proj-two-point-cal.md", at: "4.8.6", status: "done", title: "Двоточкове калібрування: зсув і нахил, збереження в NVS" },
        { kind: "comp", file: "comp-opamp-buffer.md", at: "4.8.7", status: "done", title: "Повторювач на ОП перед АЦП: проблема імпедансу джерела" },
        { kind: "math", file: "math-sample-hold.md", at: "4.8.7", status: "done", title: "Вибірка-зберігання: charge injection і завади між каналами" },
        { kind: "proj", file: "proj-sar-search.md", at: "4.8.8", status: "done", title: "SAR — двійковий пошук у залізі: N тактів на N біт" }
      ] },
    { n: 9, title: "DMA: дані без участі ядра", dir: "block-4-mcu-esp32/dma", main: "dma.md", status: "done",
      scope: "Чому переривань мало для швидких потоків; DMA-контролер, канали й дескриптори; кільцевий і подвійний буфер; DMA з АЦП і SPI/I2S; типові пастки.",
      topics: [
        { mrt: "4.9.1", title: "Проблема: потік даних швидший за цикл «прочитай-запиши»", status: "done" },
        { mrt: "4.9.2", title: "DMA-контролер: окремий «копіювальник» на шині", status: "done" },
        { mrt: "4.9.3", title: "Канали, дескриптори, пріоритети шини", status: "done" },
        { mrt: "4.9.4", title: "Кільцевий буфер і подвійна буферизація (ping-pong)", status: "done" },
        { mrt: "4.9.5", title: "DMA + АЦП: безперервний потік вимірів (з §4.8)", status: "done" },
        { mrt: "4.9.6", title: "DMA + SPI/I2S: великі блоки без переривань", status: "done" },
        { mrt: "4.9.7", title: "Пастки DMA: гонки з кешем, цілісність буфера (якісно)", status: "done" },
        { kind: "hist", file: "hist-dma-channels.md", at: "chapter", status: "done", title: "Канальні процесори IBM: як мейнфрейми розвантажили CPU" },
        { kind: "hist", file: "hist-soundblaster.md", at: "4.9.6", status: "done", title: "Sound Blaster і канал DMA 1: чому геймери 90-х знали це слово" },
        { kind: "math", file: "math-throughput.md", at: "4.9.1", status: "done", title: "Пропускна здатність: байти/с проти тактів на переривання" },
        { kind: "proj", file: "proj-memcpy-vs-dma.md", at: "4.9.2", status: "done", title: "memcpy проти DMA: коли виграє CPU (поріг доцільності)" },
        { kind: "proj", file: "proj-descriptors.md", at: "4.9.3", status: "done", title: "Дескриптори зв'язаним списком: scatter-gather своїми словами" },
        { kind: "math", file: "math-buffer-sizing.md", at: "4.9.4", status: "done", title: "Розмір ping-pong буфера: частота × час обробки + запас" },
        { kind: "proj", file: "proj-ring-buffer.md", at: "4.9.4", status: "done", title: "Кільцевий буфер з нуля: індекси, межі, переповнення" },
        { kind: "comp", file: "comp-i2s-mic.md", at: "4.9.6", status: "done", title: "I2S-мікрофон INMP441-класу: цифровий звук безперервним потоком" },
        { kind: "comp", file: "comp-spi-display.md", at: "4.9.6", status: "done", title: "SPI-дисплей ILI9341-класу: чому кадр без DMA «смикається»" },
        { kind: "proj", file: "proj-cache-dma.md", at: "4.9.7", status: "done", title: "Кеш проти DMA: інвалідація, write-back, вирівнювання буферів" }
      ] },
    { n: 10, title: "Модель виконання й RTOS", dir: "block-4-mcu-esp32/execution-rtos", main: "execution-rtos.md", status: "done",
      scope: "Super-loop проти задач; кооперативність проти витісняння; основи FreeRTOS (задачі, черги, семафори); керування пам'яттю на МК.",
      topics: [
        { mrt: "4.10.1", title: "Super-loop: один великий цикл (setup/loop)", status: "done" },
        { mrt: "4.10.2", title: "Чому super-loop не масштабується (блокування, чуйність)", status: "done" },
        { mrt: "4.10.3", title: "Задачі (tasks): кілька «програм» водночас", status: "done" },
        { mrt: "4.10.4", title: "Планувальник: хто й коли виконується (витісняючий vs кооперативний)", status: "done" },
        { mrt: "4.10.5", title: "RTOS і FreeRTOS на ESP32 (два ядра)", status: "done" },
        { mrt: "4.10.6", title: "Обмін між задачами: черги, семафори, м'ютекси", status: "done" },
        { mrt: "4.10.7", title: "Пам'ять у RTOS: стеки задач (розмір стека)", status: "done" },
        { mrt: "4.10.8", title: "Реальний час: детермінованість і пріоритети", status: "done" },
        { mrt: "4.10.9", title: "Профілювання: куди йдуть такти і байти", status: "done" },
        { kind: "hist", file: "hist-time-sharing.md", at: "chapter", status: "done", title: "Поділ часу: як один комп'ютер навчився служити багатьом (CTSS, 1961)" },
        { kind: "hist", file: "hist-freertos.md", at: "4.10.5", status: "done", title: "FreeRTOS: Річард Беррі та ОС, яку він роздав безкоштовно" },
        { kind: "hist", file: "hist-pathfinder.md", at: "4.10.6", status: "done", title: "Mars Pathfinder, 1997: пріоритетна інверсія на іншій планеті" },
        { kind: "proj", file: "proj-fsm-instead.md", at: "4.10.3", status: "done", title: "Скінченний автомат замість задачі: коли FSM простіший за RTOS" },
        { kind: "math", file: "math-tick-latency.md", at: "4.10.4", status: "done", title: "Тік 1 мс: квант, джитер, tickless-режим" },
        { kind: "proj", file: "proj-clz-bitmap.md", at: "4.10.4", status: "done", title: "CLZ і бітова карта готовності планувальника" },
        { kind: "proj", file: "proj-context-switch.md", at: "4.10.4", status: "done", title: "Перемикання контексту зсередини: регістри, стек, тік" },
        { kind: "comp", file: "comp-dual-core.md", at: "4.10.5", status: "done", title: "Два ядра ESP32 на практиці: PRO/APP, закріплення задач" },
        { kind: "proj", file: "proj-deadlock.md", at: "4.10.6", status: "done", title: "Deadlock: чотири умови і дисципліна порядку захоплення" },
        { kind: "proj", file: "proj-priority-inheritance.md", at: "4.10.6", status: "done", title: "Успадкування пріоритету: що робить м'ютекс проти інверсії" },
        { kind: "proj", file: "proj-queue-pattern.md", at: "4.10.6", status: "done", title: "Патерн «усе через чергу»: producer–consumer без спільних змінних" },
        { kind: "proj", file: "proj-no-free.md", at: "4.10.7", status: "done", title: "Жити без free(): статичні пули замість динамічної купи" },
        { kind: "proj", file: "proj-stack-overflow.md", at: "4.10.7", status: "done", title: "Ловимо переповнення стека: канарки, watermark, заповнення" },
        { kind: "math", file: "math-rate-monotonic.md", at: "4.10.8", status: "done", title: "Rate Monotonic: чому коротший період = вищий пріоритет" }
      ] },
    { n: 11, title: "Пейзаж мікроконтролерів", dir: "block-4-mcu-esp32/mcu-landscape", main: "mcu-landscape.md", status: "done",
      topics: [
        { mrt: "4.11.1", title: "Навіщо знати інші МК (критерії вибору)", status: "done" },
        { mrt: "4.11.2", title: "8-бітна класика: AVR-клас", status: "done" },
        { mrt: "4.11.3", title: "ARM Cortex-M: одне ядро — тисячі чипів", status: "done" },
        { mrt: "4.11.4", title: "STM32-клас: периферія «дорослого» МК", status: "done" },
        { mrt: "4.11.5", title: "RP2040-клас: PIO — периферія, яку програмуєш сам", status: "done" },
        { mrt: "4.11.6", title: "nRF-клас і радіо-МК: коли головне — BLE і мікроампери", status: "done" },
        { mrt: "4.11.7", title: "Екосистема важить більше за мегагерци", status: "done" },
        { mrt: "4.11.8", title: "Як обрати МК під проєкт: чеклист і типові помилки", status: "done" },
        { kind: "hist", file: "hist-arm.md", at: "chapter", status: "done", title: "ARM: Софі Вілсон, Стів Фербер і команда Acorn" },
        { kind: "hist", file: "hist-avr.md", at: "4.11.2", status: "done", title: "AVR: два студенти з Тронгейма — Боген, Воллан" },
        { kind: "hist", file: "hist-rp2040.md", at: "4.11.5", status: "done", title: "Raspberry Pi: фундація, що зробила власний чип" },
        { kind: "comp", file: "comp-uno-nano.md", at: "4.11.2", status: "done", title: "Плата Uno/Nano-класу: анатомія 8-бітної класики" },
        { kind: "comp", file: "comp-stm32-boards.md", at: "4.11.4", status: "done", title: "Плати Nucleo/«Blue Pill»-класу: відлагоджувач на платі" },
        { kind: "comp", file: "comp-pico-board.md", at: "4.11.5", status: "done", title: "Плата Pico-класу: зовнішня QSPI-Flash і прошивка UF2" },
        { kind: "proj", file: "proj-pio.md", at: "4.11.5", status: "done", title: "PIO зсередини: міні-автомати, що генерують протоколи" },
        { kind: "comp", file: "comp-nrf-modules.md", at: "4.11.6", status: "done", title: "Модулі nRF52-класу: радіо із сертифікованою антеною" },
        { kind: "proj", file: "proj-portability.md", at: "4.11.7", status: "done", title: "Один код — різні МК: HAL-шар і умовна компіляція" },
        { kind: "comp", file: "../../../components/passive/packages/packages.md", at: "4.11.8", status: "done", title: "Корпуси МК: DIP, QFP, QFN, BGA — що реально запаяти вдома" },
        { kind: "math", file: "math-decision-matrix.md", at: "4.11.8", status: "done", title: "Приклад вибору МК ваговою матрицею" }
      ] },
    { n: 12, title: "USB на мікроконтролері", dir: "block-4-mcu-esp32/usb-mcu", main: "usb-mcu.md", status: "done",
      topics: [
        { mrt: "4.12.1", title: "USB з висоти: хост і пристрій, дерево з хабами", status: "done" },
        { mrt: "4.12.2", title: "Шина фізично: D+/D−, швидкості LS/FS/HS, виявлення підтяжкою", status: "done" },
        { mrt: "4.12.3", title: "Енумерація: як хост знайомиться з пристроєм (дескриптори, VID/PID)", status: "done" },
        { mrt: "4.12.4", title: "Кінцеві точки й типи передач (control, bulk, interrupt, isochronous)", status: "done" },
        { mrt: "4.12.5", title: "Класи пристроїв: CDC, HID, MSC (чому драйвер уже є в системі)", status: "done" },
        { mrt: "4.12.6", title: "USB в ESP32: нативний USB-OTG (S2/S3) і USB-Serial-JTAG проти моста", status: "done" },
        { mrt: "4.12.7", title: "Живлення з шини: 5 В і бюджет струму (від 100 мА до USB-C)", status: "done" },
        { mrt: "4.12.8", title: "МК як USB-host: читаємо флешки й клавіатури (OTG — якісно)", status: "done" },
        { kind: "hist", file: "hist-usb-birth.md", at: "chapter", status: "done", title: "USB: сім компаній проти зоопарку роз'ємів (і роль Аджая Бхатта)" },
        { kind: "hist", file: "hist-badusb.md", at: "4.12.5", status: "done", title: "BadUSB і Rubber Ducky: коли «клавіатура» — зброя" },
        { kind: "comp", file: "../../../components/interfaces/usb-c-connector/usb-c-connector.md", at: "4.12.2", status: "done", title: "USB-C: резистори CC і «кабель лише для заряджання»" },
        { kind: "math", file: "math-nrzi.md", at: "4.12.2", status: "done", title: "NRZI і біт-стафінг: як USB передає біти без окремої лінії такту" },
        { kind: "proj", file: "proj-descriptors.md", at: "4.12.3", status: "done", title: "Мінімальний дескриптор своїми руками: байти, які бачить хост" },
        { kind: "proj", file: "proj-frames.md", at: "4.12.4", status: "done", title: "Розклад шини: фрейми 1 мс і чому миша «125 Гц»" },
        { kind: "proj", file: "proj-hid-reports.md", at: "4.12.5", status: "done", title: "HID-звіти: як МК прикидається клавіатурою (макро-пад)" },
        { kind: "comp", file: "comp-otg.md", at: "4.12.8", status: "done", title: "OTG-кабель і host-модулі: що треба, щоб МК став головним" }
      ] },
    { n: 13, title: "Енергоощадність глибоко", dir: "block-4-mcu-esp32/low-power", main: "low-power.md", status: "done",
      topics: [
        { mrt: "4.13.1", title: "Бюджет батареї: мА·год ÷ середній струм (чому рахуємо в мкА)", status: "done" },
        { mrt: "4.13.2", title: "Куди тече струм: ядро, радіо, периферія, витоки, стабілізатор", status: "done" },
        { mrt: "4.13.3", title: "Режими сну ESP32: modem-sleep, light-sleep, deep-sleep", status: "done" },
        { mrt: "4.13.4", title: "Джерела пробудження: таймер, GPIO, дотик, ULP (і ціна кожного)", status: "done" },
        { mrt: "4.13.5", title: "ULP-співпроцесор: міряти, поки ядра сплять", status: "done" },
        { mrt: "4.13.6", title: "Цикл «прокинувся → виміряв → передав → заснув»: середній струм", status: "done" },
        { mrt: "4.13.7", title: "Виміряти споживання чесно: мультиметр бреше на імпульсах", status: "done" },
        { mrt: "4.13.8", title: "Плата теж їсть: LDO, світлодіоди, підтяжки, давачі", status: "done" },
        { mrt: "4.13.9", title: "Життя після deep-sleep: RTC-пам'ять і відновлення контексту", status: "done" },
        { kind: "hist", file: "hist-pacemaker.md", at: "chapter", status: "done", title: "Кардіостимулятор і батарейка: Елмквіст, Сеннінг, Ґрейтбатч" },
        { kind: "hist", file: "hist-voyager.md", at: "4.13.2", status: "done", title: "«Вояджери»: бюджет ват, який скорочується пів століття" },
        { kind: "math", file: "math-battery-math.md", at: "4.13.1", status: "done", title: "Математика батареї: мА·год, саморозряд, температура" },
        { kind: "comp", file: "comp-sensor-standby.md", at: "4.13.2", status: "done", title: "Хто на платі не спить: standby-струми давачів (BME/LIS-класи)" },
        { kind: "comp", file: "comp-wake-hw.md", at: "4.13.4", status: "done", title: "Залізні будильники: RTC з alarm-виходом, load switch, защіпка" },
        { kind: "proj", file: "proj-ulp-program.md", at: "4.13.5", status: "done", title: "Програма для ULP: виміряти, порівняти з порогом і не будити ядра" },
        { kind: "comp", file: "comp-current-profiler.md", at: "4.13.7", status: "done", title: "Профілювальники струму (клас Power Profiler): від нА до сотень мА" },
        { kind: "math", file: "math-dynamic-range.md", at: "4.13.7", status: "done", title: "Динамічний діапазон вимірювання: п'ять порядків одним шунтом" },
        { kind: "comp", file: "comp-ldo-vs-buck.md", at: "4.13.8", status: "done", title: "LDO проти buck-конвертера для батареї: quiescent current вирішує" }
      ] },
    { n: 14, title: "Налагодження глибоко: JTAG/SWD, GDB і посмертний аналіз", dir: "block-4-mcu-esp32/debug-deep", main: "debug-deep.md", status: "done",
      topics: [
        { mrt: "4.14.1", title: "Де друк безсилий: навіщо відлагоджувач, коли є Serial", status: "done" },
        { mrt: "4.14.2", title: "SWD і JTAG зсередини: лінії, скан-ланцюг і як зонд «бачить» ядро", status: "done" },
        { mrt: "4.14.3", title: "Брейкпоінти й вотчпоінти: апаратні проти програмних", status: "done" },
        { mrt: "4.14.4", title: "OpenOCD і GDB: хост говорить із чипом", status: "done" },
        { mrt: "4.14.5", title: "Кроком по коду: стек викликів, фрейми, перегляд пам'яті й регістрів", status: "done" },
        { mrt: "4.14.6", title: "Розбір HardFault: що ядро зберігає при збої і як прочитати причину", status: "done" },
        { mrt: "4.14.7", title: "Посмертний аналіз: core dump і відновлення картини після падіння", status: "done" },
        { kind: "hist", file: "hist-jtag.md", at: "chapter", status: "done", title: "Межовий скан і JTAG: Joint Test Action Group (IEEE 1149.1)" }
      ] },
    { n: 15, title: "Відмовостійка прошивка: помилки, паніка, відновлення", dir: "block-4-mcu-esp32/fault-tolerant", main: "fault-tolerant.md", status: "done",
      topics: [
        { mrt: "4.15.1", title: "Жодна помилка не мовчить: чому проковтнутий код повернення — найгірший баг", status: "done" },
        { mrt: "4.15.2", title: "Код повернення, assert і паніка: три рівні реакції", status: "done" },
        { mrt: "4.15.3", title: "Перевірки на льоту: передумови, інваріанти й захисне програмування", status: "done" },
        { mrt: "4.15.4", title: "Безпечний стан і safe mode: що робити, коли далі працювати небезпечно", status: "done" },
        { mrt: "4.15.5", title: "Перезавантаження як стратегія: чистий старт проти пошкодження стану", status: "done" },
        { mrt: "4.15.6", title: "Лічильник перезавантажень і причина reset: поодинокий збій проти циклу смерті", status: "done" },
        { mrt: "4.15.7", title: "Brown-out і нестабільне живлення: збій, що прикидається багом (зв'язок із 4.1.8)", status: "done" },
        { mrt: "4.15.8", title: "Деградація з гідністю: працювати частково, коли одна підсистема відмовила", status: "done" },
        { kind: "hist", file: "hist-ariane5.md", at: "chapter", status: "done", title: "Ariane 5, рейс 501 (1996): необроблене переповнення за 37 секунд" }
      ] }
    // розділ 4.16 (мости, фінальним проходом) у manifest відсутній — не додаємо
  ]
});
