/* manifest — «Program architecture» (тип "guide"). Схема v5: modules→chapters→steps (AUTHORING §2).
   Структура з нуля за віссю масштабу турботи (план guide/progarch/_plan.md, застосовано 2026-07-06).
   Крок = { ref:"книга/галузь/slug", title } (book-атом) АБО власна стаття курсу { slug, title, basic, detailed }.
   Вставки не реєструємо тут — їх заводить write-batch під час письма статей. */
(window.__GUIDES__ = window.__GUIDES__ || []).push({
  type: "guide", slug: "progarch", title: "Архітектура програм",
  modules: [
    { n: 1, slug: "mindset", title: "Що таке архітектурне рішення", scope: "", chapters: [
      { title: "Архітектура як потік значущих рішень", steps: [
        { slug: "what-is-architecture", title: "Архітектура", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-big-ball-of-mud.md", status: "done" }, { file: "hist-expensive-to-change.md", status: "done" }] },
        { ref: "programming/architecture-discipline/architect-role", title: "Роль архітектора" },
        { ref: "programming/software-design/technical-debt", title: "Технічний борг і вартість зміни" },
        { slug: "dh-v0-one-sensor", title: "Digital Homes v0", basic: { status: "done" }, detailed: { status: "empty" }, proj: [{ file: "proj-dh-v0.md", status: "done" }] },
      ] },
      { title: "Якісні атрибути й сценарії", steps: [
        { ref: "programming/architecture-discipline/quality-attributes", title: "Якісні атрибути («-ilities»)" },
        { ref: "programming/architecture-discipline/attribute-scenarios", title: "Сценарії атрибутів" },
        { ref: "programming/architecture-discipline/stakeholders", title: "Стейкхолдери та їхні системи" },
        { ref: "programming/architecture-discipline/architectural-drivers", title: "Архітектурні драйвери" },
        { slug: "dh-utility-tree", title: "Дерево корисності Digital Homes", basic: { status: "done" }, detailed: { status: "empty" }, proj: [{ file: "proj-dh-utility-tree.md", status: "done" }] },
      ] },
      { title: "Trade-off і його ціна", steps: [
        { ref: "programming/architecture-discipline/tradeoff-analysis", title: "Trade-off-аналіз" },
        { ref: "programming/architecture-discipline/atam-lite", title: "ATAM-лайт" },
        { ref: "programming/architecture-discipline/architectural-tactics", title: "Тактика проти патерна" },
        { ref: "programming/architecture-discipline/modifiability-tactics", title: "Тактики змінюваності" },
        { ref: "programming/architecture-discipline/back-of-envelope", title: "Прикидка «на серветці»" },
        { slug: "dh-v0-scenario-audit", title: "Перше рев'ю", basic: { status: "done" }, detailed: { status: "empty" }, proj: [{ file: "proj-v0-audit-run.md", status: "done" }] },
        { slug: "variant-block-anatomy", title: "Анатомія варіантного блоку", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-steelman.md", status: "done" }] },
      ] },
    ] },
    { n: 2, slug: "decisions-under-uncertainty", title: "Рішення під невизначеністю та ризиком", scope: "", chapters: [
      { title: "Зворотні й незворотні рішення", steps: [
        { ref: "programming/architecture-discipline/reversible-irreversible-decisions", title: "Зворотні й незворотні рішення" },
        { ref: "programming/architecture-discipline/last-responsible-moment", title: "Останній відповідальний момент" },
        { slug: "what-makes-irreversible", title: "Що робить рішення незворотним", basic: { status: "done" }, detailed: { status: "done" }, math: [{ file: "math-hyrum-law.md", status: "done" }], proj: [{ file: "proj-expand-contract.md", status: "done" }, { file: "proj-key-rotation.md", status: "done" }] },
      ] },
      { title: "Купівля інформації", steps: [
        { ref: "programming/architecture-discipline/deciding-under-uncertainty", title: "Рішення під невизначеністю" },
        { ref: "programming/architecture-discipline/walking-skeleton", title: "Walking skeleton" },
        { slug: "cost-of-delay", title: "Вартість зволікання проти вартості помилки", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-cost-of-delay.md", status: "done" }], math: [{ file: "math-value-of-information.md", status: "done" }, { file: "math-wsjf.md", status: "done" }], proj: [{ file: "proj-cod-model.md", status: "done" }] },
      ] },
      { title: "Ризик-мислення", steps: [
        { ref: "programming/architecture-discipline/risk-thinking", title: "Ризик-мислення" },
        { ref: "programming/architecture-discipline/risk-register", title: "Ризик-реєстр як живий артефакт" },
        { slug: "dh-risk-register", title: "Ризик-реєстр Digital Homes", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-smarthome-risks-realized.md", status: "done" }], proj: [{ file: "proj-risk-register.md", status: "done" }] },
      ] },
      { title: "Коли НЕ будувати", steps: [
        { ref: "programming/software-design/dry-kiss-yagni", title: "**YAGNI за замовчуванням**, DRY і його межа (передчасне узагальнення), KISS; складність як пасив/борг; вартість передчасної абстракції" },
        { ref: "programming/architecture-discipline/evolutionary-architecture", title: "Еволюційна архітектура як дефолт" },
        { ref: "programming/architecture-discipline/build-vs-buy", title: "**Build vs buy** (і оренда/SaaS/adopt)" },
        { ref: "programming/architecture-discipline/cost-as-attribute", title: "Вартість як атрибут" },
        { slug: "dh-not-building", title: "DH", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-biometric-privacy.md", status: "done" }], proj: [{ file: "proj-broker-cost-model.md", status: "done" }] },
        { slug: "assumptions-vs-facts", title: "Припущення проти фактів як дисципліна", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-assumption-discipline.md", status: "done" }], math: [{ file: "math-value-of-information.md", status: "done" }], proj: [{ file: "proj-assumption-register.md", status: "done" }] },
        { slug: "dh-decisions-under-uncertainty", title: "DH під невизначеністю", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-smart-home-standards-war.md", status: "done" }], proj: [{ file: "proj-dh-radio-spike.md", status: "done" }] },
      ] },
    ] },
    { n: 3, slug: "views-and-communication", title: "В'ю та комунікація архітектури", scope: "", chapters: [
      { title: "Множинні в'ю однієї системи", steps: [
        { ref: "programming/architecture-discipline/architecture-views", title: "Архітектурні в'ю" },
        { ref: "programming/architecture-discipline/c4-model", title: "C4" },
        { ref: "programming/architecture-discipline/deployment-view", title: "В'ю розгортання і динамічні в'ю" },
        { ref: "programming/architecture-discipline/diagrams-as-code", title: "Діаграми як код" },
        { ref: "programming/architecture-discipline/viewpoints-perspectives", title: "Viewpoints і perspectives (Rozanski/Woods)" },
        { slug: "dh-v2-views", title: "DH на папері", basic: { status: "done" }, detailed: { status: "empty" }, proj: [{ file: "proj-dh-structurizr.md", status: "done" }] },
      ] },
      { title: "Письмові рішення: ADR / RFC / design-doc", steps: [
        { ref: "programming/software-design/architecture-decision-records", title: "Журнал архітектурних рішень (ADR)" },
        { ref: "programming/software-engineering/design-docs", title: "Design docs і RFC" },
        { ref: "programming/software-design/api-design", title: "Дизайн API модуля/бібліотеки як рішення письмом" },
        { slug: "writing-as-thinking", title: "Проєктування письмом як інструмент мислення", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Рев'ю та вплив без влади", steps: [
        { ref: "programming/architecture-discipline/architecture-review", title: "Рев'ю архітектури як практика" },
        { ref: "programming/architecture-discipline/fitness-functions", title: "Фітнес-функції" },
        { slug: "influence-without-authority", title: "Вплив без наказу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-review-workshop", title: "Рев'ю-воркшоп DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Місток до організації й наскрізний слід", steps: [
        { slug: "conway-teaser", title: "Закон Конвея як анонс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-decision-log", title: "Наскрізний слід рішень", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 4, slug: "structure-in-the-small", title: "Зчеплення, зв'язність і межі модуля", scope: "", chapters: [
      { title: "Зчеплення і зв'язність", steps: [
        { ref: "programming/software-engineering/abstraction-principle", title: "Принцип абстракції" },
        { ref: "programming/software-engineering/information-hiding", title: "Приховування інформації (Парнас" },
        { ref: "programming/software-design/coupling-cohesion", title: "Зчеплення і зв'язність" },
        { ref: "programming/software-design/law-of-demeter", title: "Закон Деметри" },
      ] },
      { title: "Напрям залежностей і межі", steps: [
        { ref: "programming/software-design/dependency-inversion", title: "Принцип інверсії залежностей (DIP)" },
        { ref: "programming/software-engineering/design-by-contract", title: "Проєктування за контрактом" },
        { ref: "programming/software-design/dto", title: "DTO" },
        { slug: "seams-and-boundaries", title: "Шов (seam) як точка зміни", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Незмінність і стан", steps: [
        { ref: "programming/software-design/immutability", title: "Незмінність як прийом дизайну" },
        { ref: "algorithms/data-structures/copy-on-write", title: "Copy-on-write" },
        { ref: "programming/software-design/pure-functions-side-effects", title: "Чисті функції і побічні ефекти" },
        { ref: "programming/software-design/type-driven-design", title: "Типи як дизайн" },
        { slug: "state-inventory", title: "Де живе стан", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Помилки й перший рефакторинг межами", steps: [
        { slug: "errors-through-layers", title: "Помилки крізь шари", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-v1-modules", title: "DH v0 → v1", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 5, slug: "solid-and-composition", title: "SOLID та композиція над спадкуванням", scope: "", chapters: [
      { title: "SOLID по одному, як інструмент", steps: [
        { ref: "programming/software-design/single-responsibility", title: "SRP" },
        { ref: "programming/software-design/open-closed", title: "OCP" },
        { slug: "lsp-isp-together", title: "LSP та ISP разом", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Композиція, делегування, наслідування", steps: [
        { ref: "programming/software-design/composition-inheritance", title: "Композиція над спадкуванням" },
        { slug: "solid-audit", title: "SOLID разом", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Інші компаси коду", steps: [
        { ref: "programming/software-design/functional-core-imperative-shell", title: "Функціональне ядро, імперативна оболонка" },
        { slug: "cqs-command-query", title: "CQS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "principles-as-tools-not-dogma", title: "Принципи як інструменти, не догми", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 6, slug: "contracts-and-testability", title: "Контракти, тестованість, рефакторинг", scope: "", chapters: [
      { title: "Контракт як межа й design-by-contract", steps: [
        { slug: "contract-as-boundary", title: "Контракт як межа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/software-engineering/contract-testing", title: "Контрактні тести" },
        { slug: "invariants-and-validation", title: "Інваріанти й валідація на межі", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Тестованість як дизайн і рефакторинг", steps: [
        { ref: "programming/architecture-discipline/testability-tactics", title: "Тактики тестовності" },
        { slug: "test-doubles-when", title: "Дублери як рішення дизайну", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "test-boundaries", title: "Що і на якому рівні тестувати", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "refactoring-safe", title: "Рефакторинг безпечно", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "characterization-tests", title: "Характеризаційні тести як страховка над кодом без тестів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "observability-as-testability", title: "Спостережність як тестованість у проді", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "debt-as-decision", title: "Технічний борг як свідоме рішення, не аварія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-testability-refactor", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 7, slug: "gof-by-intent", title: "GoF за призначенням + DI/репозиторій/антипатерни", scope: "", chapters: [
      { title: "Патерн як словник, не рецепт", steps: [
        { ref: "programming/design-patterns/what-is-pattern", title: "Що таке патерн" },
      ] },
      { title: "Творення (creational)", steps: [
        { ref: "programming/design-patterns/factory-method", title: "Фабричний метод і абстрактна фабрика" },
        { ref: "programming/design-patterns/builder", title: "Будівельник" },
        { ref: "programming/design-patterns/object-pool", title: "Пул об'єктів" },
        { ref: "programming/design-patterns/singleton", title: "Сінглтон" },
      ] },
      { title: "Структура (structural)", steps: [
        { ref: "programming/design-patterns/adapter", title: "Адаптер" },
        { ref: "programming/design-patterns/decorator", title: "Декоратор" },
        { ref: "programming/design-patterns/facade", title: "Фасад" },
        { ref: "programming/design-patterns/composite", title: "Компонувальник" },
        { ref: "programming/design-patterns/proxy", title: "Проксі" },
      ] },
      { title: "Поведінка (behavioral)", steps: [
        { ref: "programming/design-patterns/strategy", title: "Стратегія" },
        { ref: "programming/design-patterns/observer", title: "Спостерігач" },
        { ref: "programming/design-patterns/command", title: "Команда" },
        { ref: "programming/design-patterns/state", title: "Стан" },
        { ref: "programming/design-patterns/chain-of-responsibility", title: "Ланцюжок обов'язків" },
        { ref: "programming/design-patterns/gof-structural-microcatalog", title: "Решта структурних оглядово" },
        { ref: "programming/design-patterns/gof-behavioral-microcatalog", title: "Решта поведінкових оглядово" },
      ] },
      { title: "DI, репозиторій, антипатерни", steps: [
        { ref: "programming/design-patterns/dependency-injection", title: "Впровадження залежностей та IoC-контейнер (інструмент DIP); контейнер vs ручна збірка; service locator як анти-двійник (інлайн)" },
        { ref: "programming/design-patterns/repository", title: "Репозиторій" },
        { ref: "programming/design-patterns/anti-patterns", title: "Антипатерни" },
      ] },
    ] },
    { n: 8, slug: "application-shape", title: "Форми застосунку: шари, гексагон, чиста арх., PoEAA", scope: "", chapters: [
      { title: "Шари та їхні залежності", steps: [
        { ref: "programming/software-design/layered-architecture", title: "Шарова архітектура" },
        { ref: "programming/software-design/service-layer", title: "Сервісний шар" },
      ] },
      { title: "Порти й адаптери (гексагон), чиста/цибулева", steps: [
        { ref: "programming/software-design/hexagonal-architecture", title: "Порти й адаптери" },
        { ref: "programming/software-design/di-container", title: "DI-контейнер і composition root" },
        { slug: "hexagon-when-overkill", title: "Коли гексагон", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Наскрізні зрізи", steps: [
        { ref: "programming/software-design/cross-cutting-concerns", title: "Наскрізні зрізи" },
        { ref: "programming/software-design/event-driven-architecture", title: "Подієва архітектура всередині застосунку" },
        { ref: "programming/software-design/plugin-architecture", title: "Плагіни / точки розширення" },
      ] },
      { title: "PoEAA: шаблони застосунку й даних", steps: [
        { ref: "programming/design-patterns/active-record", title: "Active Record" },
        { ref: "programming/design-patterns/data-mapper", title: "Data Mapper" },
        { ref: "programming/design-patterns/identity-map", title: "Identity map" },
        { ref: "programming/design-patterns/unit-of-work", title: "Unit of Work" },
        { ref: "programming/design-patterns/lazy-loading", title: "Ліниве завантаження" },
        { slug: "data-access-choice", title: "Компакт-вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "distributed-objects-trap", title: "Чому «distributed objects»", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-v2-hexagon", title: "DH v2", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 9, slug: "ddd-lite", title: "Предметно-орієнтований дизайн (лайт) і межі контекстів", scope: "", chapters: [
      { title: "Мова, модель, тактичні цеглинки", steps: [
        { ref: "programming/software-design/domain-driven-design", title: "DDD-лайт" },
        { ref: "programming/software-design/aggregates-consistency", title: "Агрегат і корінь" },
        { slug: "dh-data-model", title: "Модель даних DH мовою домену", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Обмежені контексти й карта контекстів", steps: [
        { ref: "programming/software-design/bounded-context", title: "Обмежений контекст" },
        { ref: "programming/software-design/context-mapping", title: "Карта контекстів" },
        { ref: "programming/software-design/anti-corruption-layer", title: "Антикорупційний шар" },
        { ref: "programming/software-design/modular-monolith", title: "Модульний моноліт" },
        { slug: "context-as-service-candidate", title: "Контекст як кандидат у сервіс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ddd-when-overkill", title: "Коли DDD", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-contexts-map", title: "Мапа контекстів Digital Homes", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Життєвий цикл як автомат", steps: [
        { slug: "dh-device-fsm", title: "Життєвий цикл пристрою як автомат станів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "logic-organization-choice", title: "Вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/software-design/subdomains-strategic", title: "Стратегічний розкрій" },
        { slug: "dh-context-boundaries-choice", title: "Де провести межі контекстів DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 10, slug: "api-and-compatibility", title: "Дизайн API, версіонування, конфіг, розширюваність", scope: "", chapters: [
      { title: "Дизайн API як контракт", steps: [
        { ref: "programming/web-backend/rest-api", title: "REST" },
        { slug: "api-style-choice", title: "Стилі API як рішення, не релігія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/web-backend/api-idempotency", title: "Ідемпотентність методів як частина контракту" },
      ] },
      { title: "Еволюція без поломки клієнтів", steps: [
        { ref: "programming/web-backend/api-versioning", title: "Версіонування API" },
        { ref: "programming/software-engineering/expand-contract", title: "Expand–contract (parallel change) для API" },
        { slug: "api-evolution-dh", title: "Еволюція API DH без поломки", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Конфігурація, плагіни, feature-flags", steps: [
        { ref: "programming/software-design/config-design", title: "Конфігурація" },
        { ref: "programming/software-design/extension-points", title: "Плагіни й точки розширення назовні" },
        { ref: "programming/operations/feature-flags", title: "Прапорці функцій" },
        { slug: "config-secrets-boundary", title: "Конфіг проти секретів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/web-backend/deprecation-basics", title: "Деприкейшн API як частина контракту" },
        { slug: "api-error-contract", title: "Помилки як контракт назовні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "extensibility-choice", title: "Вибір моделі розширюваності DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-api-config-final", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 11, slug: "concurrency-models", title: "Моделі конкурентності й виконання", scope: "", chapters: [
      { title: "Спільна пам'ять і замки", steps: [
        { slug: "why-concurrency", title: "Конкурентність ≠ паралелізм", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/systems/process-vs-thread", title: "Процеси й потоки" },
        { ref: "programming/systems/data-races-locks", title: "Перегони даних і замки" },
        { ref: "programming/systems/deadlock", title: "Дедлок" },
        { ref: "programming/systems/readers-writer-lock", title: "Багато читачів, один письменник" },
      ] },
      { title: "Без замків і поза замками", steps: [
        { ref: "programming/systems/lock-free-basics", title: "Без замків" },
      ] },
      { title: "Повідомлення замість пам'яті", steps: [
        { ref: "programming/systems/actor-model", title: "Модель акторів" },
        { ref: "programming/systems/supervision-trees", title: "Дерева нагляду" },
        { ref: "programming/systems/csp-channels", title: "Канали і CSP" },
        { ref: "programming/systems/producer-consumer", title: "Виробник–споживач" },
      ] },
      { title: "Асинхронність, пули, тиск, межі приросту", steps: [
        { ref: "programming/systems/blocking-vs-nonblocking-io", title: "Блокуючий і неблокуючий ввід-вивід" },
        { ref: "programming/systems/event-loop", title: "Цикл подій" },
        { ref: "programming/systems/async-await", title: "Колбеки → проміси → async/await" },
        { ref: "programming/software-design/reactive-programming", title: "Реактивні потоки" },
        { ref: "programming/systems/thread-pool", title: "Пул потоків і його розмір" },
        { ref: "programming/systems/backpressure-local", title: "Backpressure" },
        { ref: "programming/systems/thread-per-core", title: "Thread-per-core / shared-nothing на ядрах" },
        { ref: "algorithms/parallel-distributed/amdahls-law", title: "Закон Амдала" },
      ] },
      { title: "Рішення: рантайм конкурентності", steps: [
        { slug: "runtime-threads-variant", title: "Варіант А", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "runtime-eventloop-variant", title: "Варіант Б", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "runtime-actors-variant", title: "Варіант В", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "runtime-choice", title: "Вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Синтез: межа й набір інструментів", steps: [
        { slug: "rozbir-lmax", title: "Розбір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "paradigms-toolbox", title: "Парадигми як інструменти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "concurrency-and-clocks", title: "Годинник і монотонність у конкурентності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "concurrency-observability", title: "Чим вимірюємо конкурентність", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 12, slug: "storage-as-decision", title: "Реляційне сховище як рішення", scope: "", chapters: [
      { title: "Реляційна модель, індекси, план", steps: [
        { slug: "dh-data-persistence", title: "Дані переживають процес", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/databases/relational-model", title: "Реляційна модель і нормалізація як рішення" },
        { ref: "programming/databases/database-indexes", title: "Індекси" },
        { ref: "programming/databases/query-planner", title: "Планувальник запитів і EXPLAIN" },
      ] },
      { title: "Транзакції, ізоляція, MVCC", steps: [
        { ref: "programming/databases/transactions-acid", title: "Транзакції та **ACID**" },
        { ref: "programming/databases/isolation-levels", title: "Рівні ізоляції та аномалії" },
        { ref: "programming/databases/mvcc", title: "MVCC" },
        { slug: "last-ticket-race", title: "Останній квиток", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Що під капотом: WAL і LSM", steps: [
        { ref: "programming/databases/write-ahead-log", title: "Журнал попереднього запису (WAL)" },
        { ref: "algorithms/data-structures/lsm-tree", title: "B-tree vs LSM-tree / log-structured" },
        { slug: "storage-under-hood-choice", title: "Що обрати під профіль запису/читання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-storage-guarantees", title: "Гарантії сховища DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Реляційне як свідомий вибір", steps: [
        { ref: "programming/databases/database-migrations", title: "Міграції схеми" },
        { ref: "programming/databases/orm", title: "ORM" },
        { slug: "relational-default", title: "«Нудне» реляційне за замовчуванням", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-v3-storage", title: "DH v3", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 13, slug: "nosql-and-caching", title: "Ландшафт NoSQL і стратегії кешу", scope: "", chapters: [
      { title: "Ландшафт NoSQL за формою даних", steps: [
        { ref: "programming/databases/nosql-landscape", title: "Ландшафт NoSQL" },
        { ref: "programming/databases/access-pattern-first", title: "Форма доступу диктує модель" },
        { ref: "programming/databases/polyglot-persistence", title: "Polyglot persistence і його ціна" },
        { slug: "storage-choice", title: "Вибір сховища під задачу", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Кешування як рішення", steps: [
        { ref: "programming/computer-architecture/cache", title: "Кеш" },
        { ref: "programming/distributed-systems/caching-strategies", title: "Патерни кешування" },
        { ref: "programming/distributed-systems/cache-invalidation-intro", title: "Кеш вводить друге джерело правди (ціна)" },
        { ref: "programming/distributed-systems/cache-consistency-tradeoff", title: "Свіжість проти навантаження" },
        { ref: "programming/distributed-systems/what-not-to-cache", title: "Що НЕ кешувати і чому" },
        { slug: "cache-decision-framework", title: "Рамка рішення про кеш", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nosql-migration-consideration", title: "Коли міграція з реляційного в NoSQL виправдана", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-first-cache", title: "Перший кеш DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 14, slug: "schema-evolution-and-flow", title: "Еволюція схем, матеріалізація, рух даних", scope: "", chapters: [
      { title: "Схема як контракт, що змінюється; матеріалізація", steps: [
        { ref: "programming/databases/schema-on-read-write", title: "Schema-on-write vs schema-on-read" },
        { ref: "programming/distributed-systems/schema-registry", title: "Еволюція схем і schema-registry" },
        { ref: "programming/databases/materialized-views", title: "Матеріалізовані в'ю як похідні дані" },
      ] },
      { title: "Рух даних між системами", steps: [
        { ref: "programming/databases/change-data-capture", title: "CDC" },
        { ref: "programming/data-analytics/etl-elt", title: "ETL/ELT" },
        { ref: "programming/data-analytics/data-contracts", title: "Data-контракти між продюсером і сховищем" },
        { ref: "programming/data-analytics/data-lineage", title: "Lineage «звідки це число»" },
        { ref: "programming/data-analytics/idempotent-reprocessing", title: "Ідемпотентний перерахунок історії" },
        { slug: "pipeline-consistency", title: "Консистентність конвеєра end-to-end", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-schema-flow", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "schema-evolution-choice", title: "Вибір стратегії еволюції даних", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "materialization-vs-cache", title: "Матеріалізація проти кешу проти читання наживо", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 15, slug: "distribution-fundamentals", title: "Що ламається, коли з'являється мережа", scope: "", chapters: [
      { title: "Омани розподілених обчислень і транспорт", steps: [
        { ref: "programming/distributed-systems/distributed-fallacies", title: "Вісім оман розподілених обчислень (мережа надійна / латентність нуль / пропускна нескінченна / топологія стала / …) як чекліст рев'ю; чому локальний виклик ≠ віддалений (RPC-брехня); часткова відмова як нова норма" },
        { slug: "partial-failure", title: "Часткова відмова", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "communications/cryptographic-comm/tls", title: "TLS" },
        { ref: "programming/networking/rpc", title: "RPC і серіалізація" },
        { ref: "programming/networking/connection-management", title: "Керування з'єднаннями" },
      ] },
      { title: "Таймаути, ретраї, ідемпотентність", steps: [
        { ref: "programming/distributed-systems/timeouts-deadlines", title: "Таймаути і бюджет часу" },
        { ref: "programming/distributed-systems/retries-backoff", title: "Повтори" },
        { ref: "programming/distributed-systems/idempotency", title: "Ідемпотентність" },
        { slug: "dh-bad-network", title: "Хаб на поганому Wi-Fi", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Гарантії доставки", steps: [
        { ref: "programming/distributed-systems/delivery-guarantees", title: "At-most-once / at-least-once / effectively-once" },
        { slug: "duplicates-and-reorder", title: "Дублі й переупорядкування як норма", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sync-vs-async-fundamental", title: "Синхронно проти асинхронно як фундаментальний вибір зчеплення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/security/replay-protection", title: "Захист від повтору (replay)" },
        { slug: "dh-distribution-crossing", title: "DH перетинає межу машини", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 16, slug: "replication-and-consistency", title: "Реплікація й моделі консистентності", scope: "", chapters: [
      { title: "Реплікація, лаг, кворум", steps: [
        { ref: "programming/distributed-systems/replication-leader-follower", title: "Лідер-фоловер / мультилідер / leaderless" },
        { ref: "programming/distributed-systems/replication-lag", title: "Реплікаційний лаг і сесійні гарантії" },
        { ref: "programming/distributed-systems/quorum-and-leaderless", title: "Кворуми" },
        { ref: "programming/distributed-systems/split-brain", title: "Failover і розщеплення мозку" },
        { slug: "dh-replicas", title: "Твін дому на репліках", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Мультилідер, конфлікти, сходження", steps: [
        { ref: "programming/distributed-systems/multi-leader-replication", title: "Мультилідерна реплікація" },
        { slug: "conflict-resolution-strategies", title: "Стратегії розв'язання конфліктів", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Моделі консистентності й CAP", steps: [
        { ref: "programming/distributed-systems/consistency-models", title: "Спектр консистентності" },
        { ref: "programming/distributed-systems/cap-theorem", title: "CAP (і чому не «оберіть 2») + PACELC (латентність теж у ціні)" },
        { ref: "programming/distributed-systems/eventual-consistency", title: "Кінцева узгодженість на практиці" },
        { ref: "programming/distributed-systems/anti-entropy-repair", title: "Анти-ентропія" },
        { slug: "dh-consistency-choice", title: "Що в DH строго, а що «зрештою»", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "consistency-cost-tradeoff", title: "Ціна консистентності як trade-off", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "replication-choice", title: "Вибір моделі реплікації", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 17, slug: "time-order-consensus", title: "Час, порядок, консенсус, координація", scope: "", chapters: [
      { title: "Годинники й порядок", steps: [
        { ref: "algorithms/parallel-distributed/lamport-clocks", title: "Чому wall-clock бреше (дрейф, NTP-стрибки) і **годинник Лампорта**" },
        { ref: "algorithms/parallel-distributed/vector-clocks", title: "Векторні годинники й обходи розбіжності" },
        { slug: "causality-over-walltime", title: "Причинність важливіша за настінний час", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Консенсус", steps: [
        { ref: "algorithms/parallel-distributed/consensus-problem", title: "Задача консенсусу і чому вона важка (FLP оглядово); коли потрібен консенсус, а коли ні (дорого)" },
        { ref: "algorithms/parallel-distributed/raft", title: "Raft" },
        { ref: "algorithms/parallel-distributed/two-phase-commit", title: "Двофазний коміт і його страх" },
      ] },
      { title: "Координація й розміщення", steps: [
        { ref: "programming/distributed-systems/distributed-locks", title: "Розподілені замки й лізи" },
        { ref: "programming/distributed-systems/leader-election", title: "Вибори лідера як прикладний патерн" },
        { ref: "programming/distributed-systems/partitioning-sharding", title: "Шардинг" },
        { ref: "algorithms/data-structures/consistent-hashing", title: "Консистентне хешування" },
        { ref: "algorithms/data-structures/merkle-tree", title: "Дерево Меркла" },
        { slug: "why-distribute", title: "Навіщо розподіляти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rozbir-discord-storage", title: "Розбір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sharding-consensus-choice", title: "Вибір координації під задачу", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 18, slug: "to-microservices-or-not", title: "Сервісні межі: різати чи ні; знаходити одне одного", scope: "", chapters: [
      { title: "Модульний моноліт як стандарт за замовчуванням", steps: [
        { slug: "modular-monolith-first", title: "Модульний моноліт як дефолт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-monolith-boundaries", title: "Межі всередині моноліта DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Коли й як різати на сервіси", steps: [
        { ref: "programming/software-design/microservices", title: "Мікросервіси" },
        { slug: "when-to-split", title: "Коли й як різати", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-v8-services-map", title: "Чи різати хмару DH? Рішення через ADR", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Знайти й дотягтися", steps: [
        { ref: "programming/distributed-systems/service-discovery", title: "Виявлення сервісів" },
        { ref: "programming/distributed-systems/api-gateway", title: "API-шлюз" },
        { ref: "programming/web-backend/bff-pattern", title: "BFF (backend-for-frontend)" },
        { ref: "programming/software-design/gateway", title: "Шлюз (PoEAA)" },
        { slug: "integration-styles-choice", title: "Стилі інтеграції як рішення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/web-backend/webhooks", title: "Webhooks (бік СПОЖИВАЧА)" },
        { slug: "dh-service-boundaries-final", title: "Фінал розкрою DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 19, slug: "messaging-and-eip", title: "Обмін повідомленнями й патерни інтеграції", scope: "", chapters: [
      { title: "Черги, pub/sub, журнал подій", steps: [
        { ref: "programming/distributed-systems/message-queue", title: "Черга повідомлень (point-to-point)" },
        { ref: "programming/distributed-systems/publish-subscribe", title: "Pub/sub (тема)" },
        { ref: "programming/distributed-systems/event-log", title: "Журнал подій (Kafka-модель)" },
        { ref: "programming/distributed-systems/competing-consumers", title: "Конкурентні споживачі" },
        { slug: "dh-message-classes", title: "Класи трафіку DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Enterprise Integration Patterns", steps: [
        { ref: "programming/distributed-systems/message-router", title: "Маршрутизатор повідомлень" },
        { ref: "programming/distributed-systems/message-translator", title: "Транслятор повідомлень і канонічна модель" },
        { ref: "programming/distributed-systems/dead-letter-queue", title: "Мертва черга" },
        { ref: "programming/distributed-systems/claim-check", title: "Квитанція в камері схову" },
      ] },
      { title: "Подієва архітектура, CQRS, event-sourcing", steps: [
        { ref: "programming/software-design/event-driven-architecture-distributed", title: "Подієва архітектура між сервісами" },
        { ref: "programming/software-design/cqrs", title: "CQRS" },
        { ref: "programming/software-design/event-sourcing", title: "Event sourcing" },
        { slug: "eventdriven-choice", title: "Вибір подієвого підходу", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Сага, outbox/inbox, ідемпотентні консюмери ГЛИБОКО", steps: [
        { ref: "programming/distributed-systems/saga-pattern", title: "Сага" },
        { ref: "programming/distributed-systems/outbox-pattern", title: "Transactional outbox" },
        { ref: "programming/distributed-systems/inbox-pattern", title: "Вхідна скринька (inbox)" },
        { ref: "programming/distributed-systems/idempotent-consumers-deep", title: "Ідемпотентні консюмери ГЛИБОКО" },
        { ref: "programming/distributed-systems/durable-workflows", title: "Durable workflows" },
        { slug: "saga-style-choice", title: "Вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-handover-saga", title: "Сага «сім'я продає дім»", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Рішення: твін дому", steps: [
        { slug: "dh-twin-variants", title: "Три варіанти твіна", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-twin-choice", title: "Вибір твіна", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 20, slug: "service-infrastructure-resilience", title: "Інфраструктура й стійкість зв'язку сервісів", scope: "", chapters: [
      { title: "Мережа сервісів", steps: [
        { ref: "programming/distributed-systems/sidecar", title: "Sidecar і Ambassador" },
        { ref: "programming/distributed-systems/service-mesh", title: "Сервісна сітка" },
        { ref: "programming/distributed-systems/control-data-plane", title: "Площина управління і площина даних" },
      ] },
      { title: "Стійкість виклику", steps: [
        { ref: "programming/distributed-systems/circuit-breaker", title: "Запобіжник" },
        { ref: "programming/distributed-systems/bulkhead-isolation", title: "Перебірки (bulkhead)" },
        { ref: "programming/distributed-systems/health-checks", title: "Перевірки живості й готовності" },
        { slug: "resilient-call-chain", title: "Стійкий ланцюжок A→B→C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "resilience-placement-choice", title: "Вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/operations/graceful-shutdown", title: "Штатне вимкнення і drain" },
        { ref: "programming/architecture-discipline/availability-tactics", title: "Тактики доступності" },
        { slug: "fallback-and-degradation", title: "Fallback і деградація виклику", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-resilient-path", title: "Стійкий шлях команди DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 21, slug: "nodes-identity-access", title: "Критичний вузол: хто ти й що тобі можна", scope: "", chapters: [
      { title: "Автентифікація й сесії", steps: [
        { ref: "programming/web-backend/authentication", title: "Автентифікація" },
        { ref: "programming/web-backend/jwt-tokens", title: "JWT і сесії без стану" },
        { ref: "programming/web-backend/session-management", title: "Сесія автентифікації" },
        { slug: "session-storage-choice", title: "Компакт-вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "auth-vs-authz-boundary", title: "Автентифікація проти авторизації", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Моделі авторизації", steps: [
        { ref: "programming/web-backend/authorization-models", title: "Моделі авторизації" },
        { ref: "programming/security/policy-as-code", title: "Політики як код" },
        { slug: "idor-horizontal-escalation", title: "Горизонтальна ескалація (IDOR) як загроза", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "authz-inservice-variant", title: "Варіант А", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "authz-central-variant", title: "Варіант Б", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "authz-choice", title: "Вибір-гібрид", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-auth-path", title: "Запит крізь DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 22, slug: "nodes-time-jobs-async", title: "Критичний вузол: час, фон, довгі операції", scope: "", chapters: [
      { title: "Прикладний час та i18n", steps: [
        { ref: "programming/web-backend/time-and-scheduling", title: "Прикладний час" },
        { ref: "programming/web-backend/monotonic-vs-wall-time", title: "Монотонний проти настінного часу для дедлайнів і тривалостей" },
        { ref: "programming/web-backend/recurrence-scheduling", title: "Рекурентність і календарна математика" },
        { ref: "programming/web-backend/i18n-as-architecture", title: "i18n як архітектура (не переклад)" },
      ] },
      { title: "Фонові джоби й розподілений cron", steps: [
        { ref: "programming/web-backend/background-jobs", title: "Черга задач" },
        { ref: "programming/distributed-systems/distributed-cron", title: "Розподілений cron" },
        { slug: "jobs-placement-variants", title: "Де живе черга задач", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "jobs-choice", title: "Вибір черги задач", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Довгі операції", steps: [
        { ref: "programming/web-backend/long-running-operations", title: "Довга операція" },
        { ref: "programming/web-backend/file-uploads", title: "Завантаження файлів як конвеєр" },
        { slug: "polling-vs-callback", title: "Поллінг проти колбека/вебхука для результату", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "time-storage-choice", title: "Як зберігати час", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-long-ops", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-jobs-time-final", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "async-work-recap", title: "Асинхронна робота як клас рішень", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 23, slug: "nodes-webhooks-notifications", title: "Критичний вузол: вихід назовні", scope: "", chapters: [
      { title: "Вебхуки", steps: [
        { ref: "programming/web-backend/webhook-provider", title: "Вебхуки як провайдер" },
        { ref: "programming/web-backend/webhook-security", title: "Підпис і верифікація вебхука" },
        { ref: "programming/web-backend/webhook-as-product", title: "Вебхук як продукт" },
        { slug: "dh-webhook-consumer", title: "DH як приймач-замовник вебхуків", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Сповіщення й fan-out", steps: [
        { ref: "programming/web-backend/notification-fanout", title: "Вузол сповіщень" },
        { ref: "programming/web-backend/notification-templating", title: "Шаблони й локалізація сповіщень" },
        { ref: "programming/distributed-systems/fan-out-strategies", title: "Fan-out on-write vs on-read" },
        { slug: "notification-dedup-throttle", title: "Дедуп, злиття й throttling сповіщень", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/client-architecture/push-notifications", title: "Push як канал ОС" },
        { ref: "programming/web-backend/delivery-tracking", title: "Відстеження доставки сповіщень" },
        { slug: "notification-fanout-choice", title: "Вибір моделі fan-out сповіщень DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "outbound-idempotency", title: "Ідемпотентність вихідної розмови", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-notification-pipeline", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "outbound-node-recap", title: "Вихід назовні як єдиний клас вузла", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 24, slug: "nodes-tenancy-billing-data", title: "Критичний вузол: оренда, гроші, життєвий цикл даних", scope: "", chapters: [
      { title: "Мультиарендність, білінг, гроші", steps: [
        { ref: "programming/distributed-systems/tenant-isolation", title: "Мультиарендність" },
        { slug: "tenancy-variants-choice", title: "Ізоляція орендарів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/web-backend/metering-and-billing", title: "Metering і billing як вузол" },
        { ref: "programming/web-backend/entitlements", title: "Entitlements / feature-gating за планом" },
        { ref: "programming/web-backend/payments-integration", title: "Платіжний провайдер" },
        { ref: "programming/databases/double-entry-ledger", title: "Гросбух" },
        { ref: "programming/distributed-systems/reconciliation", title: "Звірка" },
        { slug: "money-truth-choice", title: "Де живе правда про гроші", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Слід, видалення, пошук, ID", steps: [
        { ref: "programming/security/audit-logging", title: "Аудит-лог як вузол" },
        { ref: "programming/databases/soft-delete-tombstones", title: "М'яке видалення і надгробки" },
        { ref: "programming/web-backend/search-subsystem", title: "Пошук як друга правда" },
        { ref: "programming/databases/sequences-counters", title: "Людські номери й ID" },
        { slug: "data-lifecycle-node", title: "Життєвий цикл даних як вузол", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-data-lifecycle-final", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 25, slug: "resilience-tactics", title: "Тактики стійкості під навантаженням", scope: "", chapters: [
      { title: "Керування прийомом навантаження", steps: [
        { ref: "programming/distributed-systems/queue-load-leveling", title: "Черга як вирівнювач" },
        { ref: "programming/distributed-systems/admission-control", title: "Admission control" },
        { ref: "programming/distributed-systems/load-shedding", title: "Скидання навантаження і плавна деградація" },
        { ref: "programming/distributed-systems/graceful-degradation-primary", title: "Graceful degradation як ПЕРВИННА стратегія" },
        { ref: "programming/distributed-systems/adaptive-concurrency", title: "Адаптивні ліміти конкурентності" },
        { ref: "programming/distributed-systems/fairness-quotas", title: "Чесність розподілу" },
        { slug: "priority-and-shedding-choice", title: "Пріоритезація трафіку як рішення", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Приборкання хвостів і дублювання роботи", steps: [
        { ref: "programming/distributed-systems/hedged-requests", title: "Хеджовані запити" },
        { ref: "programming/distributed-systems/request-coalescing", title: "Request coalescing / single-flight" },
        { ref: "programming/distributed-systems/backpressure-end-to-end", title: "Наскрізний протитиск" },
      ] },
      { title: "Отруйні й позачергові повідомлення", steps: [
        { ref: "programming/distributed-systems/poison-message", title: "Poison message / карантин" },
        { ref: "programming/distributed-systems/out-of-order-tolerance", title: "Толерантність до безладу" },
        { slug: "dedup-boundary", title: "Дедуп на межі vs у логіці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/distributed-systems/replay-protection-tactics", title: "Захист від переграних повідомлень як тактика" },
      ] },
      { title: "Метастабільність і рекап", steps: [
        { ref: "programming/distributed-systems/metastable-failures", title: "Метастабільні відмови" },
        { slug: "dh-resilience-tactics-map", title: "Тактики стійкості DH разом", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 26, slug: "change-and-cache-tactics", title: "Обходи змін даних і кешу", scope: "", chapters: [
      { title: "Зміна живої системи без простою", steps: [
        { ref: "programming/software-design/branch-by-abstraction", title: "Branch by abstraction" },
        { ref: "programming/distributed-systems/zero-downtime-migration", title: "Zero-downtime міграції даних" },
        { ref: "programming/operations/dark-launch", title: "Темний запуск і feature-flag-міграція" },
        { ref: "programming/operations/parallel-run", title: "Parallel run" },
        { slug: "backfill-and-reprocess", title: "Backfill і reprocessing", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rollback-as-plan", title: "Rollback міграції як план, не надія", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Кеш-тактики й когерентність між сервісами", steps: [
        { ref: "programming/distributed-systems/cache-stampede", title: "Thundering herd / cache stampede і lock/coalescing" },
        { ref: "programming/distributed-systems/cache-tactics", title: "Дрібні кеш-тактики, що рятують проди" },
        { ref: "programming/distributed-systems/cache-key-design", title: "Дизайн ключів і гарячі ключі" },
        { ref: "programming/distributed-systems/cache-invalidation-patterns", title: "Патерни інвалідації" },
        { ref: "programming/distributed-systems/cache-coherence-services", title: "Кеш-когерентність МІЖ СЕРВІСАМИ" },
        { ref: "programming/distributed-systems/read-model-lag", title: "Лаг read-model як контракт" },
        { slug: "cache-coherence-choice", title: "Вибір стратегії свіжості між сервісами", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "stale-data-honestly", title: "Показати застаріле чесно", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-change-cache-final", title: "DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "migration-strategy-choice", title: "Вибір стратегії зміни живої системи", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 27, slug: "scale-and-load", title: "Високе навантаження й масштабування", scope: "", chapters: [
      { title: "Мова масштабу: хвости, черги, закони", steps: [
        { slug: "dh-fleet-envelope", title: "Прикидка на серветці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "math/statistics/percentiles-quantiles", title: "Перцентилі й хвости" },
        { ref: "math/probability/littles-law", title: "Закон Літтла" },
        { ref: "programming/distributed-systems/thundering-herd", title: "Гримуча отара на масштабі" },
      ] },
      { title: "Розподіл навантаження на вході", steps: [
        { ref: "programming/web-backend/sessions-state", title: "Сесії і stateless як передумова горизонталі" },
        { ref: "programming/distributed-systems/load-balancing", title: "Балансування L4 vs L7" },
        { ref: "programming/distributed-systems/reverse-proxy", title: "Зворотний проксі" },
        { slug: "load-distribution-dh", title: "Розподіл навантаження DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Край планети: CDN і кеш-ієрархія", steps: [
        { ref: "programming/distributed-systems/cdn", title: "CDN" },
        { ref: "communications/networks/anycast", title: "Anycast і глобальне балансування" },
        { ref: "programming/distributed-systems/distributed-cache", title: "Розподілений кеш (memcached/Redis-клас)" },
        { slug: "dh-cache-hierarchy", title: "Стан дому і список пристроїв крізь яруси кешу", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Еластичність і форми виконання", steps: [
        { ref: "programming/operations/autoscaling", title: "Автоскейл" },
        { ref: "programming/distributed-systems/cell-based-architecture", title: "Комірки і штампи" },
        { ref: "programming/operations/serverless-faas", title: "Serverless/FaaS" },
        { ref: "programming/distributed-systems/durable-workflows-scale", title: "Durable workflows на масштабі" },
        { slug: "compute-platform-choice", title: "Компакт-вибір compute", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "multi-region-topologies", title: "Топології мультирегіону", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/distributed-systems/data-residency", title: "Резидентність даних" },
        { slug: "dh-region-choice", title: "Компакт-вибір «планета DH»", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "metastable-and-scale-cases", title: "Розбори масштабу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sale-start-waiting-room", title: "Старт продажу на топ-концерт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/architecture-discipline/performance-tactics", title: "Тактики продуктивності" },
        { slug: "scale-decision-recap", title: "Коли масштабувати, а коли ні", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 28, slug: "security-architecture", title: "Безпека як архітектура", scope: "", chapters: [
      { title: "Моделювання загроз і межі довіри", steps: [
        { slug: "attacker-as-force", title: "Зловмисник як сила архітектури", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/security/threat-modeling", title: "Моделювання загроз" },
        { ref: "programming/security/trust-boundaries", title: "Межі довіри" },
        { ref: "programming/security/attack-surface", title: "Поверхня атаки" },
        { ref: "programming/security/web-vulnerability-classes", title: "Вразливість = зламана межа" },
        { ref: "programming/security/zero-trust", title: "Zero-trust" },
        { slug: "dh-threat-model", title: "Threat model Digital Homes", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Ідентичність, авторизація, секрети", steps: [
        { ref: "programming/security/least-privilege", title: "Найменші привілеї й deny-by-default" },
        { ref: "programming/security/password-hashing", title: "Зберігання паролів" },
        { ref: "programming/security/secrets-management", title: "Секрети й ротація" },
        { slug: "authz-in-depth", title: "Авторизація вглиб", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Крипто, ланцюг постачання, зловживання, безпечні дефолти", steps: [
        { ref: "communications/cryptographic-comm/public-key-crypto", title: "Криптографія з відкритим ключем" },
        { ref: "programming/security/encryption-at-rest", title: "Шифрування у спокої й ключі" },
        { ref: "programming/security/end-to-end-encryption", title: "Наскрізне шифрування" },
        { slug: "e2e-vs-serverside-choice", title: "E2E проти server-side", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/security/supply-chain-security", title: "Ланцюг постачання" },
        { ref: "programming/security/ddos-abuse-defense", title: "DDoS і зловживання" },
        { ref: "programming/security/rate-limiting", title: "Обмеження швидкості як архітектура" },
        { ref: "programming/security/secure-defaults", title: "Безпечні дефолти й відмова захисту" },
        { slug: "dh-leak-day", title: "День витоку DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 29, slug: "observability-and-operations", title: "Спостережність і експлуатація", scope: "", chapters: [
      { title: "Три стовпи спостережності", steps: [
        { ref: "programming/operations/structured-logging", title: "Структуровані логи" },
        { ref: "programming/operations/metrics-monitoring", title: "Метрики" },
        { ref: "programming/operations/distributed-tracing", title: "Розподілений трейсинг" },
        { slug: "dh-incident-observed", title: "Інцидент очима телеметрії DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Цілі рівня сервісу й бюджет помилок", steps: [
        { ref: "programming/operations/slo-sli-sla", title: "SLI/SLO/SLA і бюджет помилок" },
        { ref: "programming/operations/alerting", title: "Алерти" },
        { slug: "slo-from-drivers", title: "SLO з якісних атрибутів", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Доставка й розгортання", steps: [
        { ref: "programming/operations/ci-cd", title: "CI/CD" },
        { ref: "programming/operations/deployment-strategies", title: "Стратегії деплою" },
        { slug: "dh-canary-pipeline", title: "Конвеєр бекенда DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Субстрат і коли горить", steps: [
        { ref: "programming/operations/containers", title: "Контейнери" },
        { ref: "programming/operations/container-orchestration", title: "Оркестрація" },
        { ref: "programming/operations/infrastructure-as-code", title: "Інфраструктура як код" },
        { ref: "programming/operations/incident-response", title: "Реагування на інциденти" },
        { ref: "programming/operations/postmortems", title: "Постмортем без винних" },
        { ref: "programming/operations/chaos-engineering", title: "Хаос-інженерія" },
        { ref: "programming/operations/disaster-recovery", title: "Бекапи і DR" },
        { slug: "rozbir-roblox-73h", title: "Розбір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/architecture-discipline/operability-tactics", title: "Тактики експлуатованості й розгортуваності" },
        { slug: "dh-game-day", title: "Game day DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "algorithms/machine-learning/train-vs-inference", title: "Навчання ≠ вивід" },
        { ref: "programming/operations/model-artifact", title: "Модель як версійований артефакт" },
      ] },
    ] },
    { n: 30, slug: "conway-and-teams", title: "Закон Конвея й топології команд", scope: "", chapters: [
      { title: "Конвей і зворотний маневр", steps: [
        { ref: "programming/software-design/conways-law", title: "Закон Конвея" },
        { ref: "programming/architecture-discipline/inverse-conway", title: "Inverse Conway maneuver" },
        { ref: "programming/architecture-discipline/communication-paths", title: "Комунікаційні шляхи як обмеження архітектури" },
        { slug: "dh-conway-map", title: "Мапа команд DH проти мапи контекстів", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Топології команд і навантаження", steps: [
        { ref: "programming/architecture-discipline/team-topologies", title: "Team topologies" },
        { ref: "programming/architecture-discipline/cognitive-load-teams", title: "Когнітивне навантаження команди як межа розміру сервісу" },
        { ref: "programming/architecture-discipline/platform-engineering", title: "Платформна інженерія" },
        { slug: "cognitive-load-as-boundary", title: "Когнітивне навантаження як критерій розкрою", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-team-topology-choice", title: "Топологія команд DH", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "handoffs-and-ownership", title: "Передачі й володіння як джерело затримки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "platform-vs-premature", title: "Платформа проти передчасної платформи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "org-as-architecture", title: "Організація як архітектура", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 31, slug: "cost-and-lock-in", title: "Гроші, залежність, вибір постачальника", scope: "", chapters: [
      { title: "Хмарна економіка й вартість виходу", steps: [
        { ref: "programming/architecture-discipline/cloud-cost-model", title: "Cloud cost як архітектурний драйвер" },
        { ref: "programming/architecture-discipline/finops-levers", title: "FinOps-важелі" },
        { ref: "programming/architecture-discipline/lock-in-exit-cost", title: "Прив'язка і вартість виходу" },
        { slug: "exit-strategy", title: "Стратегія виходу як частина вибору", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rozbir-cloud-or-metal", title: "Розбір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "build-vs-buy-mature", title: "Build vs buy у зрілій оптиці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { ref: "programming/architecture-discipline/tech-radar", title: "Техрадар" },
        { ref: "programming/operations/capacity-planning", title: "Планування потужностей і headroom" },
        { slug: "overengineering", title: "Перепроєктування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cost-as-fitness-function", title: "Вартість як fitness-функція в CI", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "economics-decision-recap", title: "Економіка рішення як рамка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-cost-decisions", title: "Економічні рішення DH", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
    { n: 32, slug: "legacy-and-evolution", title: "Легасі, ерозія, стратегії переходу + КАПСТОН", scope: "", chapters: [
      { title: "Ерозія й археологія legacy", steps: [
        { ref: "programming/architecture-discipline/architecture-erosion", title: "Ерозія архітектури" },
        { ref: "programming/architecture-discipline/legacy-archaeology", title: "Археологія legacy" },
        { slug: "reading-unknown-system", title: "Прийшов у чужу систему", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Переписати, обгорнути чи оздоровити", steps: [
        { ref: "programming/architecture-discipline/rewrite-vs-refactor", title: "Rewrite vs refactor" },
        { ref: "programming/software-design/strangler-fig", title: "Strangler fig" },
        { ref: "programming/architecture-discipline/deprecation-policy", title: "Deprecation як керований процес" },
        { slug: "migration-choice", title: "Вибір стратегії переходу великого", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-cloud-v2", title: "DH переїздить", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Наскрізний кейс (капстон-синтез)", steps: [
        { slug: "request-journey-final", title: "Життя одного запиту і однієї команди", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dh-platform-retrospective", title: "Ретроспектива Digital Homes", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "capstone-setup", title: "Капстон, крок 1", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "capstone-shape-data", title: "Капстон, крок 2", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "capstone-services-nodes", title: "Капстон, крок 3", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "capstone-scale-secure-ops", title: "Капстон, крок 4", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "capstone-org-evolution", title: "Капстон, крок 5", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
      { title: "Смак архітектора", steps: [
        { slug: "architect-taste", title: "Смак архітектора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "architect-checklist", title: "Чеклист архітектора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "decision-heuristics", title: "Евристики рішення на щодень", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "where-next", title: "Куди рости після progarch", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "course-farewell", title: "Прощання з курсом", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    ] },
  ]
});
