/* embedded/block-1-circuits-physics/manifest.js — per-module маніфест Модуля 1.
   Єдине джерело: навігація + план + черга + статуси. Складає scripts/bookbuild.js
   (histories[]/extras[] ВИВОДЯТЬСЯ з topics[]). Нумерація — М.Р.Т. */
(window.__MODREG__ = window.__MODREG__ || []).push({
  n: 1,
  slug: "block-1-circuits-physics",
  title: "Фізика електрики й кіл",
  chapters: [
    {
      n: 1,
      title: "Заряд, електричне поле й потенціал",
      dir: "block-1-circuits-physics/charge-field-potential",
      main: "charge-field-potential.md",
      status: "done",
      scope: "Електричний заряд; сила й поле; потенціал і робота; напруга як різниця потенціалів; чому напругу міряють між двома точками.",
      topics: [
        { mrt: "1.1.1", title: "Заряд — фундаментальна властивість матерії", status: "done" },
        { mrt: "1.1.2", title: "Сила між зарядами: закон Кулона", status: "done" },
        { mrt: "1.1.3", title: "Поле: посередник між зарядами", status: "done" },
        { mrt: "1.1.4", title: "Робота, потенціальна енергія й потенціал", status: "done" },
        { mrt: "1.1.5", title: "Головна думка: вольт — це джоуль на кулон", status: "done" },
        { mrt: "1.1.6", title: "Поле й потенціал — одне явище двома мовами", status: "done" },
        { mrt: "1.1.7", title: "Зведення докупи", status: "done" },
        { mrt: "1.1.8", title: "Клітка Фарадея й екранування", status: "done" },
        { kind: "hist", file: "hist-electricity.md", at: "chapter", status: "done", title: "Історія: оглядова" },
        { kind: "hist", file: "hist-millikan.md", at: "1.1.1", status: "done", title: "Мілікен і краплі олії: як «зважили» заряд електрона" },
        { kind: "hist", file: "hist-coulomb.md", at: "1.1.2", status: "done", title: "Кулон і крутильні терези" },
        { kind: "hist", file: "hist-faraday.md", at: "1.1.3", status: "done", title: "Фарадей — палітурник, що вигадав поле" },
        { kind: "hist", file: "hist-volta.md", at: "1.1.5", status: "done", title: "Вольта проти Гальвані" },
        { kind: "comp", file: "comp-van-de-graaff.md", at: "1.1.2", status: "done", title: "Генератор Ван де Граафа: сотні кіловольт із гумової стрічки" },
        { kind: "math", file: "math-vectors.md", at: "1.1.2", status: "done", title: "Вектори: додавання сил і суперпозиція в координатах" },
        { kind: "math", file: "math-work-integral.md", at: "1.1.4", status: "done", title: "Робота як інтеграл: площа під кривою сили" },
        { kind: "comp", file: "comp-alkaline-cell.md", at: "1.1.5", status: "done", title: "Лужна батарейка AA зсередини: цинк, MnO₂ і чому саме 1.5 В" },
        { kind: "comp", file: "comp-piezo-igniter.md", at: "1.1.5", status: "done", title: "П'єзозапальничка: кіловольти з удару по кристалу" },
        { kind: "math", file: "../../../math/number-systems/dimensional-analysis/dimensional-analysis.md", at: "1.1.5", status: "done", title: "Аналіз розмірностей: як ловити помилки у формулах" },
        { kind: "math", file: "../../../math/number-systems/si-prefixes/si-prefixes.md", at: "1.1.5", status: "done", title: "Префікси СІ та інженерна нотація" },
        { kind: "math", file: "math-gradient.md", at: "1.1.6", status: "done", title: "Градієнт: із карти потенціалу — у вектор поля" },
        { kind: "proj", file: "proj-relaxation.md", at: "1.1.6", status: "done", title: "Потенціал на сітці: метод релаксації для рівняння Лапласа" },
        { kind: "comp", file: "comp-everyday-shields.md", at: "1.1.8", status: "done", title: "Екран навколо нас: металевий корпус, сітка мікрохвильовки, фольга" }
      ]
    },
    {
      n: 2,
      title: "Напруга, струм і провідність",
      dir: "block-1-circuits-physics/voltage-current-conduction",
      main: "voltage-current-conduction.md",
      status: "done",
      scope: "Струм як потік заряду; провідність у металах (вільні електрони, дрейфова швидкість проти швидкості поля ≈ c); напрямок струму; джерела ЕРС.",
      topics: [
        { mrt: "1.2.1", title: "Струм — це потік заряду", status: "done" },
        { mrt: "1.2.2", title: "Куди «тече» струм: умовний напрямок проти руху електронів", status: "done" },
        { mrt: "1.2.3", title: "Що рухається в металі: море електронів і повільний дрейф", status: "done" },
        { mrt: "1.2.4", title: "Парадокс: чому лампа спалахує миттєво, хоч електрони повзуть", status: "done" },
        { mrt: "1.2.5", title: "Струм не «витрачається»: він однаковий уздовж кола", status: "done" },
        { mrt: "1.2.6", title: "Напруга — причина струму", status: "done" },
        { mrt: "1.2.7", title: "Замкнене коло: чому струму потрібна петля", status: "done" },
        { mrt: "1.2.8", title: "Чому одні матеріали проводять, а інші ні", status: "done" },
        { mrt: "1.2.9", title: "Зіткнення й нагрів: звідки береться опір руху", status: "done" },
        { mrt: "1.2.10", title: "Провідність як властивість матеріалу і вплив температури", status: "done" },
        { mrt: "1.2.11", title: "Не лише метали: іони, електроліти, плазма, тіло людини", status: "done" },
        { mrt: "1.2.12", title: "Постійний і змінний струм (DC vs AC)", status: "done" },
        { mrt: "1.2.13", title: "Струм і безпека: чому небезпечний саме струм", status: "done" },
        { kind: "hist", file: "hist-conduction.md", at: "chapter", status: "done", title: "Що тече в дроті — від Ома до Друде" },
        { kind: "hist", file: "hist-ampere.md", at: "1.2.1", status: "done", title: "Ампер і 1820 рік: народження електродинаміки" },
        { kind: "hist", file: "hist-atlantic-cable.md", at: "1.2.4", status: "done", title: "Трансатлантичний кабель 1858 року: сигнал швидкий, але не миттєвий" },
        { kind: "hist", file: "hist-arrhenius.md", at: "1.2.11", status: "done", title: "Арреніус та іони" },
        { kind: "hist", file: "hist-war-of-currents.md", at: "1.2.12", status: "done", title: "Війна струмів" },
        { kind: "hist", file: "hist-dalziel.md", at: "1.2.13", status: "done", title: "Чарльз Далзіел: людина, що виміряла небезпечний струм і створила GFCI" },
        { kind: "math", file: "math-derivative.md", at: "1.2.1", status: "done", title: "I = dQ/dt: похідна як миттєва швидкість зміни" },
        { kind: "math", file: "math-estimation.md", at: "1.2.3", status: "done", title: "Оцінки порядків величин: рахунок «на серветці»" },
        { kind: "comp", file: "comp-switches.md", at: "1.2.7", status: "done", title: "Вимикачі й кнопки: полюси й напрямки (SPST/SPDT), контакти NO/NC" },
        { kind: "comp", file: "comp-galvanic-corrosion.md", at: "1.2.11", status: "done", title: "Гальванічна корозія: чому не можна скручувати мідь з алюмінієм" },
        { kind: "comp", file: "comp-rcd.md", at: "1.2.13", status: "done", title: "ПЗВ (RCD): прилад, що порівнює струм «туди» і «назад»" }
      ]
    },
    {
      n: 3,
      title: "Опір, потужність і тепло",
      dir: "block-1-circuits-physics/resistance-power-heat",
      main: "resistance-power-heat.md",
      status: "done",
      scope: "Закон Ома як властивість матеріалу; питомий опір і температура; потужність P = U·I = I²·R; нагрів, теплові межі, чому компоненти мають номінали; запобіжники й PTC; тепловий опір (°C/Вт) і радіатор.",
      topics: [
        { mrt: "1.3.1", title: "Опір: спротив струму й звідки він", status: "done" },
        { mrt: "1.3.2", title: "Закон Ома: I = V/R", status: "done" },
        { mrt: "1.3.3", title: "Від чого залежить опір: матеріал, довжина, переріз", status: "done" },
        { mrt: "1.3.4", title: "Опір і температура", status: "done" },
        { mrt: "1.3.5", title: "Потужність: P = V·I", status: "done" },
        { mrt: "1.3.6", title: "Джоулеве тепло: чому й скільки гріється", status: "done" },
        { mrt: "1.3.7", title: "Резистор як компонент: номінал, допустима потужність, добір і запас", status: "done" },
        { mrt: "1.3.8", title: "Запобіжники й самовідновні PTC: захист від надструму", status: "done" },
        { mrt: "1.3.9", title: "Тепловий опір і радіатор (°C/Вт): куди подіти ват", status: "done" },
        { mrt: "1.3.10", title: "Три шляхи тепла: кондукція, конвекція, випромінювання", status: "done" },
        { kind: "hist", file: "hist-ohm-joule.md", at: "chapter", status: "done", title: "Ом і Джоуль" },
        { kind: "hist", file: "hist-filament.md", at: "1.3.4", status: "done", title: "Полювання на нитку: від вугільного бамбука Едісона до вольфраму Кулиджа" },
        { kind: "hist", file: "hist-superconductivity.md", at: "1.3.4", status: "done", title: "Надпровідність — Камерлінг-Оннес, 1911" },
        { kind: "hist", file: "hist-watt.md", at: "1.3.5", status: "done", title: "Джеймс Уатт і «кінська сила»" },
        { kind: "hist", file: "hist-fuse.md", at: "1.3.8", status: "done", title: "Народження запобіжника: телеграфні лінії й освітлювальна система Едісона" },
        { kind: "comp", file: "../../../components/passive/wire-gauge/wire-gauge.md", at: "1.3.3", status: "done", title: "Дроти: переріз, AWG, допустимий струм" },
        { kind: "comp", file: "../../../components/protection/inrush-ntc/inrush-ntc.md", at: "1.3.4", status: "done", title: "NTC проти кидка струму: термістор на вході блока живлення" },
        { kind: "math", file: "../../../math/number-systems/energy-units/energy-units.md", at: "1.3.5", status: "done", title: "кВт·год, мА·год і джоулі: арифметика енергії та середньої потужності" },
        { kind: "comp", file: "../../../components/passive/resistor-marking/resistor-marking.md", at: "1.3.7", status: "done", title: "Як прочитати резистор: кольорові кільця й SMD-коди" },
        { kind: "comp", file: "../../../components/passive/kelvin-shunt/kelvin-shunt.md", at: "1.3.7", status: "done", title: "Шунти й силові резистори: міліоми та 4-провідне підключення Кельвіна" },
        { kind: "math", file: "../../../math/number-systems/e-series/e-series.md", at: "1.3.7", status: "done", title: "Ряди номіналів E12/E24/E96: геометрична прогресія з кроком під допуск" },
        { kind: "comp", file: "../../../components/protection/fuse-types/fuse-types.md", at: "1.3.8", status: "done", title: "Запобіжник як компонент: корпуси, швидкі/повільні (F/T), вибір номіналу" },
        { kind: "comp", file: "../../../components/passive/heatsink/heatsink.md", at: "1.3.9", status: "done", title: "Радіатори, термопаста й термопрокладки: тепловий шлях" },
        { kind: "math", file: "math-thermal-rc.md", at: "1.3.9", status: "done", title: "Теплова RC-модель: стала часу нагріву й чому короткий імпульс не страшний" },
        { kind: "comp", file: "../../../components/passive/peltier/peltier.md", at: "1.3.10", status: "done", title: "Елемент Пельтьє: качати тепло струмом" }
      ]
    },
    {
      n: 4,
      title: "Закони Кірхгофа й аналіз кіл",
      dir: "block-1-circuits-physics/kirchhoff-circuit-analysis",
      main: "kirchhoff-circuit-analysis.md",
      status: "done",
      scope: "Закони струмів і напруг як збереження заряду/енергії; послідовне/паралельне з'єднання; дільник напруги й струму; розв'язання простого кола.",
      topics: [
        { mrt: "1.4.1", title: "Вузли, гілки, контури — мова кіл", status: "done" },
        { mrt: "1.4.2", title: "Закон струмів Кірхгофа (KCL)", status: "done" },
        { mrt: "1.4.3", title: "Закон напруг Кірхгофа (KVL)", status: "done" },
        { mrt: "1.4.4", title: "Послідовне з'єднання", status: "done" },
        { mrt: "1.4.5", title: "Паралельне з'єднання", status: "done" },
        { mrt: "1.4.6", title: "Дільник напруги", status: "done" },
        { mrt: "1.4.7", title: "Дільник струму", status: "done" },
        { mrt: "1.4.8", title: "Як розв'язувати коло: метод і приклади", status: "done" },
        { mrt: "1.4.9", title: "Міст Вітстона", status: "done" },
        { kind: "hist", file: "hist-kirchhoff.md", at: "chapter", status: "done", title: "Кірхгоф — узагальнення Ома" },
        { kind: "hist", file: "hist-euler-graphs.md", at: "1.4.1", status: "done", title: "Ейлер і кенігсберзькі мости" },
        { kind: "hist", file: "hist-maxwell-mesh.md", at: "1.4.8", status: "done", title: "Контурні струми Максвелла: менше рівнянь — швидший розв'язок" },
        { kind: "hist", file: "hist-christie-wheatstone.md", at: "1.4.9", status: "done", title: "Міст, названий не за винахідником: Крісті й Вітстон" },
        { kind: "comp", file: "comp-breadboard.md", at: "1.4.1", status: "done", title: "Макетна плата (breadboard) зсередини: які гнізда вже з'єднані" },
        { kind: "math", file: "../../../math/discrete-logic/graph-theory/graph-theory.md", at: "1.4.1", status: "done", title: "Графи: вершини, ребра й матриці інцидентності" },
        { kind: "proj", file: "proj-graph-traversal.md", at: "1.4.1", status: "done", title: "Обхід графа: DFS/BFS і пошук незалежних контурів" },
        { kind: "comp", file: "../../../components/passive/potentiometer/potentiometer.md", at: "1.4.6", status: "done", title: "Потенціометр і тример: дільник, який можна крутити" },
        { kind: "math", file: "math-tolerance.md", at: "1.4.6", status: "done", title: "Допуски складаються: похибка дільника з реальних резисторів" },
        { kind: "proj", file: "proj-divider-search.md", at: "1.4.6", status: "done", title: "Добір пари зі стандартного ряду: перебір E24 під задане співвідношення" },
        { kind: "math", file: "../../../math/linear-algebra/gauss-elimination/gauss-elimination.md", at: "1.4.8", status: "done", title: "Системи лінійних рівнянь: метод Гаусса руками" },
        { kind: "math", file: "../../../math/linear-algebra/matrices-as-operations/matrices-as-operations.md", at: "1.4.8", status: "done", title: "Матриця як машина перетворень: множення і чому порядок важить" },
        { kind: "proj", file: "proj-circuit-sim.md", at: "1.4.8", status: "done", title: "Симулятор кіл (CircuitJS-клас): перевірити коло до паяння" },
        { kind: "proj", file: "proj-mna-spice.md", at: "1.4.8", status: "done", title: "Як SPICE розв'язує кола: модифікований вузловий аналіз (MNA)" },
        { kind: "math", file: "math-bridge-sensitivity.md", at: "1.4.9", status: "done", title: "Чутливість мосту: лінеаризація біля балансу" }
      ]
    },
    {
      n: 5,
      title: "Еквівалентні схеми: Тевенін, Нортон, суперпозиція",
      dir: "block-1-circuits-physics/equivalent-circuits",
      main: "equivalent-circuits.md",
      status: "done",
      scope: "Реальне джерело й внутрішній опір; згортання складного кола у просте; принцип суперпозиції; узгодження й передача потужності.",
      topics: [
        { mrt: "1.5.1", title: "Реальне джерело: внутрішній опір", status: "done" },
        { mrt: "1.5.2", title: "Принцип суперпозиції в колах", status: "done" },
        { mrt: "1.5.3", title: "Теорема Тевеніна", status: "done" },
        { mrt: "1.5.4", title: "Теорема Нортона: двоїстість", status: "done" },
        { mrt: "1.5.5", title: "Як знайти еквівалент: Vth, Rth", status: "done" },
        { mrt: "1.5.6", title: "Узгодження й максимальна передача потужності", status: "done" },
        { kind: "hist", file: "hist-thevenin-norton.md", at: "chapter", status: "done", title: "Тевенін і Нортон" },
        { kind: "hist", file: "hist-50-ohm.md", at: "1.5.6", status: "done", title: "Звідки взялися 50 Ом: компроміс коаксіального кабелю" },
        { kind: "comp", file: "comp-source-impedances.md", at: "1.5.1", status: "done", title: "Внутрішній опір у цифрах: AA, «крона», Li-Ion, USB-порт" },
        { kind: "math", file: "math-load-line.md", at: "1.5.1", status: "done", title: "Лінія навантаження: графічний розв'язок на площині V–I" },
        { kind: "math", file: "../../../math/discrete-logic/superposition/superposition.md", at: "1.5.2", status: "done", title: "Лінійність формально: адитивність і однорідність" },
        { kind: "proj", file: "proj-two-load-method.md", at: "1.5.5", status: "done", title: "Виміряти Vth і Rth на столі: метод двох навантажень" },
        { kind: "comp", file: "comp-terminator.md", at: "1.5.6", status: "done", title: "Термінатор і атенюатор: «заглушки» з коробки осцилографа" },
        { kind: "math", file: "math-derivative-max.md", at: "1.5.6", status: "done", title: "Максимум через похідну: dP/dR = 0" }
      ]
    },
    {
      n: 6,
      title: "Мова схем і вимірювання",
      dir: "block-1-circuits-physics/schematics-measurement",
      main: "schematics-measurement.md",
      status: "done",
      scope: "Як читати принципову схему (символи, вузли, землі, нети) — старт схемної грамотності; мультиметр і осцилограф — що й як вони міряють; логічний аналізатор; лабораторний блок живлення (CC/CV).",
      topics: [
        { mrt: "1.6.1", title: "Навіщо принципова схема", status: "done" },
        { mrt: "1.6.2", title: "Умовні позначення компонентів", status: "done" },
        { mrt: "1.6.3", title: "Вузли, з'єднання й перетини", status: "done" },
        { mrt: "1.6.4", title: "«Земля» та шини живлення", status: "done" },
        { mrt: "1.6.5", title: "Як читати схему", status: "done" },
        { mrt: "1.6.6", title: "Мультиметр: що і як він міряє", status: "done" },
        { mrt: "1.6.7", title: "Осцилограф: побачити сигнал у часі", status: "done" },
        { mrt: "1.6.8", title: "Похибки й безпека вимірювань", status: "done" },
        { mrt: "1.6.9", title: "Логічний аналізатор: побачити багато цифрових ліній", status: "done" },
        { mrt: "1.6.10", title: "Лабораторний блок живлення: режими CC/CV", status: "done" },
        { kind: "hist", file: "hist-instruments.md", at: "chapter", status: "done", title: "Гальванометр і вимірювальні прилади" },
        { kind: "hist", file: "hist-earth-return.md", at: "1.6.4", status: "done", title: "Чому «земля» — таки земля: телеграф із поверненням через ґрунт" },
        { kind: "hist", file: "hist-weston.md", at: "1.6.6", status: "done", title: "Едвард Вестон" },
        { kind: "hist", file: "hist-crt.md", at: "1.6.7", status: "done", title: "Браун і ЕПТ" },
        { kind: "hist", file: "hist-tektronix.md", at: "1.6.7", status: "done", title: "Tektronix і Говард Воллум: тригерна розгортка" },
        { kind: "comp", file: "comp-workbench.md", at: "chapter", status: "done", title: "Майстерня з нуля: три рівні бюджету верстака" },
        { kind: "proj", file: "proj-netlist-erc.md", at: "1.6.3", status: "done", title: "Нетлист і ERC: як редактор схем «бачить» вузли" },
        { kind: "comp", file: "comp-multimeter.md", at: "1.6.6", status: "done", title: "Мультиметр як компонент лабораторії: діапазони, вхідні опори, режими" },
        { kind: "comp", file: "comp-oscilloscope.md", at: "1.6.7", status: "done", title: "Осцилограф зблизька: канали, розгортка, вхідні режими AC/DC" },
        { kind: "comp", file: "comp-probe.md", at: "1.6.7", status: "done", title: "Щуп 1×/10×: дільник, ємність кабелю й компенсація" },
        { kind: "proj", file: "proj-trigger.md", at: "1.6.7", status: "done", title: "Тригер: алгоритм, що зупиняє хвилю на екрані" },
        { kind: "comp", file: "comp-cat-ratings.md", at: "1.6.8", status: "done", title: "Категорії CAT I–IV: чому дешевим мультиметром не лізуть у щиток" },
        { kind: "comp", file: "comp-probe-ground.md", at: "1.6.8", status: "done", title: "Земля щупа — це земля розетки: як не спалити осцилограф; диференційний щуп" },
        { kind: "math", file: "math-accuracy.md", at: "1.6.8", status: "done", title: "±(% + одиниці молодшого розряду): арифметика похибок мультиметра" }
      ]
    },
    {
      n: 7,
      title: "Змінний струм: синусоїда, фаза й RMS",
      dir: "block-1-circuits-physics/ac-signals",
      main: "ac-signals.md",
      status: "done",
      scope: "Чому коливання синусоїдні; амплітуда, період, частота; фаза і зсув фаз; середнє й діюче значення (RMS) — чому 230 В із розетки це RMS; читання синусоїди на осцилографі; чому енергомережа змінна.",
      topics: [
        { mrt: "1.7.1", title: "Чому синусоїда: природна форма коливань", status: "done" },
        { mrt: "1.7.2", title: "Амплітуда, період, частота", status: "done" },
        { mrt: "1.7.3", title: "Фаза й зсув фаз", status: "done" },
        { mrt: "1.7.4", title: "Середнє й діюче значення (RMS)", status: "done" },
        { mrt: "1.7.5", title: "Синусоїда на осцилографі", status: "done" },
        { mrt: "1.7.6", title: "Чому мережа змінна: транспорт енергії", status: "done" },
        { kind: "hist", file: "hist-steinmetz.md", at: "chapter", status: "done", title: "Штейнмец і математика змінного струму" },
        { kind: "hist", file: "hist-50-60-hz.md", at: "1.7.2", status: "done", title: "Чому 50 і 60 Гц: як світ розколовся на дві частоти" },
        { kind: "math", file: "math-trigonometry.md", at: "1.7.1", status: "done", title: "Синус і коло: тригонометрія обертання" },
        { kind: "proj", file: "proj-phase-accumulator.md", at: "1.7.1", status: "done", title: "Синус у коді: таблиця відліків і фазовий акумулятор" },
        { kind: "comp", file: "comp-signal-generator.md", at: "1.7.2", status: "done", title: "Генератор сигналів: синус, меандр і трикутник на вимогу" },
        { kind: "math", file: "math-phasor.md", at: "1.7.3", status: "done", title: "Фазор: синусоїда як вектор, що обертається" },
        { kind: "math", file: "math-rms-derivation.md", at: "1.7.4", status: "done", title: "Звідки √2: середнє від sin² за період" },
        { kind: "proj", file: "proj-true-rms.md", at: "1.7.4", status: "done", title: "True RMS у приладі: квадрат → середнє → корінь" },
        { kind: "comp", file: "comp-mains-socket.md", at: "1.7.6", status: "done", title: "Розетка: фаза, нуль, захисний провідник і 230 В RMS" }
      ]
    },
    {
      n: 8,
      title: "Магнетизм і електромагніти",
      dir: "block-1-circuits-physics/magnetism",
      main: "magnetism.md",
      status: "done",
      scope: "Магніти й поле B; магнетизм матерії й постійні магніти; струм народжує поле й електромагніт; осердя, насичення й гістерезис; сила Ампера, ефект Холла й електромагнітна індукція.",
      topics: [
        { mrt: "1.8.1", title: "Магніти й поле B: полюси, силові лінії, чому немає монополів", status: "done" },
        { mrt: "1.8.2", title: "Магнетизм матерії: домени й феромагнетики", status: "done" },
        { mrt: "1.8.3", title: "Постійні магніти: ферит і неодим", status: "done" },
        { mrt: "1.8.4", title: "Струм народжує поле: дослід Ерстеда й правило правої руки", status: "done" },
        { mrt: "1.8.5", title: "Електромагніт: котушка, осердя, ампер-витки", status: "done" },
        { mrt: "1.8.6", title: "Осердя, насичення й гістерезис", status: "done" },
        { mrt: "1.8.7", title: "Сила Ампера: поле штовхає провідник зі струмом", status: "done" },
        { mrt: "1.8.8", title: "Ефект Холла: поле відхиляє носії в провіднику", status: "done" },
        { mrt: "1.8.9", title: "Магнітне поле Землі й компас", status: "done" },
        { mrt: "1.8.10", title: "Електромагнітна індукція: закон Фарадея, правило Ленца, вихрові струми", status: "done" },
        { kind: "hist", file: "hist-lodestone-oersted.md", at: "chapter", status: "done", title: "Від магнітного каменю до Ерстеда: дві тисячі років компаса" },
        { kind: "hist", file: "hist-neodymium.md", at: "1.8.3", status: "done", title: "1984: неодимовий магніт відкривають двічі — Сагава і Кроут" },
        { kind: "hist", file: "hist-hall.md", at: "1.8.8", status: "done", title: "Едвін Холл: ефект, відкритий за 18 років до електрона" },
        { kind: "comp", file: "../../../components/passive/magnet-grades/magnet-grades.md", at: "1.8.3", status: "done", title: "Ферит проти неодиму: класи N35–N52, крихкість, корозія й температурні межі" },
        { kind: "proj", file: "proj-biot-savart.md", at: "1.8.4", status: "done", title: "Поле довільного контуру чисельно: складаємо внески за Біо—Саваром" },
        { kind: "comp", file: "../../../components/interfaces/solenoid-relay/solenoid-relay.md", at: "1.8.5", status: "done", title: "Реле, соленоїд, електромагнітний клапан: електромагніт як актуатор" },
        { kind: "math", file: "math-ampere-turns.md", at: "1.8.5", status: "done", title: "Ампер-витки: оцінити поле котушки із закону Ампера" },
        { kind: "comp", file: "../../../components/passive/ferrite-bead/ferrite-bead.md", at: "1.8.6", status: "done", title: "Осердя дроселів і трансформаторів: фізика феритів" },
        { kind: "math", file: "math-hysteresis-loop.md", at: "1.8.6", status: "done", title: "Петля B–H кількісно: площа петлі = втрати за цикл" },
        { kind: "math", file: "math-cross-product.md", at: "1.8.7", status: "done", title: "Векторний добуток: математика правил правої і лівої руки" },
        { kind: "comp", file: "../../../components/sensors/clamp-meter/clamp-meter.md", at: "1.8.8", status: "done", title: "Струмові кліщі: виміряти ампери, не розриваючи кола" }
      ]
    },
    {
      n: 9,
      title: "Шум і завади: фізичні джерела",
      dir: "block-1-circuits-physics/noise-interference",
      main: "noise-interference.md",
      status: "done",
      scope: "Внутрішні джерела шуму (тепловий, дробовий, 1/f) проти зовнішніх наводок (ємнісних, індуктивних); земляні петлі, екранування й вита пара; полювання на заваду осцилографом.",
      topics: [
        { mrt: "1.9.1", title: "Шум і завада: чому жоден сигнал не ідеальний", status: "done" },
        { mrt: "1.9.2", title: "Тепловий шум Джонсона—Найквіста: межа, яку не можна вимкнути", status: "done" },
        { mrt: "1.9.3", title: "Дробовий шум і шум 1/f", status: "done" },
        { mrt: "1.9.4", title: "Наводка через електричне поле: ємнісний зв'язок і гул 50 Гц", status: "done" },
        { mrt: "1.9.5", title: "Наводка через магнітне поле: індуктивний зв'язок і площа петлі", status: "done" },
        { mrt: "1.9.6", title: "Спільний шлях повернення: земляні петлі й спільний імпеданс", status: "done" },
        { mrt: "1.9.7", title: "Екран у дії: клітка Фарадея для сигналу", status: "done" },
        { mrt: "1.9.8", title: "Вита пара: геометрія проти наводок", status: "done" },
        { mrt: "1.9.9", title: "Полювання на заваду з осцилографом: упізнати джерело за формою", status: "done" },
        { kind: "hist", file: "hist-johnson-nyquist.md", at: "chapter", status: "done", title: "Джонсон і Найквіст: шум, що виявився властивістю самої матерії" },
        { kind: "hist", file: "hist-induction-coordination.md", at: "1.9.4", status: "done", title: "Гул у слухавці: як телефоністи воювали з силовими лініями" },
        { kind: "hist", file: "hist-twisted-pair.md", at: "1.9.8", status: "done", title: "Телефон проти телеграфу: як Белл запатентував звивання (1881)" },
        { kind: "math", file: "math-clt.md", at: "1.9.1", status: "done", title: "Центральна гранична теорема: чому шум гаусів" },
        { kind: "math", file: "math-random-variables.md", at: "1.9.1", status: "done", title: "Випадкова величина: середнє, σ і гаусів розподіл" },
        { kind: "proj", file: "proj-noise-generator.md", at: "1.9.1", status: "done", title: "Шум у коді: від rand() до гаусового (Бокс—Мюллер)" },
        { kind: "math", file: "math-kt-scale.md", at: "1.9.2", status: "done", title: "kT як універсальний масштаб: 26 меВ і больцманівський фактор" },
        { kind: "math", file: "math-noise-density.md", at: "1.9.2", status: "done", title: "нВ/√Гц: спектральна густина шуму — мова даташитів" },
        { kind: "comp", file: "comp-resistor-noise.md", at: "1.9.3", status: "done", title: "Шумлять і резистори: вуглецеві проти металоплівкових" },
        { kind: "comp", file: "comp-star-ground.md", at: "1.9.6", status: "done", title: "Розводка «землі» на макетці: зірка проти ланцюжка" },
        { kind: "comp", file: "../../../components/comms/shielded-cable/shielded-cable.md", at: "1.9.7", status: "done", title: "Коаксіал і екранований сигнальний кабель: будова й де заземлювати екран" },
        { kind: "comp", file: "../../../components/comms/utp-cable/utp-cable.md", at: "1.9.8", status: "done", title: "UTP/FTP зсередини: категорії, крок звивання, екран" },
        { kind: "math", file: "math-averaging.md", at: "1.9.9", status: "done", title: "Чому усереднення працює: σ/√N" }
      ]
    },
    {
      n: 10,
      title: "Електростатика на практиці: іскри, блискавка й ESD",
      dir: "block-1-circuits-physics/esd-static",
      main: "esd-static.md",
      status: "done",
      scope: "Трибоелектрика в побуті; тіло як накопичувач заряду; пробій повітря, корона й блискавка; приховані ESD-пошкодження мікросхем; антистатичне робоче місце, пакування й керування статикою.",
      topics: [
        { mrt: "1.10.1", title: "Кіловольти з нічого: трибоелектрика в побуті й на робочому столі", status: "done" },
        { mrt: "1.10.2", title: "Тіло як накопичувач заряду: скільки вольтів ти носиш", status: "done" },
        { mrt: "1.10.3", title: "Пробій повітря: іскра, корона й вістря", status: "done" },
        { mrt: "1.10.4", title: "Блискавка — найбільший електростатичний розряд", status: "done" },
        { mrt: "1.10.5", title: "Чому мікросхеми вмирають тихо: приховані ESD-пошкодження", status: "done" },
        { mrt: "1.10.6", title: "Антистатичне робоче місце: браслет, мат, заземлення", status: "done" },
        { mrt: "1.10.7", title: "Пакування й транспортування: розсіювальні та екранувальні пакети", status: "done" },
        { mrt: "1.10.8", title: "Вологість і матеріали: керування статикою в середовищі", status: "done" },
        { kind: "hist", file: "hist-franklin-richmann.md", at: "chapter", status: "done", title: "Франклін, Ріхман і приборкання блискавки" },
        { kind: "hist", file: "hist-dust-explosions.md", at: "1.10.5", status: "done", title: "Статика як джерело займання: елеватори, пари ефіру, паливні танкери" },
        { kind: "math", file: "math-hbm.md", at: "1.10.2", status: "done", title: "Модель людського тіла (HBM): 100 пФ і 1.5 кОм" },
        { kind: "comp", file: "../../../components/protection/gas-discharge-tube/gas-discharge-tube.md", at: "1.10.3", status: "done", title: "Іскровий проміжок і газовий розрядник (GDT): захист, старший за напівпровідники" },
        { kind: "math", file: "math-paschen.md", at: "1.10.3", status: "done", title: "Крива Пашена: пробивна напруга від добутку тиск×зазор" },
        { kind: "comp", file: "comp-esd-gun.md", at: "1.10.5", status: "done", title: "ESD-симулятор і рівні IEC 61000-4-2: як перевіряють стійкість пристроїв" },
        { kind: "math", file: "math-spark-energy.md", at: "1.10.5", status: "done", title: "Енергія іскри: ½·Q·V і чому мікроджоуля досить" },
        { kind: "comp", file: "comp-wrist-strap.md", at: "1.10.6", status: "done", title: "Браслет, мат і тестер браслетів зблизька" },
        { kind: "comp", file: "comp-ionizer.md", at: "1.10.7", status: "done", title: "Іонізатор повітря: нейтралізувати заряд там, де не можна заземлити" }
      ]
    }
  ]
});
