/* manifest — «Фізика» (тип "book"). Схема — AUTHORING.md §2 (v6). */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "physics", title: "Фізика",
  sections: [
    { slug: "mechanics", title: "Механіка", scope: "Рух точок, систем і твердого тіла під дією сил із законами збереження; лагранжів і гамільтонів формалізми та зв'язок симетрій зі збереженнями; нелінійна й дисипативна динаміка (стійкість, біфуркації, хаос, атрактори); деформації пружних тіл і плинність рідин та газів як суцільних середовищ.",
      topics: [
        { slug: "thrust-vs-weight", title: "Тяга проти ваги", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-actuator-disk.md", status: "done" }] },
        { slug: "reaction-torque", title: "Реактивний момент", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-tail-rotor.md", status: "done" }], proj: [{ file: "proj-yaw-mixer.md", status: "done" }] },
        { slug: "frame-configurations", title: "Рами й конфігурації", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-mixer-matrix.md", status: "done" }], hist: [{ file: "hist-multirotor.md", status: "done" }] },
        { slug: "propeller-geometry", title: "Гвинт", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-blade-element.md", status: "done" }], hist: [{ file: "hist-propeller.md", status: "done" }] },
        { slug: "fixed-wing-lift", title: "Літак", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-lift-theory.md", status: "done" }] },
        { slug: "vtol-transition", title: "VTOL-гібриди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-tiltrotor.md", status: "done" }] },
        { slug: "gear-tooth-geometry", title: "Геометрія зуба та зачеплення", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-involute.md", status: "done" }], math: [{ file: "math-involute.md", status: "done" }] },
        { slug: "breguet-range-endurance", title: "Рівняння дальності й тривалості Бреге", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-breguet.md", status: "done" }], math: [{ file: "math-breguet-derivation.md", status: "done" }], proj: [{ file: "proj-endurance-calculator.md", status: "done" }] },
        { slug: "specific-force", title: "Питома сила і strapdown-інтеграція", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-strapdown.md", status: "done" }], math: [{ file: "math-strapdown-mechanization.md", status: "done" }], proj: [{ file: "proj-strapdown-demo.md", status: "done" }] },
        { slug: "proper-acceleration", title: "Власне прискорення", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-four-acceleration.md", status: "done" }], proj: [{ file: "proj-imu-gravity.md", status: "done" }] },
        { slug: "equivalence-principle", title: "Принцип еквівалентності", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-equivalence-tests.md", status: "done" }], math: [{ file: "math-eotvos-parameter.md", status: "done" }], proj: [{ file: "proj-accelerometer-equivalence.md", status: "done" }] },
        { slug: "coriolis-effect", title: "Ефект Коріоліса", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-coriolis.md", status: "done" }], math: [{ file: "math-coriolis.md", status: "done" }], comp: [{ file: "comp-mems-gyro.md", status: "done" }], proj: [{ file: "proj-mems-gyro.md", status: "done" }], api: [{ file: "api-mems-gyro.md", status: "done" }] },
        { slug: "vibration-transmissibility", title: "Передавання вібрації (transmissibility)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-soft-mounting.md", status: "done" }], math: [{ file: "math-transmissibility.md", status: "done" }], proj: [{ file: "proj-isolator-design.md", status: "done" }] },
        { slug: "mechanical-resonance", title: "Механічний резонанс", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bridges.md", status: "done" }], math: [{ file: "math-forced-oscillator.md", status: "done" }], proj: [{ file: "proj-resonance-sweep.md", status: "done" }] },
        { slug: "squeeze-film-damping", title: "Squeeze-film демпфування", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-squeeze-film.md", status: "done" }], math: [{ file: "math-reynolds-squeeze.md", status: "done" }], proj: [{ file: "proj-squeeze-calculator.md", status: "done" }] },
        { slug: "angular-velocity", title: "Кутова швидкість і прискорення", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-radian.md", status: "done" }], math: [{ file: "math-omega-cross-r.md", status: "done" }], proj: [{ file: "proj-gyro-to-angle.md", status: "done" }] },
        { slug: "torque", title: "Момент сили", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-lever.md", status: "done" }], math: [{ file: "math-rotational-second-law.md", status: "done" }] },
        { slug: "similarity-scaling", title: "Подібність і масштабування", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-galileo-scaling.md", status: "done" }], proj: [{ file: "proj-model-scaling.md", status: "done" }] },
        { slug: "noether-theorem", title: "Теорема Нетер", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-noether.md", status: "done" }], math: [{ file: "math-noether-derivation.md", status: "done" }], proj: [{ file: "proj-symmetry-conservation.md", status: "done" }] },
        { slug: "positive-negative-feedback", title: "Додатний і від'ємний зворотний зв'язок", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-feedback-control.md", status: "done" }], math: [{ file: "math-linear-stability.md", status: "done" }], proj: [{ file: "proj-feedback-sim.md", status: "done" }] },
        { slug: "uncertainty-budget", title: "Бюджет невизначеності", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-propagation.md", status: "done" }], hist: [{ file: "hist-gum.md", status: "done" }], proj: [{ file: "proj-monte-carlo.md", status: "done" }] },
        { slug: "dynamic-pressure", title: "Динамічний тиск і число Бернуллі", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bernoulli.md", status: "done" }], math: [{ file: "math-bernoulli-derivation.md", status: "done" }], proj: [{ file: "proj-pitot-airspeed.md", status: "done" }] },
        { slug: "atmospheric-pressure", title: "Атмосферний тиск", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-barometer.md", status: "done" }], math: [{ file: "math-barometric-formula.md", status: "done" }] },
        { slug: "si-base-units", title: "Базові одиниці СІ", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-metric-system.md", status: "done" }], math: [{ file: "math-dimensional-analysis.md", status: "done" }], proj: [{ file: "proj-unit-safety.md", status: "done" }] },
        { slug: "center-of-mass", title: "Центр мас", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-barycenter.md", status: "done" }], math: [{ file: "math-com-theorem.md", status: "done" }], proj: [{ file: "proj-polygon-centroid.md", status: "done" }] },
        { slug: "surface-tension", title: "Поверхневий натяг", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-surface-tension.md", status: "done" }], math: [{ file: "math-young-laplace.md", status: "done" }] },
        { slug: "material-fatigue", title: "Втома матеріалу", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fatigue-discovery.md", status: "done" }], math: [{ file: "math-fatigue-laws.md", status: "done" }], proj: [{ file: "proj-rainflow-miner.md", status: "done" }] },
        { slug: "lift-to-drag-ratio", title: "Аеродинамічна якість (L/D)", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-drag-polar.md", status: "done" }], proj: [{ file: "proj-speed-to-fly.md", status: "done" }], hist: [{ file: "hist-cayley.md", status: "done" }] },
        { slug: "newtons-second-law", title: "Другий закон Ньютона", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-second-law.md", status: "done" }], math: [{ file: "math-force-momentum.md", status: "done" }], proj: [{ file: "proj-numerical-integration.md", status: "done" }] },
        { slug: "inertial-frame", title: "Інерціальна система відліку", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-inertial-frame.md", status: "done" }], math: [{ file: "math-fictitious-forces.md", status: "done" }], proj: [{ file: "proj-rotating-frame.md", status: "done" }] },
        { slug: "free-fall", title: "Вільне падіння", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-galileo-fall.md", status: "done" }], math: [{ file: "math-fall-kinematics.md", status: "done" }], proj: [{ file: "proj-terminal-velocity.md", status: "done" }] },
        { slug: "newton-gravitation", title: "Закон всесвітнього тяжіння", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-newton-principia.md", status: "done" }, { file: "hist-cavendish.md", status: "done" }], math: [{ file: "math-orbits-kepler.md", status: "done" }], proj: [{ file: "proj-orbit-integrator.md", status: "done" }] },
        { slug: "centrifugal-force", title: "Відцентрова сила", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-huygens-newton.md", status: "done" }], math: [{ file: "math-effective-gravity.md", status: "done" }], proj: [{ file: "proj-rotating-habitat.md", status: "done" }] },
        { slug: "tuned-mass-damper", title: "Настроєний гаситель коливань (tuned mass damper)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-frahm-den-hartog.md", status: "done" }], math: [{ file: "math-den-hartog-tuning.md", status: "done" }], proj: [{ file: "proj-tmd-simulation.md", status: "done" }] },
        { slug: "viscosity", title: "В'язкість", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-viscosity.md", status: "done" }], math: [{ file: "math-momentum-diffusion.md", status: "done" }], proj: [{ file: "proj-falling-ball-viscometer.md", status: "done" }] },
        { slug: "poiseuille-flow", title: "Течія Пуазейля", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hagen-poiseuille.md", status: "done" }], math: [{ file: "math-poiseuille-derivation.md", status: "done" }], proj: [{ file: "proj-hydraulic-network.md", status: "done" }] },
        { slug: "velocity", title: "Швидкість", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-velocity.md", status: "done" }], math: [{ file: "math-velocity-derivative.md", status: "done" }], proj: [{ file: "proj-velocity-from-samples.md", status: "done" }] },
        { slug: "acceleration", title: "Прискорення", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-acceleration.md", status: "done" }], hist: [{ file: "hist-acceleration.md", status: "done" }] },
        { slug: "centripetal-acceleration", title: "Центрострімке прискорення", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-centripetal-derivation.md", status: "done" }], hist: [{ file: "hist-huygens-newton.md", status: "done" }] },
        { slug: "moment-of-inertia", title: "Момент інерції", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-oscillation-center.md", status: "done" }], math: [{ file: "math-inertia-tensor.md", status: "done" }], proj: [{ file: "proj-inertia-calculator.md", status: "done" }] },
        { slug: "force", title: "Сила", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-free-body-equilibrium.md", status: "done" }], hist: [{ file: "hist-force-concept.md", status: "done" }] },
        { slug: "angular-momentum", title: "Момент імпульсу", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-angular-momentum.md", status: "done" }], math: [{ file: "math-angular-momentum.md", status: "done" }], proj: [{ file: "proj-tennis-racket.md", status: "done" }] },
        { slug: "reynolds-number", title: "Число Рейнольдса", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-reynolds-experiment.md", status: "done" }], math: [{ file: "math-reynolds-derivation.md", status: "done" }], proj: [{ file: "proj-reynolds-regime.md", status: "done" }] },
        { slug: "least-action-principle", title: "Принцип найменшої дії", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-least-action.md", status: "done" }], math: [{ file: "math-euler-lagrange.md", status: "done" }], proj: [{ file: "proj-least-action.md", status: "done" }] },
        { slug: "pressure", title: "Тиск", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-pressure.md", status: "done" }], math: [{ file: "math-pressure-scalar.md", status: "done" }] },
        { slug: "density", title: "Густина", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-archimedes-crown.md", status: "done" }], math: [{ file: "math-atomic-density.md", status: "done" }] },
        { slug: "kinetic-energy", title: "Кінетична енергія", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-vis-viva.md", status: "done" }], math: [{ file: "math-work-energy-theorem.md", status: "done" }], proj: [{ file: "proj-collision-energy.md", status: "done" }] },
        { slug: "energy-conservation", title: "Закон збереження енергії", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-energy-conservation.md", status: "done" }], math: [{ file: "math-work-energy-theorem.md", status: "done" }], proj: [{ file: "proj-energy-audit.md", status: "done" }] },
        { slug: "flow-continuity", title: "Нерозривність течії", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-continuity-flow.md", status: "done" }], math: [{ file: "math-continuity-equation.md", status: "done" }], proj: [{ file: "proj-flow-network.md", status: "done" }] },
        { slug: "mass", title: "Маса", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-mass-concept.md", status: "done" }], math: [{ file: "math-inertial-mass.md", status: "done" }] },
        { slug: "momentum", title: "Імпульс", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-momentum.md", status: "done" }], math: [{ file: "math-conservation-derivation.md", status: "done" }], proj: [{ file: "proj-collision-sim.md", status: "done" }] },
        { slug: "newtons-first-law", title: "Перший закон Ньютона", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-law-of-inertia.md", status: "done" }] },
        { slug: "newtons-third-law", title: "Третій закон Ньютона", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-third-law.md", status: "done" }], math: [{ file: "math-momentum-conservation.md", status: "done" }], proj: [{ file: "proj-collision-sim.md", status: "done" }] },
        { slug: "galilean-relativity", title: "Принцип відносності Ґалілея", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-galileo-ship.md", status: "done" }], math: [{ file: "math-galilean-transformation.md", status: "done" }] },
        { slug: "projectile-motion", title: "Рух тіла, кинутого під кутом (балістична траєкторія)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ballistics.md", status: "done" }], math: [{ file: "math-projectile-range.md", status: "done" }], proj: [{ file: "proj-trajectory-drag.md", status: "done" }] },
        { slug: "aerodynamic-drag", title: "Аеродинамічний опір (сила опору повітря)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-drag-theory.md", status: "done" }], math: [{ file: "math-drag-derivation.md", status: "done" }], proj: [{ file: "proj-drag-trajectory.md", status: "done" }] },
        { slug: "keplers-laws", title: "Закони Кеплера", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-kepler-mars.md", status: "done" }], math: [{ file: "math-orbital-ellipse.md", status: "done" }], proj: [{ file: "proj-kepler-equation.md", status: "done" }] },
        { slug: "displacement", title: "Переміщення і шлях", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-path-length.md", status: "done" }], proj: [{ file: "proj-odometry.md", status: "done" }] },
        { slug: "jerk", title: "Ривок (похідна прискорення)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-jerk-naming.md", status: "done" }], math: [{ file: "math-higher-derivatives.md", status: "done" }], proj: [{ file: "proj-scurve-profile.md", status: "done" }] },
        { slug: "work", title: "Механічна робота", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-work-concept.md", status: "done" }], math: [{ file: "math-conservative-work.md", status: "done" }], proj: [{ file: "proj-work-integral.md", status: "done" }] },
        { slug: "friction", title: "Тертя", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-friction-laws.md", status: "done" }], math: [{ file: "math-real-contact-area.md", status: "done" }], proj: [{ file: "proj-stick-slip.md", status: "done" }] },
        { slug: "gyroscopic-precession", title: "Гіроскопічна прецесія", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-gyroscope.md", status: "done" }], math: [{ file: "math-precession-rate.md", status: "done" }], proj: [{ file: "proj-top-simulation.md", status: "done" }] },
        { slug: "potential-energy", title: "Потенціальна енергія", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-potential-energy.md", status: "done" }], math: [{ file: "math-force-from-potential.md", status: "done" }], proj: [{ file: "proj-potential-landscape.md", status: "done" }] },
        { slug: "buoyancy", title: "Виштовхувальна сила (закон Архімеда)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-floating-bodies.md", status: "done" }], math: [{ file: "math-buoyancy-derivation.md", status: "done" }], proj: [{ file: "proj-floating-buoy.md", status: "done" }] },
        { slug: "collisions", title: "Зіткнення (пружні й непружні)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-collision-laws.md", status: "done" }], math: [{ file: "math-elastic-collision.md", status: "done" }], proj: [{ file: "proj-collision-resolver.md", status: "done" }] },
        { slug: "weight", title: "Вага", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-weight.md", status: "done" }], math: [{ file: "math-apparent-weight.md", status: "done" }], proj: [{ file: "proj-elevator-ride.md", status: "done" }] },
        { slug: "boundary-layer", title: "Примежовий шар", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-prandtl.md", status: "done" }], math: [{ file: "math-blasius.md", status: "done" }], proj: [{ file: "proj-flat-plate-drag.md", status: "done" }] },
        { slug: "position", title: "Положення і радіус-вектор", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-coordinates.md", status: "done" }], proj: [{ file: "proj-coordinate-transform.md", status: "done" }] },
        { slug: "deterministic-chaos", title: "Детермінований хаос", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power", title: "Потужність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "normal-force", title: "Нормальна сила", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rolling-resistance", title: "Тертя кочення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hookes-law", title: "Закон Гука", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "reduced-mass", title: "Зведена маса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flow-separation", title: "Відрив потоку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "degrees-of-freedom", title: "Ступені вільності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "navier-stokes", title: "Рівняння Нав'є–Стокса", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "circulation-lift-theorem", title: "Циркуляція та підіймальна сила", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "jerk-equation-chaos", title: "Рівняння на ривок і поріг хаосу", basic: { status: "empty" }, detailed: { status: "done" } },
      ] },
    { slug: "oscillations-waves", title: "Хвилі", scope: "Періодичний рух біля рівноваги та поширення механічних збурень: коливання, резонанс, дисперсія, інтерференція, звук.",
      topics: [
        { slug: "sine-wave", title: "Синусоїда", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-steinmetz.md", status: "done" }], math: [{ file: "math-trigonometry.md", status: "done" }], proj: [{ file: "proj-phase-accumulator.md", status: "done" }] },
        { slug: "amplitude-frequency", title: "Амплітуда й частота", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-50-60-hz.md", status: "done" }], comp: [{ file: "comp-signal-generator.md", status: "done" }] },
        { slug: "phase", title: "Фаза", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "damped-oscillator", title: "Загасний осцилятор", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-damping.md", status: "done" }], math: [{ file: "math-damped-solution.md", status: "done" }], proj: [{ file: "proj-ringdown.md", status: "done" }] },
        { slug: "wave-superposition", title: "Суперпозиція хвиль", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-vibrating-string.md", status: "done" }], math: [{ file: "math-superposition.md", status: "done" }], proj: [{ file: "proj-wave-sum.md", status: "done" }] },
        { slug: "beats", title: "Биття", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-sauveur.md", status: "done" }], math: [{ file: "math-sum-to-product.md", status: "done" }], proj: [{ file: "proj-beat-detect.md", status: "done" }] },
        { slug: "frequency-spectrum", title: "Частотний спектр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wave-interference", title: "Інтерференція хвиль", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "group-delay", title: "Групова затримка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lissajous", title: "Фігури Ліссажу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "harmonic-oscillator", title: "Гармонічний осцилятор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lc-circuit", title: "LC-контур", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "resonance", title: "Резонанс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "multipath-fading", title: "Багатопроменевість і завмирання сигналу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sampling-theorem", title: "Теорема Найквіста–Шеннона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lissajous-figures", title: "Фігури Ліссажу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "acoustic-impedance", title: "Акустичний імпеданс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "acoustic-absorption", title: "Поглинання звуку в повітрі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "beam-pattern", title: "Діаграма спрямованості перетворювача", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sound-attenuation-air", title: "Загасання звуку в повітрі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "superposition-physics", title: "Суперпозиція у фізиці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "superposition", title: "Принцип суперпозиції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "q-factor", title: "Добротність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "coupled-oscillators", title: "Зв'язані осцилятори й нормальні моди", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "standing-wave", title: "Стояча хвиля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wave-equation", title: "Хвильове рівняння", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "doppler-effect", title: "Ефект Доплера", basic: { status: "empty" }, detailed: { status: "done" } },
      ] },
    { slug: "thermal-statistical", title: "Термодинаміка", scope: "Макроскопічні закони теплоти, роботи, температури й ентропії, цикли та фазові переходи разом із їх мікроскопічним виведенням зі статистичних ансамблів: розподіли, флуктуації, критичні явища.",
      topics: [
        { slug: "heat-transfer", title: "Теплопередача (тепло тече від гарячого до холодного)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-resistance", title: "Тепловий опір", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-thermal-rc.md", status: "done" }] },
        { slug: "thermal-noise", title: "Тепловий шум", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-noise-density.md", status: "done" }] },
        { slug: "boltzmann-factor", title: "Больцманівський фактор і масштаб kT", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "ideal-gas-law", title: "Рівняння стану ідеального газу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "white-noise-spectrum", title: "Білий шум і спектральна щільність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "heat-pipe", title: "Теплова трубка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "natural-convection", title: "Природна конвекція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fin-efficiency", title: "Ефективність ребра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "equipartition-theorem", title: "Теорема рівнорозподілу енергії", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "brownian-motion", title: "Броунівський рух", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fluctuation-dissipation-theorem", title: "Теорема флуктуації-дисипації", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fluctuation-dissipation", title: "Теорема флуктуацій і дисипації", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-runaway", title: "Тепловий розгін (thermal runaway)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-conductivity", title: "Теплопровідність матеріалів (λ)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ragone-chart", title: "Діаграма Рагоне", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "standard-atmosphere", title: "Стандартна атмосфера ISA", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "humidity-measurement", title: "Вимірювання вологості", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dew-point", title: "Точка роси і конденсація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-expansion", title: "Теплове розширення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "first-law-thermodynamics", title: "Перший закон термодинаміки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-diffusivity", title: "Температуропровідність", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "thermodynamics", title: "Термодинаміка (прикладна)", scope: "Прикладні атмосферні й вологісні величини для давачів середовища.",
      topics: [
        { slug: "relative-humidity", title: "Відносна вологість повітря", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "electromagnetism", title: "Електромагнетизм", scope: "Заряди й поля, струм і провідність, магнетизм та індукція, зведені в рівняння Максвелла.",
      topics: [
        { slug: "electric-charge", title: "Заряд", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-millikan.md", status: "done" }, { file: "hist-electricity.md", status: "done" }] },
        { slug: "charge-conservation", title: "Закон збереження заряду", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "elementary-charge", title: "Елементарний заряд і квантування", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "coulomb-law", title: "Закон Кулона", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-coulomb.md", status: "done" }], comp: [{ file: "comp-van-de-graaff.md", status: "done" }], math: [{ file: "math-vectors.md", status: "done" }] },
        { slug: "electric-field", title: "Електричне поле", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-faraday.md", status: "done" }] },
        { slug: "electric-potential", title: "Потенціал", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-work-integral.md", status: "done" }] },
        { slug: "volt", title: "Вольт", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-volta.md", status: "done" }], comp: [{ file: "comp-alkaline-cell.md", status: "done" }, { file: "comp-piezo-igniter.md", status: "done" }] },
        { slug: "faraday-cage", title: "Клітка Фарадея", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-everyday-shields.md", status: "done" }] },
        { slug: "electric-current", title: "Струм", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ampere.md", status: "done" }, { file: "hist-conduction.md", status: "done" }], math: [{ file: "math-derivative.md", status: "done" }] },
        { slug: "current-direction", title: "Напрямок струму", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "signal-speed", title: "Швидкість сигналу", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-atlantic-cable.md", status: "done" }] },
        { slug: "current-continuity", title: "Неперервність струму", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "voltage", title: "Напруга", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "closed-circuit", title: "Замкнене коло", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-switches.md", status: "done" }] },
        { slug: "ionic-conduction", title: "Іонна провідність", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-arrhenius.md", status: "done" }], comp: [{ file: "comp-galvanic-corrosion.md", status: "done" }] },
        { slug: "dc-vs-ac", title: "DC і AC", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-war-of-currents.md", status: "done" }] },
        { slug: "current-safety", title: "Електробезпека", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-dalziel.md", status: "done" }], comp: [{ file: "comp-rcd.md", status: "done" }] },
        { slug: "electric-power", title: "Потужність", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-watt.md", status: "done" }] },
        { slug: "joule-heating", title: "Джоулеве тепло", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "rms-value", title: "Діюче значення", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-rms-derivation.md", status: "done" }], proj: [{ file: "proj-true-rms.md", status: "done" }] },
        { slug: "ac-power-grid", title: "Змінна мережа", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-mains-socket.md", status: "done" }] },
        { slug: "magnetic-field", title: "Магнітне поле", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-lodestone-oersted.md", status: "done" }] },
        { slug: "oersted-experiment", title: "Дослід Ерстеда", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-biot-savart.md", status: "done" }] },
        { slug: "electromagnet", title: "Електромагніт", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-ampere-turns.md", status: "done" }] },
        { slug: "ampere-force", title: "Сила Ампера", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-cross-product.md", status: "done" }] },
        { slug: "hall-effect", title: "Ефект Холла", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hall.md", status: "done" }] },
        { slug: "earth-magnetic-field", title: "Поле Землі", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "electromagnetic-induction", title: "Електромагнітна індукція", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "capacitive-coupling", title: "Ємнісна наводка", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-induction-coordination.md", status: "done" }] },
        { slug: "inductive-coupling", title: "Індуктивна наводка", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "triboelectricity", title: "Трибоелектрика", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-franklin-richmann.md", status: "done" }] },
        { slug: "body-charge", title: "Заряд тіла", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-hbm.md", status: "done" }] },
        { slug: "lightning", title: "Блискавка", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-spark-gap-gdt.md", status: "done" }] },
        { slug: "humidity-static-control", title: "Вологість і статика", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "em-wave", title: "Електромагнітна хвиля", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hertz.md", status: "done" }] },
        { slug: "hertz-dipole", title: "Осцилювальний диполь Герца", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "faraday-rotation", title: "Фарадеєвське обертання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "velocity-factor", title: "Коефіцієнт укорочення: хвиля в діелектрику", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "image-theory", title: "Метод дзеркальних зображень в електродинаміці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "skin-effect", title: "Скін-ефект", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "characteristic-impedance", title: "Характеристичний імпеданс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ionospheric-delay", title: "Іоносферна затримка радіосигналу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "displacement-current", title: "Струм зміщення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lumped-circuit-model", title: "Модель зосереджених елементів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "conservative-field", title: "Потенціальне поле й циркуляція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ferroelectrics", title: "Сегнетоелектрики", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electric-field-energy", title: "Енергія електричного поля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pzt-piezo-ceramics", title: "П'єзокераміка (PZT)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "negative-differential-resistance", title: "Від'ємний диференційний опір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ferromagnetism-domains", title: "Феромагнетизм і домени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-monopole", title: "Магнітний монополь", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetostriction", title: "Магнітострикція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "4wire-resistance", title: "Чотирипровідний метод вимірювання опору", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pyroelectric-effect", title: "Піроелектричний ефект", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "three-phase-power", title: "Потужність у трифазній мережі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "transformer", title: "Трансформатор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "reactive-power", title: "Реактивна потужність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hvdc", title: "HVDC — постійний струм високої напруги", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lorentz-force", title: "Сила Лоренца", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-moment", title: "Магнітний момент", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "two-wire-force", title: "Сила між паралельними провідниками", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gauge-symmetry", title: "Калібрувальна симетрія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ground-loop", title: "Петля землі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "permittivity", title: "Діелектрична проникність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gauss-law", title: "Закон Гаусса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "surface-charge-conduction", title: "Поверхневий заряд у провіднику", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "charge-relaxation", title: "Час релаксації заряду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electric-insulation", title: "Ізоляція провідників", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "protective-grounding", title: "Захисне заземлення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ventricular-fibrillation", title: "Фібриляція шлуночків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "step-voltage", title: "Крокова й дотикова напруга", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "three-phase-ac", title: "Трифазний змінний струм", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "geodynamo", title: "Геодинамо", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-inclination", title: "Магнітний нахил і вектор поля Землі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "corona-discharge", title: "Коронний розряд", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "charge-induction", title: "Електростатична індукція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "current-density", title: "Щільність струму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "energy-of-charge-system", title: "Енергія системи зарядів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dipole-field", title: "Електричний диполь і його поле", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "poisson-laplace-eq", title: "Рівняння Пуассона і Лапласа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-factor", title: "Коефіцієнт потужності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "efficiency", title: "Коефіцієнт корисної дії", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "instantaneous-power", title: "Миттєва та середня потужність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-reluctance", title: "Магнітний опір і магнітне коло", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "faraday-law-differential", title: "Закон Фарадея у диференціальній формі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "induction-heating", title: "Індукційний нагрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quantum-hall-effect", title: "Квантовий ефект Холла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "si-2019-redefinition", title: "Редефініція SI 2019", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "em-spectrum", title: "Електромагнітний спектр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "poynting-vector", title: "Вектор Пойнтінга", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "radiation-zones", title: "Ближня і далека зони випромінювання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "potential-energy-electric", title: "Потенціальна енергія в електричному полі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "field-line-geometry", title: "Геометрія силових ліній і еквіпотенціалей", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "phase-group-velocity", title: "Фазова й групова швидкість", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "anomalous-hall-effect", title: "Аномальний ефект Холла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "surface-conductivity", title: "Поверхнева провідність діелектриків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lenz-law", title: "Правило Ленца", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "plasma-physics", title: "Плазма", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electrolysis", title: "Електроліз", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bioelectricity", title: "Біоелектрика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "atmospheric-electricity", title: "Атмосферна електрика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-flux", title: "Магнітний потік", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "maxwell-equations", title: "Рівняння Максвелла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-monopole-theory", title: "Магнітний монополь", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "biot-savart-law", title: "Закон Біо–Савара", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-dipole", title: "Магнітний диполь", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "right-hand-rule", title: "Правило правої руки і псевдовектори", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ampere-circuital-law", title: "Теорема про циркуляцію (закон Ампера)", basic: { status: "pending" }, detailed: { status: "empty" } },

        { slug: "electrostatic-discharge", title: "Електростатичний розряд (ESD)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electron-volt", title: "Електронвольт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "emf", title: "Електрорушійна сила (ЕРС)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "surface-charge-circuits", title: "Поверхневі заряди в колі зі струмом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "superconductor", title: "Надпровідність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "transmission-line", title: "Лінія передачі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dielectric-breakdown", title: "Пробій діелектрика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electric-polarization", title: "Поляризація діелектрика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "energy-density-field", title: "Густина енергії електромагнітного поля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electrophoresis", title: "Електрофорез", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetoresistance", title: "Магнітоопір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-declination", title: "Магнітне схилення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "battery-discharge-curve", title: "Крива розряду батареї", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "optics", title: "Оптика", scope: "Поширення електромагнітних хвиль і поведінка світла як променя й хвилі: відбиття, заломлення, дифракція, поляризація.",
      topics: [
        { slug: "total-internal-reflection", title: "Повне внутрішнє відбиття", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "luminance-chrominance", title: "Яскравість і колірність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "color-gamut", title: "Колірний охоплення і хроматичність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "color-spaces", title: "Колірні простори", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quantum-efficiency", title: "Квантова ефективність фотодетектора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "colorimetry-basics", title: "Кольорометрія: CIE, колірна температура і CRI", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "solar-irradiance-model", title: "Модель сонячної інсоляції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fresnel-lens", title: "Лінза Френеля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "retroreflector", title: "Ретрорефлектор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fresnel-equations", title: "Рівняння Френеля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lambert-cosine-law", title: "Закон косинуса Ламберта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "photon-budget-optical", title: "Фотонний бюджет оптичної системи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "snells-law", title: "Закон Снелла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "refractive-index", title: "Показник заломлення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "evanescent-wave", title: "Еванесцентна хвиля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "optical-dispersion", title: "Оптична дисперсія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "solar-cell-efficiency", title: "ККД сонячного елемента", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fermat-principle", title: "Принцип Ферма (найменшого часу)", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "relativity", title: "Відносність", scope: "Фізика великих швидкостей і викривленого простору-часу: спеціальна та загальна теорія відносності й гравітація як геометрія.",
      topics: [
        { slug: "general-relativity", title: "Загальна теорія відносності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mass-energy-equivalence", title: "Еквівалентність маси та енергії (E = mc²)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "special-relativity", title: "Спеціальна теорія відносності", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "quantum-mechanics", title: "Квантова механіка", scope: "Дискретність, дуалізм і ймовірнісний опис мікросвіту (рівняння Шредінгера, оператори, заплутаність) разом із будовою, спектрами та світловими переходами атомів і молекул і квантовою природою хімічного зв'язку.",
      topics: [
        { slug: "quantum-volt-standard", title: "Квантовий стандарт вольта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "direct-indirect-bandgap", title: "Пряма і непряма заборонена зона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electron-spin", title: "Спін електрона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pair-production", title: "Народження й анігіляція пар", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "condensed-matter-physics", title: "Конденсована речовина", scope: "Колективні квантові ефекти у твердих тілах і рідинах (кристали, зонна структура, напівпровідники, надпровідність, магнетизм) та іонізований стан речовини з динамікою заряджених частинок у полях: розряди, утримання, хвилі в плазмі.",
      topics: [
        { slug: "electron-drift", title: "Дрейф електронів", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "conductors-insulators", title: "Провідники й діелектрики", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "resistance-origin", title: "Природа опору", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "conductivity", title: "Провідність", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "resistance", title: "Опір", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ohm-joule.md", status: "done" }] },
        { slug: "resistivity", title: "Питомий опір", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "resistance-temperature", title: "Опір і температура", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-filament.md", status: "done" }, { file: "hist-superconductivity.md", status: "done" }] },
        { slug: "ferromagnetism", title: "Феромагнетизм", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "permanent-magnets", title: "Постійні магніти", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-neodymium.md", status: "done" }] },
        { slug: "saturation-hysteresis", title: "Насичення й гістерезис", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-hysteresis-loop.md", status: "done" }] },
        { slug: "shot-flicker-noise", title: "Дробовий шум", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-resistor-noise.md", status: "done" }] },
        { slug: "air-breakdown", title: "Пробій повітря", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-paschen.md", status: "done" }] },
        { slug: "semiconductor", title: "Напівпровідник", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-silicon-germanium.md", status: "done" }, { file: "hist-diode.md", status: "done" }] },
        { slug: "doping", title: "Легування", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "pn-junction", title: "PN-перехід", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "piezoelectric-effect", title: "П'єзоефект", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "minority-carrier-diffusion", title: "Дифузія неосновних носіїв", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-domains", title: "Магнітні домени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "curie-temperature", title: "Точка Кюрі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "avalanche-breakdown", title: "Лавинний пробій і тунелювання Зенера", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "diffusion-length", title: "Дифузійна довжина носіїв", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electroluminescence", title: "Електролюмінесценція: випромінювання світла в p-n переході", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flicker-noise", title: "Фліккер-шум і шум 1/f", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "piezoresistivity", title: "П'єзорезистивність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "elastic-deformation", title: "Пружна деформація і закон Гука", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "drude-model", title: "Модель Друде", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "superconductivity", title: "Надпровідність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "band-theory", title: "Зонна теорія твердого тіла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fermi-level", title: "Рівень Фермі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ionic-conductor", title: "Іонний провідник", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ion-implantation", title: "Іонна імплантація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "zone-refining", title: "Зонне очищення кремнію", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mean-free-path", title: "Довжина вільного пробігу та час релаксації", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "carrier-mobility", title: "Рухливість носіїв заряду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "electromigration", title: "Електроміграція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "exchange-interaction", title: "Обмінна взаємодія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "antiferromagnetism", title: "Антиферомагнетизм і феримагнетизм", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mlc-tlc-cell-physics", title: "Фізика MLC/TLC/QLC комірок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "charge-trap-flash", title: "Charge trap Flash (SONOS/CTF)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "3d-nand-architecture", title: "3D NAND: фізика вертикального стека", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dram-capacitor-scaling", title: "Масштабування конденсатора DRAM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-anisotropy", title: "Магнітна анізотропія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "samarium-cobalt", title: "Самарій-кобальтові магніти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "demagnetization-curve", title: "Крива розмагнічування та робоча точка магніту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "halbach-array", title: "Масив Гальбаха", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ferroelectricity", title: "Сегнетоелектрики", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "crystal-symmetry-piezo", title: "Симетрія кристалів і п'єзоелектричний ефект", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quartz-growth", title: "Вирощування синтетичного кварцу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "energy-bands", title: "Зонна структура й рівень Фермі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "minority-carrier-injection", title: "Ін'єкція меншинних носіїв", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "metal-semiconductor-contact", title: "Контакт метал–напівпровідник", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "solar-cell-physics", title: "Фізика сонячного елемента", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nonohmic-resistance", title: "Неомічний опір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "phonon", title: "Фонон", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "temperature-coefficient-alloys", title: "Сплави з нульовим ТКО", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "matthiessens-rule", title: "Правило Матіссена", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "four-probe-measurement", title: "Чотирьохзондове вимірювання опору", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sheet-resistance", title: "Поверхневий опір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "eddy-currents", title: "Вихрові струми", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "steinmetz-equation", title: "Рівняння Штейнмеця", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "magnetic-shielding", title: "Магнітне екранування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quantum-noise-limit", title: "Квантова межа шуму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "holes-carriers", title: "Дірки як носії заряду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quark-confinement", title: "Конфайнмент кварків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-wear-model", title: "Знос Flash: charge trapping і ресурс запису", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "schottky-barrier", title: "Бар'єр Шотткі: контакт метал–напівпровідник", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "manganese-alloys-tcr", title: "Сплави з низьким TCR (манганін, константан)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inversion-layer", title: "Шар інверсії в напівпровіднику", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "crystal-defects", title: "Дефекти кристалічної ґратки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "plastic-deformation", title: "Пластична деформація і границя плинності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "czochralski-growth", title: "Метод Чохральського: витягування монокристала з розплаву", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "polytypism", title: "Політипізм", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "nuclear-particle", title: "Ядерна фізика", scope: "Будова, стійкість і перетворення ядра (радіоактивність, поділ, синтез, ядерні моделі) та елементарні частинки й фундаментальні взаємодії: Стандартна модель, кварки, калібрувальні поля, симетрії, механізм Хіггса.",
      topics: [
        { slug: "fundamental-interactions", title: "Фундаментальні взаємодії", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "astrophysics-cosmology", title: "Астрофізика", scope: "Будова й еволюція зір, галактик і компактних об'єктів (акреція, нейтронні зорі) разом із походженням і еволюцією Всесвіту як цілого: розширення, реліктове випромінювання, темна матерія й темна енергія.",
      topics: [
      ] },
    { slug: "biophysics", title: "Біофізика", scope: "Фізичні принципи живих систем: мембрани, молекулярні мотори, дифузія в клітині, ентропійна пружність, низькорейнольдсова гідродинаміка.",
      topics: [
        { slug: "weber-fechner", title: "Закон Вебера–Фехнера", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
  ]
});
