/* book/physics/manifest.js — книга-предмет «Фізика» (тип "book").
   Схема — AUTHORING.md §2. Статуси: done | empty | update | deeper | recheck. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "physics", title: "Фізика",
  sections: [
    { slug: "mechanics", title: "Механіка", scope: "Рух точок, систем і твердого тіла під дією сил із законами збереження; лагранжів і гамільтонів формалізми та зв'язок симетрій зі збереженнями; нелінійна й дисипативна динаміка (стійкість, біфуркації, хаос, атрактори); деформації пружних тіл і плинність рідин та газів як суцільних середовищ.",
      topics: [
        { slug: "thrust-vs-weight", title: "Тяга проти ваги", status: "empty", origin: "embedded/undefined#7.2.1" },
        { slug: "reaction-torque", title: "Реактивний момент", status: "empty", origin: "embedded/undefined#7.2.2" },
        { slug: "frame-configurations", title: "Рами й конфігурації", status: "empty", origin: "embedded/undefined#7.2.6" },
        { slug: "propeller-geometry", title: "Гвинт", status: "empty", origin: "embedded/undefined#7.2.7" },
        { slug: "fixed-wing-lift", title: "Літак", status: "empty", origin: "embedded/undefined#7.12.3" },
        { slug: "vtol-transition", title: "VTOL-гібриди", status: "empty", origin: "embedded/undefined#7.12.4" },
      ] },
    { slug: "oscillations-waves", title: "Хвилі", scope: "Періодичний рух біля рівноваги та поширення механічних збурень: коливання, резонанс, дисперсія, інтерференція, звук.",
      topics: [
        { slug: "sine-wave", title: "Синусоїда", status: "recheck", origin: "embedded/block-1-circuits-physics/ac-signals#1.7.1", hist: [{ file: "hist-steinmetz.md", status: "recheck" }], math: [{ file: "math-trigonometry.md", status: "recheck" }], proj: [{ file: "proj-phase-accumulator.md", status: "recheck" }] },
        { slug: "amplitude-frequency", title: "Амплітуда й частота", status: "recheck", origin: "embedded/block-1-circuits-physics/ac-signals#1.7.2", hist: [{ file: "hist-50-60-hz.md", status: "recheck" }], comp: [{ file: "comp-signal-generator.md", status: "recheck" }] },
        { slug: "phase", title: "Фаза", status: "recheck", origin: "embedded/block-1-circuits-physics/ac-signals#1.7.3", math: [{ file: "math-phasor.md", status: "recheck" }] },
      ] },
    { slug: "thermal-statistical", title: "Термодинаміка", scope: "Макроскопічні закони теплоти, роботи, температури й ентропії, цикли та фазові переходи разом із їх мікроскопічним виведенням зі статистичних ансамблів: розподіли, флуктуації, критичні явища.",
      topics: [
        { slug: "thermal-resistance", title: "Тепловий опір", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.9", math: [{ file: "math-thermal-rc.md", status: "recheck" }] },
        { slug: "heat-transfer", title: "Передача тепла", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.10" },
        { slug: "thermal-noise", title: "Тепловий шум", status: "recheck", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.2", math: [{ file: "math-kt-scale.md", status: "recheck" }, { file: "math-noise-density.md", status: "recheck" }] },
      ] },
    { slug: "electromagnetism", title: "Електромагнетизм", scope: "Заряди й поля, струм і провідність, магнетизм та індукція, зведені в рівняння Максвелла.",
      topics: [
        { slug: "electric-charge", title: "Заряд", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.1", hist: [{ file: "hist-millikan.md", status: "recheck" }, { file: "hist-electricity.md", status: "recheck" }] },
        { slug: "coulomb-law", title: "Закон Кулона", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.2", hist: [{ file: "hist-coulomb.md", status: "recheck" }], comp: [{ file: "comp-van-de-graaff.md", status: "recheck" }], math: [{ file: "math-vectors.md", status: "recheck" }] },
        { slug: "electric-field", title: "Електричне поле", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.3", hist: [{ file: "hist-faraday.md", status: "recheck" }] },
        { slug: "electric-potential", title: "Потенціал", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.4", math: [{ file: "math-work-integral.md", status: "recheck" }] },
        { slug: "volt", title: "Вольт", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.5", hist: [{ file: "hist-volta.md", status: "recheck" }], comp: [{ file: "comp-alkaline-cell.md", status: "recheck" }, { file: "comp-piezo-igniter.md", status: "recheck" }] },
        { slug: "field-and-potential", title: "Поле й потенціал", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.6", math: [{ file: "math-gradient.md", status: "recheck" }], proj: [{ file: "proj-relaxation.md", status: "recheck" }] },
        { slug: "electrostatics-summary", title: "Зведення електростатики", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.7" },
        { slug: "faraday-cage", title: "Клітка Фарадея", status: "recheck", origin: "embedded/block-1-circuits-physics/charge-field-potential#1.1.8", comp: [{ file: "comp-everyday-shields.md", status: "recheck" }] },
        { slug: "electric-current", title: "Струм", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.1", hist: [{ file: "hist-ampere.md", status: "recheck" }, { file: "hist-conduction.md", status: "recheck" }], math: [{ file: "math-derivative.md", status: "recheck" }] },
        { slug: "current-direction", title: "Напрямок струму", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.2" },
        { slug: "signal-speed", title: "Швидкість сигналу", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.4", hist: [{ file: "hist-atlantic-cable.md", status: "recheck" }] },
        { slug: "current-continuity", title: "Неперервність струму", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.5" },
        { slug: "voltage", title: "Напруга", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.6" },
        { slug: "closed-circuit", title: "Замкнене коло", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.7", comp: [{ file: "comp-switches.md", status: "recheck" }] },
        { slug: "ionic-conduction", title: "Іонна провідність", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.11", hist: [{ file: "hist-arrhenius.md", status: "recheck" }], comp: [{ file: "comp-galvanic-corrosion.md", status: "recheck" }] },
        { slug: "dc-vs-ac", title: "DC і AC", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.12", hist: [{ file: "hist-war-of-currents.md", status: "recheck" }] },
        { slug: "current-safety", title: "Електробезпека", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.13", hist: [{ file: "hist-dalziel.md", status: "recheck" }], comp: [{ file: "comp-rcd.md", status: "recheck" }] },
        { slug: "electric-power", title: "Потужність", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.5", hist: [{ file: "hist-watt.md", status: "recheck" }] },
        { slug: "joule-heating", title: "Джоулеве тепло", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.6" },
        { slug: "rms-value", title: "Діюче значення", status: "recheck", origin: "embedded/block-1-circuits-physics/ac-signals#1.7.4", math: [{ file: "math-rms-derivation.md", status: "recheck" }], proj: [{ file: "proj-true-rms.md", status: "recheck" }] },
        { slug: "ac-power-grid", title: "Змінна мережа", status: "recheck", origin: "embedded/block-1-circuits-physics/ac-signals#1.7.6", comp: [{ file: "comp-mains-socket.md", status: "recheck" }] },
        { slug: "magnetic-field", title: "Магнітне поле", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.1", hist: [{ file: "hist-lodestone-oersted.md", status: "recheck" }] },
        { slug: "oersted-experiment", title: "Дослід Ерстеда", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.4", proj: [{ file: "proj-biot-savart.md", status: "recheck" }] },
        { slug: "electromagnet", title: "Електромагніт", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.5", math: [{ file: "math-ampere-turns.md", status: "recheck" }] },
        { slug: "ampere-force", title: "Сила Ампера", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.7", math: [{ file: "math-cross-product.md", status: "recheck" }] },
        { slug: "hall-effect", title: "Ефект Холла", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.8", hist: [{ file: "hist-hall.md", status: "recheck" }] },
        { slug: "earth-magnetic-field", title: "Поле Землі", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.9" },
        { slug: "electromagnetic-induction", title: "Електромагнітна індукція", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.10" },
        { slug: "noise-interference", title: "Шум і завади", status: "recheck", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.1", hist: [{ file: "hist-johnson-nyquist.md", status: "recheck" }], math: [{ file: "math-clt.md", status: "recheck" }, { file: "math-random-variables.md", status: "recheck" }], proj: [{ file: "proj-noise-generator.md", status: "recheck" }] },
        { slug: "capacitive-coupling", title: "Ємнісна наводка", status: "recheck", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.4", hist: [{ file: "hist-induction-coordination.md", status: "recheck" }] },
        { slug: "inductive-coupling", title: "Індуктивна наводка", status: "recheck", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.5" },
        { slug: "triboelectricity", title: "Трибоелектрика", status: "recheck", origin: "embedded/block-1-circuits-physics/esd-static#1.10.1", hist: [{ file: "hist-franklin-richmann.md", status: "recheck" }] },
        { slug: "body-charge", title: "Заряд тіла", status: "recheck", origin: "embedded/block-1-circuits-physics/esd-static#1.10.2", math: [{ file: "math-hbm.md", status: "recheck" }] },
        { slug: "lightning", title: "Блискавка", status: "recheck", origin: "embedded/block-1-circuits-physics/esd-static#1.10.4", comp: [{ file: "comp-spark-gap-gdt.md", status: "empty" }] },
        { slug: "humidity-static-control", title: "Вологість і статика", status: "recheck", origin: "embedded/block-1-circuits-physics/esd-static#1.10.8" },
        { slug: "em-wave", title: "Електромагнітна хвиля", status: "recheck", origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.1", hist: [{ file: "hist-hertz.md", status: "recheck" }] },
        { slug: "frequency-wavelength", title: "Частота й довжина", status: "recheck", origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.2" },
      ] },
    { slug: "optics", title: "Оптика", scope: "Поширення електромагнітних хвиль і поведінка світла як променя й хвилі: відбиття, заломлення, дифракція, поляризація.",
      topics: [
      ] },
    { slug: "relativity", title: "Відносність", scope: "Фізика великих швидкостей і викривленого простору-часу: спеціальна та загальна теорія відносності й гравітація як геометрія.",
      topics: [
      ] },
    { slug: "quantum-mechanics", title: "Квантова механіка", scope: "Дискретність, дуалізм і ймовірнісний опис мікросвіту (рівняння Шредінгера, оператори, заплутаність) разом із будовою, спектрами та світловими переходами атомів і молекул і квантовою природою хімічного зв'язку.",
      topics: [
      ] },
    { slug: "condensed-matter-physics", title: "Конденсована речовина", scope: "Колективні квантові ефекти у твердих тілах і рідинах (кристали, зонна структура, напівпровідники, надпровідність, магнетизм) та іонізований стан речовини з динамікою заряджених частинок у полях: розряди, утримання, хвилі в плазмі.",
      topics: [
        { slug: "electron-drift", title: "Дрейф електронів", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.3", math: [{ file: "math-estimation.md", status: "recheck" }] },
        { slug: "conductors-insulators", title: "Провідники й діелектрики", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.8" },
        { slug: "resistance-origin", title: "Природа опору", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.9" },
        { slug: "conductivity", title: "Провідність", status: "recheck", origin: "embedded/block-1-circuits-physics/voltage-current-conduction#1.2.10" },
        { slug: "resistance", title: "Опір", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.1", hist: [{ file: "hist-ohm-joule.md", status: "recheck" }] },
        { slug: "resistivity", title: "Питомий опір", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.3" },
        { slug: "resistance-temperature", title: "Опір і температура", status: "recheck", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.4", hist: [{ file: "hist-filament.md", status: "recheck" }, { file: "hist-superconductivity.md", status: "recheck" }] },
        { slug: "ferromagnetism", title: "Феромагнетизм", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.2" },
        { slug: "permanent-magnets", title: "Постійні магніти", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.3", hist: [{ file: "hist-neodymium.md", status: "recheck" }] },
        { slug: "saturation-hysteresis", title: "Насичення й гістерезис", status: "recheck", origin: "embedded/block-1-circuits-physics/magnetism#1.8.6", math: [{ file: "math-hysteresis-loop.md", status: "recheck" }] },
        { slug: "shot-flicker-noise", title: "Дробовий шум", status: "recheck", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.3", comp: [{ file: "comp-resistor-noise.md", status: "recheck" }] },
        { slug: "air-breakdown", title: "Пробій повітря", status: "recheck", origin: "embedded/block-1-circuits-physics/esd-static#1.10.3", math: [{ file: "math-paschen.md", status: "recheck" }] },
        { slug: "semiconductor", title: "Напівпровідник", status: "recheck", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.1", hist: [{ file: "hist-silicon-germanium.md", status: "recheck" }, { file: "hist-diode.md", status: "recheck" }] },
        { slug: "doping", title: "Легування", status: "recheck", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.2" },
        { slug: "pn-junction", title: "PN-перехід", status: "recheck", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.3" },
        { slug: "piezoelectric-effect", title: "П'єзоефект", status: "recheck", origin: "embedded/block-2-components-analog/resonators-references#2.10.2" },
        { slug: "memory-cell-physics", title: "Фізика комірок", status: "recheck", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.8", hist: [{ file: "hist-frohman-eprom.md", status: "recheck" }], math: [{ file: "math-tunneling.md", status: "recheck" }] },
      ] },
    { slug: "nuclear-particle", title: "Ядерна фізика", scope: "Будова, стійкість і перетворення ядра (радіоактивність, поділ, синтез, ядерні моделі) та елементарні частинки й фундаментальні взаємодії: Стандартна модель, кварки, калібрувальні поля, симетрії, механізм Хіггса.",
      topics: [
      ] },
    { slug: "astrophysics-cosmology", title: "Астрофізика", scope: "Будова й еволюція зір, галактик і компактних об'єктів (акреція, нейтронні зорі) разом із походженням і еволюцією Всесвіту як цілого: розширення, реліктове випромінювання, темна матерія й темна енергія.",
      topics: [
      ] },
    { slug: "biophysics", title: "Біофізика", scope: "Фізичні принципи живих систем: мембрани, молекулярні мотори, дифузія в клітині, ентропійна пружність, низькорейнольдсова гідродинаміка.",
      topics: [
      ] },
  ]
});
