/* manifest — «Математика» (тип "book"). Схема — AUTHORING.md §2 (v6). */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "math", title: "Математика",
  sections: [
    { slug: "logic-foundations", title: "Логіка", scope: "Формальні системи, доведення, обчислюваність і самі підвалини математики, включно з теорією множин.",
      topics: [
        { slug: "boolean-algebra", title: "Булева алгебра", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-boole.md", status: "done" }], math: [{ file: "math-axioms-proofs.md", status: "done" }] },
        { slug: "karnaugh-maps", title: "Карти Карно", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-quine-mccluskey.md", status: "done" }] },
        { slug: "finite-automata", title: "Скінченні автомати", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "shannon-expansion", title: "Теорема Шеннона про розкладання", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-boole-shannon.md", status: "done" }], math: [{ file: "math-cofactors.md", status: "done" }], proj: [{ file: "proj-recursive-expansion.md", status: "done" }] },
        { slug: "logic-minimization", title: "Мінімізація логічних функцій", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-minimization.md", status: "done" }], math: [{ file: "math-prime-implicants.md", status: "done" }] },
        { slug: "regular-languages", title: "Регулярні мови", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-chomsky-hierarchy.md", status: "done" }], math: [{ file: "math-pumping-lemma.md", status: "done" }], proj: [{ file: "proj-product-construction.md", status: "done" }] },
        { slug: "pushdown-automata", title: "Магазинні автомати", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-pushdown-store.md", status: "done" }], math: [{ file: "math-pda-cfg-equivalence.md", status: "done" }], proj: [{ file: "proj-expression-parser.md", status: "done" }] },
        { slug: "turing-machine", title: "Машина Тюринга", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-computable-numbers.md", status: "done" }], proj: [{ file: "proj-turing-simulator.md", status: "done" }] },
        { slug: "karnaugh-map", title: "Карта Карно і мінімізація схем", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-quine-mccluskey.md", status: "done" }], math: [{ file: "math-prime-implicants.md", status: "done" }] },
        { slug: "functional-completeness", title: "Функціональна повнота", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-post.md", status: "done" }], math: [{ file: "math-post-criterion.md", status: "done" }], proj: [{ file: "proj-completeness-check.md", status: "done" }] },
        { slug: "mathematical-induction", title: "Математична індукція", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-induction-history.md", status: "done" }], proj: [{ file: "proj-code-correctness.md", status: "done" }] },
        { slug: "mathematical-proof", title: "Математичне доведення", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-birth-of-proof.md", status: "done" }], math: [{ file: "math-proof-methods.md", status: "done" }], proj: [{ file: "proj-proof-checker.md", status: "done" }] },
        { slug: "natural-numbers", title: "Натуральні числа", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-peano-axioms.md", status: "done" }], math: [{ file: "math-recursive-arithmetic.md", status: "done" }], proj: [{ file: "proj-peano-numbers.md", status: "done" }] },
        { slug: "well-ordering-principle", title: "Принцип повного впорядкування", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-zermelo.md", status: "done" }], math: [{ file: "math-well-founded.md", status: "done" }], proj: [{ file: "proj-termination.md", status: "done" }] },
        { slug: "infinite-descent", title: "Нескінченний спуск Ферма", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-fermat-descent.md", status: "done" }], math: [{ file: "math-right-triangle-area.md", status: "done" }, { file: "math-two-squares-descent.md", status: "done" }] },
        { slug: "formal-language", title: "Формальна мова", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-thue-to-backus.md", status: "done" }], math: [{ file: "math-how-many-languages.md", status: "done" }], proj: [{ file: "proj-language-algebra.md", status: "done" }] },
        { slug: "chomsky-hierarchy", title: "Ієрархія Хомського", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-strict-inclusions.md", status: "done" }] },
        { slug: "zhegalkin-polynomial", title: "Поліном Жегалкіна", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-arithmetization.md", status: "done" }], math: [{ file: "math-mobius-transform.md", status: "done" }], proj: [{ file: "proj-anf-transform.md", status: "done" }] },
        { slug: "binary-decision-diagram", title: "Двійкова діаграма рішень (BDD)", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-canonicity.md", status: "done" }] },
        { slug: "boolean-satisfiability", title: "Задача здійсненності (SAT)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-cook-levin.md", status: "done" }], math: [{ file: "math-reductions.md", status: "done" }], proj: [{ file: "proj-dpll-solver.md", status: "done" }] },
        { slug: "godel-incompleteness", title: "Теореми Геделя про неповноту", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-hilbert-program.md", status: "done" }], math: [{ file: "math-godel-numbering.md", status: "done" }], proj: [{ file: "proj-self-reference-code.md", status: "done" }] },
        { slug: "church-turing-thesis", title: "Теза Черча–Тюринга", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-thesis-birth.md", status: "done" }], proj: [{ file: "proj-three-models.md", status: "done" }] },
        { slug: "busy-beaver", title: "Завзятий бобер (busy beaver)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-beaver-hunt.md", status: "done" }], math: [{ file: "math-uncomputable.md", status: "done" }], proj: [{ file: "proj-beaver-search.md", status: "done" }] },
        { slug: "set-theory", title: "Теорія множин", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-cantor.md", status: "done" }], math: [{ file: "math-everything-is-a-set.md", status: "done" }], proj: [{ file: "proj-sets-in-code.md", status: "done" }] },
        { slug: "axiom-of-choice", title: "Аксіома вибору", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-nonmeasurable.md", status: "done" }, { file: "math-zorn-equivalence.md", status: "done" }] },
        { slug: "ordinal-numbers", title: "Порядкові числа (ординали)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-cantor-ordinals.md", status: "done" }], math: [{ file: "math-ordinal-arithmetic.md", status: "done" }], proj: [{ file: "proj-goodstein.md", status: "done" }] },
        { slug: "proof-by-contradiction", title: "Доведення від супротивного", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "countable-sets", title: "Зліченні та незліченні множини", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "linear-bounded-automaton", title: "Лінійно обмежений автомат", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "decidable-languages", title: "Розв'язні мови", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "russell-paradox", title: "Парадокс Рассела", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cantor-diagonal", title: "Діагональний метод Кантора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tarski-undefinability", title: "Теорема Тарського про невизначність істини", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "zfc-set-theory", title: "Аксіоматика Цермело-Френкеля (ZFC)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lambda-calculus", title: "Лямбда-числення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "general-recursive-functions", title: "Загальнорекурсивні функції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "primitive-recursive-functions", title: "Примітивно-рекурсивні функції", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "kleene-recursion-theorem", title: "Теорема рекурсії Кліні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cardinal-numbers", title: "Кардинальні числа (потужність)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "continuum-hypothesis", title: "Гіпотеза континууму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "equivalence-relation", title: "Відношення еквівалентності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rice-theorem", title: "Теорема Райса", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "number-theory", title: "Теорія чисел", scope: "Властивості цілих чисел, подільність, прості числа, діофантові рівняння та арифметичні структури.",
      topics: [
        { slug: "why-binary", title: "Чому двійкова", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-leibniz.md", status: "done" }] },
        { slug: "positional-systems", title: "Позиційні системи", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-hex-notation.md", status: "done" }] },
        { slug: "twos-complement", title: "Доповняльний код", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-modular-arithmetic.md", status: "done" }], math: [{ file: "math-modular-arithmetic.md", status: "done" }] },
        { slug: "modular-arithmetic", title: "Модульна арифметика", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "address-space", title: "Адресний простір", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "twos-complement-arithmetic", title: "Арифметика доповняльного коду", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-method-of-complements.md", status: "done" }], math: [{ file: "math-overflow-detection.md", status: "done" }] },
        { slug: "binary-logarithm", title: "Двійковий логарифм", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-binary-logarithm.md", status: "done" }], math: [{ file: "math-change-of-base.md", status: "done" }], proj: [{ file: "proj-ilog2.md", status: "done" }] },
        { slug: "gcd-euclidean", title: "НСД і алгоритм Евкліда", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-euclid-algorithm.md", status: "done" }], math: [{ file: "math-bezout.md", status: "done" }], proj: [{ file: "proj-gcd-code.md", status: "done" }] },
        { slug: "chinese-remainder-theorem", title: "Китайська теорема про залишки", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-sunzi-to-gauss.md", status: "done" }], math: [{ file: "math-crt-derivation.md", status: "done" }], proj: [{ file: "proj-crt-solver.md", status: "done" }] },
        { slug: "euler-totient", title: "Функція Ейлера і теорема Ейлера", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-euler-fermat.md", status: "done" }], math: [{ file: "math-euler-proof.md", status: "done" }], proj: [{ file: "proj-rsa-toy.md", status: "done" }] },
        { slug: "floating-point", title: "Числа з рухомою комою", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-birth-of-floating-point.md", status: "done" }], math: [{ file: "math-representable-set.md", status: "done" }] },
        { slug: "bcd", title: "BCD — двійково-десятковий код", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "octal-system", title: "Вісімкова система та Unix-права", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ones-complement", title: "Обернений код", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sign-magnitude", title: "Знак-величина", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ternary-computing", title: "Трійкова основа та комп'ютер Сетунь", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "binary-arithmetic", title: "Арифметика в двійковій системі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "binary-fractions", title: "Двійкові дроби: representability", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "signed-multiplication", title: "Знакове множення: алгоритм Бута", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "prime-numbers", title: "Прості числа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fundamental-theorem-arithmetic", title: "Основна теорема арифметики", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lcm", title: "НСК — найменше спільне кратне", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "linear-diophantine", title: "Лінійні діофантові рівняння", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "modular-inverse", title: "Обернений елемент за модулем", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "modular-exponentiation", title: "Піднесення до степеня за модулем", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fermat-little-theorem", title: "Мала теорема Ферма", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "multiplicative-order", title: "Мультиплікативний порядок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "carmichael-function", title: "Функція Кармайкла λ(n)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "fibonacci-numbers", title: "Числа Фібоначчі", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "continued-fractions", title: "Ланцюгові дроби", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "perfect-numbers", title: "Досконалі числа", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "mersenne-primes", title: "Числа Мерсенна і прості Мерсенна", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "irrational-numbers", title: "Ірраціональні числа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pythagorean-triples", title: "Трійки Піфагора", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "fermats-last-theorem", title: "Велика теорема Ферма", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "quadratic-residue", title: "Квадратичні лишки", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "algebra", title: "Алгебра", scope: "Абстрактні алгебраїчні структури — групи, кільця, поля, модулі — та поліноміальні рівняння.",
      topics: [
        { slug: "rearranging-formulas", title: "Перестановка формул", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "crc", title: "Циклічна надмірність", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "galois-field", title: "Скінченні поля (поля Галуа)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "finite-fields", title: "Скінченні поля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "polynomial-rings", title: "Кільця многочленів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lie-group-so3", title: "Група SO(3) і її подвійне покриття SU(2)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rotation-group-so3", title: "Група SO(3)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "group-theory", title: "Групи, підгрупи й теорема Лагранжа", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "rings", title: "Кільця: додавання й множення в одній структурі", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "monoid", title: "Моноїд", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "linear-algebra", title: "Лінійна алгебра", scope: "Векторні простори, лінійні відображення, матриці та спектральна теорія.",
      topics: [
        { slug: "superposition", title: "Суперпозиція", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "linear-systems", title: "Лінійні системи", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "gauss-elimination", title: "Метод Гаусса", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "matrices-as-operations", title: "Матриці як дії", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "rotation-matrices", title: "Матриці повороту", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "vector-components", title: "Складові вектора", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-vector-concept.md", status: "done" }] },
        { slug: "vector-addition", title: "Додавання векторів", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "dot-product", title: "Скалярний добуток", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "cross-product", title: "Векторний добуток", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "state-space-representation", title: "Простір станів: опис динамічних систем", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "state-transition-matrix", title: "Матриця переходу стану", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "exterior-product", title: "Зовнішній добуток (форма Грассмана)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vector-norm", title: "Норма вектора й нормування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inner-product-space", title: "Простір зі скалярним добутком", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lu-decomposition", title: "LU-розклад", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "matrix-condition-number", title: "Умовне число матриці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gaussian-jordan-elimination", title: "Метод Гаусса–Жордана", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "matrix-rank", title: "Ранг матриці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "null-space", title: "Ядро лінійного відображення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "matrix-determinant", title: "Визначник матриці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "eigenvalues", title: "Власні вектори та власні значення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "affine-transform", title: "Афінні перетворення та однорідні координати", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gram-schmidt", title: "Процес Грама–Шмідта та ортогоналізація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "homogeneous-transform", title: "Однорідні перетворення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "linear-map", title: "Лінійне відображення і матриця", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "linear-combination", title: "Лінійна комбінація векторів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vector-space", title: "Векторний простір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "change-of-basis", title: "Зміна базису", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "curvilinear-coordinates", title: "Криволінійні координати і локальний базис", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "combinatorics", title: "Комбінаторика", scope: "Підрахунок, перелік і структура скінченних та дискретних конфігурацій, графи.",
      topics: [
        { slug: "graph-theory", title: "Теорія графів", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "graph-coloring", title: "Розфарбування графів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spanning-tree", title: "Кістякове дерево", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bipartite-graph", title: "Дводольний граф", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lfsr", title: "Лінійний регістр зі зворотним зв'язком (LFSR)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "unsigned-arithmetic", title: "Беззнакова арифметика і переповнення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "formal-grammar", title: "Формальні граматики (CFG, BNF)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "combinations", title: "Комбінації і біноміальний коефіцієнт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inclusion-exclusion", title: "Принцип включення-виключення", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "de-bruijn-sequence", title: "Послідовності де Брейна", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "geometry", title: "Геометрія", scope: "Фігури, простори, відстані й симетрії — від евклідової до проєктивної та алгебраїчної геометрії; включає диференціальну геометрію: гладкі многовиди, кривизну, зв'язності.",
      topics: [
        { slug: "euler-angles", title: "Кути Ейлера", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-governor-pid.md", status: "done" }] },
        { slug: "quaternions", title: "Кватерніони", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "sine-cosine", title: "Синус і косинус", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "phase-shift", title: "Фаза й зсув", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "power-triangle", title: "Трикутник потужності", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "trilateration", title: "Трилатерація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gimbal", title: "Кардановий підвіс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "direction-cosine-matrix", title: "Матриця напрямних косинусів (DCM)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gimbal-lock", title: "Складання рамок (gimbal lock)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rodrigues-rotation", title: "Формула повороту Родриґа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tangent-cotangent", title: "Тангенс і котангенс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inverse-trig", title: "Обернені тригонометричні функції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "trig-identities", title: "Тригонометричні тотожності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pythagorean-theorem", title: "Теорема Піфагора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "surface-normal", title: "Нормаль до поверхні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ellipse", title: "Еліпс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "coordinate-system", title: "Система координат", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "trigonometry", title: "Тригонометрія", scope: "Тригонометричні функції, тотожності та обернені функції, кутові співвідношення в прямокутному трикутнику й на колі.",
      topics: [
        { slug: "atan2", title: "atan2 — чотиричвертний арктангенс", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "topology", title: "Топологія", scope: "Властивості просторів, інваріантні щодо неперервних деформацій, та їхні алгебраїчні інваріанти.",
      topics: [
      ] },
    { slug: "real-analysis", title: "Аналіз", scope: "Границі, диференціювання, інтегрування, теорія міри; включає гармонічний аналіз — ряди й перетворення Фур'є, вейвлети.",
      topics: [
        { slug: "time-and-frequency", title: "Час і частота", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-fourier.md", status: "done" }] },
        { slug: "fourier-idea", title: "Ідея Фур'є", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "spectrum", title: "Спектр", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "dft", title: "ДПФ", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "windowing-leakage", title: "Вікно й витік", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "derivative", title: "Похідна", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "integral", title: "Інтеграл", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "convolution", title: "Згортка", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "extrema", title: "Екстремуми", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "rms", title: "RMS", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "sine-derivative", title: "Похідна синуса", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "work-integral", title: "Інтеграл роботи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "half-power", title: "Точка -3 дБ", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "logarithms", title: "Логарифми", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "divergence", title: "Дивергенція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gauss-flux-theorem", title: "Теорема Гаусса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "z-transform", title: "Z-перетворення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "time-frequency-tradeoff", title: "Принцип невизначеності для сигналів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fourier-series", title: "Ряди Фур'є", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "taylor-series", title: "Ряди Тейлора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "numerical-differentiation", title: "Чисельне диференціювання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "numerical-integration", title: "Чисельне інтегрування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "impulse-response", title: "Імпульсна характеристика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "circular-convolution", title: "Кільцева згортка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fir-filter", title: "FIR-фільтр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "chain-rule", title: "Ланцюгове правило", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "zero-padding", title: "Zero-padding: інтерполяція спектра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hessian-matrix", title: "Матриця Гессе й багатовимірні екстремуми", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "convex-functions", title: "Опуклі функції й глобальний мінімум", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bode-plot", title: "Діаграма Боде", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "improper-integral", title: "Невласний інтеграл", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lebesgue-integral", title: "Інтеграл Лебега", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "line-integral", title: "Криволінійний інтеграл", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "e-number", title: "Число e", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spectrogram", title: "Спектрограма", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "psd", title: "Спектральна щільність потужності (PSD)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sampling-theorem", title: "Теорема Найквіста — Шеннона про дискретизацію", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dirichlet-kernel", title: "Ядро Діріхле", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "parseval-theorem", title: "Теорема Парсеваля і RMS гармонік", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "image-gradient", title: "Градієнт зображення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gibbs-phenomenon", title: "Явище Гіббса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "universal-approximation", title: "Теорема про універсальну апроксимацію", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "homogeneous-ode", title: "Лінійні диференціальні рівняння: однорідне і частинний розв'язок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "laplace-equation", title: "Рівняння Лапласа і гармонічні функції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sequence-limit", title: "Границя послідовності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gradient", title: "Градієнт", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "complex-analysis", title: "Комплексний аналіз", scope: "Голоморфні функції комплексної змінної, лишки та конформні відображення.",
      topics: [
        { slug: "phasors", title: "Фазори", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "euler-formula", title: "Формула Ейлера", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "impedance", title: "Імпеданс", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "smith-chart", title: "Діаграма Сміта: навігація в комплексному імпедансі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "complex-numbers", title: "Комплексні числа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "admittance", title: "Адмітанс", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "functional-analysis", title: "Функціональний аналіз", scope: "Нескінченновимірні векторні простори, оператори та спектральна теорія на функціях.",
      topics: [
        { slug: "signal-orthogonality", title: "Ортогональність сигналів", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "differential-equations", title: "Диференціальні рівняння", scope: "Звичайні та частинні рівняння, що описують динаміку, і методи їх аналізу.",
      topics: [
        { slug: "capacitor-derivative", title: "Похідна конденсатора", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "exponential-ode", title: "Експоненційне ОДУ", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rl-ode", title: "ОДУ RL-кола", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "transfer-function", title: "Передавальна функція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cascading", title: "Каскадування фільтрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thomson-formula", title: "Формула Томсона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "damping", title: "Загасання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "q-factor", title: "Добротність Q", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "laplace-transform", title: "Перетворення Лапласа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bessel-functions", title: "Функції Бесселя", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "probability", title: "Імовірність", scope: "Математична теорія випадковості — випадкові величини, процеси та граничні теореми.",
      topics: [
        { slug: "probability-basics", title: "Імовірність як міра непевності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mean-variance", title: "Середнє й дисперсія", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "central-limit", title: "Центральна гранична теорема", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "thermal-fluctuations", title: "Теплові флуктуації", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "bayesian-estimation", title: "Байєсівське оцінювання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "covariance-matrix-intuition", title: "Матриця коваріації: інтуїція і геометрія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gaussian-distribution", title: "Нормальний розподіл", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "heavy-tail-distributions", title: "Розподіли з важкими хвостами", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "characteristic-functions", title: "Характеристичні функції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "normal-distribution", title: "Нормальний розподіл", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "covariance", title: "Коваріація і кореляція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "central-limit-theorem", title: "Центральна гранична теорема", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "binomial-distribution", title: "Біноміальний розподіл", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "poisson-process", title: "Пуассонівський процес", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "order-statistics", title: "Порядкові статистики", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "independent-trials", title: "Незалежні спроби", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "littles-law", title: "Закон Літтла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "markov-chain", title: "Ланцюги Маркова", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "random-walk", title: "Випадкове блукання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "birthday-paradox", title: "Парадокс днів народжень", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "martingale", title: "Мартингал", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "law-of-large-numbers", title: "Закон великих чисел", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "statistics", title: "Статистика", scope: "Висновки з даних — оцінювання, перевірка гіпотез, регресія та байєсів підхід.",
      topics: [
        { slug: "averaging", title: "Усереднення", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "noise-density", title: "Густина шуму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "accuracy", title: "Точність і похибка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tolerance", title: "Допуски", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "least-squares", title: "Найменші квадрати", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "error-propagation", title: "Додавання похибок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "poisson-statistics", title: "Статистика Пуассона", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "q-stability", title: "Стабільність Q", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "derating", title: "Деретинг", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "averaging-gain", title: "Виграш усереднення", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "uncertainty-propagation", title: "Поширення невизначеності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "allan-variance", title: "Дисперсія Аллана", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sample-variance", title: "Вибіркова дисперсія і поправка Бесселя", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "median-robust-stats", title: "Медіана і робастна статистика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "exponential-smoothing", title: "Експоненційне згладжування (EMA)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "oversampling-decimation", title: "Oversampling і decimation", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "robust-averaging", title: "Робасне усереднення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "weighted-average", title: "Зважене середнє", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "moving-average", title: "Ковзне середнє", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "correlation-coefficient", title: "Коефіцієнт кореляції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "goodness-of-fit", title: "Якість підгонки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "weighted-least-squares", title: "Зважений МНК", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "chi-squared-test", title: "Критерій χ² Пірсона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "percentiles-quantiles", title: "Перцентилі й хвости", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "optimization", title: "Оптимізація", scope: "Пошук екстремумів за обмежень — лінійне, опукле й дискретне програмування; включає теорію керування: системи зі зворотним зв'язком.",
      topics: [
        { slug: "step-response", title: "Крокова відповідь", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "feedforward", title: "Феєдфорвард", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pid-calculus", title: "ПІД-регулятор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "derivative-filter", title: "Фільтрація D-члена: смугообмежений диференціатор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "phase-lead-lag", title: "Фазо-випереджаючі та фазо-відстаючі ланки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "integrator-windup", title: "Накопичувальне насичення (windup)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nyquist-criterion", title: "Критерій Найквіста", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "conditional-stability", title: "Умовна стійкість", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "positive-feedback", title: "Додатний зворотний зв'язок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "block-diagram-algebra", title: "Алгебра блок-схем", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "anti-windup", title: "Анти-windup", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gain-scheduling", title: "Gain scheduling", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "relay-autotuning", title: "Relay-автоналаштування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bang-bang-control", title: "Дворежимний регулятор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "loop-gain", title: "Петльове підсилення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lyapunov-stability", title: "Стійкість за Ляпуновим", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "game-theory", title: "Теорія ігор", scope: "Математика стратегічної взаємодії, рівноваг і прийняття рішень за конфлікту.",
      topics: [
      ] },
    { slug: "information-theory", title: "Теорія інформації", scope: "Кількісна міра інформації, ентропія, кодування та межі передавання й стиснення.",
      topics: [
        { slug: "hamming-distance", title: "Відстань Гемінга", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-popcount-distance.md", status: "done" }] },
        { slug: "kraft-inequality", title: "Нерівність Крафта", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "source-coding-theorem", title: "Теорема Шеннона про кодування джерела", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "kl-divergence", title: "Розбіжність Кульбака–Лейблера", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "weight-distribution", title: "Ваговий розподіл коду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "coding-bounds", title: "Межі на коди: Сінглтон, Плоткін, Гілберт–Варшамов", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "singleton-bound", title: "Межа Сінглтона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "complete-codes", title: "Повні коди та рівність Крафта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rary-codes", title: "Коди над r-арним алфавітом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gibbs-inequality", title: "Нерівність Гіббса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "uniquely-decodable-codes", title: "Однозначно декодовні коди", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "information-entropy", title: "Інформаційна ентропія Шеннона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gray-code", title: "Код Грея", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "numerical-analysis", title: "Числові методи", scope: "Алгоритми наближеного розв'язання математичних задач і аналіз їхньої похибки та збіжності.",
      topics: [
        { slug: "ieee754", title: "IEEE 754", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "si-prefixes", title: "Префікси СІ", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "dimensional-analysis", title: "Розмірний аналіз", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "e-series", title: "Ряди E", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "energy-units", title: "Одиниці енергії", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "ppm", title: "PPM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-resistance", title: "Тепловий опір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "error-budget", title: "Бюджет похибок", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "quantization-noise", title: "Шум квантування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inverse-problem", title: "Обернена задача вимірювання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "buckingham-pi-theorem", title: "Теорема Бекінгема (Π-теорема)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "preferred-numbers", title: "Переважні числа (ряди Ренара)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tolerance-stack", title: "Накопичення допусків у ланцюжку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "monte-carlo-propagation", title: "Метод Монте-Карло для поширення похибок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tolerance-stackup", title: "Складання допусків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "float-arithmetic-error", title: "Модель похибки операцій з плаваючою комою", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "scientific-notation", title: "Наукова та інженерна нотація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "unit-conversion", title: "Переведення одиниць", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "numeric-stability", title: "Чисельна стійкість алгоритмів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dct", title: "Дискретне косинусне перетворення (DCT)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dft-spectrum", title: "Дискретне перетворення Фур'є", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "window-functions", title: "Віконні функції у спектральному аналізі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "polynomial-fit", title: "Підгонка полінома", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "aliasing", title: "Аліасинг (теорема Найквіста)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fixed-point-iteration", title: "Ітерація нерухомої точки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "newton-raphson", title: "Метод Ньютона — Рафсона", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
  ]
});
