/* book/math/manifest.js — книга-предмет «Математика» (тип "book").
   Схема — AUTHORING.md §2. Статуси: done | empty | update | deeper | recheck. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "math", title: "Математика",
  sections: [
    { slug: "logic-foundations", title: "Логіка", scope: "Формальні системи, доведення, обчислюваність і самі підвалини математики, включно з теорією множин.",
      topics: [
        { slug: "boolean-algebra", title: "Булева алгебра", status: "recheck", origin: "embedded/block-3-digital-processor/logic-gates#3.2.1", hist: [{ file: "hist-boole.md", status: "recheck" }] },
        { slug: "boolean-algebra-2", title: "Булева алгебра", status: "recheck", origin: "math/boolean-algebra/" },
        { slug: "karnaugh-maps", title: "Карти Карно", status: "recheck", origin: "math/karnaugh-maps/" },
        { slug: "finite-automata", title: "Скінченні автомати", status: "recheck", origin: "math/fsm-formal/" },
      ] },
    { slug: "number-theory", title: "Теорія чисел", scope: "Властивості цілих чисел, подільність, прості числа, діофантові рівняння та арифметичні структури.",
      topics: [
        { slug: "why-binary", title: "Чому двійкова", status: "recheck", origin: "embedded/block-3-digital-processor/number-representation#3.4.1", hist: [{ file: "hist-leibniz.md", status: "recheck" }] },
        { slug: "positional-systems", title: "Позиційні системи", status: "recheck", origin: "embedded/block-3-digital-processor/number-representation#3.4.2" },
        { slug: "twos-complement", title: "Доповняльний код", status: "recheck", origin: "embedded/block-3-digital-processor/number-representation#3.4.3", hist: [{ file: "hist-modular-arithmetic.md", status: "recheck" }], math: [{ file: "math-modular-arithmetic.md", status: "empty" }] },
        { slug: "modular-arithmetic", title: "Модульна арифметика", status: "recheck", origin: "math/modular-arithmetic/" },
        { slug: "address-space", title: "Адресний простір", status: "recheck", origin: "math/address-space/" },
      ] },
    { slug: "algebra", title: "Алгебра", scope: "Абстрактні алгебраїчні структури — групи, кільця, поля, модулі — та поліноміальні рівняння.",
      topics: [
        { slug: "rearranging-formulas", title: "Перестановка формул", status: "empty", origin: "xref:chemistry/mass-fraction" },
        { slug: "crc", title: "Циклічна надмірність", status: "recheck", origin: "math/crc-cyclic-redundancy/" },
      ] },
    { slug: "linear-algebra", title: "Лінійна алгебра", scope: "Векторні простори, лінійні відображення, матриці та спектральна теорія.",
      topics: [
        { slug: "superposition", title: "Суперпозиція", status: "done", levels: ["basic"], origin: "math/superposition/" },
        { slug: "linear-systems", title: "Лінійні системи", status: "empty", origin: "math/linear-algebra/undefined" },
        { slug: "gauss-elimination", title: "Метод Гаусса", status: "deeper", levels: ["basic"], origin: "math/gauss-elimination/" },
        { slug: "matrices-as-operations", title: "Матриці як дії", status: "deeper", levels: ["basic"], origin: "math/matrices-as-operations/" },
        { slug: "rotation-matrices", title: "Матриці повороту", status: "empty", origin: "math/linear-algebra/undefined" },
        { slug: "vector-components", title: "Складові вектора", status: "empty", origin: "math/vector-components/" },
        { slug: "vector-addition", title: "Додавання векторів", status: "empty", origin: "math/vector-analysis/undefined" },
        { slug: "dot-product", title: "Скалярний добуток", status: "empty", origin: "math/gradient/" },
        { slug: "cross-product", title: "Векторний добуток", status: "empty", origin: "math/cross-product/" },
      ] },
    { slug: "combinatorics", title: "Комбінаторика", scope: "Підрахунок, перелік і структура скінченних та дискретних конфігурацій, графи.",
      topics: [
        { slug: "graph-theory", title: "Теорія графів", status: "update", levels: ["basic"], origin: "math/graph-theory/" },
      ] },
    { slug: "geometry", title: "Геометрія", scope: "Фігури, простори, відстані й симетрії — від евклідової до проєктивної та алгебраїчної геометрії; включає диференціальну геометрію: гладкі многовиди, кривизну, зв'язності.",
      topics: [
        { slug: "euler-angles", title: "Кути Ейлера", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.1", hist: [{ file: "hist-governor-pid.md", status: "recheck" }] },
        { slug: "quaternions", title: "Кватерніони", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.2" },
        { slug: "sine-cosine", title: "Синус і косинус", status: "empty", origin: "math/sine-cosine/" },
        { slug: "phase-shift", title: "Фаза й зсув", status: "empty", origin: "math/phasors/" },
        { slug: "power-triangle", title: "Трикутник потужності", status: "empty", origin: "math/power-triangle/" },
      ] },
    { slug: "topology", title: "Топологія", scope: "Властивості просторів, інваріантні щодо неперервних деформацій, та їхні алгебраїчні інваріанти.",
      topics: [
      ] },
    { slug: "real-analysis", title: "Аналіз", scope: "Границі, диференціювання, інтегрування, теорія міри; включає гармонічний аналіз — ряди й перетворення Фур'є, вейвлети.",
      topics: [
        { slug: "time-and-frequency", title: "Час і частота", status: "recheck", origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.1", hist: [{ file: "hist-fourier.md", status: "recheck" }] },
        { slug: "fourier-idea", title: "Ідея Фур'є", status: "recheck", origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.2" },
        { slug: "spectrum", title: "Спектр", status: "recheck", origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.3" },
        { slug: "dft", title: "ДПФ", status: "recheck", origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.4" },
        { slug: "windowing-leakage", title: "Вікно й витік", status: "recheck", origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.6" },
        { slug: "why-frequency-domain", title: "Навіщо частота", status: "recheck", origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.7" },
        { slug: "derivative", title: "Похідна", status: "empty", origin: "math/derivative/" },
        { slug: "integral", title: "Інтеграл", status: "empty", origin: "math/calculus/undefined" },
        { slug: "convolution", title: "Згортка", status: "empty", origin: "math/calculus/undefined" },
        { slug: "extrema", title: "Екстремуми", status: "empty", origin: "math/derivative-max/" },
        { slug: "rms", title: "RMS", status: "empty", origin: "math/rms-derivation/" },
        { slug: "sine-derivative", title: "Похідна синуса", status: "empty", origin: "math/sine-derivative/" },
        { slug: "work-integral", title: "Інтеграл роботи", status: "empty", origin: "math/work-integral/" },
        { slug: "half-power", title: "Точка -3 дБ", status: "empty", origin: "math/half-power/" },
        { slug: "logarithms", title: "Логарифми", status: "empty", origin: "math/logarithms/" },
        { slug: "divergence", title: "Дивергенція", status: "empty", origin: "math/vector-analysis/undefined" },
        { slug: "gauss-flux-theorem", title: "Теорема Гаусса", status: "empty", origin: "math/vector-analysis/undefined" },
        { slug: "calculus-for-pid", title: "Похідна й інтеграл для PID", status: "empty" },
      ] },
    { slug: "complex-analysis", title: "Комплексний аналіз", scope: "Голоморфні функції комплексної змінної, лишки та конформні відображення.",
      topics: [
        { slug: "phasors", title: "Фазори", status: "empty", origin: "math/complex-phasors/" },
        { slug: "euler-formula", title: "Формула Ейлера", status: "empty", origin: "math/trigonometry-phasors/undefined" },
        { slug: "impedance", title: "Імпеданс", status: "empty", origin: "math/impedance/" },
      ] },
    { slug: "functional-analysis", title: "Функціональний аналіз", scope: "Нескінченновимірні векторні простори, оператори та спектральна теорія на функціях.",
      topics: [
      ] },
    { slug: "differential-equations", title: "Диференціальні рівняння", scope: "Звичайні та частинні рівняння, що описують динаміку, і методи їх аналізу.",
      topics: [
        { slug: "capacitor-derivative", title: "Похідна конденсатора", status: "empty", origin: "math/derivative-cap/" },
        { slug: "exponential-ode", title: "Експоненційне ОДУ", status: "empty", origin: "math/exponential-ode/" },
        { slug: "rl-ode", title: "ОДУ RL-кола", status: "empty", origin: "math/rl-ode/" },
        { slug: "transfer-function", title: "Передавальна функція", status: "empty", origin: "math/transfer-function/" },
        { slug: "cascading", title: "Каскадування фільтрів", status: "empty", origin: "math/cascading/" },
        { slug: "thomson-formula", title: "Формула Томсона", status: "empty", origin: "math/thomson-formula/" },
        { slug: "damping", title: "Загасання", status: "empty", origin: "math/damping/" },
        { slug: "q-factor", title: "Добротність Q", status: "empty", origin: "math/q-factor/" },
      ] },
    { slug: "probability", title: "Імовірність", scope: "Математична теорія випадковості — випадкові величини, процеси та граничні теореми.",
      topics: [
        { slug: "mean-variance", title: "Середнє й дисперсія", status: "empty", origin: "math/random-variables/" },
        { slug: "central-limit", title: "Центральна гранична теорема", status: "empty", origin: "math/central-limit/" },
        { slug: "thermal-fluctuations", title: "Теплові флуктуації", status: "empty", origin: "math/kt-thermal/" },
      ] },
    { slug: "statistics", title: "Статистика", scope: "Висновки з даних — оцінювання, перевірка гіпотез, регресія та байєсів підхід.",
      topics: [
        { slug: "averaging", title: "Усереднення", status: "empty", origin: "math/averaging/" },
        { slug: "noise-density", title: "Густина шуму", status: "empty", origin: "math/noise-density/" },
        { slug: "accuracy", title: "Точність і похибка", status: "empty", origin: "math/accuracy/" },
        { slug: "tolerance", title: "Допуски", status: "empty", origin: "math/tolerance/" },
        { slug: "least-squares", title: "Найменші квадрати", status: "empty", origin: "math/statistics-errors/undefined" },
        { slug: "error-propagation", title: "Додавання похибок", status: "empty", origin: "math/statistics-errors/undefined" },
        { slug: "poisson-statistics", title: "Статистика Пуассона", status: "empty", origin: "math/statistics-errors/undefined" },
        { slug: "q-stability", title: "Стабільність Q", status: "empty", origin: "math/q-stability/" },
        { slug: "derating", title: "Деретинг", status: "empty", origin: "math/derating/" },
        { slug: "averaging-gain", title: "Виграш усереднення", status: "empty" },
      ] },
    { slug: "optimization", title: "Оптимізація", scope: "Пошук екстремумів за обмежень — лінійне, опукле й дискретне програмування; включає теорію керування: системи зі зворотним зв'язком.",
      topics: [
        { slug: "open-vs-closed-loop", title: "Зворотний зв'язок", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.5" },
        { slug: "proportional-control", title: "П-регулятор", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.6" },
        { slug: "integral-control", title: "І-складова", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.7" },
        { slug: "derivative-control", title: "Д-складова", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.8" },
        { slug: "pid-tuning-cascade", title: "Налаштування ПІД", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.10" },
        { slug: "loop-stability", title: "Запас стійкості", status: "empty", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.11" },
        { slug: "step-response", title: "Крокова відповідь", status: "empty", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.12" },
        { slug: "feedforward", title: "Феєдфорвард", status: "empty", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.13" },
        { slug: "pid-calculus", title: "ПІД-регулятор", status: "empty", origin: "math/calculus/undefined" },
      ] },
    { slug: "game-theory", title: "Теорія ігор", scope: "Математика стратегічної взаємодії, рівноваг і прийняття рішень за конфлікту.",
      topics: [
      ] },
    { slug: "information-theory", title: "Теорія інформації", scope: "Кількісна міра інформації, ентропія, кодування та межі передавання й стиснення.",
      topics: [
        { slug: "hamming-distance", title: "Відстань Гемінга", status: "recheck", origin: "math/hamming-distance/" },
      ] },
    { slug: "numerical-analysis", title: "Числові методи", scope: "Алгоритми наближеного розв'язання математичних задач і аналіз їхньої похибки та збіжності.",
      topics: [
        { slug: "ieee754", title: "IEEE 754", status: "recheck", origin: "math/ieee754/" },
        { slug: "si-prefixes", title: "Префікси СІ", status: "done", levels: ["basic"], origin: "math/si-prefixes/" },
        { slug: "dimensional-analysis", title: "Розмірний аналіз", status: "done", levels: ["basic"], origin: "math/dimensional-analysis/" },
        { slug: "e-series", title: "Ряди E", status: "done", levels: ["basic"], origin: "math/e-series/" },
        { slug: "energy-units", title: "Одиниці енергії", status: "done", levels: ["basic"], origin: "math/energy-units/" },
        { slug: "ppm", title: "PPM", status: "empty", origin: "math/ppm-math/" },
        { slug: "thermal-resistance", title: "Тепловий опір", status: "empty", origin: "math/thermal-resistance/" },
        { slug: "error-budget", title: "Бюджет похибок", status: "empty" },
      ] },
  ]
});
