/* ──────────────────────────────────────────────────────────────────────────
   manifest.js — структура книги (повна мапа курсу: 7 модулів · 60 розділів)
   Єдине джерело правди для навігації. Редагується вручну.

   Нумерація — М.Р.Т (модуль.розділ.тема): «4.3.2» = модуль 4, розділ 3,
   тема 2. n у розділі — номер РОЗДІЛУ ВСЕРЕДИНІ модуля (Р).

   Як додати новий готовий розділ:
     1) знайди його в потрібному модулі нижче;
     2) додай йому поля: dir, main, histories і постав status:'done'.
        • dir       — шлях до папки розділу ВІД embedded/ (тобто з block-…);
                      префікс embedded/ додає basePath нижче.
                      Старі папки звуться chNN-… (історичні наскрізні номери),
                      нові розділи — rРР-… (внутрімодульний номер Р)
        • main      — головний .md розділу (теми)
        • histories — історичні вставки В ПОРЯДКУ ЧИТАННЯ (спершу історія
                      до розділу, далі — історії до тем). Заголовки тягнуться
                      з самих файлів автоматично, тож тут лише імена.
     Усе інше (сайдбар, якорі, перехресні лінки) збереться саме.
   ────────────────────────────────────────────────────────────────────────── */
window.BOOK = {
  title: "Вбудована електроніка й автономні системи",
  subtitle: "Глибокий курс — від заряду в атомі до машинного бачення на борту. " +
            "Сім модулів, шістдесят розділів, побудованих від першопричин.",
  // короткий підпис у шапці сайдбару
  shortTitle: "Вбудована електроніка",

  // посилання «← Бібліотека» у сайдбарі (стартова сторінка зі списком книг)
  libraryHref: "index.html",

  // Префікс до контенту відносно index.html. Обгортка лежить у корені репо,
  // а самі .md/.svg — у embedded/. Так Pages «from root» і локальний сервер
  // у корені працюють однаково. Хочеш покласти обгортку в /docs поряд із
  // контентом — постав "" і перемісти embedded/ туди.
  basePath: "embedded/",

  modules: [
    {
      n: 1,
      title: "Фізика електрики й кіл",
      slug: "block-1-circuits-physics",
      chapters: [
        { n: 1, status: "done", title: "Заряд, електричне поле й потенціал",
          dir: "block-1-circuits-physics/ch01-charge-field-potential", main: "ch01-charge-field-potential.md",
          histories: ["history-electricity.md", "ch01-s1-history-millikan.md", "ch01-s2-history-coulomb.md", "ch01-s3-history-faraday.md", "ch01-s5-history-volta.md"],
          extras: ["ch01-s2-c-van-de-graaff.md", "ch01-s2-m-vectors.md", "ch01-s4-m-work-integral.md", "ch01-s5-c-alkaline-cell.md", "ch01-s5-c-piezo-igniter.md", "ch01-s5-m-dimensional-analysis.md", "ch01-s5-m-si-prefixes.md", "ch01-s6-m-gradient.md", "ch01-s6-a-relaxation.md", "ch01-s8-c-everyday-shields.md"] },
        { n: 2, status: "done", title: "Напруга, струм і провідність",
          dir: "block-1-circuits-physics/ch02-voltage-current-conduction", main: "ch02-voltage-current-conduction.md",
          histories: ["ch02-history-conduction.md", "ch02-s1-history-ampere.md", "ch02-s4-history-atlantic-cable.md", "ch02-s11-history-arrhenius.md", "ch02-s12-history-war-of-currents.md", "ch02-s13-history-dalziel.md"],
          extras: ["ch02-s1-m-derivative.md", "ch02-s3-m-estimation.md", "ch02-s7-c-switches.md", "ch02-s11-c-galvanic-corrosion.md", "ch02-s13-c-rcd.md"] },
        { n: 3, status: "done", title: "Опір, потужність і тепло",
          dir: "block-1-circuits-physics/ch03-resistance-power-heat", main: "ch03-resistance-power-heat.md",
          histories: ["ch03-history-ohm-joule.md", "ch03-s4-history-filament.md", "ch03-s4-history-superconductivity.md", "ch03-s5-history-watt.md", "ch03-s8-history-fuse.md"],
          extras: ["ch03-s3-c-wires.md", "ch03-s4-c-inrush-ntc.md", "ch03-s5-m-energy-units.md", "ch03-s7-c-resistor-marking.md", "ch03-s7-c-shunt-kelvin.md", "ch03-s7-m-e-series.md", "ch03-s8-c-fuse-types.md", "ch03-s9-c-heatsinks.md", "ch03-s9-m-thermal-rc.md", "ch03-s10-c-peltier.md"] },
        { n: 4, status: "done", title: "Закони Кірхгофа й аналіз кіл",
          dir: "block-1-circuits-physics/ch04-kirchhoff-circuit-analysis", main: "ch04-kirchhoff-circuit-analysis.md",
          histories: ["ch04-history-kirchhoff.md", "ch04-s1-history-euler-graphs.md", "ch04-s8-history-maxwell-mesh.md", "ch04-s9-history-christie-wheatstone.md"],
          extras: ["ch04-s1-c-breadboard.md", "ch04-s1-m-graphs.md", "ch04-s1-a-graph-traversal.md", "ch04-s6-c-potentiometer.md", "ch04-s6-m-tolerance.md", "ch04-s6-a-divider-search.md", "ch04-s8-m-gauss.md", "ch04-s8-m-matrix-machine.md", "ch04-s8-a-circuit-sim.md", "ch04-s8-a-mna-spice.md", "ch04-s9-m-bridge-sensitivity.md"] },
        { n: 5, status: "done", title: "Еквівалентні схеми: Тевенін, Нортон, суперпозиція",
          dir: "block-1-circuits-physics/ch05-equivalent-circuits", main: "ch05-equivalent-circuits.md",
          histories: ["ch05-history-thevenin-norton.md", "ch05-s6-history-50-ohm.md"],
          extras: ["ch05-s1-c-source-impedances.md", "ch05-s1-m-load-line.md", "ch05-s2-m-linearity.md", "ch05-s5-a-two-load-method.md", "ch05-s6-c-terminator.md", "ch05-s6-m-derivative-max.md"] },
        { n: 6, status: "done", title: "Мова схем і вимірювання",
          dir: "block-1-circuits-physics/ch06-schematics-measurement", main: "ch06-schematics-measurement.md",
          histories: ["ch06-history-instruments.md", "ch06-s4-history-earth-return.md", "ch06-s6-history-weston.md", "ch06-s7-history-crt.md", "ch06-s7-history-tektronix.md"],
          extras: ["ch06-s0-c-workbench.md", "ch06-s3-a-netlist-erc.md", "ch06-s6-c-multimeter.md", "ch06-s7-c-oscilloscope.md", "ch06-s7-c-probe.md", "ch06-s7-a-trigger.md", "ch06-s8-c-cat-ratings.md", "ch06-s8-c-probe-ground.md", "ch06-s8-m-accuracy.md"] },
        { n: 7, status: "done", title: "Змінний струм: синусоїда, фаза й RMS",
          dir: "block-1-circuits-physics/r07-ac-signals", main: "r07-ac-signals.md",
          histories: ["r07-history-steinmetz.md", "r07-s2-history-50-60-hz.md"],
          extras: ["r07-s1-m-trigonometry.md", "r07-s1-a-phase-accumulator.md", "r07-s2-c-signal-generator.md", "r07-s3-m-phasor.md", "r07-s4-m-rms-derivation.md", "r07-s4-a-true-rms.md", "r07-s6-c-mains-socket.md"] },
        { n: 8, status: "done", title: "Магнетизм і електромагніти",
          dir: "block-1-circuits-physics/r08-magnetism", main: "r08-magnetism.md",
          histories: ["r08-history-lodestone-oersted.md", "r08-s3-history-neodymium.md", "r08-s8-history-hall.md"],
          extras: ["r08-s3-c-magnet-grades.md", "r08-s4-a-biot-savart.md", "r08-s5-c-solenoid-relay.md", "r08-s5-m-ampere-turns.md", "r08-s6-c-ferrites.md", "r08-s6-m-hysteresis-loop.md", "r08-s7-m-cross-product.md", "r08-s8-c-clamp-meter.md"] },
        { n: 9, status: "done", title: "Шум і завади: фізичні джерела",
          dir: "block-1-circuits-physics/r09-noise-interference", main: "r09-noise-interference.md",
          histories: ["r09-history-johnson-nyquist.md", "r09-s4-history-induction-coordination.md", "r09-s8-history-twisted-pair.md"],
          extras: ["r09-s1-m-clt.md", "r09-s1-m-random-variables.md", "r09-s1-a-noise-generator.md", "r09-s2-m-kt-scale.md", "r09-s2-m-noise-density.md", "r09-s3-c-resistor-noise.md", "r09-s6-c-star-ground.md", "r09-s7-c-shielded-cables.md", "r09-s8-c-utp-cables.md", "r09-s9-m-averaging.md"] },
        { n: 10, status: "done", title: "Електростатика на практиці: іскри, блискавка й ESD",
          dir: "block-1-circuits-physics/r10-esd-static", main: "r10-esd-static.md",
          histories: ["r10-history-franklin-richmann.md", "r10-s5-history-dust-explosions.md"],
          extras: ["r10-s2-m-hbm.md", "r10-s3-c-spark-gap-gdt.md", "r10-s3-m-paschen.md", "r10-s5-c-esd-gun.md", "r10-s5-m-spark-energy.md", "r10-s6-c-wrist-strap.md", "r10-s7-c-ionizer.md"] }
      ]
    },
    {
      n: 2,
      title: "Компоненти й аналогова електроніка",
      slug: "block-2-components-analog",
      chapters: [
        { n: 1, status: "done", title: "Конденсатор",
          dir: "block-2-components-analog/ch07-capacitor", main: "ch07-capacitor.md",
          histories: ["ch07-history-leyden-jar.md", "ch07-s5-history-capacitor-plague.md", "ch07-s8-history-supercap.md"],
          extras: ["ch07-s2-m-derivative-current.md", "ch07-s2-a-touch-sensing.md", "ch07-s4-m-exponential-ode.md", "ch07-s4-a-capacitance-meter.md", "ch07-s5-c-electrolytic-tantalum.md", "ch07-s5-c-marking-sizes.md", "ch07-s5-c-mlcc.md", "ch07-s6-c-bleeder.md", "ch07-s6-c-decoupling.md", "ch07-s8-c-supercap-backup.md"] },
        { n: 2, status: "done", title: "Котушка та індуктивність",
          dir: "block-2-components-analog/ch08-inductor", main: "ch08-inductor.md",
          histories: ["ch08-history-induction.md", "ch08-s1-history-oersted-ampere.md", "ch08-s6-history-transformer.md"],
          extras: ["ch08-s4-m-rl-ode.md", "ch08-s4-a-inductance-meter.md", "ch08-s5-c-rc-snubber.md", "ch08-s6-c-transformers.md", "ch08-s6-m-turns-ratio.md", "ch08-s7-c-power-inductors.md", "ch08-s9-c-ferrite-clamp.md"] },
        { n: 3, status: "done", title: "Реактивність, фази й резонанс",
          dir: "block-2-components-analog/ch09-reactance-resonance", main: "ch09-reactance-resonance.md",
          histories: ["ch09-history-tuned-circuit.md", "ch09-s6-history-tacoma.md"],
          extras: ["ch09-s1-m-complex-phasors.md", "ch09-s2-c-capacitive-dropper.md", "ch09-s3-c-lc-supply-filter.md", "ch09-s4-m-impedance.md", "ch09-s4-m-power-triangle.md", "ch09-s4-m-sine-derivative.md", "ch09-s4-a-lissajous.md", "ch09-s5-c-nfc-rfid.md", "ch09-s5-m-thomson-formula.md", "ch09-s5-a-resonance-sweep.md", "ch09-s6-m-damping.md", "ch09-s6-m-q-factor.md"] },
        { n: 4, status: "done", title: "АЧХ, децибели й фільтри",
          dir: "block-2-components-analog/r04-frequency-response", main: "r04-frequency-response.md",
          histories: ["r04-history-bode.md", "r04-s4-history-decibel.md"],
          extras: ["r04-s1-c-breadboard-parasitics.md", "r04-s1-c-scope-probe.md", "r04-s2-c-input-rc.md", "r04-s2-m-transfer-function.md", "r04-s3-c-coupling-cap.md", "r04-s4-m-logarithms.md", "r04-s5-a-bode-measurement.md", "r04-s6-m-half-power.md", "r04-s6-m-risetime-bandwidth.md", "r04-s7-c-speaker-crossover.md", "r04-s7-m-cascading.md"] },
        { n: 5, status: "done", title: "Діод і PN-перехід",
          dir: "block-2-components-analog/ch10-diode-pn-junction", main: "ch10-diode-pn-junction.md",
          histories: ["ch10-history-diode.md", "ch10-s1-history-silicon-germanium.md", "ch10-s7-history-blue-led.md", "ch10-s7-history-led.md", "ch10-s8-history-zener.md"],
          extras: ["ch10-s5-m-shockley-equation.md", "ch10-s5-a-diode-thermometer.md", "ch10-s6-c-bridge-rectifier.md", "ch10-s6-m-ripple-calc.md", "ch10-s7-c-leds-practice.md", "ch10-s7-m-photon-energy.md", "ch10-s7-a-charlieplexing.md", "ch10-s8-c-diode-families.md", "ch10-s8-c-tvs-esd.md", "ch10-s8-m-reverse-recovery.md", "ch10-s10-c-optocoupler.md"] },
        { n: 6, status: "done", title: "Біполярний транзистор (BJT)",
          dir: "block-2-components-analog/ch11-bjt", main: "ch11-bjt.md",
          histories: ["ch11-history-transistor.md", "ch11-s1-history-traitorous-eight.md", "ch11-s8-history-tr1-sony.md"],
          extras: ["ch11-s4-a-measure-hfe.md", "ch11-s6-c-darlington-uln.md", "ch11-s6-c-high-side-pnp.md", "ch11-s6-m-base-resistor.md", "ch11-s7-c-common-emitter.md", "ch11-s7-m-load-line.md", "ch11-s8-c-bjt-families.md", "ch11-s9-c-relay-inside.md", "ch11-s9-c-relay-module.md"] },
        { n: 7, status: "done", title: "Польовий транзистор (MOSFET)",
          dir: "block-2-components-analog/ch12-mosfet", main: "ch12-mosfet.md",
          histories: ["ch12-history-mosfet.md", "ch12-s5-history-hexfet.md", "ch12-s9-history-cmos.md"],
          extras: ["ch12-s2-c-body-diode.md", "ch12-s3-m-square-law.md", "ch12-s4-c-pmos-load-switch.md", "ch12-s6-c-ideal-diode.md", "ch12-s6-c-logic-level.md", "ch12-s6-a-thermal-calc.md", "ch12-s7-c-gate-driver.md", "ch12-s7-m-gate-charge.md", "ch12-s10-c-h-bridge-board.md", "ch12-s10-a-shoot-through.md"] },
        { n: 8, status: "done", title: "Операційний підсилювач і компаратор",
          dir: "block-2-components-analog/ch13-opamp-comparator", main: "ch13-opamp-comparator.md",
          histories: ["ch13-history-opamp.md", "ch13-s2-history-harold-black.md"],
          extras: ["ch13-s2-m-feedback-formula.md", "ch13-s5-c-buffer-divider.md", "ch13-s5-m-cap-load.md", "ch13-s6-a-signal-scaling.md", "ch13-s7-c-comparator-ics.md", "ch13-s8-m-hysteresis-calc.md", "ch13-s8-a-light-threshold.md", "ch13-s9-c-rail-to-rail.md", "ch13-s9-m-gbw-slew.md", "ch13-s9-m-noise-budget.md", "ch13-s10-m-current-mirror.md", "ch13-s11-c-regulator-module.md", "ch13-s11-m-ldo-dissipation.md"] },
        { n: 9, status: "done", title: "Як читати даташит",
          dir: "block-2-components-analog/r09-reading-datasheets", main: "r09-reading-datasheets.md",
          histories: ["r09-s1-history-databooks.md", "r09-s6-history-pentium-fdiv.md"],
          extras: ["r09-s2-c-abs-max-failures.md", "r09-s3-m-tolerance-statistics.md", "r09-s4-m-derating.md", "r09-s4-m-thermal-resistance.md", "r09-s4-a-log-graph-reading.md", "r09-s5-c-packages.md", "r09-s5-c-smd-marking.md", "r09-s7-c-component-tester.md", "r09-s7-a-selection-checklist.md"] },
        { n: 10, status: "done", title: "Резонатори й опорні частоти",
          dir: "block-2-components-analog/r10-resonators-references", main: "r10-resonators-references.md",
          histories: ["r10-history-pierce-ft243.md", "r10-s7-history-quartz-crisis.md"],
          extras: ["r10-s1-c-internal-rc.md", "r10-s3-m-q-stability.md", "r10-s5-c-crystal-layout.md", "r10-s5-a-oscillator-debug.md", "r10-s6-m-ppm-math.md", "r10-s6-a-measure-drift.md", "r10-s7-c-watch-crystal.md", "r10-s8-c-mems-vs-quartz.md", "r10-s9-c-tcxo.md"] },
        { n: 11, status: "done", title: "Силова комутація змінного струму",
          dir: "block-2-components-analog/r11-ac-power-switching", main: "r11-ac-power-switching.md",
          histories: ["r11-history-thyristor.md", "r11-s6-history-ssr.md", "r11-s7-history-igbt-baliga.md"],
          extras: ["r11-s2-c-crowbar.md", "r11-s3-c-triac-driver.md", "r11-s4-m-phase-power.md", "r11-s4-a-dimmer-algorithm.md", "r11-s5-c-zero-cross-module.md", "r11-s5-a-burst-control.md", "r11-s6-c-ssr.md", "r11-s8-m-snubber-calc.md", "r11-s9-c-mov-fuse.md"] },
        { n: 12, status: "done", title: "Легендарні аналогові ІМС",
          dir: "block-2-components-analog/r12-legendary-analog-ics", main: "r12-legendary-analog-ics.md",
          histories: ["r12-history-camenzind-555.md", "r12-s5-history-bandgap.md"],
          extras: ["r12-s1-c-ic-naming.md", "r12-s2-c-555-versions.md", "r12-s3-m-astable-formulas.md", "r12-s4-a-monostable.md", "r12-s5-c-tl431.md", "r12-s5-m-bandgap-math.md", "r12-s6-c-analog-mux.md", "r12-s6-a-mux-scanning.md", "r12-s7-c-inamp-bridge.md", "r12-s7-m-inamp-cmrr.md"] }
      ]
    },
    {
      n: 3,
      title: "Цифрова електроніка й процесор",
      slug: "block-3-digital-processor",
      chapters: [
        { n: 1, status: "done", title: "Логічні рівні: від аналога до цифри",
          dir: "block-3-digital-processor/ch14-logic-levels", main: "ch14-logic-levels.md",
          histories: ["ch14-history-shannon.md", "ch14-s4-history-5-volts.md"],
          extras: ["ch14-s3-m-noise-margin.md", "ch14-s4-c-74-families.md", "ch14-s5-c-series-termination.md", "ch14-s5-m-rise-time.md", "ch14-s6-c-74hc14.md", "ch14-s6-a-software-hysteresis.md"] },
        { n: 2, status: "done", title: "Логічні вентилі й комбінаційні схеми",
          dir: "block-3-digital-processor/ch15-logic-gates", main: "ch15-logic-gates.md",
          histories: ["ch15-history-boole.md", "ch15-s3-history-apollo-nor.md"],
          extras: ["ch15-s1-m-boolean-algebra.md", "ch15-s2-c-74hc-breadboard.md", "ch15-s2-a-bitwise-c.md", "ch15-s4-a-xor-tricks.md", "ch15-s6-c-74hc138-chip-select.md", "ch15-s6-m-karnaugh-maps.md", "ch15-s6-a-gate-simulator.md"] },
        { n: 3, status: "done", title: "Тригери, регістри й тактування",
          dir: "block-3-digital-processor/ch16-flip-flops-registers", main: "ch16-flip-flops-registers.md",
          histories: ["ch16-history-flip-flop.md", "ch16-s5-history-shift-register-ics.md", "ch16-s7-history-cmos-counters.md", "ch16-s8-history-metastability.md"],
          extras: ["ch16-s5-c-74hc165.md", "ch16-s5-c-74hc595.md", "ch16-s6-c-clock-sources.md", "ch16-s7-c-counter-ics.md", "ch16-s8-m-timing-budget.md", "ch16-s8-a-two-ff-synchronizer.md", "ch16-s9-m-fsm-formal.md", "ch16-s9-a-fsm-in-code.md"] },
        { n: 4, status: "done", title: "Представлення чисел",
          dir: "block-3-digital-processor/ch17-number-representation", main: "ch17-number-representation.md",
          histories: ["ch17-history-leibniz.md", "ch17-s3-history-modular-arithmetic.md", "ch17-s4-history-ariane5.md", "ch17-s5-history-patriot.md", "ch17-s6-history-ieee754.md", "ch17-s8-history-utf8-diner.md"],
          extras: ["ch17-s3-m-modular-arithmetic.md", "ch17-s4-a-overflow-checks.md", "ch17-s5-a-cordic.md", "ch17-s5-a-fixed-point.md", "ch17-s6-m-ieee754-details.md", "ch17-s6-a-float-compare.md", "ch17-s7-c-sensor-byte-order.md", "ch17-s7-a-serialization.md", "ch17-s8-a-utf8-decoder.md"] },
        { n: 5, status: "done", title: "Архітектура процесора",
          dir: "block-3-digital-processor/ch18-processor-architecture", main: "ch18-processor-architecture.md",
          histories: ["ch18-history-von-neumann.md", "ch18-s1-history-babbage-lovelace.md", "ch18-s4-history-riscv.md", "ch18-s5-history-megahertz-myth.md", "ch18-s7-history-harvard-architecture.md"],
          extras: ["ch18-s3-a-toy-cpu-emulator.md", "ch18-s4-c-isa-in-boards.md", "ch18-s4-a-reading-disassembly.md", "ch18-s5-m-performance-math.md", "ch18-s6-m-pipeline-hazards.md", "ch18-s7-c-esp32-buses.md", "ch18-s9-a-cache-friendly-code.md"] },
        { n: 6, status: "done", title: "Пам'ять, адресація, стек і купа",
          dir: "block-3-digital-processor/ch19-memory-stack-heap", main: "ch19-memory-stack-heap.md",
          histories: ["ch19-history-core-memory.md", "ch19-s4-history-heartbleed.md", "ch19-s5-history-stack-painting.md", "ch19-s7-c-history-mpu.md", "ch19-s7-history-morris-worm.md", "ch19-s8-history-frohman-eprom.md"],
          extras: ["ch19-s1-m-address-space.md", "ch19-s2-c-real-memory-map.md", "ch19-s3-c-spi-flash-xip.md", "ch19-s4-a-pointer-arithmetic.md", "ch19-s5-a-stack-watermark.md", "ch19-s6-m-fragmentation.md", "ch19-s6-a-block-pools.md", "ch19-s6-a-toy-allocator.md", "ch19-s7-c-mpu.md", "ch19-s8-c-psram.md", "ch19-s8-m-tunneling.md"] },
        { n: 7, status: "done", title: "Програмована логіка: ПЛІС/FPGA",
          dir: "block-3-digital-processor/r07-fpga", main: "r07-fpga.md",
          histories: ["r07-history-xilinx.md", "r07-s5-history-hdl.md"],
          extras: ["r07-s1-c-fpga-in-the-wild.md", "r07-s2-c-greenpak.md", "r07-s3-m-lut-math.md", "r07-s4-c-hobby-fpga-boards.md", "r07-s5-a-verilog-first-projects.md", "r07-s6-a-open-toolchain.md", "r07-s7-m-critical-path.md"] },
        { n: 8, status: "done", title: "Зовнішня пам'ять",
          dir: "block-3-digital-processor/r08-external-memory", main: "r08-external-memory.md",
          histories: ["r08-history-dennard-dram.md", "r08-s6-history-sd-card-wars.md"],
          extras: ["r08-s2-m-dram-refresh.md", "r08-s3-c-ddr-labels.md", "r08-s3-m-bandwidth.md", "r08-s5-c-w25q-raw-commands.md", "r08-s7-a-toy-ftl.md"] },
        { n: 9, status: "done", title: "Коди виявлення й корекції помилок",
          dir: "block-3-digital-processor/r09-error-correction", main: "r09-error-correction.md",
          histories: ["r09-history-hamming.md", "r09-s1-history-bit-flip-election.md", "r09-s8-history-voyager-codes.md"],
          extras: ["r09-s1-m-seu-sel.md", "r09-s3-a-checksums-in-code.md", "r09-s4-c-hardware-crc.md", "r09-s4-m-gf2-polynomials.md", "r09-s4-a-crc-implementation.md", "r09-s5-m-hamming-distance.md", "r09-s6-a-hamming-codec.md", "r09-s7-c-ecc-hardware.md"] },
        { n: 10, status: "done", title: "Як народжується чіп: від піску до корпуса",
          dir: "block-3-digital-processor/r10-chip-fabrication", main: "r10-chip-fabrication.md",
          histories: ["r10-history-kilby-noyce.md", "r10-s2-history-asml-euv.md", "r10-s8-history-tsmc.md"],
          extras: ["r10-s2-a-place-and-route.md", "r10-s5-m-yield-math.md", "r10-s6-c-chip-markings.md", "r10-s6-a-scan-chain.md", "r10-s7-c-package-guide.md", "r10-s8-m-moore-dennard.md"] }
      ]
    },
    {
      n: 4,
      title: "Мікроконтролер і прошивка: ESP32",
      slug: "block-4-mcu-esp32",
      chapters: [
        { n: 1, status: "done", title: "Анатомія мікроконтролера й архітектура ESP32",
          dir: "block-4-mcu-esp32/ch20-mcu-esp32", main: "ch20-mcu-esp32.md",
          histories: ["ch20-history-first-mcu.md", "ch20-s5-history-esp.md", "ch20-s6-history-8051.md", "ch20-s7-history-riscv.md"],
          extras: ["ch20-s2-c-antenna.md", "ch20-s2-c-wroom-module.md", "ch20-s3-a-reg-access.md", "ch20-s4-c-crystal.md", "ch20-s4-m-clock-tree.md", "ch20-s5-c-devkit.md", "ch20-s6-m-benchmarks.md", "ch20-s8-c-brownout.md"] },
        { n: 2, status: "done", title: "Тулчейн: як код стає прошивкою",
          dir: "block-4-mcu-esp32/ch21-toolchain", main: "ch21-toolchain.md",
          histories: ["ch21-history-grace-hopper.md", "ch21-s2-history-gcc.md", "ch21-s7-history-arduino.md"],
          extras: ["ch21-s2-a-optimizer.md", "ch21-s4-m-image-checksums.md", "ch21-s4-a-firmware-version.md", "ch21-s4-a-map-file.md", "ch21-s4-a-size-opt.md", "ch21-s5-c-usb-uart.md", "ch21-s5-a-flash-protocol.md", "ch21-s6-c-strapping.md", "ch21-s8-c-debug-probes.md", "ch21-s8-a-binary-logging.md", "ch21-s8-a-logging.md", "ch21-s9-a-emulators.md"] },
        { n: 3, status: "done", title: "Постійні дані: Flash-розділи, NVS і файлові системи",
          dir: "block-4-mcu-esp32/r03-persistent-storage", main: "r03-persistent-storage.md",
          histories: ["r03-history-flash.md", "r03-s6-history-fat.md"],
          extras: ["r03-s1-a-flash-ring-log.md", "r03-s3-c-fram.md", "r03-s3-m-endurance.md", "r03-s4-a-partition-table.md", "r03-s5-a-nvs-internals.md", "r03-s6-c-sd-module.md", "r03-s7-a-atomic-config.md", "r03-s9-m-hash-signature.md"] },
        { n: 4, status: "done", title: "GPIO глибоко",
          dir: "block-4-mcu-esp32/ch22-gpio", main: "ch22-gpio.md",
          histories: ["ch22-s5-history-relay-bounce.md"],
          extras: ["ch22-s4-m-pullup-value.md", "ch22-s5-c-tact-button.md", "ch22-s5-a-debounce.md", "ch22-s6-m-pin-budget.md", "ch22-s7-a-bitbang.md", "ch22-s8-c-gpio-expander.md", "ch22-s8-a-key-matrix.md"] },
        { n: 5, status: "done", title: "Переривання",
          dir: "block-4-mcu-esp32/ch23-interrupts", main: "ch23-interrupts.md",
          histories: ["ch23-history-interrupt.md", "ch23-s4-history-apollo.md", "ch23-s6-history-therac25.md"],
          extras: ["ch23-s1-c-int-pin.md", "ch23-s1-a-spsc-ring.md", "ch23-s2-c-int-controllers.md", "ch23-s3-a-deferred-work.md", "ch23-s3-a-reentrancy.md", "ch23-s4-m-latency.md", "ch23-s5-a-volatile-asm.md", "ch23-s6-a-atomics-barriers.md", "ch23-s6-a-critical-sections.md", "ch23-s7-m-isr-budget.md"] },
        { n: 6, status: "done", title: "Таймери й керування часом",
          dir: "block-4-mcu-esp32/ch24-timers", main: "ch24-timers.md",
          histories: ["ch24-history-quartz.md", "ch24-s8-history-y2k-2038.md"],
          extras: ["ch24-s1-m-prescaler.md", "ch24-s2-m-unsigned-wrap.md", "ch24-s3-a-input-capture.md", "ch24-s5-a-coop-scheduler.md", "ch24-s6-a-timer-wheel.md", "ch24-s7-c-esp32-watchdogs.md", "ch24-s7-a-watchdog-feed.md", "ch24-s8-c-rtc-module.md", "ch24-s8-m-calendar-math.md"] },
        { n: 7, status: "done", title: "PWM і ЦАП",
          dir: "block-4-mcu-esp32/ch25-pwm-dac", main: "ch25-pwm-dac.md",
          histories: ["ch25-history-dimmer.md"],
          extras: ["ch25-s1-c-buzzer.md", "ch25-s1-m-pwm-spectrum.md", "ch25-s2-a-pwm-alignment.md", "ch25-s3-m-freq-resolution.md", "ch25-s4-m-rc-design.md", "ch25-s5-c-mosfet-module.md", "ch25-s5-a-gamma.md", "ch25-s6-c-external-dac.md", "ch25-s7-c-ws2812-strip.md", "ch25-s7-a-ws2812-timing.md"] },
        { n: 8, status: "done", title: "Аналого-цифрове перетворення (АЦП)",
          dir: "block-4-mcu-esp32/ch26-adc", main: "ch26-adc.md",
          histories: ["ch26-history-sampling.md", "ch26-s8-history-delta-sigma.md"],
          extras: ["ch26-s1-c-potentiometer.md", "ch26-s2-m-quantization-noise.md", "ch26-s3-m-dithering.md", "ch26-s3-m-enob.md", "ch26-s4-c-voltage-reference.md", "ch26-s5-m-alias-folding.md", "ch26-s6-c-ads1115.md", "ch26-s6-a-two-point-cal.md", "ch26-s7-c-opamp-buffer.md", "ch26-s7-m-sample-hold.md", "ch26-s8-a-sar-search.md"] },
        { n: 9, status: "done", title: "DMA: дані без участі ядра",
          dir: "block-4-mcu-esp32/r09-dma", main: "r09-dma.md",
          histories: ["r09-history-dma-channels.md", "r09-s6-history-soundblaster.md"],
          extras: ["r09-s1-m-throughput.md", "r09-s2-a-memcpy-vs-dma.md", "r09-s3-a-descriptors.md", "r09-s4-m-buffer-sizing.md", "r09-s4-a-ring-buffer.md", "r09-s6-c-i2s-mic.md", "r09-s6-c-spi-display.md", "r09-s7-a-cache-dma.md"] },
        { n: 10, status: "done", title: "Модель виконання й RTOS",
          dir: "block-4-mcu-esp32/ch27-execution-rtos", main: "ch27-execution-rtos.md",
          histories: ["ch27-history-time-sharing.md", "ch27-s5-history-freertos.md", "ch27-s6-history-pathfinder.md"],
          extras: ["ch27-s3-a-fsm-instead.md", "ch27-s4-m-tick-latency.md", "ch27-s4-a-clz-bitmap.md", "ch27-s4-a-context-switch.md", "ch27-s5-c-dual-core.md", "ch27-s6-a-deadlock.md", "ch27-s6-a-priority-inheritance.md", "ch27-s6-a-queue-pattern.md", "ch27-s7-a-no-free.md", "ch27-s7-a-stack-overflow.md", "ch27-s8-m-rate-monotonic.md"] },
        { n: 11, status: "done", title: "Пейзаж мікроконтролерів",
          dir: "block-4-mcu-esp32/r11-mcu-landscape", main: "r11-mcu-landscape.md",
          histories: ["r11-history-arm.md", "r11-s2-history-avr.md", "r11-s5-history-rp2040.md"],
          extras: ["r11-s2-c-uno-nano.md", "r11-s4-c-stm32-boards.md", "r11-s5-c-pico-board.md", "r11-s5-a-pio.md", "r11-s6-c-nrf-modules.md", "r11-s7-a-portability.md", "r11-s8-c-packages.md", "r11-s8-m-decision-matrix.md"] },
        { n: 12, status: "done", title: "USB на мікроконтролері",
          dir: "block-4-mcu-esp32/r12-usb-mcu", main: "r12-usb-mcu.md",
          histories: ["r12-history-usb-birth.md", "r12-s5-history-badusb.md"],
          extras: ["r12-s2-c-usb-c.md", "r12-s2-m-nrzi.md", "r12-s3-a-descriptors.md", "r12-s4-a-frames.md", "r12-s5-a-hid-reports.md", "r12-s8-c-otg.md"] },
        { n: 13, status: "done", title: "Енергоощадність глибоко",
          dir: "block-4-mcu-esp32/r13-low-power", main: "r13-low-power.md",
          histories: ["r13-history-pacemaker.md", "r13-s2-history-voyager.md"],
          extras: ["r13-s1-m-battery-math.md", "r13-s2-c-sensor-standby.md", "r13-s4-c-wake-hw.md", "r13-s5-a-ulp-program.md", "r13-s7-c-current-profiler.md", "r13-s7-m-dynamic-range.md", "r13-s8-c-ldo-vs-buck.md"] },
        { n: 14, status: "done", title: "Налагодження глибоко: JTAG/SWD, GDB і посмертний аналіз",
          dir: "block-4-mcu-esp32/r14-debug-deep", main: "r14-debug-deep.md",
          histories: ["r14-history-jtag.md"] },
        { n: 15, status: "done", title: "Відмовостійка прошивка: помилки, паніка, відновлення",
          dir: "block-4-mcu-esp32/r15-fault-tolerant", main: "r15-fault-tolerant.md",
          histories: ["r15-history-ariane5.md"] }
      ]
    },
    {
      n: 5,
      title: "Давачі, сигнали й керування",
      slug: "block-5-sensors-control",
      chapters: [
        { n: 1, status: "done", title: "Фізика давачів",
          dir: "block-5-sensors-control/ch28-sensor-physics", main: "ch28-sensor-physics.md",
          histories: ["ch28-history-seebeck.md"],
          extras: ["ch28-s9-history-strain-gauge.md"] },
        { n: 2, status: "done", title: "Вимірювання відстані й оточення",
          dir: "block-5-sensors-control/ch29-distance-environment", main: "ch29-distance-environment.md",
          histories: ["ch29-history-sonar.md"] },
        { n: 3, status: "pending", title: "Давачі обертання й положення: енкодери" },
        { n: 4, status: "done", title: "Цифрова фільтрація сигналів",
          dir: "block-5-sensors-control/ch30-digital-filtering", main: "ch30-digital-filtering.md",
          histories: [] },
        { n: 5, status: "done", title: "Спектр і перетворення Фур'є",
          dir: "block-5-sensors-control/ch31-spectrum-fourier", main: "ch31-spectrum-fourier.md",
          histories: ["ch31-history-fourier.md", "ch31-s5-history-fft.md"] },
        { n: 6, status: "done", title: "Цифрові фільтри в мікроконтролері",
          dir: "block-5-sensors-control/ch32-digital-filters-mcu", main: "ch32-digital-filters-mcu.md",
          histories: [] },
        { n: 7, status: "done", title: "Інерціальні давачі: MEMS",
          dir: "block-5-sensors-control/ch33-imu-mems", main: "ch33-imu-mems.md",
          histories: ["ch33-history-mems-airbag.md"] },
        { n: 8, status: "done", title: "Орієнтація й керування зі зворотним зв'язком (ПІД)",
          dir: "block-5-sensors-control/ch34-orientation-pid", main: "ch34-orientation-pid.md",
          histories: ["ch34-history-governor-pid.md", "ch34-s4-history-kalman.md"] },
        { n: 9, status: "pending", title: "Виконавчі механізми: мотори й рух" },
        { n: 10, status: "pending", title: "Давачі середовища глибше" },
        { n: 11, status: "pending", title: "Час і синхронізація вимірювань" }
      ]
    },
    {
      n: 6,
      title: "Зв'язок: дротовий і радіо",
      slug: "block-6-comms-radio",
      chapters: [
        { n: 1, status: "done", title: "UART і протоколи поверх нього",
          dir: "block-6-comms-radio/ch35-uart", main: "ch35-uart.md",
          histories: ["ch35-history-baudot.md"] },
        { n: 2, status: "done", title: "Шина I2C",
          dir: "block-6-comms-radio/ch36-i2c", main: "ch36-i2c.md",
          histories: ["ch36-history-i2c.md"] },
        { n: 3, status: "done", title: "Шина SPI",
          dir: "block-6-comms-radio/ch37-spi", main: "ch37-spi.md",
          histories: [] },
        { n: 4, status: "pending", title: "Диференційні шини: RS-485 і CAN" },
        { n: 5, status: "done", title: "Бездротовий зв'язок на чіпі: Wi-Fi і Bluetooth",
          dir: "block-6-comms-radio/ch38-wifi-bluetooth", main: "ch38-wifi-bluetooth.md",
          histories: ["ch38-history-bluetooth-name.md"] },
        { n: 6, status: "done", title: "Радіо: фізика електромагнітних хвиль",
          dir: "block-6-comms-radio/ch39-radio-em-waves", main: "ch39-radio-em-waves.md",
          histories: ["ch39-history-hertz.md"] },
        { n: 7, status: "done", title: "Радіо: модуляція й бюджет лінії",
          dir: "block-6-comms-radio/ch40-modulation-link-budget", main: "ch40-modulation-link-budget.md",
          histories: ["ch40-history-armstrong.md", "ch40-s5-history-hedy-lamarr.md"] },
        { n: 8, status: "done", title: "Антени й лінії передачі",
          dir: "block-6-comms-radio/ch41-antennas", main: "ch41-antennas.md",
          histories: ["ch41-history-marconi.md"] },
        { n: 9, status: "done", title: "Радіозв'язок системи: керування, телеметрія, MAVLink",
          dir: "block-6-comms-radio/ch42-telemetry-mavlink", main: "ch42-telemetry-mavlink.md",
          histories: ["ch42-history-mavlink.md"] },
        { n: 10, status: "pending", title: "Мережі: Ethernet, IP і як пакет знаходить дорогу" },
        { n: 11, status: "pending", title: "MAVLink у роботі: словник даних і керування" },
        { n: 12, status: "pending", title: "Приєднання модулів: розпіновки, рівні, конектори, надійність" }
      ]
    },
    {
      n: 7,
      title: "Системи: ArduPilot, відео, машинне бачення",
      slug: "block-7-systems",
      chapters: [
        { n: 1, status: "done", title: "Архітектура автономної системи й політний контролер",
          dir: "block-7-systems/ch43-architecture-flight-controller", main: "ch43-architecture-flight-controller.md",
          histories: ["ch43-history-ardupilot.md"] },
        { n: 2, status: "pending", title: "Як літає мультиротор" },
        { n: 3, status: "done", title: "Компоненти польотної системи",
          dir: "block-7-systems/ch44-flight-components", main: "ch44-flight-components.md",
          histories: ["ch44-history-gps.md"] },
        { n: 4, status: "done", title: "Живлення складних систем",
          dir: "block-7-systems/ch45-power-systems", main: "ch45-power-systems.md",
          histories: ["ch45-history-lithium.md"] },
        { n: 5, status: "done", title: "Оцінювання стану й сенсорний фьюжн",
          dir: "block-7-systems/ch46-state-estimation-fusion", main: "ch46-state-estimation-fusion.md",
          histories: ["ch46-history-draper.md"] },
        { n: 6, status: "pending", title: "Польотні режими, місії та failsafe" },
        { n: 7, status: "done", title: "Відеосигнали I: від світла до кадру",
          dir: "block-7-systems/ch47-video-signals-1", main: "ch47-video-signals-1.md",
          histories: ["ch47-history-farnsworth.md", "ch47-s2-history-ccd.md"] },
        { n: 8, status: "done", title: "Відеосигнали II: стиснення й передача",
          dir: "block-7-systems/ch48-video-signals-2", main: "ch48-video-signals-2.md",
          histories: ["ch48-history-dct.md"] },
        { n: 9, status: "done", title: "Машинне бачення: основи",
          dir: "block-7-systems/ch49-computer-vision", main: "ch49-computer-vision.md",
          histories: ["ch49-history-summer-vision.md", "ch49-s7-history-neural-nets.md"] },
        { n: 10, status: "done", title: "Машинне навчання й нейромережі на пристрої",
          dir: "block-7-systems/ch50-machine-learning", main: "ch50-machine-learning.md",
          histories: ["ch50-history-ai-winters.md", "ch50-s5-history-lecun-cnn.md"] },
        { n: 11, status: "pending", title: "Бортовий комп'ютер: «політ» + «розум» разом" },
        { n: 12, status: "pending", title: "Інші автономні платформи: ровер, човен, літак" },
        { n: 13, status: "pending", title: "Наземна станція й оператор" },
        { n: 14, status: "pending", title: "Зібрати систему від батареї до місії" }
      ]
    },
    {
      n: 8,
      title: "Схемотехніка власних плат",
      slug: "block-8-circuit-design",
      chapters: [
        { n: 1, status: "pending", title: "Від ідеї до структурної схеми" },
        { n: 2, status: "pending", title: "Вибір компонентів і розрахунок обв'язки" },
        { n: 3, status: "pending", title: "Вузол живлення на схемі" },
        { n: 4, status: "pending", title: "Скидання, тактування, прошивання: обв'язка мікроконтролера" },
        { n: 5, status: "pending", title: "Інтерфейси назовні й захист виводів" },
        { n: 6, status: "pending", title: "SPICE: схема в симуляторі" },
        { n: 7, status: "pending", title: "САПР: бібліотеки, символи, нетліст" },
        { n: 8, status: "pending", title: "Рев'ю схеми і підготовка до розведення" }
      ]
    },
    {
      n: 9,
      title: "Плати фізично: розведення, виготовлення, монтаж",
      slug: "block-9-pcb-layout-assembly",
      chapters: [
        { n: 1, status: "pending", title: "Плата зсередини: шари, стек, матеріали" },
        { n: 2, status: "pending", title: "Трасування сигналів" },
        { n: 3, status: "pending", title: "Земля, полігони і EMI плати" },
        { n: 4, status: "pending", title: "DFM і DFT: спроєктовано для фабрики" },
        { n: 5, status: "pending", title: "Замовлення: файли, фабрика, компоненти" },
        { n: 6, status: "pending", title: "Паяння і монтаж" },
        { n: 7, status: "pending", title: "Бріг-ап нової плати" },
        { n: 8, status: "pending", title: "Ревізії і життя плати" },
        { n: 9, status: "pending", title: "Пристрій у корпусі: механіка саморобки" }
      ]
    },
    {
      n: 10,
      title: "Живлення і енергія",
      slug: "block-10-power-energy",
      chapters: [
        { n: 1, status: "pending", title: "Топології перетворювачів" },
        { n: 2, status: "pending", title: "Спроєктувати і виміряти перетворювач" },
        { n: 3, status: "pending", title: "USB-живлення і розумна зарядка" },
        { n: 4, status: "pending", title: "Батареї і заряд" },
        { n: 5, status: "pending", title: "Сонячна енергія і MPPT" },
        { n: 6, status: "pending", title: "Енергоощадна архітектура" },
        { n: 7, status: "pending", title: "Захисти живлення" }
      ]
    },
    {
      n: 11,
      title: "Автономія і робототехніка",
      slug: "block-11-autonomy-robotics",
      chapters: [
        { n: 1, status: "pending", title: "Бортовий Linux і одноплатники" },
        { n: 2, status: "pending", title: "ROS2: нервова система робота" },
        { n: 3, status: "pending", title: "Сприйняття: лідар, камера, карта" },
        { n: 4, status: "pending", title: "Локалізація і ймовірність" },
        { n: 5, status: "pending", title: "Планування шляху" },
        { n: 6, status: "pending", title: "Локальне керування і обхід перешкод" },
        { n: 7, status: "pending", title: "Платформи: ровер, маніпулятор, коптер" },
        { n: 8, status: "pending", title: "Симуляція робота" }
      ]
    },
    {
      n: 12,
      title: "Глибокий ШІ на краю",
      slug: "block-12-edge-ai",
      chapters: [
        { n: 1, status: "pending", title: "Навчання по-справжньому: бекпроп і оптимізатори" },
        { n: 2, status: "pending", title: "Від CNN до трансформерів" },
        { n: 3, status: "pending", title: "Дані і розмітка" },
        { n: 4, status: "pending", title: "Стиснення моделей: квантування, прунінг, дистиляція" },
        { n: 5, status: "pending", title: "NPU і акселератори" },
        { n: 6, status: "pending", title: "MLOps парку пристроїв" },
        { n: 7, status: "pending", title: "Надійність ML на краю" }
      ]
    },
    {
      n: 13,
      title: "UI та HMI на залізі",
      slug: "block-13-ui-hmi",
      chapters: [
        { n: 1, status: "done", title: "Дисплеї і дотик як компоненти",
          dir: "block-13-ui-hmi/r01-displays-touch", main: "r01-displays-touch.md",
          histories: ["r01-history-lcd.md", "r01-s7-history-eink.md"],
          extras: ["r01-s1-c-ssd1306.md", "r01-s3-m-bandwidth-budget.md", "r01-s4-c-spi-tft.md", "r01-s5-c-backlight-drivers.md", "r01-s6-c-touch-controllers.md", "r01-s7-c-eink-modules.md"] },
        { n: 2, status: "done", title: "Графічний конвеєр",
          dir: "block-13-ui-hmi/r02-graphics-pipeline", main: "r02-graphics-pipeline.md",
          histories: ["r02-s1-history-alto.md"] },
        { n: 3, status: "pending", title: "Архітектура UI-застосунку" },
        { n: 4, status: "pending", title: "Qt: від десктопа до MCU" },
        { n: 5, status: "pending", title: "LVGL і TouchGFX" },
        { n: 6, status: "pending", title: "Slint, Embedded Wizard і вибір фреймворку" },
        { n: 7, status: "pending", title: "Практичні патерни UI на залізі" }
      ]
    },
    {
      n: 14,
      title: "Продукт: від прототипа до серії",
      slug: "block-14-product",
      chapters: [
        { n: 1, status: "pending", title: "Вимоги і архітектура виробу" },
        { n: 2, status: "pending", title: "DFM і вартість BOM" },
        { n: 3, status: "pending", title: "EMC і сертифікація" },
        { n: 4, status: "pending", title: "Тестування: від юнітів до HIL і фабрики" },
        { n: 5, status: "pending", title: "Надійність і аналіз відмов" },
        { n: 6, status: "pending", title: "OTA-флот і версіонування" },
        { n: 7, status: "pending", title: "Безпека продукту" },
        { n: 8, status: "pending", title: "Документація, постачання, підтримка" },
        { n: 9, status: "pending", title: "Пристрій в екосистемі: стільниковий IoT, Matter і хмара" }
      ]
    }
  ]
};
