/* embedded/block-2-components-analog/manifest.js — per-module маніфест Модуля 2. Складає scripts/bookbuild.js
   (histories[]/extras[] ВИВОДЯТЬСЯ з topics[]). Нумерація — М.Р.Т. */
(window.__MODREG__ = window.__MODREG__ || []).push({
  n: 2, slug: "block-2-components-analog", title: "Компоненти й аналогова електроніка",
  chapters: [
    { n: 1, title: "Конденсатор", dir: "block-2-components-analog/capacitor", main: "capacitor.md", status: "done",
      scope: "Накопичення заряду, ємність, енергія поля; заряд/розряд і постійна часу RC; типи й паразити (ESR/ESL); навіщо для фільтрації й розв'язки.",
      topics: [
        { mrt: "2.1.1", title: "Що таке конденсатор: два провідники, що тримають розділений заряд", status: "done" },
        { mrt: "2.1.2", title: "Ємність: Q = C·V (фарад; від чого залежить)", status: "done" },
        { mrt: "2.1.3", title: "Енергія в конденсаторі й полі (½·C·V²)", status: "done" },
        { mrt: "2.1.4", title: "Зарядка й розрядка: стала часу RC (експонента)", status: "done" },
        { mrt: "2.1.5", title: "Типи й паразити; гранична напруга (ESR/ESL; полярність; пробій)", status: "done" },
        { mrt: "2.1.6", title: "Навіщо конденсатори: розв'язка, згладжування, накопичувач", status: "done" },
        { mrt: "2.1.7", title: "Послідовно й паралельно (на відміну від резисторів)", status: "done" },
        { mrt: "2.1.8", title: "Суперконденсатор: між конденсатором і акумулятором", status: "done" },
        { kind: "hist", file: "hist-leyden-jar.md", at: "chapter", status: "done", title: "Лейденська банка" },
        { kind: "hist", file: "hist-capacitor-plague.md", at: "2.1.5", status: "done", title: "«Конденсаторна чума» 2000-х" },
        { kind: "hist", file: "hist-supercap.md", at: "2.1.8", status: "done", title: "Іоністор: від GE до NEC" },
        { kind: "math", file: "math-derivative-current.md", at: "2.1.2", status: "done", title: "I = C·dV/dt: струм як швидкість зміни напруги" },
        { kind: "proj", file: "proj-touch-sensing.md", at: "2.1.2", status: "done", title: "Ємнісна сенсорна кнопка" },
        { kind: "math", file: "math-exponential-ode.md", at: "2.1.4", status: "done", title: "Експонента й диференціальне рівняння RC-кола" },
        { kind: "proj", file: "proj-capacitance-meter.md", at: "2.1.4", status: "done", title: "RC-метр: ємність часом заряду" },
        { kind: "comp", file: "../../../components/passive/electrolytic/electrolytic.md", at: "2.1.5", status: "done", title: "Електролітичні й танталові" },
        { kind: "comp", file: "../../../components/passive/capacitor-marking/capacitor-marking.md", at: "2.1.5", status: "done", title: "Маркування й типорозміри" },
        { kind: "comp", file: "../../../components/passive/mlcc/mlcc.md", at: "2.1.5", status: "done", title: "Керамічні MLCC: X7R/C0G/Y5V і DC bias" },
        { kind: "comp", file: "../../../components/passive/bleeder/bleeder.md", at: "2.1.6", status: "done", title: "Bleeder-резистор: чому БЖ «кусається»" },
        { kind: "comp", file: "../../../components/passive/decoupling/decoupling.md", at: "2.1.6", status: "done", title: "Розв'язувальні конденсатори: 100 нФ біля ніжки" },
        { kind: "comp", file: "../../../components/passive/supercap/supercap.md", at: "2.1.8", status: "done", title: "Іоністор як резервне живлення" }
      ] },
    { n: 2, title: "Котушка та індуктивність", dir: "block-2-components-analog/inductor", main: "inductor.md", status: "done",
      scope: "Енергія в магнітному полі; V = L·di/dt, чому струм не стрибає миттєво; перехідні RL; самоіндукція й викиди при комутації; взаємоіндукція.",
      topics: [
        { mrt: "2.2.1", title: "Котушка й магнітне поле струму", status: "done" },
        { mrt: "2.2.2", title: "Індуктивність і самоіндукція: V = L·di/dt", status: "done" },
        { mrt: "2.2.3", title: "Енергія в магнітному полі (½·L·I²)", status: "done" },
        { mrt: "2.2.4", title: "Перехідні процеси RL: стала часу L/R", status: "done" },
        { mrt: "2.2.5", title: "«Брикання» котушки: викиди напруги при комутації", status: "done" },
        { mrt: "2.2.6", title: "Взаємоіндукція й трансформація (принцип трансформатора)", status: "done" },
        { mrt: "2.2.7", title: "Типи й застосування котушок", status: "done" },
        { mrt: "2.2.9", title: "Ферити й EMI-бусини: «опір лише для шуму»", status: "done" },
        { kind: "hist", file: "hist-induction.md", at: "chapter", status: "done", title: "Фарадей і Генрі" },
        { kind: "hist", file: "hist-oersted-ampere.md", at: "2.2.1", status: "done", title: "1820: компас Ерстеда й відповідь Ампера" },
        { kind: "hist", file: "hist-transformer.md", at: "2.2.6", status: "done", title: "Трансформатор і перемога змінного струму" },
        { kind: "math", file: "math-rl-ode.md", at: "2.2.4", status: "done", title: "Диференціальне рівняння RL: дзеркальне до RC" },
        { kind: "proj", file: "proj-inductance-meter.md", at: "2.2.4", status: "done", title: "Вимірюємо індуктивність (L/R і резонанс)" },
        { kind: "comp", file: "comp-rc-snubber.md", at: "2.2.5", status: "done", title: "RC-снабер біля контактів і котушок DC" },
        { kind: "comp", file: "../../../components/passive/transformer/transformer.md", at: "2.2.6", status: "done", title: "Трансформатори в пристроях" },
        { kind: "math", file: "math-turns-ratio.md", at: "2.2.6", status: "done", title: "Коефіцієнт трансформації і відбитий імпеданс" },
        { kind: "comp", file: "../../../components/passive/power-inductor/power-inductor.md", at: "2.2.7", status: "done", title: "Силові дроселі на платі" },
        { kind: "comp", file: "../../../components/passive/ferrite-clamp/ferrite-clamp.md", at: "2.2.9", status: "done", title: "Феритове кільце на кабелі" }
      ] },
    { n: 3, title: "Реактивність, фази й резонанс", dir: "block-2-components-analog/reactance-resonance", main: "reactance-resonance.md", status: "done",
      scope: "Реактивний опір і його залежність від частоти; зсув фаз у C та L; LC-резонанс; добротність; перший погляд на частотну поведінку кіл.",
      topics: [
        { mrt: "2.3.1", title: "Чому «опір» C і L залежить від частоти (реактивність)", status: "done" },
        { mrt: "2.3.2", title: "Реактивний опір конденсатора Xc = 1/(2·π·f·C)", status: "done" },
        { mrt: "2.3.3", title: "Реактивний опір котушки XL = 2·π·f·L", status: "done" },
        { mrt: "2.3.4", title: "Зсув фаз: струм і напруга «не в ногу»", status: "done" },
        { mrt: "2.3.5", title: "LC-резонанс: реактивності гасять одна одну (f₀)", status: "done" },
        { mrt: "2.3.6", title: "Добротність Q і смуга", status: "done" },
        { mrt: "2.3.7", title: "RLC і частотна вибірковість", status: "done" },
        { kind: "hist", file: "hist-tuned-circuit.md", at: "chapter", status: "done", title: "Налаштований контур: «ловимо» одну частоту" },
        { kind: "hist", file: "hist-tacoma.md", at: "2.3.6", status: "done", title: "Міст Такома-Нерроуз: не резонанс, а флатер" },
        { kind: "math", file: "math-complex-phasors.md", at: "2.3.1", status: "done", title: "Комплексні числа й фазори" },
        { kind: "comp", file: "comp-capacitive-dropper.md", at: "2.3.2", status: "done", title: "Ємнісний баласт у дешевих LED-лампах" },
        { kind: "comp", file: "comp-lc-supply-filter.md", at: "2.3.3", status: "done", title: "Дросель і LC-фільтр у колі живлення" },
        { kind: "math", file: "math-impedance.md", at: "2.3.4", status: "done", title: "Імпеданс Z як узагальнений закон Ома" },
        { kind: "math", file: "math-power-triangle.md", at: "2.3.4", status: "done", title: "Активна, реактивна й повна потужність (P, Q, S, cosφ)" },
        { kind: "math", file: "math-sine-derivative.md", at: "2.3.4", status: "done", title: "Похідні синуса й косинуса: чому зсув 90°" },
        { kind: "proj", file: "proj-lissajous.md", at: "2.3.4", status: "done", title: "Фігури Ліссажу в режимі XY" },
        { kind: "comp", file: "../../../components/comms/nfc-rfid/nfc-rfid.md", at: "2.3.5", status: "done", title: "Резонанс, що живить картку: NFC/RFID" },
        { kind: "math", file: "math-thomson-formula.md", at: "2.3.5", status: "done", title: "Формула Томсона f₀ = 1/(2π√(LC))" },
        { kind: "proj", file: "proj-resonance-sweep.md", at: "2.3.5", status: "done", title: "Знайти резонанс свіпом" },
        { kind: "math", file: "math-damping.md", at: "2.3.6", status: "done", title: "Коливання з демпфуванням: ζ і зв'язок із Q" },
        { kind: "math", file: "math-q-factor.md", at: "2.3.6", status: "done", title: "Добротність Q математично" }
      ] },
    { n: 4, title: "АЧХ, децибели й фільтри", dir: "block-2-components-analog/frequency-response", main: "frequency-response.md", status: "done",
      scope: "Коло як фільтр; RC-фільтри НЧ/ВЧ і частота зрізу; децибели — навіщо логарифмічна шкала; АЧХ і діаграма Боде (−20 дБ/декаду); смуга пропускання й −3 дБ; LC/RLC і порядок фільтра.",
      topics: [
        { mrt: "2.4.1", title: "Коло як фільтр: що таке частотна характеристика", status: "done" },
        { mrt: "2.4.2", title: "RC-фільтр низьких частот: частота зрізу", status: "done" },
        { mrt: "2.4.3", title: "RC-фільтр високих частот", status: "done" },
        { mrt: "2.4.4", title: "Децибели: чому логарифмічна шкала", status: "done" },
        { mrt: "2.4.5", title: "АЧХ і діаграма Боде (−20 дБ/декаду)", status: "done" },
        { mrt: "2.4.6", title: "Смуга пропускання й точка −3 дБ", status: "done" },
        { mrt: "2.4.7", title: "LC- і RLC-фільтри; порядок фільтра (якісно)", status: "done" },
        { kind: "hist", file: "hist-bode.md", at: "chapter", status: "done", title: "Гендрік Боде: графіки, що приручили зворотний зв'язок" },
        { kind: "hist", file: "hist-decibel.md", at: "2.4.4", status: "done", title: "Бел і «миля стандартного кабелю»" },
        { kind: "comp", file: "comp-breadboard-parasitics.md", at: "2.4.1", status: "done", title: "Чому макетка бреше на ВЧ" },
        { kind: "comp", file: "comp-scope-probe.md", at: "2.4.1", status: "done", title: "Щуп осцилографа 10:1: компенсований дільник" },
        { kind: "comp", file: "comp-input-rc.md", at: "2.4.2", status: "done", title: "RC-фільтр на вході вимірювання" },
        { kind: "math", file: "math-transfer-function.md", at: "2.4.2", status: "done", title: "Передавальна функція RC: модуль і фаза" },
        { kind: "comp", file: "comp-coupling-cap.md", at: "2.4.3", status: "done", title: "Розділовий конденсатор: ФВЧ в аудіотракті" },
        { kind: "math", file: "math-logarithms.md", at: "2.4.4", status: "done", title: "Логарифми" },
        { kind: "proj", file: "proj-bode-measurement.md", at: "2.4.5", status: "done", title: "Зняти АЧХ власноруч" },
        { kind: "math", file: "math-half-power.md", at: "2.4.6", status: "done", title: "Чому −3 дБ — це половина потужності й 0.707" },
        { kind: "math", file: "math-risetime-bandwidth.md", at: "2.4.6", status: "done", title: "Фронт і смуга: f ≈ 0.35/t_rise" },
        { kind: "comp", file: "comp-speaker-crossover.md", at: "2.4.7", status: "done", title: "Кросовер у колонці: LC-фільтри" },
        { kind: "math", file: "math-cascading.md", at: "2.4.7", status: "done", title: "Каскадування фільтрів: взаємне навантаження" }
      ] },
    { n: 5, title: "Діод і PN-перехід", dir: "block-2-components-analog/diode-pn-junction", main: "diode-pn-junction.md", status: "done",
      scope: "Напівпровідник, легування n/p; PN-перехід і бар'єр; ВАХ діода, пряме падіння, пробій; випрямлення, обмеження, захист; світлодіод і фотодіод; оптопара й гальванічна розв'язка.",
      topics: [
        { mrt: "2.5.1", title: "Напівпровідник: між провідником та ізолятором", status: "done" },
        { mrt: "2.5.2", title: "Легування: n- і p-тип (донори/акцептори)", status: "done" },
        { mrt: "2.5.3", title: "PN-перехід: бар'єр і збіднена область", status: "done" },
        { mrt: "2.5.4", title: "Пряме й зворотне зміщення: клапан для струму", status: "done" },
        { mrt: "2.5.5", title: "ВАХ діода: пряме падіння й пробій (~0.7 В)", status: "done" },
        { mrt: "2.5.6", title: "Випрямлення: змінний → постійний", status: "done" },
        { mrt: "2.5.7", title: "Світлодіод і фотодіод", status: "done" },
        { mrt: "2.5.8", title: "Особливі діоди: Зенера, Шотткі", status: "done" },
        { mrt: "2.5.9", title: "Захист: flyback для котушки і від зворотної полярності", status: "done" },
        { mrt: "2.5.10", title: "Оптопара й гальванічна розв'язка", status: "done" },
        { kind: "hist", file: "hist-diode.md", at: "chapter", status: "done", title: "Від «котячого вуса» до PN-переходу (Рассел Ол)" },
        { kind: "hist", file: "hist-silicon-germanium.md", at: "2.5.1", status: "done", title: "Кремній проти германію: чому виграв «пісок»" },
        { kind: "hist", file: "hist-blue-led.md", at: "2.5.7", status: "done", title: "Блакитний світлодіод: Акасакі, Амано, Накамура" },
        { kind: "hist", file: "hist-led.md", at: "2.5.7", status: "done", title: "Олег Лосєв і забутий світлодіод" },
        { kind: "hist", file: "hist-zener.md", at: "2.5.8", status: "done", title: "Кларенс Зенер і пробій, що став корисним" },
        { kind: "math", file: "math-shockley-equation.md", at: "2.5.5", status: "done", title: "Рівняння Шоклі: чому «0.7 В» не константа" },
        { kind: "proj", file: "proj-diode-thermometer.md", at: "2.5.5", status: "done", title: "Діод як термометр" },
        { kind: "comp", file: "../../../components/active/bridge-rectifier/bridge-rectifier.md", at: "2.5.6", status: "done", title: "Діодний міст як компонент" },
        { kind: "math", file: "math-ripple-calc.md", at: "2.5.6", status: "done", title: "Пульсації після випрямляча: згладжувальний конденсатор" },
        { kind: "comp", file: "../../../components/active/led-practice/led-practice.md", at: "2.5.7", status: "done", title: "Світлодіоди на практиці" },
        { kind: "math", file: "math-photon-energy.md", at: "2.5.7", status: "done", title: "Фотон і заборонена зона: E = hf, колір LED" },
        { kind: "proj", file: "proj-charlieplexing.md", at: "2.5.7", status: "done", title: "Charlieplexing" },
        { kind: "comp", file: "../../../components/active/diode-families/diode-families.md", at: "2.5.8", status: "done", title: "Сімейства діодів 1N4148/1N400x/Шотткі" },
        { kind: "comp", file: "../../../components/active/tvs-diode/tvs-diode.md", at: "2.5.8", status: "done", title: "TVS-діоди: захист входів від ESD і викидів" },
        { kind: "math", file: "math-reverse-recovery.md", at: "2.5.8", status: "done", title: "Зворотне відновлення діода (Qrr)" },
        { kind: "comp", file: "../../../components/active/optocoupler/optocoupler.md", at: "2.5.10", status: "done", title: "Оптопара PC817-класу: CTR і розрахунок резисторів" }
      ] },
    { n: 6, title: "Біполярний транзистор (BJT)", dir: "block-2-components-analog/bjt", main: "bjt.md", status: "done",
      scope: "Керування струмом; режими відсічки/активний/насичення; ключ проти підсилювача; коефіцієнт підсилення; базові схеми ввімкнення; реле з драйвером.",
      topics: [
        { mrt: "2.6.1", title: "Транзистор: ідея керованого «крана» струму", status: "done" },
        { mrt: "2.6.2", title: "Будова BJT: два p-n переходи (NPN/PNP)", status: "done" },
        { mrt: "2.6.3", title: "Як працює: малий струм бази керує великим струмом колектора", status: "done" },
        { mrt: "2.6.4", title: "Коефіцієнт підсилення β (hFE): Ic = β·Ib", status: "done" },
        { mrt: "2.6.5", title: "Режими: відсічка, активний, насичення", status: "done" },
        { mrt: "2.6.6", title: "BJT як ключ", status: "done" },
        { mrt: "2.6.7", title: "BJT як підсилювач", status: "done" },
        { mrt: "2.6.8", title: "Практика: керування навантаженням, вибір за даташитом", status: "done" },
        { mrt: "2.6.9", title: "Реле і його драйвер: котушка, flyback, ключ", status: "done" },
        { kind: "hist", file: "hist-transistor.md", at: "chapter", status: "done", title: "1947, Bell Labs — винахід транзистора" },
        { kind: "hist", file: "hist-traitorous-eight.md", at: "2.6.1", status: "done", title: "Шоклі, «зрадницька вісімка» і Кремнієва долина" },
        { kind: "hist", file: "hist-tr1-sony.md", at: "2.6.8", status: "done", title: "Regency TR-1 і шлях Sony" },
        { kind: "proj", file: "proj-measure-hfe.md", at: "2.6.4", status: "done", title: "Виміряти β самому" },
        { kind: "comp", file: "../../../components/active/darlington-uln/darlington-uln.md", at: "2.6.6", status: "done", title: "Дарлінгтон і ULN2003-клас" },
        { kind: "comp", file: "comp-high-side-pnp.md", at: "2.6.6", status: "done", title: "Ключ у плюсовому проводі: PNP high-side" },
        { kind: "math", file: "math-base-resistor.md", at: "2.6.6", status: "done", title: "Розрахунок резистора бази: насичення з запасом" },
        { kind: "comp", file: "comp-common-emitter.md", at: "2.6.7", status: "done", title: "Найпростіший підсилювач: спільний емітер" },
        { kind: "math", file: "math-load-line.md", at: "2.6.7", status: "done", title: "Робоча точка й навантажувальна пряма" },
        { kind: "comp", file: "../../../components/active/bjt-families/bjt-families.md", at: "2.6.8", status: "done", title: "Робочі конячки 2N2222/BC547/2N3904" },
        { kind: "comp", file: "comp-relay-inside.md", at: "2.6.9", status: "done", title: "Електромеханічне реле зсередини" },
        { kind: "comp", file: "comp-relay-module.md", at: "2.6.9", status: "done", title: "Модуль реле: що на платі, крім реле" }
      ] },
    { n: 7, title: "Польовий транзистор (MOSFET)", dir: "block-2-components-analog/mosfet", main: "mosfet.md", status: "done",
      scope: "Керування полем, ємність затвора, поріг; опір у відкритому стані; комутація потужності; чому MOSFET витіснив BJT у ключах.",
      topics: [
        { mrt: "2.7.1", title: "Інша ідея: керувати струмом полем, а не струмом", status: "done" },
        { mrt: "2.7.2", title: "Будова MOSFET: затвор–ізолятор–канал", status: "done" },
        { mrt: "2.7.3", title: "Поріг і канал: як поле відкриває провідність", status: "done" },
        { mrt: "2.7.4", title: "N-канальний і P-канальний (NMOS/PMOS)", status: "done" },
        { mrt: "2.7.5", title: "Опір у відкритому стані Rds(on)", status: "done" },
        { mrt: "2.7.6", title: "MOSFET як силовий ключ", status: "done" },
        { mrt: "2.7.7", title: "Затвор як ємність: швидкість перемикання", status: "done" },
        { mrt: "2.7.8", title: "BJT проти MOSFET: коли що", status: "done" },
        { mrt: "2.7.9", title: "CMOS: пара, з якої зроблено всю цифрову техніку", status: "done" },
        { mrt: "2.7.10", title: "H-міст: чотири ключі, щоб крутити мотор в обидва боки", status: "done" },
        { mrt: "2.7.11", title: "Верхній ключ: bootstrap, charge pump і драйвер півмоста", status: "done" },
        { kind: "hist", file: "hist-mosfet.md", at: "chapter", status: "done", title: "MOSFET: ідея на 30 років раніше (Лілієнфельд → Аталла й Кан)" },
        { kind: "hist", file: "hist-hexfet.md", at: "2.7.5", status: "done", title: "HEXFET (1979): потужний MOSFET став масовим" },
        { kind: "hist", file: "hist-cmos.md", at: "2.7.9", status: "done", title: "CMOS — Френк Ванласс і майже нульове споживання" },
        { kind: "comp", file: "../../../components/active/mosfet-body-diode/mosfet-body-diode.md", at: "2.7.2", status: "done", title: "Паразитний body-діод" },
        { kind: "math", file: "math-square-law.md", at: "2.7.3", status: "done", title: "Квадратичний закон: Id від Vgs" },
        { kind: "comp", file: "../../../components/active/pmos-load-switch/pmos-load-switch.md", at: "2.7.4", status: "done", title: "P-канальний load switch" },
        { kind: "comp", file: "../../../components/active/ideal-diode-ic/ideal-diode-ic.md", at: "2.7.6", status: "done", title: "«Ідеальний діод»: P-MOSFET замість Шотткі" },
        { kind: "comp", file: "../../../components/active/logic-level-mosfet/logic-level-mosfet.md", at: "2.7.6", status: "done", title: "Logic-level MOSFET (IRLZ44/AO3400)" },
        { kind: "proj", file: "proj-thermal-calc.md", at: "2.7.6", status: "done", title: "Тепловий розрахунок ключа" },
        { kind: "comp", file: "../../../components/active/gate-driver/gate-driver.md", at: "2.7.7", status: "done", title: "Драйвер затвора" },
        { kind: "math", file: "math-gate-charge.md", at: "2.7.7", status: "done", title: "Заряд затвора Qg і втрати на перемикання" },
        { kind: "comp", file: "comp-h-bridge-board.md", at: "2.7.10", status: "done", title: "Плата H-моста: L298-клас і MOSFET-драйвери" },
        { kind: "proj", file: "proj-shoot-through.md", at: "2.7.10", status: "done", title: "Наскрізний струм і мертвий час" }
      ] },
    { n: 8, title: "Операційний підсилювач і компаратор", dir: "block-2-components-analog/opamp-comparator", main: "opamp-comparator.md", status: "done",
      scope: "Ідеальний ОП, від'ємний зворотний зв'язок, «віртуальне коротке»; інвертуючий/неінвертуючий/повторювач/диференційний; компаратор і тригер Шмітта; що всередині ОП (дифпара); LDO зсередини.",
      topics: [
        { mrt: "2.8.1", title: "Ідеальний операційний підсилювач", status: "done" },
        { mrt: "2.8.2", title: "Від'ємний зворотний зв'язок: магія стабільності", status: "done" },
        { mrt: "2.8.3", title: "«Віртуальне коротке»: правило для розрахунку", status: "done" },
        { mrt: "2.8.4", title: "Неінвертуючий та інвертуючий підсилювач", status: "done" },
        { mrt: "2.8.5", title: "Повторювач (буфер): розв'язка опорів", status: "done" },
        { mrt: "2.8.6", title: "Суматор і різницевий підсилювач", status: "done" },
        { mrt: "2.8.7", title: "Компаратор: порівняти дві напруги", status: "done" },
        { mrt: "2.8.8", title: "Гістерезис і тригер Шмітта", status: "done" },
        { mrt: "2.8.9", title: "Реальний ОП: межі (зсув, смуга, швидкість наростання)", status: "done" },
        { mrt: "2.8.10", title: "Що всередині ОП: диференційна пара (якісно)", status: "done" },
        { mrt: "2.8.11", title: "LDO зсередини: ОП + транзистор + опорна напруга", status: "done" },
        { kind: "hist", file: "hist-opamp.md", at: "chapter", status: "done", title: "ОП: від аналогових обчислювачів до µA741" },
        { kind: "hist", file: "hist-harold-black.md", at: "2.8.2", status: "done", title: "Гарольд Блек: від'ємний зворотний зв'язок (1927)" },
        { kind: "math", file: "math-feedback-formula.md", at: "2.8.2", status: "done", title: "Формула зворотного зв'язку A/(1+A·β)" },
        { kind: "comp", file: "comp-buffer-divider.md", at: "2.8.5", status: "done", title: "Повторювач рятує дільник" },
        { kind: "math", file: "math-cap-load.md", at: "2.8.5", status: "done", title: "ОП і ємнісне навантаження: чому буфер «дзвонить»" },
        { kind: "proj", file: "proj-signal-scaling.md", at: "2.8.6", status: "done", title: "Зміщення й масштабування: ±5 В у 0–3.3 В" },
        { kind: "comp", file: "../../../components/active/comparator-ics/comparator-ics.md", at: "2.8.7", status: "done", title: "Компаратор ≠ ОП: LM393-клас, відкритий колектор" },
        { kind: "math", file: "math-hysteresis-calc.md", at: "2.8.8", status: "done", title: "Розрахунок порогів гістерезису" },
        { kind: "proj", file: "proj-light-threshold.md", at: "2.8.8", status: "done", title: "Поріг із гістерезисом наживо: нічник" },
        { kind: "comp", file: "../../../components/active/rail-to-rail-opamp/rail-to-rail-opamp.md", at: "2.8.9", status: "done", title: "Rail-to-rail і single-supply" },
        { kind: "math", file: "math-gbw-slew.md", at: "2.8.9", status: "done", title: "GBW і slew rate у числах" },
        { kind: "math", file: "math-noise-budget.md", at: "2.8.9", status: "done", title: "Шумовий бюджет входу ОП" },
        { kind: "math", file: "math-current-mirror.md", at: "2.8.10", status: "done", title: "Струмове дзеркало: цеглинка всередині ОП" },
        { kind: "comp", file: "../../../components/active/ldo-module/ldo-module.md", at: "2.8.11", status: "done", title: "Модуль лінійного стабілізатора: AMS1117-клас" },
        { kind: "math", file: "math-ldo-dissipation.md", at: "2.8.11", status: "done", title: "Розсіювання LDO: (Vin−Vout)·I" }
      ] },
    { n: 9, title: "Як читати даташит", dir: "block-2-components-analog/reading-datasheets", main: "reading-datasheets.md", status: "done",
      scope: "Структура даташита; Absolute Maximum проти Recommended Operating; min/typ/max та умови вимірювання; графіки derating; корпуси й маркування; примітки дрібним шрифтом та errata; практикум на знайомих компонентах.",
      topics: [
        { mrt: "2.9.1", title: "Даташит — паспорт компонента: структура документа", status: "done" },
        { mrt: "2.9.2", title: "Absolute Maximum vs Recommended Operating", status: "done" },
        { mrt: "2.9.3", title: "Min/typ/max і умови вимірювання", status: "done" },
        { mrt: "2.9.4", title: "Графіки: derating, ВАХ, температурні залежності", status: "done" },
        { mrt: "2.9.5", title: "Корпуси, маркування, розпіновка", status: "done" },
        { mrt: "2.9.6", title: "Дрібний шрифт: примітки, умови тестів, errata", status: "done" },
        { mrt: "2.9.7", title: "Практикум: даташити діода, MOSFET і ОП", status: "done" },
        { kind: "hist", file: "hist-databooks.md", at: "2.9.1", status: "done", title: "Епоха Databook-ів: каталоги RCA і томи TTL від TI" },
        { kind: "hist", file: "hist-pentium-fdiv.md", at: "2.9.6", status: "done", title: "Pentium FDIV (1994): баг, що навчив публікувати errata" },
        { kind: "comp", file: "comp-abs-max-failures.md", at: "2.9.2", status: "done", title: "Absolute Maximum на практиці: latch-up, перенапруга" },
        { kind: "math", file: "math-tolerance-statistics.md", at: "2.9.3", status: "done", title: "Min/typ/max як статистика" },
        { kind: "math", file: "math-derating.md", at: "2.9.4", status: "done", title: "Derating-графіки: інтерполяція і правило запасу" },
        { kind: "math", file: "math-thermal-resistance.md", at: "2.9.4", status: "done", title: "Теплова модель: Rθ як тепловий закон Ома" },
        { kind: "proj", file: "proj-log-graph-reading.md", at: "2.9.4", status: "done", title: "Зчитати число з графіка правильно (лог-осі)" },
        { kind: "comp", file: "../../../components/passive/packages/packages.md", at: "2.9.5", status: "done", title: "Корпуси наживо: THT проти SMD" },
        { kind: "comp", file: "../../../components/passive/smd-marking/smd-marking.md", at: "2.9.5", status: "done", title: "Коди SMD-маркування" },
        { kind: "comp", file: "comp-component-tester.md", at: "2.9.7", status: "done", title: "Кишеньковий тестер компонентів (TC1-клас)" },
        { kind: "proj", file: "proj-selection-checklist.md", at: "2.9.7", status: "done", title: "Чеклист вибору компонента" }
      ] },
    { n: 10, title: "Резонатори й опорні частоти", dir: "block-2-components-analog/resonators-references", main: "resonators-references.md", status: "done",
      scope: "Кварцові й керамічні резонатори, MEMS і TCXO/OCXO: п'єзоефект, добротність, схема генератора П'єрса, точність у ppm і опорна частота для такту, часу й зв'язку.",
      topics: [
        { mrt: "2.10.1", title: "Навіщо системі опорна частота", status: "done" },
        { mrt: "2.10.2", title: "П'єзоефект: кристал перетворює напругу на деформацію і навпаки", status: "done" },
        { mrt: "2.10.3", title: "Кварцовий резонатор: механічний резонанс із добротністю в десятки тисяч", status: "done" },
        { mrt: "2.10.4", title: "Еквівалентна RLC-схема кварцу (модель Баттерворта–ван Дайка)", status: "done" },
        { mrt: "2.10.5", title: "Схема генератора: кварц + інвертор + два конденсатори (П'єрс)", status: "done" },
        { mrt: "2.10.6", title: "Точність у ppm: температурний дрейф, старіння, допуск", status: "done" },
        { mrt: "2.10.7", title: "Годинниковий кварц 32768 Гц і RTC", status: "done" },
        { mrt: "2.10.8", title: "Керамічні резонатори й MEMS-осцилятори", status: "done" },
        { mrt: "2.10.9", title: "TCXO та OCXO: коли потрібна компенсація температури", status: "done" },
        { kind: "hist", file: "hist-pierce-ft243.md", at: "chapter", status: "done", title: "Джордж П'єрс і FT-243: мільйони кварців на фронт" },
        { kind: "hist", file: "hist-quartz-crisis.md", at: "2.10.7", status: "done", title: "Кварцова криза: Seiko Astron і крах годинникової індустрії" },
        { kind: "comp", file: "comp-internal-rc.md", at: "2.10.1", status: "done", title: "Внутрішній RC-генератор МК проти кварцу" },
        { kind: "math", file: "math-q-stability.md", at: "2.10.3", status: "done", title: "Q = 10⁴…10⁶: добротність і стабільність частоти" },
        { kind: "comp", file: "comp-crystal-layout.md", at: "2.10.5", status: "done", title: "Кварц на платі: HC-49, SMD 3225, навантажувальні C" },
        { kind: "proj", file: "proj-oscillator-debug.md", at: "2.10.5", status: "done", title: "Чому генератор не стартує" },
        { kind: "math", file: "math-ppm-math.md", at: "2.10.6", status: "done", title: "ppm-арифметика: ±20 ppm у секунди за добу" },
        { kind: "proj", file: "proj-measure-drift.md", at: "2.10.6", status: "done", title: "Виміряти власний дрейф" },
        { kind: "comp", file: "../../../components/passive/watch-crystal/watch-crystal.md", at: "2.10.7", status: "done", title: "Годинниковий кварц зблизька" },
        { kind: "comp", file: "comp-mems-vs-quartz.md", at: "2.10.8", status: "done", title: "MEMS-осцилятори проти кварцу" },
        { kind: "comp", file: "comp-tcxo.md", at: "2.10.9", status: "done", title: "TCXO зсередини" }
      ] },
    { n: 11, title: "Силова комутація змінного струму", dir: "block-2-components-analog/ac-power-switching", main: "ac-power-switching.md", status: "done",
      scope: "Тиристор, симістор, IGBT і твердотільне реле для мережі: фазове керування й перехід через нуль, оптична розв'язка, снабери й dv/dt, безпека робіт із мережею.",
      topics: [
        { mrt: "2.11.1", title: "Чому ключі з §2.6/§2.7 не пасують мережі", status: "done" },
        { mrt: "2.11.2", title: "Тиристор (SCR): защіпка, що вмикається імпульсом", status: "done" },
        { mrt: "2.11.3", title: "Симістор (TRIAC): ключ для обох півхвиль", status: "done" },
        { mrt: "2.11.4", title: "Фазове керування потужністю: димер", status: "done" },
        { mrt: "2.11.5", title: "Перехід через нуль: комутація без сплесків і завад", status: "done" },
        { mrt: "2.11.6", title: "Твердотільне реле (SSR): оптична розв'язка + симістор/MOSFET", status: "done" },
        { mrt: "2.11.7", title: "IGBT: гібрид MOSFET і BJT для великих потужностей", status: "done" },
        { mrt: "2.11.8", title: "Снабери й dv/dt: чому симістор самовмикається на індуктивному навантаженні", status: "done" },
        { mrt: "2.11.9", title: "Безпека робіт із мережею", status: "done" },
        { kind: "hist", file: "hist-thyristor.md", at: "chapter", status: "done", title: "Від тиратрона до тиристора: GE 1957" },
        { kind: "hist", file: "hist-ssr.md", at: "2.11.6", status: "done", title: "Народження SSR: від ртутних контакторів до оптосимістора" },
        { kind: "hist", file: "hist-igbt-baliga.md", at: "2.11.7", status: "done", title: "Баліга, RCA проти GE і спірне батьківство IGBT" },
        { kind: "comp", file: "../../../components/protection/crowbar/crowbar.md", at: "2.11.2", status: "done", title: "Тиристор у crowbar-захисті" },
        { kind: "comp", file: "comp-triac-driver.md", at: "2.11.3", status: "done", title: "Симістори BT136/BTA16 і оптодрайвер MOC30xx" },
        { kind: "math", file: "math-phase-power.md", at: "2.11.4", status: "done", title: "Потужність від кута відсікання: інтеграл півхвилі" },
        { kind: "proj", file: "proj-dimmer-algorithm.md", at: "2.11.4", status: "done", title: "Алгоритм димера: від імпульсу нуля до затримки" },
        { kind: "comp", file: "comp-zero-cross-module.md", at: "2.11.5", status: "done", title: "Модуль детектора нуля (H11AA1-клас)" },
        { kind: "proj", file: "proj-burst-control.md", at: "2.11.5", status: "done", title: "Burst-керування нагрівачем" },
        { kind: "comp", file: "../../../components/active/ssr/ssr.md", at: "2.11.6", status: "done", title: "Твердотільне реле SSR-40DA-класу" },
        { kind: "math", file: "math-snubber-calc.md", at: "2.11.8", status: "done", title: "Оцінка RC-снабера: від струму до номіналів" },
        { kind: "comp", file: "../../../components/protection/mov-varistor/mov-varistor.md", at: "2.11.9", status: "done", title: "Варистор і запобіжник: перший рубіж" }
      ] },
    { n: 12, title: "Легендарні аналогові ІМС", dir: "block-2-components-analog/legendary-analog-ics", main: "legendary-analog-ics.md", status: "done",
      scope: "Чому деякі ІМС живуть 50 років: таймер 555 (астабіл/моностабіл), джерела опорної напруги й bandgap, аналогові ключі й мультиплексори, інструментальний підсилювач.",
      topics: [
        { mrt: "2.12.1", title: "Чому деякі мікросхеми живуть 50 років", status: "done" },
        { mrt: "2.12.2", title: "Таймер 555 зсередини: два компаратори, тригер і дільник", status: "done" },
        { mrt: "2.12.3", title: "555 в астабільному режимі: генератор прямокутника", status: "done" },
        { mrt: "2.12.4", title: "555 у моностабільному режимі: одновібратор", status: "done" },
        { mrt: "2.12.5", title: "Джерела опорної напруги: від стабілітрона до bandgap", status: "done" },
        { mrt: "2.12.6", title: "Аналогові ключі й мультиплексори (4066/4051)", status: "done" },
        { mrt: "2.12.7", title: "Інструментальний підсилювач: три ОП проти синфазної завади", status: "done" },
        { kind: "hist", file: "hist-camenzind-555.md", at: "chapter", status: "done", title: "Ганс Камензінд і таймер 555 (Signetics, 1971)" },
        { kind: "hist", file: "hist-bandgap.md", at: "2.12.5", status: "done", title: "Відлар, Брокау і bandgap" },
        { kind: "comp", file: "comp-ic-naming.md", at: "2.12.1", status: "done", title: "Розшифровка назв ІМС: NE/LM/TL/CD/74" },
        { kind: "comp", file: "comp-555-versions.md", at: "2.12.2", status: "done", title: "NE555 і TLC555: біполярна проти CMOS" },
        { kind: "math", file: "math-astable-formulas.md", at: "2.12.3", status: "done", title: "Формули астабільного 555: t = 0.693·R·C" },
        { kind: "proj", file: "proj-monostable.md", at: "2.12.4", status: "done", title: "Одновібратор у ділі: антидребезг і пастка перезапуску" },
        { kind: "comp", file: "../../../components/active/tl431/tl431.md", at: "2.12.5", status: "done", title: "TL431-клас: «програмований стабілітрон»" },
        { kind: "math", file: "math-bandgap-math.md", at: "2.12.5", status: "done", title: "Bandgap у числах: компенсація −2 мВ/°C через ΔVbe" },
        { kind: "comp", file: "../../../components/active/analog-mux/analog-mux.md", at: "2.12.6", status: "done", title: "CD4051/74HC4066: вісім давачів на один вхід" },
        { kind: "proj", file: "proj-mux-scanning.md", at: "2.12.6", status: "done", title: "Сканування входів через мультиплексор" },
        { kind: "comp", file: "comp-inamp-bridge.md", at: "2.12.7", status: "done", title: "Інструментальний підсилювач: чому три ОП" },
        { kind: "math", file: "math-inamp-cmrr.md", at: "2.12.7", status: "done", title: "Чому саме три ОП: підсилення і CMRR" }
      ] }
    // ── розділ 2.13+ (pending) у книжковому індексі ще не існує; цей модуль завершено (12/12 done) ──
  ]
});
