/* manifest — «Давачі» (тип "catalog"). Схема — AUTHORING.md §2 (v6). Заведено з hardware-інвентарю. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "catalog", slug: "sensors", title: "Давачі",
  sections: [
    { slug: "series", title: "Серії/родини модулів", scope: "Оглядові статті родин модулів (спільна історія, архітектура, як обрати варіант).",
      topics: [
        { slug: "ky-series", title: "KY-серія (Keyes 37-в-1)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-keyes-brand.md", status: "done" }] },
        { slug: "gy-series", title: "GY-серія (брейкаут-модулі)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-breakout-era.md", status: "done" }] },
        { slug: "pololu-imu-family", title: "Родина Pololu IMU (MinIMU-9 / AltIMU-10)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-chip-lineage.md", status: "done" }] },
        { slug: "mq-family", title: "Родина MQ (напівпровідникові давачі газу)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-taguchi-mq.md", status: "done" }] },
      ] },
    { slug: "environment", title: "Довкілля", scope: "Давачі середовища: температура, вологість, час, атмосферні явища.",
      topics: [
        { slug: "dht11", title: "DHT11 — температура/вологість", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-dht11-driver.md", status: "done" }] },
        { slug: "gy-21", title: "GY-21 (Si7021/HTU21D) — температура/вологість", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-si7021.md", status: "done" }], api: [{ file: "api-si7021.md", status: "done" }] },
        { slug: "ds1302-rtc", title: "DS1302 — RTC-модуль (CR2032)", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-ds1302.md", status: "done" }] },
        { slug: "as3935-lightning", title: "DFRobot SEN0290 (AS3935) — давач блискавок", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-dfrobot-as3935.md", status: "done" }] },
        { slug: "gy-bmp280", title: "GY-BMP280 — барометр/висотомір (BMP280)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bosch-barometers.md", status: "done" }], math: [{ file: "math-compensation.md", status: "done" }], api: [{ file: "api-bmp280.md", status: "done" }] },
        { slug: "gy-bmp180", title: "GY-68 / BMP180 — барометр (тиск, висота)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-bmp180.md", status: "done" }], api: [{ file: "api-bmp180.md", status: "done" }] },
        { slug: "gy-63", title: "GY-63 — прецизійний барометр MS5611", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ms5611.md", status: "done" }], api: [{ file: "api-ms5611.md", status: "done" }] },
      ] },
    { slug: "motion", title: "Рух і орієнтація", scope: "Відстань, рух, нахил, вібрація, магнітне поле, орієнтація.",
      topics: [
        { slug: "hc-sr04", title: "HC-SR04 — ультразвуковий далекомір", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-newping.md", status: "done" }] },
        { slug: "tof250", title: "TOF250 — лазерний далекомір", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-tof250-api.md", status: "done" }] },
        { slug: "hc-sr501", title: "HC-SR501 — PIR-давач руху", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-pir-firmware.md", status: "done" }] },
        { slug: "adxl335", title: "GY-61 ADXL335 — 3-осьовий акселерометр", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-adxl335.md", status: "done" }] },
        { slug: "pololu-imu", title: "Pololu IMU (LSM6DS33 / MinIMU-9)", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-lsm6.md", status: "done" }] },
        { slug: "hmc5883l", title: "GY-271 / HMC5883L — компас/магнетометр", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-hmc5883l.md", status: "done" }] },
        { slug: "sw-520d", title: "SW-520D — давач нахилу/вібрації", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-sw520d.md", status: "done" }] },
        { slug: "ky-002-vibration", title: "KY-002 — давач вібрації (SW-18020P)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky002-shock.md", status: "done" }] },
        { slug: "ky-020-tilt", title: "KY-020 — давач нахилу", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky020-driver.md", status: "done" }] },
        { slug: "ky-021-reed", title: "KY-021 — міні герконовий давач", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-reed-switch.md", status: "done" }], proj: [{ file: "proj-ky021.md", status: "done" }] },
        { slug: "ky-025-reed", title: "KY-025 — геркон у скляній колбі", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-reed-switch.md", status: "done" }], proj: [{ file: "proj-reed-firmware.md", status: "done" }] },
        { slug: "ky-003-hall", title: "KY-003 / KY-024 — давач Голла", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-hall-driver.md", status: "done" }] },
        { slug: "mpu6050", title: "GY-521 / MPU-6050 — 6-осьовий IMU (акселерометр+гіроскоп)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-invensense.md", status: "done" }], proj: [{ file: "proj-mpu6050.md", status: "done" }] },
        { slug: "mpu9250", title: "GY-91 / MPU-9250 — 9/10-осьовий IMU (+BMP280)", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-mpu9250-api.md", status: "done" }] },
        { slug: "tof10120", title: "TOF10120 — лазерний далекомір (ToF, до ~180 см)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-tof10120.md", status: "done" }], api: [{ file: "api-tof10120.md", status: "done" }] },
      ] },
    { slug: "light-sound", title: "Світло і звук", scope: "Освітленість, полумʼя, звук, дотик, оптичні переривачі.",
      topics: [
        { slug: "ky-018-photoresistor", title: "KY-018 — фоторезистор", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-photoresistor.md", status: "done" }], proj: [{ file: "proj-ky018.md", status: "done" }] },
        { slug: "ky-026-flame", title: "KY-026 — давач полумʼя", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky026-driver.md", status: "done" }] },
        { slug: "sound-lm393", title: "Звуковий давач з мікрофоном (LM393)", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-sound-lm393.md", status: "done" }] },
        { slug: "ky-038-mic", title: "KY-038 — мікрофонний давач звуку", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky038-driver.md", status: "done" }] },
        { slug: "ky-037-mic", title: "KY-037 — давач звуку (великий мікрофон)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky037-driver.md", status: "done" }], api: [{ file: "api-ky037-driver.md", status: "done" }] },
        { slug: "ttp223-touch", title: "TTP223 — сенсорний давач дотику", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-tontek-tontouch.md", status: "done" }], api: [{ file: "api-ttp223-driver.md", status: "done" }] },
        { slug: "ky-010-interrupter", title: "KY-010 — оптичний переривач", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky010-counter.md", status: "done" }] },
      ] },
    { slug: "temp-gas", title: "Температура і гази", scope: "Температура контактно, гази, біометрія (пульс/SpO2).",
      topics: [
        { slug: "ds18b20", title: "DS18B20 — цифровий давач температури (1-Wire)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-dallas-1wire.md", status: "done" }], api: [{ file: "api-ds18b20-driver.md", status: "done" }] },
        { slug: "ky-013-thermistor", title: "KY-013 — аналоговий давач температури (термістор)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-thermistor.md", status: "done" }], api: [{ file: "api-ky013.md", status: "done" }] },
        { slug: "ky-028-temp", title: "KY-028 — цифровий давач температури", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-thermistor-temp.md", status: "done" }], proj: [{ file: "proj-ky028-thermostat.md", status: "done" }] },
        { slug: "mq-gas", title: "MQ — давач газу (Keyes K869051)", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-mq-driver.md", status: "done" }] },
        { slug: "max30102", title: "GY-MAX30102 — давач пульсу/SpO2", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-max30102.md", status: "done" }] },
        { slug: "ky-039-pulse", title: "KY-039 — давач пульсу", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky039-driver.md", status: "done" }] },
      ] },
    { slug: "water-soil", title: "Вода і ґрунт", scope: "Вологість ґрунту, рівень води, дощ.",
      topics: [
        { slug: "soil-moisture", title: "Давач вологості ґрунту (+LM393)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-soil-moisture.md", status: "done" }] },
        { slug: "hw-038-water-level", title: "HW-038 — давач рівня води", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-hw038-driver.md", status: "done" }] },
        { slug: "funduino-rain", title: "Funduino — давач дощу (+LM358)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-funduino-rain.md", status: "done" }] },
        { slug: "capacitive-soil", title: "Ємнісний давач вологості ґрунту (v1.2)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-capacitive-soil.md", status: "done" }] },
      ] },
    { slug: "optical", title: "Оптичні/ІЧ", scope: "Виявлення перешкод, стук.",
      topics: [
        { slug: "ir-obstacle", title: "IR-давачі перешкод (FC-51 / KY-032)", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-ir-obstacle.md", status: "done" }] },
        { slug: "ky-031-knock", title: "KY-031 — давач стуку", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky031-knock.md", status: "done" }] },
      ] },
    { slug: "input", title: "Ввід (HMI)", scope: "Органи керування: кнопки, клавіатури, енкодери, джойстики, потенціометри.",
      topics: [
        { slug: "keypad-4x4-membrane", title: "Матрична клавіатура 4×4 (мембранна)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-keypad-driver.md", status: "done" }] },
        { slug: "keypad-4x4-tactile", title: "Матрична клавіатура 4×4 (тактильна)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ghosting.md", status: "done" }], api: [{ file: "api-keypad-scan.md", status: "done" }] },
        { slug: "ky-023-joystick", title: "KY-023 — джойстик-модуль", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-analog-stick.md", status: "done" }], proj: [{ file: "proj-ky023-driver.md", status: "done" }] },
        { slug: "ky-040-encoder", title: "KY-040 — поворотний енкодер", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky040.md", status: "done" }] },
        { slug: "tactile-buttons", title: "Тактильні кнопки з ковпачками", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "potentiometer", title: "Поворотний потенціометр", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-poggendorff.md", status: "done" }], proj: [{ file: "proj-potentiometer.md", status: "done" }] },
        { slug: "ky-004-button", title: "KY-004 — тактильна кнопка на платі", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ky004-button.md", status: "done" }] },
      ] },
  ]
});
