/* manifest — «Вбудована електроніка й автономні системи» (тип "guide"). Схема — AUTHORING.md §2 (v4). */
(window.__GUIDES__ = window.__GUIDES__ || []).push({
  type: "guide", slug: "embedded", title: "Вбудована електроніка й автономні системи",
  sections: [
    { slug: "osnovy", title: "Основи: заряд, струм, поле, тепло", scope: "",
      topics: [
        { ref: "physics/electric-charge", title: "Електричний заряд" },
        { ref: "physics/elementary-charge", title: "Елементарний заряд і квантування" },
        { ref: "physics/charge-conservation", title: "Закон збереження заряду" },
        { ref: "physics/coulomb-law", title: "Закон Кулона" },
        { ref: "physics/electric-field", title: "Електричне поле" },
        { ref: "physics/electric-potential", title: "Електричний потенціал" },
        { ref: "physics/voltage", title: "Напруга як різниця потенціалів" },
        { ref: "physics/faraday-cage", title: "Клітка Фарадея" },
        { ref: "physics/electric-current", title: "Електричний струм" },
        { ref: "physics/current-direction", title: "Напрямок струму: технічний і реальний" },
        { ref: "physics/electron-drift", title: "Дрейф електронів" },
        { ref: "physics/signal-speed", title: "Швидкість сигналу проти дрейфу носіїв" },
        { ref: "physics/current-continuity", title: "Неперервність струму" },
        { ref: "physics/ionic-conduction", title: "Іонна провідність" },
        { ref: "physics/resistance-origin", title: "Природа опору" },
        { ref: "physics/resistivity", title: "Питомий опір і провідність" },
        { ref: "physics/resistance", title: "Електричний опір" },
        { ref: "physics/resistance-temperature", title: "Опір і температура" },
        { ref: "physics/electric-power", title: "Електрична потужність" },
        { ref: "physics/joule-heating", title: "Джоулеве тепло" },
        { ref: "physics/thermal-resistance", title: "Тепловий опір і відведення тепла" },
        { ref: "physics/closed-circuit", title: "Замкнене коло й джерело ЕРС" },
        { ref: "physics/dc-vs-ac", title: "Постійний і змінний струм" },
        { ref: "physics/sine-wave", title: "Синусоїда" },
        { ref: "physics/amplitude-frequency", title: "Амплітуда, частота й період" },
        { ref: "physics/rms-value", title: "Діюче значення" },
        { ref: "physics/magnetic-field", title: "Магнітне поле" },
        { ref: "physics/oersted-experiment", title: "Магнітне поле струму" },
        { ref: "physics/ampere-force", title: "Сила Ампера" },
        { ref: "physics/electromagnet", title: "Електромагніт" },
        { ref: "physics/ferromagnetism", title: "Феромагнетизм і гістерезис" },
        { ref: "physics/electromagnetic-induction", title: "Електромагнітна індукція" },
        { ref: "physics/hall-effect", title: "Ефект Холла" },
        { ref: "physics/noise-interference", title: "Шум і завади як фізика" },
        { ref: "physics/thermal-noise", title: "Тепловий шум" },
        { ref: "physics/capacitive-coupling", title: "Ємнісна наводка" },
        { ref: "physics/inductive-coupling", title: "Індуктивна наводка" },
        { ref: "physics/triboelectricity", title: "Трибоелектрика й заряд тіла" },
        { ref: "physics/air-breakdown", title: "Пробій повітря й іскра" },
        { slug: "heat-transfer", title: "Передача тепла", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "field-and-potential", title: "Поле й потенціал", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-gradient.md", status: "done" }], proj: [{ file: "proj-relaxation.md", status: "done" }] },
        { slug: "electrostatics-summary", title: "Зведення електростатики", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "noise-interference", title: "Шум і завади", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-johnson-nyquist.md", status: "done" }], math: [{ file: "math-clt.md", status: "done" }, { file: "math-random-variables.md", status: "done" }], proj: [{ file: "proj-noise-generator.md", status: "done" }] },
        { slug: "frequency-wavelength", title: "Частота й довжина", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "memory-cell-physics", title: "Фізика комірок", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-frohman-eprom.md", status: "done" }], math: [{ file: "math-tunneling.md", status: "done" }] },
        { slug: "color-management", title: "Управління кольором: колірні профілі та гама", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vibration-diagnostics", title: "Вібродіагностика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "emerging-nvm-physics", title: "Фізика нових нелеткостей: FeRAM, MRAM, PCM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lightning-protection", title: "Захист від блискавки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "emf-sources", title: "Типи ЕРС: хімічна, теплова, світлова, індукційна", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "active-noise-cancellation", title: "Активне гасіння шуму", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "kola", title: "Кола й закони", scope: "",
      topics: [
        { ref: "electronics/ohms-law", title: "Закон Ома" },
        { ref: "electronics/voltage-divider", title: "Дільник напруги" },
        { ref: "electronics/current-divider", title: "Дільник струму" },
        { ref: "electronics/internal-resistance", title: "Внутрішній опір джерела" },
        { ref: "electronics/nodes-branches-loops", title: "Вузли, вітки й контури" },
        { ref: "electronics/kcl", title: "Закон струмів Кірхгофа" },
        { ref: "electronics/kvl", title: "Закон напруг Кірхгофа" },
        { ref: "electronics/series-connection", title: "Послідовне з'єднання" },
        { ref: "electronics/parallel-connection", title: "Паралельне з'єднання" },
        { ref: "electronics/superposition", title: "Принцип суперпозиції" },
        { ref: "electronics/thevenin", title: "Теорема Тевеніна" },
        { ref: "electronics/norton", title: "Теорема Нортона" },
        { ref: "electronics/power-matching", title: "Узгодження навантаження за потужністю" },
        { ref: "electronics/wheatstone-bridge", title: "Міст Вітстона" },
        { ref: "electronics/phase-shift", title: "Фаза й зсув фаз" },
        { ref: "electronics/rc-time-constant", title: "Стала часу RC" },
        { ref: "electronics/rl-time-constant", title: "Стала часу RL" },
        { ref: "electronics/instrumentation-amp", title: "Інструментальний підсилювач" },
        { slug: "circuit-analysis", title: "Аналіз кіл", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-maxwell-mesh.md", status: "done" }], proj: [{ file: "proj-circuit-sim.md", status: "done" }, { file: "proj-mna-spice.md", status: "done" }] },
        { slug: "reading-schematics", title: "Читання схем", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "bjt-load-driving", title: "BJT: навантаження", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-tr1-sony.md", status: "done" }], comp: [{ file: "comp-darlington-uln.md", status: "done" }] },
        { slug: "bjt-vs-mosfet", title: "BJT проти MOSFET", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "multistage-amplifier", title: "Багатокаскадний підсилювач", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "darlington-vs-sziklai", title: "Пара Дарлінгтона проти Sziklai", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "filter-families", title: "Родини фільтрів: Баттерворт, Чебишов, Бесель", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tail-current-source", title: "Джерело струму хвоста: від резистора до каскоду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "single-supply-opamp", title: "ОП на однополярному живленні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "filter-approximations", title: "Апроксимації фільтрів: Баттерворт, Чебишов, Бессель", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "feedback-topologies", title: "Топології зворотного зв'язку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "impedance-matching-networks", title: "Схеми узгодження імпедансів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cascaded-rc-filters", title: "Каскадовані RC-ланки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "reading-datasheet", title: "Як читати даташит", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "signal-conditioning", title: "Кондиціонування сигналу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dc-ac-bias", title: "DC-зміщення і AC-сигнал у підсилювачі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "kcl-opamp-analysis", title: "KCL у вузлах схем на ОП", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "opamp-input-types", title: "Типи входів ОП: BJT, JFET, CMOS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pierce-oscillator-design", title: "Генератор Пірса: схема й розрахунок обв'язки кварцу", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "komponenty", title: "Пасивні компоненти", scope: "",
      topics: [
        { ref: "electronics/resistor", title: "Резистор" },
        { ref: "electronics/resistor-marking", title: "Номінали й допуск" },
        { ref: "electronics/potentiometer", title: "Потенціометр і підлаштовник" },
        { ref: "electronics/capacitor", title: "Конденсатор" },
        { ref: "electronics/capacitor-dielectrics", title: "Діелектрики конденсаторів" },
        { ref: "electronics/capacitor-parasitics", title: "Паразити конденсатора" },
        { ref: "electronics/supercapacitor", title: "Суперконденсатор" },
        { ref: "electronics/inductor-coil", title: "Котушка" },
        { ref: "electronics/inductor-types", title: "Осердя й насичення" },
        { ref: "electronics/ferrite-bead", title: "Феритова намистина" },
        { ref: "electronics/mutual-inductance", title: "Зв'язані котушки" },
        { ref: "electronics/transformer", title: "Трансформатор" },
        { slug: "fuses-ptc", title: "Запобіжники", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-fuse.md", status: "done" }] },
        { slug: "zener-schottky", title: "Діоди Зенера", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-zener.md", status: "done" }], math: [{ file: "math-reverse-recovery.md", status: "done" }] },
        { slug: "flyback-protection", title: "Захист flyback", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "datasheet-practice", title: "Практикум даташитів", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-component-tester.md", status: "done" }], proj: [{ file: "proj-selection-checklist.md", status: "done" }] },
        { slug: "ceramic-mems-resonators", title: "Керамічні резонатори", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-mems-vs-quartz.md", status: "done" }] },
        { slug: "tcxo-ocxo", title: "TCXO та OCXO", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-tcxo.md", status: "done" }] },
        { slug: "energy-density-comparison", title: "Щільність енергії та потужності: конденсатор, суперконденсатор, акумулятор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "datasheet-bjt", title: "Практикум даташитів: BJT", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "datasheet-mcu", title: "Практикум даташитів: мікроконтролер", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "frequency-budget-analysis", title: "Частотний бюджет у системах зв'язку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "surge-protection-cascade", title: "Каскадний захист від перенапруги", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-budget", title: "Тепловий бюджет системи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "active-inrush-limiter", title: "Активний обмежувач пускового струму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pcb-thermal-design", title: "Тепловідведення на PCB", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pcb-assembly-methods", title: "Методи монтажу плат (THT і SMD)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "smd-rework", title: "Ручне паяння SMD", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "surge-protection-coordination", title: "Координація ланцюга захисту від перенапруг", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "napivprovidnyky", title: "Напівпровідники й діоди", scope: "",
      topics: [
        { ref: "electronics/esd-damage", title: "Електростатичний розряд" },
        { slug: "diodes", title: "Діоди", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "nor-vs-nand", title: "NOR і NAND", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-w25q-raw-commands.md", status: "done" }] },
        { slug: "eeprom-fram", title: "EEPROM і FRAM", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-serial-eeprom-fram.md", status: "done" }] },
        { slug: "sic-gan-comparison", title: "SiC і GaN: відмінності від кремнію", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mram-rram-pcm", title: "MRAM, RRAM і PCM: нові нелеткі пам'яті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-fail-safety", title: "Захист від зникнення живлення: brown-out і рятування стану", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "eda-tools", title: "EDA-інструменти", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "cyfra-pamyat", title: "Цифра й памʼять", scope: "",
      topics: [
        { ref: "electronics/shift-register", title: "Зсувний регістр" },
        { slug: "pal-to-fpga", title: "Від PAL до FPGA", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-greenpak.md", status: "done" }] },
        { slug: "fpga-flow", title: "Потік розробки", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-open-toolchain.md", status: "done" }] },
        { slug: "fpga-vs-mcu", title: "FPGA чи МК", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-edge-pulse.md", status: "done" }] },
        { slug: "when-memory-runs-out", title: "Коли пам'яті мало", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-dennard-dram.md", status: "done" }] },
        { slug: "choosing-memory", title: "Вибір пам'яті", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "digital-filters-intro", title: "Цифрові фільтри: FIR та IIR", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "synchronous-reset", title: "Синхронне й асинхронне скидання в цифрових схемах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "signal-integrity", title: "Цілісність сигналу (signal integrity)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ddr-signal-integrity", title: "Цілісність сигналу DDR-шини", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "custom-instruction", title: "Кастомні інструкції процесора", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "zhyvlennia", title: "Живлення", scope: "",
      topics: [
        { slug: "topology-map", title: "Вибір топології", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-efficiency-chain.md", status: "done" }] },
        { slug: "usb-power-map", title: "Живлення через USB", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-one-charger.md", status: "done" }] },
        { slug: "pd-sink-design", title: "PD у пристрої", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-pd-trigger.md", status: "done" }], proj: [{ file: "proj-pd-state-machine.md", status: "done" }] },
        { slug: "usb-cables-field", title: "Кабелі й сумісність", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-cable-drop.md", status: "done" }] },
        { slug: "battery-chemistries", title: "Хімії батарей", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-plante-jungner.md", status: "done" }] },
        { slug: "reverse-polarity", title: "Захист переполюсування", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "ac-switch-need", title: "Ключі для мережі", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-thyristor.md", status: "done" }] },
        { slug: "pwm-power-control", title: "Керування потужністю", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-mosfet-module.md", status: "done" }], proj: [{ file: "proj-gamma.md", status: "done" }] },
        { slug: "board-consumption", title: "Споживання плати", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-ldo-vs-buck.md", status: "done" }] },
        { slug: "linear-vs-switching", title: "Лінійний vs імпульсний", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-lithium.md", status: "done" }] },
        { slug: "pullup-resistor-design", title: "Розрахунок підтяжки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rf-frontend", title: "RF-тракт: підсилювачі, перемикач і балун", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "isp-pipeline", title: "ISP-пайплайн", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rc-antialiasing-design", title: "Проектування RC-антиаліасного фільтра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-supply-filtering", title: "Фільтрація живлення: згладжувач і розв'язка разом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inductive-load-switching", title: "Комутація індуктивного навантаження", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inductive-clamp-design", title: "Розрахунок клампу для індуктивного навантаження", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bridge-rectifier-design", title: "Місток Гретца: схема і розрахунок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "image-stabilization", title: "Стабілізація зображення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "transmission-line-pcb", title: "Лінія передачі на PCB: імпеданс і термінація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bms-architecture", title: "Архітектура BMS: монітор комірок, ізоляція, контактор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "active-balancing", title: "Активне балансування: топології і вибір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "battery-pack-thermal", title: "Тепловий менеджмент батарейного пакета", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sleep-current-audit", title: "Аудит струму спокою плати", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "emi-filter-design", title: "Вхідний EMI-фільтр перетворювача", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-spec-template", title: "Шаблон ТЗ на вузол живлення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "loop-gain-measurement", title: "Вимірювання петлевого підсилення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flyback-transformer-design", title: "Проектування трансформатора flyback", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fast-charging-protocols", title: "Протоколи швидкої зарядки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ldo-post-regulator", title: "LDO-постстабілізатор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-tree-reading", title: "Читання дерева живлення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-cc-adc-circuit", title: "Схема зчитування CC: АЦП, фільтрація, гістерезис", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-budget", title: "Бюджет потужності пристрою", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "esd-protection-circuits", title: "ESD-захист у схемах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thermal-runaway-protection", title: "Захист від теплової втечі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "frequency-measurement-methods", title: "Методи вимірювання частоти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-uart-bridge", title: "Перетворювач USB↔UART", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "mk", title: "Мікроконтролер і процесор", scope: "",
      topics: [
        { slug: "von-neumann-harvard", title: "Фон Нейман і Гарвард", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-harvard-architecture.md", status: "done" }], comp: [{ file: "comp-esp32-buses.md", status: "done" }] },
        { slug: "risc-cisc", title: "RISC і CISC", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-risc-revolution.md", status: "done" }] },
        { slug: "esp32-vs-8bit", title: "ESP32 проти 8-біт", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-8051.md", status: "done" }], math: [{ file: "math-benchmarks.md", status: "done" }] },
        { slug: "esp32-family", title: "Сімейство ESP32", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-riscv.md", status: "done" }] },
        { slug: "baremetal-vs-framework", title: "Голе залізо vs фреймворк", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-arduino.md", status: "done" }] },
        { slug: "jtag-swd-tools", title: "Serial, JTAG/SWD", basic: { status: "done" }, detailed: { status: "empty" }, comp: [{ file: "comp-debug-probes.md", status: "done" }], proj: [{ file: "proj-binary-logging.md", status: "done" }, { file: "proj-logging.md", status: "done" }] },
        { slug: "polling-vs-interrupts", title: "Polling vs переривання", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-isr-budget.md", status: "done" }] },
        { slug: "dma-adc", title: "DMA + АЦП", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "dma-spi-i2s", title: "DMA + SPI/I2S", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-soundblaster.md", status: "done" }], comp: [{ file: "comp-i2s-mic.md", status: "done" }, { file: "comp-spi-display.md", status: "done" }] },
        { slug: "super-loop-limits", title: "Межі super-loop", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "mcu-selection", title: "Вибір МК", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-arm.md", status: "done" }] },
        { slug: "mcu-checklist", title: "Чеклист вибору МК", basic: { status: "done" }, detailed: { status: "empty" }, math: [{ file: "math-decision-matrix.md", status: "done" }] },
        { slug: "duty-cycle-current", title: "Цикл і середній струм", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-energy-budget-table.md", status: "done" }] },
        { slug: "openocd-gdb", title: "OpenOCD і GDB", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "core-dump", title: "Посмертний аналіз", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-coredump-workflow.md", status: "done" }] },
        { slug: "mavlink-commands", title: "Команди MAVLink", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-command-ack-loop.md", status: "done" }] },
        { slug: "autonomous-system", title: "Автономна система", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-ardupilot.md", status: "done" }], proj: [{ file: "proj-control-loop.md", status: "done" }] },
        { slug: "memory-budget-mcu", title: "Бюджет пам'яті мікроконтролера", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-logger", title: "Логер споживання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "current-profiler-tools", title: "Вимірювання профілю струму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "edge-inference", title: "Інференс на пристрої (Edge AI)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pic-architecture", title: "Архітектура PIC", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pin-mux", title: "Мультиплексування пінів (IO_MUX / GPIO matrix)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ota-server", title: "Серверна частина OTA", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mission-planner-qgc", title: "Mission Planner і QGroundControl: порівняння GCS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "esptool-workflow", title: "esptool: прошивання й читання Flash", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "boot-time-budget", title: "Бюджет часу завантаження", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "reset-sequence", title: "Послідовність graceful reset", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wifi-fast-connect", title: "Швидке підключення Wi-Fi: кешування PMK і IP", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "debug-io-comparison", title: "Порівняння каналів налагоджувального виводу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fault-injection-testing", title: "Тестування відмовостійкості: fault injection", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hal-ll-registers", title: "HAL, LL і голі регістри в STM32", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "peryferiia", title: "Периферія й шини", scope: "",
      topics: [
        { ref: "communications/differential-pair", title: "Диференційна пара" },
        { ref: "communications/rs-485", title: "RS-485" },
        { slug: "spi-vs-i2c", title: "SPI проти I2C", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-bus-abstraction.md", status: "done" }] },
      ] },
    { slug: "proshyvka", title: "Прошивка й відлагодження", scope: "",
      topics: [
        { ref: "electronics/kelvin-shunt", title: "Струмовимірювальний шунт" },
        { slug: "sine-on-scope", title: "Синусоїда на осцилографі", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "noise-hunting", title: "Полювання на заваду", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-averaging.md", status: "done" }] },
        { slug: "measure-consumption", title: "Виміряти споживання", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-current-profiler.md", status: "done" }], math: [{ file: "math-dynamic-range.md", status: "done" }] },
        { slug: "firmware-testing", title: "Тестування прошивки", basic: { status: "done" }, detailed: { status: "done" }, proj: [{ file: "proj-emulators.md", status: "done" }] },
        { slug: "error-codes-vs-exceptions", title: "Коди помилок проти винятків", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "spi-dma", title: "SPI з DMA", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fatfs-integration", title: "Інтеграція FatFs у вбудований проєкт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "led-animation-patterns", title: "Анімаційні патерни LED", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "adc-reference-calibration", title: "Калібрування АЦП зовнішньою опорою", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "error-budget-ranging", title: "Бюджет похибок далекоміра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "calibration-procedure", title: "Процедура калібрування давача", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fmea-embedded", title: "FMEA у вбудованих системах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "addr2line-workflow", title: "Декодування адрес аварії: addr2line та символи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tpm-trustzone", title: "TPM і TrustZone: апаратний корінь довіри", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "solid-principles", title: "Принципи SOLID", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gitflow-branching", title: "Стратегії гілкування в git", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "error-propagation-patterns", title: "Патерни поширення помилок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "memory-safety", title: "Безпека роботи з пам'яттю", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spinlock-mutex", title: "Спінлок і мʼютекс: вибір і ціна", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "davachi", title: "Давачі", scope: "",
      topics: [
        { ref: "electronics/load-cell", title: "Тензодавач" },
        { slug: "contactless-distance", title: "Безконтактна відстань", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-sonar.md", status: "done" }] },
        { slug: "onboard-sensors", title: "Давачі апарата", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-gps.md", status: "done" }] },
        { slug: "imu-barometer", title: "IMU й барометр", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "barometric-altimeter", title: "Барометр-альтиметр", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "imu-mounting-materials", title: "Матеріали для кріплення IMU", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lidar-architecture", title: "Архітектури LiDAR", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "stereo-vision", title: "Стереозір", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "dyspleyi", title: "Дисплеї", scope: "",
      topics: [
        { slug: "display-classes", title: "Класи дисплеїв", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-lcd.md", status: "done" }] },
        { slug: "display-selection", title: "Вибір дисплея", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-display-module.md", status: "done" }] },
        { slug: "gram-init-sequence", title: "Ініціалізація контролера дисплея", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "display-lifecycle", title: "Керування життєвим циклом дисплея", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "keruvannia", title: "Керування й сигнали", scope: "",
      topics: [
        { slug: "choosing-a-filter", title: "Вибір фільтра", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "fir-vs-iir", title: "КІХ проти БІХ", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "signal-acquisition", title: "Зчитування сигналу", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-opamp-buffer.md", status: "done" }], math: [{ file: "math-sample-hold.md", status: "done" }] },
        { slug: "why-frequency-domain", title: "Навіщо частота", basic: { status: "done" }, detailed: { status: "empty" }, proj: [{ file: "proj-goertzel.md", status: "done" }] },
        { slug: "calculus-for-pid", title: "Похідна й інтеграл для PID", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "open-vs-closed-loop", title: "Зворотний зв'язок", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-feedback.md", status: "done" }] },
        { slug: "proportional-control", title: "П-регулятор", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-steady-state-offset.md", status: "done" }] },
        { slug: "integral-control", title: "І-складова", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-zero-offset.md", status: "done" }] },
        { slug: "derivative-control", title: "Д-складова", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "pid-tuning-cascade", title: "Налаштування ПІД", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-ziegler-nichols.md", status: "done" }] },
        { slug: "loop-stability", title: "Запас стійкості", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "filter-specification", title: "Специфікація фільтра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fir-design", title: "Проєктування КІХ-фільтрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "filter-latency-budget", title: "Бюджет затримки фільтра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sensor-fault-detection", title: "Виявлення відмови давача", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "antialiasing-filter-design", title: "Проєктування антиаліасингового фільтра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inertial-navigation", title: "Інерціальна навігація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "slam-navigation", title: "SLAM: одночасне картографування й локалізація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "attitude-estimation", title: "Оцінка орієнтації (attitude estimation)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "regex-engine-implementation", title: "Реалізація рушія регулярних виразів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lexer-design", title: "Лексичний аналіз", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "logic-minimization-algorithms", title: "Алгоритми мінімізації логіки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "float-formats-landscape", title: "Сімейство форматів плаваючої коми", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pi-controller-tuning", title: "Налаштування ПІ-регулятора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lead-lag-compensator", title: "Lead/lag-компенсатор", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tone-detection", title: "Виявлення тонів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "kalman-filter", title: "Фільтр Калмана", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "zvyazok", title: "Звʼязок і радіо", scope: "",
      topics: [
        { ref: "communications/ip-routing", title: "Маршрутизація" },
        { slug: "data-reliability", title: "Надійність даних", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "jamming-fhss", title: "Лінк під глушінням", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "link-budget", title: "Бюджет лінії", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "esp32-antenna", title: "Антена ESP32", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-ufl-connector.md", status: "done" }], math: [{ file: "math-friis-range.md", status: "done" }] },
        { slug: "nfc-rfid", title: "NFC/RFID", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "esp32-module", title: "ESP32-модуль", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "mavlink-from-ground", title: "MAVLink із землі", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "pymavlink", title: "pymavlink", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "pcb-antenna-layout", title: "Топологія антени на PCB: keep-out, заземлення, розведення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "arq-strategies", title: "Стратегії ARQ", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fpv-video-systems", title: "FPV-відеосистеми: аналог vs DJI O3/HDZero/Walksnail", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "multiple-access-methods", title: "Методи множинного доступу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "video-streaming-protocols", title: "Протоколи відеострімінгу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "802-11-versions", title: "Стандарти 802.11: від b/g/n до Wi-Fi 7", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "itu-r-propagation-models", title: "Моделі розповсюдження ITU-R і 3GPP", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "propagation-modes", title: "Режими поширення радіохвиль", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mission-planning", title: "Проєктування місії (вейпойнти)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lpwan", title: "LPWAN", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thread-matter-zigbee", title: "Thread, Zigbee і Matter: стек розумного дому на 802.15.4", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rpc-embedded", title: "RPC у вбудованих системах", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "drony", title: "Дрони й автономність", scope: "",
      topics: [
        { slug: "mjpeg-vs-h264", title: "MJPEG vs H.264", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "where-to-compute", title: "Де рахувати", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "output-mixing", title: "Узгодження сигналів керування", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "model-zoo", title: "Зоопарк моделей детекції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lz-family", title: "Сімейство LZ-алгоритмів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "on-device-benchmarking", title: "Бенчмаркінг на пристрої", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "model-export", title: "Експорт і розгортання моделей ML", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "training-data-pipeline", title: "Підготовка навчальних даних", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "servo-sizing", title: "Вибір сервопривода: момент, швидкість, маса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "esc-bldc-driver", title: "Регулятор обертів (ESC)", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
  ]
});
