/* reference/unix-linux/manifest.js — ДОВІДНИК «Unix і Linux» (тип "reference").
   Довідник — 4-й вид книги (AUTHORING §1): рукотворна система, описана як довідка.
   Схема — як у book (§2 v6): sections[] → topics[], статус на КОЖНУ версію.

   ПРИНЦИП ДОБОРУ ТЕМ: суть, а не наповнення. Ціль — ЯК СИСТЕМА ВЛАШТОВАНА Й ЧОМУ САМЕ ТАК,
   а не перелік команд і ключів. Кожна тема відповідає на «що це за механізм, яку задачу
   він розв'язує і які наслідки має», а команди з'являються лише як ілюстрація механізму.
   Тому тут є «Перенаправлення як робота з дескрипторами», але немає «10 ключів ls».

   126 тем у 14 розділах. Усі заведено як detailed:pending (basic — за потреби, §3).
   Послідовна доріжка по цих атомах — курс guide/unix. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "reference", slug: "unix-linux", title: "Unix і Linux",
  sections: [
    { slug: "foundations", title: "Ідея та родовід", scope: "Звідки Unix узявся, які рішення в ньому засадничі й що з них випливає для всього іншого.",
      topics: [
        { slug: "unix-philosophy", title: "Філософія Unix: малі програми, що складаються", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-birth.md", status: "done" }] , proj: [{ file: "proj-pipeline-by-hand.md", status: "done" }] , api: [{ file: "api-filter-contract.md", status: "done" }] },
        { slug: "everything-is-a-file", title: "«Усе є файлом»: один інтерфейс на все", basic: { status: "done" }, detailed: { status: "done" } , hist: [{ file: "hist-one-namespace.md", status: "done" }] , proj: [{ file: "proj-uniform-copy.md", status: "done" }] },
        { slug: "kernel-and-userspace", title: "Ядро й простір користувача", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-border-origin.md", status: "done" }] , proj: [{ file: "proj-border-probe.md", status: "done" }] },
        { slug: "syscall-mechanics", title: "Системний виклик: як програма просить ядро", basic: { status: "empty" }, detailed: { status: "done" } , proj: [{ file: "proj-entry-path-walk.md", status: "done" }] },
        { slug: "unix-lineage", title: "Родовід Unix: AT&T, BSD і поява Linux", basic: { status: "done" }, detailed: { status: "done" } , hist: [{ file: "hist-multics.md", status: "done" }, { file: "hist-usl-bsdi.md", status: "done" }] , proj: [{ file: "proj-portable-c.md", status: "done" }] },
        { slug: "posix-standard", title: "POSIX: що саме стандартизовано", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-standard-wars.md", status: "done" }] , api: [{ file: "api-conformance-query.md", status: "done" }] , proj: [{ file: "proj-portable-shell.md", status: "done" }] },
        { slug: "kernel-vs-distribution", title: "Ядро, дистрибутив і що між ними", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-first-distributions.md", status: "done" }] , proj: [{ file: "proj-min-userland.md", status: "done" }] },
        { slug: "gnu-userland", title: "Інструментарій GNU і чому «GNU/Linux»", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-two-halves.md", status: "done" }] , api: [{ file: "api-gnu-vs-posix.md", status: "done" }] , proj: [{ file: "proj-minimal-userland.md", status: "done" }] },
        { slug: "libc-as-gateway", title: "libc як шлюз до ядра", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-libc-story.md", status: "done" }] , proj: [{ file: "proj-syscall-without-libc.md", status: "done" }] , api: [{ file: "api-libc-boundary.md", status: "done" }] },
        { slug: "monolithic-with-modules", title: "Монолітне ядро з модулями: вибір Linux", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-tanenbaum-torvalds.md", status: "done" }] , proj: [{ file: "proj-hello-module.md", status: "done" }] },
        { slug: "userspace-abi-stability", title: "Що саме заморожено: ABI до простору користувача", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-abi-surface.md", status: "done" }] , hist: [{ file: "hist-vsyscall-trap.md", status: "done" }] , proj: [{ file: "proj-abi-extensible-syscall.md", status: "done" }] },
        { slug: "kernel-abi-stability", title: "«Не ламати простір користувача»: сталість ABI ядра", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-do-not-break.md", status: "done" }] , proj: [{ file: "proj-feature-probe.md", status: "done" }] },
        { slug: "kernel-release-model", title: "Модель випусків ядра: вікно злиття, -rc і стабільні гілки", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-release-metadata.md", status: "done" }] , hist: [{ file: "hist-two-branches.md", status: "done" }] , proj: [{ file: "proj-where-is-my-fix.md", status: "done" }] },
        { slug: "kernel-timekeeping", title: "Час у ядрі: тики, монотонний годинник і джерела часу", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-tick-to-tickless.md", status: "done" }] , math: [{ file: "math-cycles-to-nanoseconds.md", status: "done" }] , proj: [{ file: "proj-clock-lab.md", status: "done" }] },
        { slug: "compat-32-on-64", title: "32-бітні програми на 64-бітному ядрі: шар сумісности", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-compat-contract.md", status: "done" }] , hist: [{ file: "hist-64bit-transition.md", status: "done" }] , proj: [{ file: "proj-see-the-seam.md", status: "done" }] },
        { slug: "kernel-cve-and-security-fixes", title: "CVE в ядрі: потік номерів і що з ним робити", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "time-representation-y2038", title: "Час як число: time_t, епоха і межа 2038 року", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "processes", title: "Процес", scope: "Процес як головна одиниця системи: як народжується, як планується, як ізолюється.",
      topics: [
        { slug: "process-model", title: "Процес: що це насправді", basic: { status: "empty" }, detailed: { status: "done" } , proj: [{ file: "proj-clone-flags.md", status: "done" }] , hist: [{ file: "hist-process-and-fork.md", status: "done" }] },
        { slug: "pid-and-hierarchy", title: "PID і дерево процесів", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-pid-and-init.md", status: "done" }] , proj: [{ file: "proj-pidfd-supervisor.md", status: "done" }] , api: [{ file: "api-pid-interfaces.md", status: "done" }] },
        { slug: "fork-semantics", title: "fork: розмноження процесу", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-fork-origin.md", status: "done" }] , proj: [{ file: "proj-cow-observed.md", status: "done" }] },
        { slug: "exec-semantics", title: "exec: заміна образу", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-exec-family.md", status: "done" }] , hist: [{ file: "hist-shebang.md", status: "done" }] , proj: [{ file: "proj-exec-survivors.md", status: "done" }] },
        { slug: "exit-wait-zombies", title: "Завершення, wait і зомбі", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-wait-family.md", status: "done" }] , hist: [{ file: "hist-wait-and-zombie.md", status: "done" }] , proj: [{ file: "proj-zombie-lab.md", status: "done" }] },
        { slug: "orphan-reparenting", title: "Сироти й перепідпорядкування", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-orphan-and-subreaper.md", status: "done" }] , proj: [{ file: "proj-reparenting-lab.md", status: "done" }] },
        { slug: "process-states", title: "Стани процесу і що означає стан D", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-state-reporting.md", status: "done" }] , hist: [{ file: "hist-killable-sleep.md", status: "done" }] , proj: [{ file: "proj-catch-d-state.md", status: "done" }] },
        { slug: "scheduler-model", title: "Планувальник: як ядро ділить час", basic: { status: "done" }, detailed: { status: "done" } , hist: [{ file: "hist-scheduler-evolution.md", status: "done" }] , math: [{ file: "math-virtual-time.md", status: "done" }] , proj: [{ file: "proj-share-experiment.md", status: "done" }] },
        { slug: "priority-nice-realtime", title: "Пріоритети, nice і реальночасові класи", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-sched-interfaces.md", status: "done" }] , hist: [{ file: "hist-nice-to-deadline.md", status: "done" }] , math: [{ file: "math-shares-and-bandwidth.md", status: "done" }] , proj: [{ file: "proj-realtime-thread.md", status: "done" }] },
        { slug: "threads-as-tasks", title: "Потоки в Linux: задача як одиниця планування", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-per-thread-scope.md", status: "done" }] , hist: [{ file: "hist-linuxthreads-to-nptl.md", status: "done" }] , proj: [{ file: "proj-thread-anatomy.md", status: "done" }] },
        { slug: "cgroups", title: "cgroups: облік і обмеження ресурсів", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-cgroup2-interface.md", status: "done" }] , hist: [{ file: "hist-two-hierarchies.md", status: "done" }] , proj: [{ file: "proj-cgroup-by-hand.md", status: "done" }] },
        { slug: "namespaces", title: "Простори імен: ізоляція погляду на систему", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-namespace-interfaces.md", status: "done" }] , hist: [{ file: "hist-namespaces-origin.md", status: "done" }] , proj: [{ file: "proj-mini-container.md", status: "done" }] },
        { slug: "spawn-alternatives", title: "vfork, posix_spawn і clone: чим ще народжують процес", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-clone-flags.md", status: "done" }, { file: "api-posix-spawn.md", status: "done" }] , proj: [{ file: "proj-spawn-cost.md", status: "done" }] },
        { slug: "resource-limits", title: "Ліміти ресурсів: rlimit і ulimit", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-rlimit.md", status: "done" }] , hist: [{ file: "hist-limits-lineage.md", status: "done" }] , proj: [{ file: "proj-fd-limit.md", status: "done" }] },
        { slug: "cpu-time-accounting", title: "Облік процесорного часу: як ядро набирає user і sys", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-cputime-interfaces.md", status: "done" }] , hist: [{ file: "hist-tick-accounting.md", status: "done" }] , math: [{ file: "math-sampling-error.md", status: "done" }] , proj: [{ file: "proj-utime-vs-runtime.md", status: "done" }] },
        { slug: "daemonize", title: "Демонізація: відхід у фон", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-daemon-word.md", status: "done" }] , proj: [{ file: "proj-daemonize.md", status: "done" }] },
        { slug: "cpu-affinity", title: "Прив'язка задач до ядер: affinity, taskset і cpuset", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-affinity-interfaces.md", status: "done" }] , proj: [{ file: "proj-isolated-core.md", status: "done" }] },
        { slug: "kernel-preemption", title: "Витісненість ядра: від PREEMPT_NONE до PREEMPT_RT", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-preempt-controls.md", status: "done" }] , hist: [{ file: "hist-preemptible-kernel.md", status: "done" }] , proj: [{ file: "proj-measure-latency.md", status: "done" }] },
        { slug: "kernel-threads", title: "Потоки ядра: задачі без простору користувача", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-kthread-names.md", status: "done" }] , hist: [{ file: "hist-from-daemonize-to-kworkers.md", status: "done" }] , proj: [{ file: "proj-kthread-module.md", status: "done" }] },
        { slug: "binfmt-misc", title: "binfmt_misc: як ядро вчиться запускати чужі формати", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-register-format.md", status: "done" }] , hist: [{ file: "hist-binfmt-misc.md", status: "done" }] , proj: [{ file: "proj-register-own-format.md", status: "done" }] },
        { slug: "kernel-wait-queues", title: "Черги очікування в ядрі: як задача засинає й прокидається", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "kernel-locking", title: "Замки в ядрі й атомарний контекст: де спати не можна", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "memory", title: "Пам'ять процесу", scope: "Віртуальна пам'ять як механізм: чому адреси брешуть і що з цього виходить.",
      topics: [
        { slug: "virtual-address-space", title: "Віртуальний адресний простір процесу", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-maps-format.md", status: "done" }] , hist: [{ file: "hist-one-level-store.md", status: "done" }] , proj: [{ file: "proj-address-space-probe.md", status: "done" }] },
        { slug: "paging-and-mmu", title: "Сторінки, таблиці сторінок і MMU", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-pte-format.md", status: "done" }] , math: [{ file: "math-page-table-cost.md", status: "done" }] , proj: [{ file: "proj-virt-to-phys.md", status: "done" }] },
        { slug: "page-fault", title: "Сторінковий збій: чому все ліниве", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-fault-counters.md", status: "done" }] , hist: [{ file: "hist-demand-paging.md", status: "done" }] , proj: [{ file: "proj-fault-cost.md", status: "done" }] },
        { slug: "mmap-model", title: "mmap: файл і пам'ять як одне", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-mmap-flags.md", status: "done" }] , hist: [{ file: "hist-mmap-origin.md", status: "done" }] , proj: [{ file: "proj-mmap-vs-read.md", status: "done" }] },
        { slug: "copy-on-write", title: "Копіювання при записі", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-cow-controls.md", status: "done" }] , hist: [{ file: "hist-dirty-cow.md", status: "done" }] },
        { slug: "swap-and-reclaim", title: "Свопінг і витіснення сторінок", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-reclaim-counters.md", status: "done" }] , hist: [{ file: "hist-from-swapping-to-reclaim.md", status: "done" }] , math: [{ file: "math-thrashing-cliff.md", status: "done" }] , proj: [{ file: "proj-observe-reclaim.md", status: "done" }] },
        { slug: "overcommit-and-oom", title: "Overcommit і OOM-killer", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-oom-knobs.md", status: "done" }] , hist: [{ file: "hist-out-of-fuel.md", status: "done" }] , proj: [{ file: "proj-touch-the-promise.md", status: "done" }] },
        { slug: "memory-accounting", title: "Як міряти пам'ять процесу: VSZ, RSS, PSS", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-pss-birth.md", status: "done" }] , api: [{ file: "api-proc-memory-fields.md", status: "done" }] , proj: [{ file: "proj-pss-by-hand.md", status: "done" }] },
        { slug: "allocator-and-kernel", title: "Звідки алокатор бере пам'ять: brk і mmap", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-program-break.md", status: "done" }] , api: [{ file: "api-mallopt-tunables.md", status: "done" }] , proj: [{ file: "proj-heap-probe.md", status: "done" }] },
        { slug: "huge-pages", title: "Великі сторінки: HugeTLB і прозорі великі сторінки", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-huge-pages.md", status: "done" }] , api: [{ file: "api-huge-page-interfaces.md", status: "done" }] , proj: [{ file: "proj-huge-page-benchmark.md", status: "done" }] },
        { slug: "address-space-randomization", title: "Рандомізація адресного простору в системі: рівні та вимикачі", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-aslr-lineage.md", status: "done" }] , proj: [{ file: "proj-entropy-lab.md", status: "done" }] , api: [{ file: "api-randomization-controls.md", status: "done" }] },
        { slug: "userfaultfd", title: "userfaultfd: сторінкові збої в руках програми", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "kernel-page-table-isolation", title: "Ізоляція таблиць сторінок ядра (KPTI): чому ядро прибрали з простору процесу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ksm-page-merging", title: "KSM: злиття однакових сторінок", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "kernel-memory-slab", title: "Пам'ять ядра: slab і зменшувачі кешів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "physical-page-allocator", title: "Фізичні сторінки в ядрі: зони, блоки за порядками й ущільнення", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "memory-protection-keys", title: "Ключі захисту пам'яті: PKU і PKRU", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "files", title: "Файли й файлові системи", scope: "Що таке файл у Unix, як імена відв'язані від вмісту й на чому тримається узгодженість.",
      topics: [
        { slug: "file-descriptor", title: "Файловий дескриптор", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-fd-origin.md", status: "done" }] , api: [{ file: "api-fd-lifecycle.md", status: "done" }] , proj: [{ file: "proj-fd-table-tour.md", status: "done" }] },
        { slug: "open-file-description", title: "Опис відкритого файлу: що спільне після fork", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-file-table.md", status: "done" }] , api: [{ file: "api-fd-vs-ofd.md", status: "done" }] , proj: [{ file: "proj-shared-offset.md", status: "done" }] },
        { slug: "inode-model", title: "Inode: файл без імені", basic: { status: "empty" }, detailed: { status: "done" } , hist: [{ file: "hist-i-number.md", status: "done" }] , api: [{ file: "api-stat-fields.md", status: "done" }] , proj: [{ file: "proj-inode-identity.md", status: "done" }] },
        { slug: "directory-as-mapping", title: "Каталог як відображення імен", basic: { status: "empty" }, detailed: { status: "done" } , api: [{ file: "api-directory-syscalls.md", status: "done" }] , proj: [{ file: "proj-walk-directory.md", status: "done" }] , hist: [{ file: "hist-directory-formats.md", status: "done" }] },
        { slug: "hard-and-symbolic-links", title: "Жорсткі й символьні посилання", basic: { status: "empty" }, detailed: { status: "done" } , proj: [{ file: "proj-two-counters.md", status: "done" }] , api: [{ file: "api-link-syscalls.md", status: "done" }] , hist: [{ file: "hist-symlink-arrival.md", status: "done" }] },
        { slug: "path-resolution", title: "Розбір шляху", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "vfs-layer", title: "VFS: спільний шар над файловими системами", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mount-model", title: "Монтування й дерево монтувань", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "filesystem-families", title: "Родини файлових систем: ext4, XFS, Btrfs, F2FS", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "journaling-consistency", title: "Журналювання й узгодженість після збою", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "page-cache-durability", title: "Кеш сторінок, fsync і довговічність запису", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pseudo-filesystems", title: "Псевдо-ФС: procfs, sysfs, tmpfs, devtmpfs", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "fuse-userspace-filesystems", title: "FUSE: файлова система в просторі користувача", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "sparse-files", title: "Розріджені файли: діри замість нулів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "chroot", title: "chroot і його межі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "network-filesystems", title: "Мережеві файлові системи: NFS, SMB і чого від них чекати", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "file-locking", title: "Блокування файлів: flock, POSIX-замки й замки на опис відкритого файлу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "at-family-syscalls", title: "Сімейство *at: шлях, відлічений від дескриптора каталогу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "reflink-copies", title: "Копії з поділом блоків: reflink і copy_file_range", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "readahead", title: "Випереджувальне читання: як ядро вгадує наступний блок", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "overlay-filesystems", title: "Накладені файлові системи: overlayfs, шари й «білило»", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "overlayfs", title: "OverlayFS: об'єднання шарів в одне дерево", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "io", title: "Ввід-вивід і очікування", scope: "Як програма чекає на дані й чому саме тут вирішується, скільки з'єднань вона потягне.",
      topics: [
        { slug: "blocking-and-nonblocking", title: "Блокуючий і неблокуючий режим", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "readiness-vs-completion", title: "Готовність проти завершення: дві моделі вводу-виводу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "select-poll-epoll", title: "select, poll, epoll: чекати на багато джерел", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "io-uring", title: "io_uring: кільця подань і завершень", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pipes-and-fifo", title: "Канали й іменовані канали", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "unix-domain-sockets", title: "Сокети домену Unix і передача дескрипторів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "socket-as-descriptor", title: "Сокет як дескриптор", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "buffered-and-direct-io", title: "Буферизований і прямий ввід-вивід", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "zero-copy", title: "Передача без копіювання: sendfile і splice", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "eintr-and-restart", title: "EINTR: перервані виклики й перезапуск", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "stdio-buffering", title: "Буферизація stdio: порядкова, поблокова, без буфера", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "signals-ipc", title: "Сигнали й взаємодія процесів", scope: "Асинхронні сповіщення та способи, якими процеси домовляються між собою.",
      topics: [
        { slug: "signal-model", title: "Сигнал: асинхронне сповіщення", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "signal-disposition", title: "Диспозиція сигналу: обробник, ігнорування, типова дія", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "async-signal-safety", title: "Що взагалі можна робити в обробнику сигналу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "signal-mask-signalfd", title: "Маскування сигналів і signalfd", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ipc-landscape", title: "Огляд засобів взаємодії: що коли обирати", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "posix-shared-memory", title: "Спільна пам'ять POSIX", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "message-queues", title: "Черги повідомлень", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "eventfd-and-futex", title: "eventfd і futex: сповіщення й дешеве очікування", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "process-timers", title: "Таймери процесу: alarm, setitimer, POSIX-таймери й timerfd", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "permissions", title: "Права й ідентичність", scope: "Хто такий процес з погляду системи і як вирішується, що йому дозволено.",
      topics: [
        { slug: "uid-gid-model", title: "Користувачі, групи й ідентичність процесу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "permission-bits", title: "Біти прав і як їх перевіряють", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "setuid-and-privilege", title: "setuid, setgid і підвищення прав", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "umask-and-defaults", title: "umask і типові права новоствореного", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "capabilities", title: "Можливості (capabilities) замість всесильного root", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "acl-and-xattr", title: "Розширені права (ACL) і атрибути (xattr)", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mac-selinux-apparmor", title: "Обов'язковий контроль доступу: SELinux і AppArmor", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "device-access-groups", title: "Доступ до пристроїв через групи: dialout, plugdev", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "seccomp-filtering", title: "seccomp: фільтрація системних викликів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pam-stack", title: "PAM: стек модулів автентифікації", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "devices", title: "Пристрої та ядро", scope: "Як залізо стає файлом і як ядро керує тим, що під'єднали.",
      topics: [
        { slug: "device-file-model", title: "Файл пристрою: символьний і блоковий", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "major-minor-numbers", title: "Старший і молодший номери пристрою", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "sysfs-device-model", title: "Модель пристроїв у sysfs", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "udev-rules", title: "udev: іменування пристроїв і правила", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "kernel-modules", title: "Модулі ядра: завантаження, параметри, залежності", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tty-and-termios", title: "TTY і послідовний порт: модель termios", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "usb-in-linux", title: "USB у Linux: шина, класи, доступ із простору користувача", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "interrupts-bottom-halves", title: "Переривання, softirq і робочі черги", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dma-and-buffers", title: "DMA і відображення буферів у ядрі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ioctl-interface", title: "Керуючий канал до драйвера: ioctl", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "device-mapper", title: "Device mapper: блоковий пристрій, зібраний із шарів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dma-buf", title: "dma-buf: спільний буфер між драйверами", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dmabuf-sharing", title: "DMA-BUF: спільний буфер між підсистемами ядра", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "v4l2-video-devices", title: "V4L2: модель відеопристрою в ядрі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "block-device-model", title: "Блоковий пристрій: сектори, блоки й черга запитів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "random-devices", title: "Джерело випадковості в ядрі: /dev/random, /dev/urandom і getrandom", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "rcu-mechanism", title: "RCU: читання без замків і відкладене звільнення", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "boot-init", title: "Завантаження й служби", scope: "Шлях від увімкнення живлення до працюючої системи та як тримають служби.",
      topics: [
        { slug: "boot-chain", title: "Ланцюг завантаження: від прошивки до init", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "bootloader-and-cmdline", title: "Завантажувач і командний рядок ядра", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "initramfs", title: "initramfs: тимчасовий корінь", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "init-and-pid1", title: "Роль init і особливість PID 1", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "systemd-model", title: "systemd: юніти, залежності, цілі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "service-lifecycle", title: "Життєвий цикл служби й політика перезапуску", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "socket-activation", title: "Активація за сокетом", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "journald-logging", title: "journald: журнал як структуровані записи", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "suspend-and-resume", title: "Призупинення й пробудження: suspend, hibernate і стан пристроїв", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "shell", title: "Оболонка як модель", scope: "Оболонка не як набір команд, а як механізм складання процесів і потоків даних.",
      topics: [
        { slug: "shell-role", title: "Оболонка: що вона робить насправді", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "argv-and-environment", title: "argv, оточення й що успадковує дитина", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "standard-streams", title: "Три потоки: stdin, stdout, stderr", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "redirection-model", title: "Перенаправлення як робота з дескрипторами", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pipeline-composition", title: "Конвеєр: композиція процесів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "exit-status", title: "Код виходу як інтерфейс програми", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "expansion-and-quoting", title: "Розкриття й лапки: коли текст стає аргументами", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "job-control", title: "Керування завданнями й термінальні сигнали", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "session-environment", title: "Оточення сеансу: profile, rc і пошук у PATH", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "locale-and-collation", title: "Локаль: як мова змінює поведінку програм", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "networking", title: "Мережа в ядрі", scope: "Як Linux бачить мережу зсередини: від інтерфейсу до маршруту й фільтра.",
      topics: [
        { slug: "network-stack", title: "Мережевий стек у ядрі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "interfaces-and-addresses", title: "Інтерфейси, адреси й стан лінка", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "socket-api-linux", title: "Сокети в Linux: від дескриптора до з'єднання", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "routing-decision", title: "Таблиця маршрутів і рішення про маршрут", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "netfilter-model", title: "netfilter: ланцюги, таблиці й NAT", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "network-namespaces", title: "Мережеві простори імен, veth і мости", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "name-resolution-path", title: "Шлях розв'язання імені: NSS, resolv, systemd-resolved", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tun-tap", title: "TUN/TAP: віртуальні інтерфейси", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "netlink-protocol", title: "Обмін повідомленнями через netlink", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "linking", title: "Від файлу до процесу", scope: "Що відбувається між «є виконуваний файл» і «є працюючий процес».",
      topics: [
        { slug: "elf-structure", title: "ELF: сегменти, секції, точка входу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "static-and-dynamic-linking", title: "Статичне й динамічне лінкування", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dynamic-loader", title: "Динамічний завантажувач і його робота", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "soname-versioning", title: "SONAME і версіонування спільних бібліотек", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "library-search-order", title: "Порядок пошуку бібліотек: rpath, LD_LIBRARY_PATH, кеш", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "symbol-resolution", title: "Розв'язання символів і перекриття (interposition)", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "plt-and-got", title: "PLT і GOT: як працює виклик через межу бібліотеки", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "library-abi-compat", title: "Сумісність ABI бібліотеки й що її ламає", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "vdso", title: "vDSO: бібліотека від ядра в кожному процесі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "elf-tls", title: "TLS в ELF: як потік дістає власні глобальні змінні", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "auxiliary-vector", title: "Допоміжний вектор ELF: що ядро передає програмі на старті", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "position-independent-code", title: "Позиційно-незалежний код: PIC, PIE й ціна непрямості", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "observability", title: "Побачити, що відбувається", scope: "Механізми, якими система показує себе зсередини — і що з них можна дізнатися.",
      topics: [
        { slug: "proc-filesystem", title: "/proc: процеси як файли", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ptrace-model", title: "ptrace: на чому тримається трасування й налагодження", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "syscall-tracing", title: "Трасування системних викликів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "perf-events", title: "Підсистема perf: лічильники й вибірковий профіль", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ftrace-tracepoints", title: "ftrace і трасувальні точки ядра", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ebpf", title: "eBPF: власні програми всередині ядра", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "core-dump", title: "Аварійний дамп: як налаштувати й що з нього видно", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "load-and-pressure", title: "Середнє навантаження й тиск на ресурси (PSI)", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "kernel-oops-panic", title: "Oops і паніка: що система робить, коли падає саме ядро", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },

    { slug: "packaging", title: "Постачання програм", scope: "Як програма доходить до користувача і чому способів кілька.",
      topics: [
        { slug: "package-manager-model", title: "Модель пакетного менеджера", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "deb-and-rpm", title: "deb і rpm: два світи пакування", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "repositories-and-trust", title: "Репозиторії, підписи й довіра", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dependency-resolution", title: "Розв'язання залежностей і конфлікти версій", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "fhs-layout", title: "Ієрархія файлової системи: куди що кладуть", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "self-contained-bundles", title: "Самодостатні пакунки: AppImage, Flatpak, Snap", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "containers-vs-packages", title: "Контейнер проти пакунка", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "multilib-multiarch", title: "Multilib і multiarch: два комплекти бібліотек в одній ієрархії", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
  ]
});
