/* manifest — «Зв'язок» (тип "book"). Схема — AUTHORING.md §2. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "communications", title: "Зв'язок",
  sections: [
    { slug: "information-theory", title: "Теорія інформації", scope: "Математична межа стиснення й передачі: ентропія, пропускна здатність каналу, теореми Шеннона.",
      topics: [
        { slug: "bandwidth-capacity", title: "Смуга і межа Шеннона", status: "done", origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.4", math: [{ file: "math-shannon-capacity.md", status: "done" }] },
      ] },
    { slug: "coding-theory", title: "Кодування", scope: "Захист повідомлення від помилок і його компактне подання кодами джерела й каналу.",
      topics: [
        { slug: "parity-bit", title: "Біт парності", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.2", proj: [{ file: "proj-parity-in-code.md", status: "done" }] },
        { slug: "checksums", title: "Контрольні суми", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.3", math: [{ file: "math-checksum-arithmetic.md", status: "done" }], proj: [{ file: "proj-checksums-in-code.md", status: "done" }] },
        { slug: "crc", title: "CRC", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.4", comp: [{ file: "comp-hardware-crc.md", status: "done" }], math: [{ file: "math-gf2-polynomials.md", status: "done" }], proj: [{ file: "proj-crc-implementation.md", status: "done" }] },
        { slug: "hamming-distance", title: "Відстань Геммінга", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.5", hist: [{ file: "hist-hamming-1950.md", status: "done" }] },
        { slug: "hamming-code", title: "Код Геммінга", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.6", proj: [{ file: "proj-hamming-codec.md", status: "done" }] },
        { slug: "ecc-ram-flash", title: "ECC у пам'яті", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.7", comp: [{ file: "comp-ecc-hardware.md", status: "done" }] },
        { slug: "reed-solomon", title: "Рід–Соломон", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.8", hist: [{ file: "hist-voyager-codes.md", status: "done" }] },
        { slug: "data-reliability", title: "Надійність даних", status: "done", origin: "embedded/block-3-digital-processor/error-correction#3.9.9" },
      ] },
    { slug: "modulation", title: "Модуляція", scope: "Накладання інформації на несучу: амплітудні, частотні, фазові та квадратурні схеми.",
      topics: [
        { slug: "why-modulation", title: "Навіщо модуляція", status: "done", origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.1", hist: [{ file: "hist-armstrong.md", status: "done" }] },
        { slug: "am-fm", title: "AM і FM", status: "done", origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.2", proj: [{ file: "proj-am-fm-synthesis.md", status: "done" }] },
        { slug: "fsk-psk", title: "FSK і PSK", status: "done", origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.3", math: [{ file: "math-iq-plane.md", status: "done" }] },
        { slug: "spread-spectrum", title: "Розширений спектр", status: "done", origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.5", hist: [{ file: "hist-hedy-lamarr.md", status: "done" }] },
        { slug: "jamming-fhss", title: "Лінк під глушінням", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.9" },
        { slug: "analog-video", title: "Аналогове відео", status: "done", origin: "embedded/block-7-systems/video-signals-1#7.7.6" },
      ] },
    { slug: "signal-processing", title: "Обробка сигналів", scope: "Перетворення, фільтрація та виявлення сигналів у цифровій і аналоговій формі.",
      topics: [
        { slug: "nyquist-aliasing", title: "Найквіст і аліасинг", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.5", math: [{ file: "math-alias-folding.md", status: "done" }] },
        { slug: "signal-acquisition", title: "Зчитування сигналу", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.7", comp: [{ file: "comp-opamp-buffer.md", status: "done" }], math: [{ file: "math-sample-hold.md", status: "done" }] },
        { slug: "resolution-framerate", title: "Роздільність і кадри", status: "recheck", origin: "embedded/block-7-systems/video-signals-1#7.7.5" },
      ] },
    { slug: "propagation", title: "Поширення хвиль", scope: "Поведінка електромагнітних хвиль у середовищі: загасання, відбиття, завмирання, дальність.",
      topics: [
        { slug: "propagation-polarization", title: "Поширення й поляризація", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.3" },
        { slug: "frequency-bands", title: "Діапазони частот", status: "done", origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.4" },
        { slug: "power-decibels", title: "Потужність і децибели", status: "done", origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.5", hist: [{ file: "hist-decibel-origin.md", status: "done" }], math: [{ file: "math-log-decibel.md", status: "done" }] },
        { slug: "free-space-loss", title: "Загасання у просторі", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.6" },
        { slug: "link-budget", title: "Бюджет лінії", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.6" },
        { slug: "multipath-fading", title: "Багатопроменевість", status: "done", origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.7", math: [{ file: "math-rayleigh-fading.md", status: "done" }] },
        { slug: "ism-bands", title: "ISM-діапазони", status: "empty", origin: "embedded/block-6-comms-radio/antennas#6.8.8" },
      ] },
    { slug: "antennas", title: "Антени", scope: "Випромінювання й приймання хвиль: діаграми спрямованості, підсилення, апертури, решітки.",
      topics: [
        { slug: "esp32-antenna", title: "Антена ESP32", status: "done", origin: "components/comms/esp32-antenna/", comp: [{ file: "comp-ufl-connector.md", status: "done" }], math: [{ file: "math-friis-range.md", status: "done" }] },
        { slug: "antenna", title: "Антена", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/antennas#6.8.1", hist: [{ file: "hist-marconi.md", status: "done" }] },
        { slug: "resonance-dipole", title: "Резонанс і диполь", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/antennas#6.8.2" },
        { slug: "antenna-gain", title: "Підсилення антени", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/antennas#6.8.3" },
        { slug: "antenna-polarization", title: "Поляризація антени", status: "done", origin: "embedded/block-6-comms-radio/antennas#6.8.4", math: [{ file: "math-mismatch.md", status: "done" }] },
      ] },
    { slug: "radio-engineering", title: "Радіотехніка", scope: "Схемотехніка приймачів і передавачів: підсилювачі, змішувачі, гетеродини, синтезатори.",
      topics: [
        { slug: "rf-module", title: "Радіомодуль", status: "empty", origin: "components/comms/undefined" },
        { slug: "lora", title: "LoRa", status: "done", levels: ["basic"], origin: "components/comms/undefined" },
        { slug: "nfc-rfid", title: "NFC/RFID", status: "done", levels: ["basic"], origin: "components/comms/nfc-rfid/" },
        { slug: "esp32-module", title: "ESP32-модуль", status: "done", origin: "components/comms/wroom-module/" },
        { slug: "superheterodyne", title: "Супергетеродин", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/modulation-link-budget#6.7.9" },
        { slug: "transmission-lines", title: "Лінії передачі", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/antennas#6.8.5" },
        { slug: "vswr", title: "Відбиття і КСХ", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/antennas#6.8.6" },
        { slug: "telemetry-link", title: "Канал земля-борт", status: "empty", origin: "embedded/undefined#7.13.2" },
      ] },
    { slug: "photonics", title: "Фотоніка", scope: "Передача світлом по волокну й у вільному просторі: лазери, детектори, дисперсія, підсилювачі.",
      topics: [
        { slug: "optical-fiber", title: "Оптоволокно", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/radio-em-waves#6.6.7" },
        { slug: "fiber-in-network", title: "Оптоволокно в мережі", status: "empty", origin: "embedded/undefined#6.10.8" },
      ] },
    { slug: "networks", title: "Мережі", scope: "Топологія, комутація й маршрутизація потоків між вузлами в локальних і глобальних структурах.",
      topics: [
        { slug: "utp-cable", title: "UTP-кабель", status: "done", origin: "components/comms/utp-cable/" },
        { slug: "on-chip-radio", title: "Радіо на чіпі", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.1", hist: [{ file: "hist-bluetooth-name.md", status: "done" }] },
        { slug: "channel-band-packet", title: "Канал і пакет", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.2", proj: [{ file: "proj-listen-before-talk.md", status: "done" }] },
        { slug: "wifi", title: "Wi-Fi", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.3", hist: [{ file: "hist-wifi-name.md", status: "done" }, { file: "hist-csiro-ofdm.md", status: "done" }] },
        { slug: "bluetooth-spp", title: "Bluetooth SPP", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.5", proj: [{ file: "proj-command-parser.md", status: "done" }] },
        { slug: "esp-now", title: "ESP-NOW", status: "empty", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.8" },
        { slug: "latency-reliability", title: "Затримка й надійність", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.4" },
        { slug: "video-transmission", title: "Передача відео", status: "done", origin: "embedded/block-7-systems/video-signals-2#7.8.6" },
        { slug: "bandwidth-loss", title: "Пропускна й втрати", status: "done", origin: "embedded/block-7-systems/video-signals-2#7.8.7" },
        { slug: "ethernet-frame", title: "Кадр Ethernet", status: "empty", origin: "embedded/undefined#6.10.1" },
        { slug: "ethernet-link-phy", title: "Фізика лінка", status: "empty", origin: "embedded/undefined#6.10.2" },
        { slug: "mac-ip-arp", title: "MAC, IP і ARP", status: "done", levels: ["basic"], origin: "embedded/undefined#6.10.3" },
        { slug: "ip-routing", title: "Маршрутизація", status: "done", levels: ["basic"], origin: "embedded/undefined#6.10.4" },
        { slug: "dhcp-dns", title: "DHCP і DNS", status: "empty", origin: "embedded/undefined#6.10.5" },
        { slug: "nat", title: "NAT", status: "empty", origin: "embedded/undefined#6.10.6" },
      ] },
    { slug: "protocols", title: "Протоколи", scope: "Правила обміну й керування з'єднанням: стеки, рівні, контроль потоку й помилок.",
      topics: [
        { slug: "flow-control", title: "Керування потоком", status: "done", origin: "embedded/block-6-comms-radio/uart#6.1.5", proj: [{ file: "proj-ring-buffer.md", status: "done" }] },
        { slug: "packet-design", title: "Проєктування пакета", status: "done", origin: "embedded/block-6-comms-radio/uart#6.1.6", proj: [{ file: "proj-crc-table.md", status: "done" }] },
        { slug: "tcp-vs-udp", title: "TCP проти UDP", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.4" },
        { slug: "ble-gatt", title: "BLE GATT", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.6", proj: [{ file: "proj-cccd-notify.md", status: "done" }] },
        { slug: "reliable-link", title: "Надійний обмін", status: "done", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.7", proj: [{ file: "proj-stop-and-wait.md", status: "done" }] },
        { slug: "mqtt", title: "MQTT", status: "empty", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.10" },
        { slug: "control-telemetry", title: "Керування й телеметрія", status: "done", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.1", hist: [{ file: "hist-mavlink.md", status: "done" }] },
        { slug: "rc-link", title: "RC-лінк", status: "done", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.2", proj: [{ file: "proj-sbus-decode.md", status: "done" }] },
        { slug: "telemetry-stream", title: "Телеметрія", status: "done", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.3", comp: [{ file: "comp-telemetry-radio.md", status: "done" }] },
        { slug: "mavlink-packet", title: "Пакет MAVLink", status: "done", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.5" },
        { slug: "mavlink-message-dictionary", title: "Словник MAVLink", status: "empty", origin: "embedded/undefined#6.11.1" },
        { slug: "coordinate-frames-units", title: "Координати й одиниці", status: "empty", origin: "embedded/undefined#6.11.2" },
        { slug: "stream-rates", title: "Частоти потоків", status: "empty", origin: "embedded/undefined#6.11.3" },
        { slug: "param-protocol", title: "Протокол параметрів", status: "empty", origin: "embedded/undefined#6.11.4" },
        { slug: "mission-protocol", title: "Протокол місій", status: "empty", origin: "embedded/undefined#6.11.5" },
        { slug: "mavlink-commands", title: "Команди MAVLink", status: "done", levels: ["basic"], origin: "embedded/undefined#6.11.6" },
        { slug: "motion-control-setpoints", title: "Керування рухом", status: "empty", origin: "embedded/undefined#6.11.7" },
        { slug: "mavlink-pitfalls", title: "Граблі MAVLink", status: "empty", origin: "embedded/undefined#6.11.9" },
        { slug: "mavlink-from-ground", title: "MAVLink із землі", status: "done", levels: ["basic"], origin: "embedded/undefined#7.13.3" },
      ] },
    { slug: "multiple-access", title: "Множинний доступ", scope: "Спільне використання середовища багатьма абонентами через поділ ресурсу й арбітраж.",
      topics: [
        { slug: "clock-stretch-arbitration", title: "Розтягування й арбітраж", status: "done", origin: "embedded/block-6-comms-radio/i2c#6.2.6", comp: [{ file: "comp-clock-stretching-slave.md", status: "done" }] },
      ] },
    { slug: "synchronization", title: "Синхронізація", scope: "Узгодження часу, частоти й фази між передавачем і приймачем, відновлення тактів.",
      topics: [
        { slug: "gnss", title: "GNSS", status: "done", levels: ["basic"], origin: "components/comms/undefined" },
        { slug: "baud-rate", title: "Швидкість baud", status: "done", origin: "embedded/block-6-comms-radio/uart#6.1.3" },
        { slug: "measurement-time", title: "Час вимірювання", status: "empty", origin: "embedded/undefined#5.11.1" },
        { slug: "timestamps", title: "Мітки часу", status: "empty", origin: "embedded/undefined#5.11.2" },
        { slug: "sampling-jitter", title: "Джиттер вибірки", status: "empty", origin: "embedded/undefined#5.11.3" },
        { slug: "synchronous-multi-sensor-read", title: "Синхронне зчитування", status: "empty", origin: "embedded/undefined#5.11.4" },
        { slug: "pps-pulse", title: "PPS-імпульс", status: "empty", origin: "embedded/undefined#5.11.5" },
        { slug: "clock-offset-drift", title: "Дрейф годинників", status: "empty", origin: "embedded/undefined#5.11.6" },
        { slug: "sensor-latency-compensation", title: "Затримка давача", status: "empty", origin: "embedded/undefined#5.11.7" },
      ] },
    { slug: "cryptographic-comm", title: "Криптозв'язок", scope: "Захист конфіденційності, цілісності й автентичності переданих повідомлень.",
      topics: [
        { slug: "mavlink-security", title: "Безпека MAVLink", status: "empty", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.8" },
      ] },
    { slug: "buses", title: "Шини", scope: "Провідний обмін між пристроями на коротких відстанях: послідовні й паралельні інтерфейси.",
      topics: [
        { slug: "i2c-expander", title: "I²C-розширювач", status: "empty", origin: "components/interfaces/undefined" },
        { slug: "usb-c-connector", title: "USB-C конектор", status: "done", levels: ["basic", "detailed"], origin: "components/interfaces/usb-c-connector/" },
        { slug: "async-serial", title: "Асинхронна передача", status: "done", origin: "embedded/block-6-comms-radio/uart#6.1.1", hist: [{ file: "hist-baudot.md", status: "done" }] },
        { slug: "uart-frame", title: "Кадр UART", status: "done", origin: "embedded/block-6-comms-radio/uart#6.1.2", proj: [{ file: "proj-frame-in-code.md", status: "done" }] },
        { slug: "i2c-bus", title: "Шина I2C", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/i2c#6.2.1", hist: [{ file: "hist-i2c.md", status: "done" }] },
        { slug: "i2c-addressing", title: "Адресація I2C", status: "done", origin: "embedded/block-6-comms-radio/i2c#6.2.3", comp: [{ file: "comp-i2c-mux.md", status: "done" }] },
        { slug: "start-stop-ack", title: "Старт, стоп, ACK", status: "done", origin: "embedded/block-6-comms-radio/i2c#6.2.4", proj: [{ file: "proj-ack-handling.md", status: "done" }] },
        { slug: "i2c-transaction", title: "Транзакція I2C", status: "done", origin: "embedded/block-6-comms-radio/i2c#6.2.5" },
        { slug: "register-map", title: "Регістрова карта", status: "done", origin: "embedded/block-6-comms-radio/i2c#6.2.7", proj: [{ file: "proj-sensor-driver.md", status: "done" }] },
        { slug: "spi-bus", title: "Шина SPI", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/spi#6.3.1", hist: [{ file: "hist-spi.md", status: "done" }], proj: [{ file: "proj-spi-transfer.md", status: "done" }] },
        { slug: "spi-lines", title: "Лінії SPI", status: "done", origin: "embedded/block-6-comms-radio/spi#6.3.2", comp: [{ file: "comp-tri-state-buffer.md", status: "done" }] },
        { slug: "cpol-cpha", title: "Режими CPOL/CPHA", status: "done", origin: "embedded/block-6-comms-radio/spi#6.3.3", hist: [{ file: "hist-motorola-spi.md", status: "done" }] },
        { slug: "chip-select", title: "Вибір кристала", status: "done", origin: "embedded/block-6-comms-radio/spi#6.3.4" },
        { slug: "spi-speed", title: "Швидкість SPI", status: "done", origin: "embedded/block-6-comms-radio/spi#6.3.5" },
        { slug: "spi-vs-i2c", title: "SPI проти I2C", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/spi#6.3.6", proj: [{ file: "proj-bus-abstraction.md", status: "done" }] },
        { slug: "single-ended-line-limits", title: "Межі односторонніх ліній", status: "empty", origin: "embedded/undefined#6.4.1" },
        { slug: "differential-pair", title: "Диференційна пара", status: "done", levels: ["basic"], origin: "embedded/undefined#6.4.2" },
        { slug: "rs-485", title: "RS-485", status: "done", levels: ["basic"], origin: "embedded/undefined#6.4.3" },
        { slug: "can-arbitration", title: "Арбітраж CAN", status: "empty", origin: "embedded/undefined#6.4.4" },
        { slug: "can-frame-errors", title: "Кадр CAN", status: "empty", origin: "embedded/undefined#6.4.5" },
        { slug: "dronecan", title: "DroneCAN", status: "empty", origin: "embedded/undefined#6.4.6" },
        { slug: "usb-ethernet-differential", title: "USB та Ethernet пари", status: "done", levels: ["basic"], origin: "embedded/undefined#6.4.7" },
        { slug: "bus-resource-conflicts", title: "Конфлікти шин", status: "empty", origin: "embedded/undefined#6.12.5" },
      ] },
  ]
});
