/* manifest — «Зв'язок» (тип "book"). Схема — AUTHORING.md §2 (v6). */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "communications", title: "Зв'язок",
  sections: [
    { slug: "information-theory", title: "Теорія інформації", scope: "Математична межа стиснення й передачі: ентропія, пропускна здатність каналу, теореми Шеннона.",
      topics: [
        { slug: "bandwidth-capacity", title: "Смуга і межа Шеннона", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-shannon-capacity.md", status: "done" }] },
        { slug: "shannon-entropy", title: "Ентропія Шеннона", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-entropy-name.md", status: "done" }], math: [{ file: "math-entropy-axioms.md", status: "done" }] },
        { slug: "channel-coding-theorem", title: "Теорема Шеннона про кодування каналу", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-approaching-the-limit.md", status: "done" }], math: [{ file: "math-random-coding.md", status: "done" }], proj: [{ file: "proj-simulate-threshold.md", status: "done" }] },
        { slug: "awgn-channel", title: "Канал AWGN", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-johnson-nyquist.md", status: "done" }], math: [{ file: "math-gaussian-noise.md", status: "done" }], proj: [{ file: "proj-awgn-simulation.md", status: "done" }] },
        { slug: "mutual-information", title: "Взаємна інформація", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-naming.md", status: "done" }], math: [{ file: "math-mi-identities.md", status: "done" }], proj: [{ file: "proj-estimate-mutual-information.md", status: "done" }] },
        { slug: "binary-symmetric-channel", title: "Двійковий симетричний канал", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-capacity-derivation.md", status: "done" }], proj: [{ file: "proj-bsc-simulation.md", status: "done" }] },
        { slug: "conditional-entropy", title: "Умовна ентропія", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-equivocation.md", status: "done" }], math: [{ file: "math-chain-rule.md", status: "done" }] },
        { slug: "erasure-channel", title: "Канал зі стиранням", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-elias-erasure.md", status: "done" }], proj: [{ file: "proj-erasure-recovery.md", status: "done" }] },
        { slug: "binary-erasure-channel", title: "Двійковий канал зі стиранням", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-elias-erasure.md", status: "done" }], math: [{ file: "math-capacity-erasure.md", status: "done" }] },
        { slug: "log-likelihood-ratio", title: "Логарифм відношення правдоподібностей (LLR)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-likelihood-ratio.md", status: "done" }] },
      ] },
    { slug: "coding-theory", title: "Кодування", scope: "Захист повідомлення від помилок і його компактне подання кодами джерела й каналу.",
      topics: [
        { slug: "parity-bit", title: "Біт парності", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-parity-in-code.md", status: "done" }] },
        { slug: "checksums", title: "Контрольні суми", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-checksum-arithmetic.md", status: "done" }], proj: [{ file: "proj-checksums-in-code.md", status: "done" }] },
        { slug: "crc", title: "CRC", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-hardware-crc.md", status: "done" }], math: [{ file: "math-gf2-polynomials.md", status: "done" }], proj: [{ file: "proj-crc-implementation.md", status: "done" }] },
        { slug: "hamming-distance", title: "Відстань Геммінга", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hamming-1950.md", status: "done" }] },
        { slug: "hamming-code", title: "Код Геммінга", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-hamming-codec.md", status: "done" }] },
        { slug: "ecc-ram-flash", title: "ECC у пам'яті", basic: { status: "done" }, detailed: { status: "done" }, comp: [{ file: "comp-ecc-hardware.md", status: "done" }] },
        { slug: "reed-solomon", title: "Рід–Соломон", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-voyager-codes.md", status: "done" }] },
        { slug: "internet-checksum", title: "Інтернет-контрольна сума (IP/TCP/UDP)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-internet-checksum.md", status: "done" }], math: [{ file: "math-incremental-update.md", status: "done" }], proj: [{ file: "proj-tcp-udp-checksum.md", status: "done" }] },
        { slug: "adler-32", title: "Adler-32", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-adler-zlib.md", status: "done" }], proj: [{ file: "proj-adler32-in-code.md", status: "done" }] },
        { slug: "concatenated-codes", title: "Конкатеновані коди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-forney-concatenation.md", status: "done" }], math: [{ file: "math-concatenation-params.md", status: "done" }], proj: [{ file: "proj-concatenated-pipeline.md", status: "done" }] },
        { slug: "memory-scrubbing", title: "Memory scrubbing: фоновий ремонт пам'яті", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-scrub-race.md", status: "done" }], proj: [{ file: "proj-scrub-loop.md", status: "done" }] },
        { slug: "ldpc", title: "LDPC: код розрідженої перевірки паритету", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-gallager.md", status: "done" }], math: [{ file: "math-belief-propagation.md", status: "done" }], proj: [{ file: "proj-bit-flipping-decoder.md", status: "done" }] },
        { slug: "flash-wear-leveling", title: "Wear leveling у Flash-пам'яті", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-uber-rber.md", status: "done" }], proj: [{ file: "proj-device-uber.md", status: "done" }] },
        { slug: "secded", title: "SECDED: виправити один біт, виявити два", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hsiao-code.md", status: "done" }], math: [{ file: "math-secded-distance.md", status: "done" }], proj: [{ file: "proj-secded-codec.md", status: "done" }] },
        { slug: "perfect-codes", title: "Досконалі коди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-golay-codes.md", status: "done" }], math: [{ file: "math-sphere-packing-bound.md", status: "done" }], proj: [{ file: "proj-perfect-code-check.md", status: "done" }] },
        { slug: "linear-block-codes", title: "Лінійні блокові коди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-slepian-group-codes.md", status: "done" }], proj: [{ file: "proj-linear-codec.md", status: "done" }] },
        { slug: "2d-parity", title: "Двовимірна парність", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-tape-vrc-lrc.md", status: "done" }], proj: [{ file: "proj-2d-parity.md", status: "done" }] },
        { slug: "burst-error", title: "Пакетна помилка (burst error)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fire-code.md", status: "done" }], math: [{ file: "math-reiger-bound.md", status: "done" }], proj: [{ file: "proj-burst-simulation.md", status: "done" }] },
        { slug: "convolutional-codes", title: "Згорткові коди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-elias-viterbi.md", status: "done" }], math: [{ file: "math-generator-polynomials.md", status: "done" }], proj: [{ file: "proj-viterbi-decoder.md", status: "done" }] },
        { slug: "bch-codes", title: "Коди BCH", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bch-origins.md", status: "done" }], math: [{ file: "math-bch-bound.md", status: "done" }], proj: [{ file: "proj-bch-codec.md", status: "done" }] },
        { slug: "interleaving", title: "Перемішування (interleaving)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-interleaving-birth.md", status: "done" }], math: [{ file: "math-interleaving-depth.md", status: "done" }], proj: [{ file: "proj-interleaver-code.md", status: "done" }] },
        { slug: "linear-codes", title: "Лінійні коди", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-subspace-duality.md", status: "done" }] },
        { slug: "ber-snr-curve", title: "BER і SNR: крива надійності каналу", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-q-function-ber.md", status: "done" }], proj: [{ file: "proj-ber-monte-carlo.md", status: "done" }] },
        { slug: "gilbert-elliott-model", title: "Модель Гілберта–Елліота: пакетні помилки", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-gilbert-elliott.md", status: "done" }], math: [{ file: "math-burst-statistics.md", status: "done" }], proj: [{ file: "proj-channel-simulator.md", status: "done" }] },
        { slug: "fec-channel-coding", title: "FEC для потокового відео", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fountain-codes.md", status: "done" }], math: [{ file: "math-fec-overhead.md", status: "done" }], proj: [{ file: "proj-packet-fec.md", status: "done" }] },
        { slug: "ecc-flash", title: "ECC у флеш-пам'яті", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-code-escalation.md", status: "done" }], math: [{ file: "math-vth-overlap.md", status: "done" }], proj: [{ file: "proj-soft-read.md", status: "done" }] },
        { slug: "turbo-codes", title: "Турбокоди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-turbo-birth.md", status: "done" }], math: [{ file: "math-iterative-decoding.md", status: "done" }], proj: [{ file: "proj-turbo-decoder.md", status: "done" }] },
        { slug: "polar-codes", title: "Полярні коди", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-arikan.md", status: "done" }], math: [{ file: "math-channel-polarization.md", status: "done" }], proj: [{ file: "proj-successive-cancellation.md", status: "done" }] },
        { slug: "golay-code", title: "Коди Голея", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-golay-construction.md", status: "done" }], proj: [{ file: "proj-golay-codec.md", status: "done" }] },
        { slug: "reed-muller-code", title: "Коди Ріда–Маллера", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-mars-mariner.md", status: "done" }], math: [{ file: "math-plotkin-recursion.md", status: "done" }], proj: [{ file: "proj-majority-decoder.md", status: "done" }] },
        { slug: "cyclic-codes", title: "Циклічні коди", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-prange.md", status: "done" }], math: [{ file: "math-generator-polynomial.md", status: "done" }], proj: [{ file: "proj-cyclic-codec.md", status: "done" }] },
        { slug: "fountain-codes", title: "Фонтанні коди", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-digital-fountain.md", status: "done" }], math: [{ file: "math-soliton-distribution.md", status: "done" }], proj: [{ file: "proj-lt-codec.md", status: "done" }] },
        { slug: "viterbi-algorithm", title: "Алгоритм Вітербі", basic: { status: "pending" }, detailed: { status: "done" }, math: [{ file: "math-branch-metric.md", status: "done" }], proj: [{ file: "proj-hmm-viterbi.md", status: "done" }] },
        { slug: "viterbi-decoder", title: "Декодер Вітербі", basic: { status: "pending" }, detailed: { status: "done" }, math: [{ file: "math-ml-metric.md", status: "done" }], proj: [{ file: "proj-survivor-memory.md", status: "done" }] },
        { slug: "product-codes", title: "Добуткові коди", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "punctured-codes", title: "Виколоті коди (puncturing)", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "modulation", title: "Модуляція", scope: "Накладання інформації на несучу: амплітудні, частотні, фазові та квадратурні схеми.",
      topics: [
        { slug: "why-modulation", title: "Навіщо модуляція", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-armstrong.md", status: "done" }] },
        { slug: "am-fm", title: "AM і FM", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-am-fm-synthesis.md", status: "done" }] },
        { slug: "fsk-psk", title: "FSK і PSK", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-iq-plane.md", status: "done" }] },
        { slug: "spread-spectrum", title: "Розширений спектр", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hedy-lamarr.md", status: "done" }] },
        { slug: "analog-video", title: "Аналогове відео", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "ofdm", title: "OFDM: мультиплексування з ортогональними піднесними", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-ofdm-birth.md", status: "done" }], math: [{ file: "math-orthogonality-ifft.md", status: "done" }], proj: [{ file: "proj-ofdm-modem.md", status: "done" }] },
        { slug: "ssb-modulation", title: "Односмугова модуляція (SSB)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-ssb-birth.md", status: "done" }], math: [{ file: "math-phasing-cancellation.md", status: "done" }] },
        { slug: "fm-capture-effect", title: "Ефект захоплення FM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cvbs-signal", title: "Композитний відеосигнал CVBS: рівні, тайминг, IRE", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "interlacing", title: "Черезрядкова розгортка (interlacing): поля, зубчастий vsync, twitter", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "osd-overlay", title: "OSD-накладання телеметрії на аналоговий відеосигнал", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pal-ntsc-color", title: "PAL і NTSC: колірна квадратура і фазовий маятник", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "adaptive-modulation", title: "Адаптивна модуляція і кодування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "partial-band-jamming", title: "Типи завад і протидія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fhss-sync", title: "Синхронізація в FHSS-лінку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "baseband-passband", title: "База й смугова область", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "iq-representation", title: "IQ-подання сигналу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "carson-rule", title: "Правило Карсона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "chirp-coding", title: "Чирп і кодований сигнал", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rs422-rs485", title: "RS-422 і RS-485: диференційний послідовний зв'язок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "carrier-ir-modulation", title: "Модуляція несучої для відсіву перешкод (38 кГц як у ІЧ-пультах)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "qam", title: "Квадратурна амплітудна модуляція (QAM)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dsb-sc", title: "Двосмугова модуляція з придушеною несучою (DSB-SC)", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "signal-processing", title: "Обробка сигналів", scope: "Перетворення, фільтрація та виявлення сигналів у цифровій і аналоговій формі.",
      topics: [
        { slug: "nyquist-aliasing", title: "Найквіст і аліасинг", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-alias-folding.md", status: "done" }] },
        { slug: "resolution-framerate", title: "Роздільність і кадри", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "pn-sequences", title: "PN-послідовності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rake-receiver", title: "RAKE-приймач", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sampling-reconstruction", title: "Відновлення сигналу з відліків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "oversampling-decimation", title: "Передискретизування і децимація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "chroma-subsampling", title: "Колірне субдискретування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "color-spaces-video", title: "Колірні простори у відео", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "generation-loss", title: "Втрата поколінь: накопичення похибки при копіюванні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ycbcr", title: "Колірний простір YCbCr", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bandwidth", title: "Смуга пропускання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "h264-hardware-codec", title: "Апаратний кодек H.264", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "decimation", title: "Проріджування (decimation): фільтр і зниження частоти відліків", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-multirate-birth.md", status: "done" }], math: [{ file: "math-decimation-spectrum.md", status: "done" }], proj: [{ file: "proj-decimator-c.md", status: "done" }] },
        { slug: "sensor-fusion", title: "Сенсорне злиття (fusion): комплементарний фільтр і Калман", basic: { status: "pending" }, detailed: { status: "done" }, math: [{ file: "math-gaussian-fusion.md", status: "done" }], proj: [{ file: "proj-fusion-compare-c.md", status: "done" }] },
        { slug: "analytic-signal", title: "Аналітичний сигнал і перетворення Гільберта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "interpolation-upsampling", title: "Інтерполяція (upsampling): вставлення нулів і згладжувальний фільтр", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "channel-equalization", title: "Вирівнювання каналу: zero-forcing і MMSE", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "media-container", title: "Медіаконтейнер: як стиснені кадри складають у файл", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "propagation", title: "Поширення хвиль", scope: "Поведінка електромагнітних хвиль у середовищі: загасання, відбиття, завмирання, дальність.",
      topics: [
        { slug: "propagation-polarization", title: "Поширення й поляризація", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "frequency-bands", title: "Діапазони частот", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "power-decibels", title: "Потужність і децибели", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-decibel-origin.md", status: "done" }], math: [{ file: "math-log-decibel.md", status: "done" }] },
        { slug: "free-space-loss", title: "Загасання у просторі", basic: { status: "done" }, detailed: { status: "done" }, math: [{ file: "math-fspl-derivation.md", status: "done" }] },
        { slug: "multipath-fading", title: "Багатопроменевість", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-rayleigh-fading.md", status: "done" }] },
        { slug: "ism-bands", title: "ISM-діапазони", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "friis-transmission", title: "Рівняння Фріїса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ionospheric-propagation", title: "Іоносферне поширення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "atmospheric-absorption", title: "Атмосферне поглинання хвиль", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "noise-figure", title: "Коефіцієнт шуму й шумова температура", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fresnel-zones", title: "Зони Френеля й умова вільного простору", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fading-statistics", title: "Статистика завмирань: Релей, Раєна, Накагамі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "delay-spread", title: "Delay spread і когерентна смуга", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "db-reference-variants", title: "Варіанти децибельних одиниць (dBW, dBc, dBFS, dBu…)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rssi-signal-strength", title: "RSSI і вимірювання рівня сигналу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "link-quality-metrics", title: "Метрики якості лінку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "velocity-factor", title: "Коефіцієнт укорочення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "link-budget", title: "Бюджет лінку", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "antennas", title: "Антени", scope: "Випромінювання й приймання хвиль: діаграми спрямованості, підсилення, апертури, решітки.",
      topics: [
        { slug: "antenna", title: "Антена", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-marconi.md", status: "done" }] },
        { slug: "resonance-dipole", title: "Резонанс і диполь", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "antenna-gain", title: "Підсилення антени", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "antenna-polarization", title: "Поляризація антени", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-mismatch.md", status: "done" }] },
        { slug: "radiation-pattern-3d", title: "Тривимірна діаграма спрямованості", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "directivity", title: "Спрямованість антени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "effective-aperture", title: "Ефективна апертура антени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "parabolic-antenna", title: "Параболічна антена", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "yagi-uda-antenna", title: "Антена Яґі-Уда", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "helix-antenna", title: "Спіральна антена", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "polarization-diversity", title: "Поляризаційне різноманіття", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "antenna-impedance-matching", title: "Узгодження імпедансу антени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "antenna-feed", title: "Живлення антен: балун, гама-узгоджувач, узгодження імпедансів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "loading-coil", title: "Завантажувальна котушка: укорочення антени індуктивністю", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "radiation-resistance", title: "Опір випромінювання антени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "circular-polarization", title: "Кругова та еліптична поляризація", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "radio-engineering", title: "Радіотехніка", scope: "Схемотехніка приймачів і передавачів: підсилювачі, змішувачі, гетеродини, синтезатори.",
      topics: [
        { slug: "rf-module", title: "Радіомодуль", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rf-amplifiers", title: "Радіочастотні підсилювачі (LNA і PA)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mixer", title: "Змішувач частот", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "local-oscillator", title: "Гетеродин", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lora", title: "LoRa", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "superheterodyne", title: "Супергетеродин", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "transmission-lines", title: "Лінії передачі", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "vswr", title: "Відбиття і КСХ", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "telemetry-link", title: "Канал земля-борт", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-rf-frontend.md", status: "done" }] },
        { slug: "emc-certification", title: "Модульна сертифікація: FCC, CE та EMC-випроби", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-spectrum-order.md", status: "done" }] },
        { slug: "nfc-protocols", title: "Протоколи NFC: ISO 14443, NDEF і режими роботи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rfid-security", title: "Безпека NFC/RFID: атаки та захист", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "double-conversion", title: "Подвійне перетворення частоти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "zero-if-receiver", title: "Zero-IF та Low-IF архітектури", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "frequency-synthesizer", title: "Синтезатор частоти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "impedance-matching-networks", title: "Мережі узгодження імпедансу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "smith-chart", title: "Діаграма Сміта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tdr", title: "Рефлектометрія у часовій області (TDR)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "return-loss", title: "Зворотні втрати (return loss)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "balun", title: "Балун", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "time-on-air", title: "Час у ефірі (time on air)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "reflection-coefficient", title: "Коефіцієнт відбиття", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "elrs-architecture", title: "Архітектура ExpressLRS", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-elrs-origin.md", status: "done" }] },
        { slug: "wifi-6-basics", title: "Wi-Fi 6: ключові ідеї", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "photonics", title: "Фотоніка", scope: "Передача світлом по волокну й у вільному просторі: лазери, детектори, дисперсія, підсилювачі.",
      topics: [
        { slug: "optical-fiber", title: "Оптоволокно", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "fiber-in-network", title: "Оптоволокно в мережі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wdm", title: "Хвильове мультиплексування (WDM/DWDM)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "optical-amplifier", title: "Оптичний підсилювач (EDFA)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "chromatic-dispersion", title: "Хроматична дисперсія у волокні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fiber-splicing", title: "Зрощення та конектори оптоволокна", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "networks", title: "Мережі", scope: "Топологія, комутація й маршрутизація потоків між вузлами в локальних і глобальних структурах.",
      topics: [
        { slug: "utp-cable", title: "UTP-кабель", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "on-chip-radio", title: "Радіо на чіпі", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bluetooth-name.md", status: "done" }] },
        { slug: "channel-band-packet", title: "Канал і пакет", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-listen-before-talk.md", status: "done" }] },
        { slug: "wifi", title: "Wi-Fi", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-wifi-name.md", status: "done" }, { file: "hist-csiro-ofdm.md", status: "done" }] },
        { slug: "bluetooth-spp", title: "Bluetooth SPP", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-command-parser.md", status: "done" }] },
        { slug: "esp-now", title: "ESP-NOW", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "latency-reliability", title: "Затримка й надійність", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "video-transmission", title: "Передача відео", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "bandwidth-loss", title: "Пропускна й втрати", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "ethernet-frame", title: "Кадр Ethernet", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ethernet-link-phy", title: "Фізика лінка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mac-ip-arp", title: "MAC, IP і ARP", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "ip-routing", title: "Маршрутизація", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "dhcp-dns", title: "DHCP і DNS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nat", title: "NAT", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "shannon-capacity", title: "Ємність каналу за Шенноном", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fec-codes", title: "Коди виправлення помилок (FEC)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "queue-theory-networks", title: "Черги в мережах: затримка і втрати", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gilbert-elliott-channel", title: "Модель каналу Гілберта–Елліота", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bluetooth-classic-stack", title: "Стек Bluetooth Classic", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bt-pairing-security", title: "Безпека спарювання Bluetooth", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rfcomm", title: "RFCOMM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "guard-band-duplexing", title: "Захисні смуги і дуплекс", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cidr", title: "CIDR і префікси", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ospf", title: "OSPF: протокол стану каналів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bgp", title: "BGP: протокол між провайдерами", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ipv6-routing", title: "Маршрутизація IPv6", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "jitter", title: "Джитер: варіація затримки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "arp-security", title: "Безпека ARP", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "subnet-addressing", title: "Адресація підмереж", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "csma-ca", title: "CSMA/CA: уникнення колізій у спільному ефірі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "csma-cd", title: "CSMA/CD: колізії у спільному дроті Ethernet", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "poe", title: "PoE — живлення по витій парі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mdi-mdix", title: "MDI/MDI-X і авто-погодження", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "adaptive-bitrate", title: "Адаптивний бітрейт (ABR)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wpa-security", title: "WPA2 і WPA3: захист бездротового ефіру", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dhcp", title: "DHCP: динамічне призначення IP-адрес", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "auto-negotiation", title: "Автопогодження Ethernet", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "anycast", title: "Anycast і глобальне балансування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ip-fragmentation-mtu", title: "MTU і фрагментація IP", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "source-specific-multicast", title: "Фільтрація за джерелом: IGMPv3, MLDv2 і SSM", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mtu-and-fragmentation", title: "MTU й фрагментація IP", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "middleboxes", title: "Проміжні коробки (middlebox): фаєрволи, проксі, кеші, транслятори на шляху пакета", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "circuit-vs-packet-switching", title: "Комутація каналів проти комутації пакетів", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "protocols", title: "Протоколи", scope: "Правила обміну й керування з'єднанням: стеки, рівні, контроль потоку й помилок.",
      topics: [
        { slug: "flow-control", title: "Керування потоком", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ring-buffer.md", status: "done" }] },
        { slug: "packet-design", title: "Проєктування пакета", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-crc-table.md", status: "done" }] },
        { slug: "tcp-vs-udp", title: "TCP проти UDP", basic: { status: "done" }, detailed: { status: "done" }, api: [{ file: "api-headers.md", status: "done" }, { file: "api-sockets.md", status: "done" }] },
        { slug: "ble-gatt", title: "BLE GATT", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-cccd-notify.md", status: "done" }] },
        { slug: "reliable-link", title: "Надійний обмін", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-stop-and-wait.md", status: "done" }] },
        { slug: "mqtt", title: "MQTT", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "control-telemetry", title: "Керування й телеметрія", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-mavlink.md", status: "done" }] },
        { slug: "rc-link", title: "RC-лінк", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-sbus-decode.md", status: "done" }] },
        { slug: "telemetry-stream", title: "Телеметрія", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-telemetry-radio.md", status: "done" }] },
        { slug: "mavlink-packet", title: "Пакет MAVLink", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "mavlink-message-dictionary", title: "Словник MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "coordinate-frames-units", title: "Координати й одиниці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "stream-rates", title: "Частоти потоків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "param-protocol", title: "Протокол параметрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mission-protocol", title: "Протокол місій", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-commands", title: "Команди MAVLink", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "motion-control-setpoints", title: "Керування рухом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-pitfalls", title: "Граблі MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "arq-protocol", title: "ARQ: автоматичний повтор запиту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ble-gap", title: "BLE GAP", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ble-att", title: "ATT-протокол BLE", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ble-security", title: "Безпека й спарювання BLE", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ble-beacon-formats", title: "Формати BLE-маячків", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-mission-protocol", title: "Протокол місій MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-parameters", title: "Параметри MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-v2-signing", title: "MAVLink v2 і підпис", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gcs-failsafe", title: "Failsafe на стороні GCS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sequence-numbering", title: "Нумерація послідовності пакетів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "crsf-protocol", title: "Протокол CRSF", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-crsf-origin.md", status: "done" }], proj: [{ file: "proj-crsf-parser.md", status: "done" }] },
        { slug: "rc-failsafe-modes", title: "Режими failsafe RC", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-failsafe-origin.md", status: "done" }] },
        { slug: "sliding-window-arq", title: "ARQ зі ковзним вікном", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quic-protocol", title: "QUIC та HTTP/3", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nat-traversal", title: "NAT-траверсаль", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lorawan", title: "LoRaWAN", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rc-signal-protocol", title: "RC-сигнал: PWM, PPM і S.BUS", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-sbus-frame-parser.md", status: "done" }] },
        { slug: "slip-protocol", title: "Протокол SLIP: кадрування послідовного потоку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ble-link-layer", title: "BLE Link Layer: канальний стрибок і connection events", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "thread-mesh", title: "Thread: IPv6-mesh для IoT", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-mission-items", title: "MAVLink: місія й команди польоту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ntp-sync", title: "NTP: мережевий протокол синхронізації часу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cobs-framing", title: "Кадрування COBS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-dialect", title: "Діалекти MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "regulatory-radio-certification", title: "Радіосертифікація: FCC, CE, SRRC", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rtp-rtcp", title: "RTP і RTCP: транспорт медіа поверх UDP", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "rtsp-sdp", title: "RTSP і SDP: керування сеансом потокового відео", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-xml-codegen", title: "Генерація коду з XML-опису MAVLink", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-camera-gimbal", title: "Протоколи камери й підвісу MAVLink", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-ftp", title: "MAVFTP: передача файлів поверх MAVLink", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-high-latency", title: "Протокол великої затримки MAVLink", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-heartbeat", title: "HEARTBEAT: як апарат оголошує себе", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-capabilities", title: "Можливості апарата: бітова маска AUTOPILOT_VERSION", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-terrain-protocol", title: "Протокол рельєфу MAVLink: TERRAIN_REQUEST, TERRAIN_DATA, TERRAIN_REPORT", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mpeg-ts", title: "MPEG-TS: транспортний потік як обгортка для ефіру", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mavlink-events-protocol", title: "Протокол подій MAVLink: подія як ідентифікатор", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "flight-log-formats", title: "Формати бортових логів: ULog і DataFlash", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "multiple-access", title: "Множинний доступ", scope: "Спільне використання середовища багатьма абонентами через поділ ресурсу й арбітраж.",
      topics: [
        { slug: "clock-stretch-arbitration", title: "Розтягування й арбітраж", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-clock-stretching-slave.md", status: "done" }] },
        { slug: "cdma", title: "CDMA: код як адреса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mimo", title: "MIMO", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ofdma", title: "OFDMA: множинний доступ на ортогональних піднесних", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "synchronization", title: "Синхронізація", scope: "Узгодження часу, частоти й фази між передавачем і приймачем, відновлення тактів.",
      topics: [
        { slug: "gnss", title: "GNSS", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "baud-rate", title: "Швидкість baud", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "measurement-time", title: "Час вимірювання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "timestamps", title: "Мітки часу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sampling-jitter", title: "Джиттер вибірки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "synchronous-multi-sensor-read", title: "Синхронне зчитування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pps-pulse", title: "PPS-імпульс", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-pps-origins.md", status: "done" }], proj: [{ file: "proj-pps-input-capture.md", status: "done" }] },
        { slug: "clock-offset-drift", title: "Дрейф годинників", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sensor-latency-compensation", title: "Затримка давача", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fractional-baud", title: "Дробовий дільник baud", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "uart-oversampling", title: "Передискретизація UART", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sbas-corrections", title: "Супутникові системи доповнення (SBAS)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-sbas-origins.md", status: "done" }] },
        { slug: "leap-second", title: "Високосна секунда", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "ptp-1588", title: "PTP (IEEE 1588): точна синхронізація часу в мережі", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "cryptographic-comm", title: "Криптозв'язок", scope: "Захист конфіденційності, цілісності й автентичності переданих повідомлень.",
      topics: [
        { slug: "mavlink-security", title: "Безпека MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "public-key-crypto", title: "Криптографія з відкритим ключем: ключі, підпис, ланцюг сертифікатів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tls", title: "TLS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hmac", title: "HMAC і коди автентичності повідомлень", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "buses", title: "Шини", scope: "Провідний обмін між пристроями на коротких відстанях: послідовні й паралельні інтерфейси.",
      topics: [
        { slug: "i2c-expander", title: "I²C-розширювач", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-c-connector", title: "USB-C конектор", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "async-serial", title: "Асинхронна передача", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-baudot.md", status: "done" }] },
        { slug: "uart-frame", title: "Кадр UART", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-frame-in-code.md", status: "done" }] },
        { slug: "i2c-bus", title: "Шина I2C", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-i2c.md", status: "done" }] },
        { slug: "i2c-addressing", title: "Адресація I2C", basic: { status: "empty" }, detailed: { status: "done" }, api: [{ file: "api-i2c-mux.md", status: "done" }], proj: [{ file: "proj-i2c-mux-scan.md", status: "done" }] },
        { slug: "start-stop-ack", title: "Старт, стоп, ACK", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ack-handling.md", status: "done" }] },
        { slug: "i2c-transaction", title: "Транзакція I2C", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "register-map", title: "Регістрова карта", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-sensor-driver.md", status: "done" }] },
        { slug: "spi-bus", title: "Шина SPI", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-spi.md", status: "done" }], proj: [{ file: "proj-spi-transfer.md", status: "done" }] },
        { slug: "spi-lines", title: "Лінії SPI", basic: { status: "empty" }, detailed: { status: "done" }, comp: [{ file: "comp-tri-state-buffer.md", status: "done" }] },
        { slug: "cpol-cpha", title: "Режими CPOL/CPHA", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-motorola-spi.md", status: "done" }] },
        { slug: "chip-select", title: "Вибір кристала", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "spi-speed", title: "Швидкість SPI", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "single-ended-line-limits", title: "Межі односторонніх ліній", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "differential-pair", title: "Диференційна пара", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "rs-485", title: "RS-485", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "can-arbitration", title: "Арбітраж CAN", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-can-bosch.md", status: "done" }] },
        { slug: "can-frame-errors", title: "Кадр CAN", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dronecan", title: "DroneCAN", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-uavcan-split.md", status: "done" }] },
        { slug: "usb-ethernet-differential", title: "USB та Ethernet пари", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "bus-resource-conflicts", title: "Конфлікти шин", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "baud-vs-bitrate", title: "Baud проти біт/с", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "clock-tolerance-uart", title: "Допуск годинника UART", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "break-signal-uart", title: "Break-сигнал UART", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "half-duplex-uart", title: "Напівдуплекс UART", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spi-cs-timing", title: "Часові параметри CS у SPI", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spi-timing", title: "Тайминг SPI: t_su, t_h, t_clk", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spi-multimaster", title: "SPI з кількома веденими і режимами", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "termination", title: "Термінування ліній передачі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "eye-diagram", title: "Eye-діаграма", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lvds", title: "LVDS — низьковольтна диференційна сигналізація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2c-multimaster", title: "Кілька ведучих на I2C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2c-10bit-addressing", title: "10-бітна адресація I2C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2c-speeds", title: "Режими швидкості I2C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "smbus-protocol", title: "Протокол SMBus", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "burst-read", title: "Пакетне зчитування регістрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "drdy-pattern", title: "Шаблон DRDY і переривання давача", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fifo-register", title: "FIFO-регістри в давачах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "modbus", title: "Modbus", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rs-422", title: "RS-422", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spi-modes", title: "Режими SPI (CPOL/CPHA)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "daisy-chain-spi", title: "Daisy-chain у SPI", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "qspi-multi-lane", title: "QSPI та багатолінійний SPI", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "clock-stretching", title: "Clock stretching у I2C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2c-clock-stretching", title: "Розтягування такту I2C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "smbus", title: "SMBus", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2s-bus", title: "Шина I2S", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-i2s.md", status: "done" }], proj: [{ file: "proj-i2s-transmit.md", status: "done" }] },
        { slug: "mdi-mdio-bus", title: "Шина MDC/MDIO", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sd-card-protocol", title: "Протокол SD/SDIO", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2c-bus-timing", title: "Часові діаграми I²C: START, STOP, ACK і clock stretching", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "i2c-bus-capacity", title: "Ємність шини I²C і вибір підтяжок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sdio-bus", title: "Шина SDIO", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quad-spi", title: "Quad-SPI (QSPI)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb3-physical", title: "USB 3.x фізично: SuperSpeed і вище", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-device-basics", title: "Пристрій на шині USB: хост, енумерація, кінцеві точки, класи", basic: { status: "pending" }, detailed: { status: "done" }, api: [{ file: "api-standard-requests.md", status: "done" }], proj: [{ file: "proj-descriptor-parser.md", status: "done" }] },
        { slug: "one-wire", title: "1-Wire — шина на одному дроті", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-dallas-ibutton.md", status: "done" }], api: [{ file: "api-onewire-reference.md", status: "done" }], proj: [{ file: "proj-rom-search.md", status: "done" }, { file: "proj-bitbang-master.md", status: "done" }] },
        { slug: "i3c", title: "Шина I3C", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "radio", title: "Радіо", scope: "Радіочастотні діапазони, канальні плани й бездротові лінки конкретних застосувань.",
      topics: [
        { slug: "fpv-channels", title: "Канали 5.8 ГГц для FPV (Raceband і смуги A/B/E/F)", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "reliability", title: "Надійність", scope: "Забезпечення доставки попри помилки й втрати: повтори, підтвердження, відновлення зв'язку.",
      topics: [
        { slug: "arq", title: "ARQ: автоматичний запит на повтор", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
  ]
});
