/* manifest — «Алгоритми» (тип "book"). Схема — AUTHORING.md §2 (v6). */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "algorithms", title: "Алгоритми",
  sections: [
    { slug: "complexity-computability", title: "Складність", scope: "Теорія обчислюваності та складності: межі обчислюваного, класи задач, нижні оцінки.",
      topics: [
        { slug: "state-minimization", title: "Мінімізація скінченного автомата", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-moore-hopcroft.md", status: "done" }], math: [{ file: "math-myhill-nerode.md", status: "done" }], proj: [{ file: "proj-hopcroft.md", status: "done" }] },
        { slug: "fmea", title: "FMEA: аналіз видів і наслідків відмов", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fmea.md", status: "done" }], math: [{ file: "math-rpn-ordinal.md", status: "done" }], proj: [{ file: "proj-fmea-rpn.md", status: "done" }] },
        { slug: "loop-variant", title: "Варіант циклу", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-termination-proofs.md", status: "done" }], math: [{ file: "math-well-founded.md", status: "done" }], proj: [{ file: "proj-variant-bounds.md", status: "done" }] },
        { slug: "halting-problem", title: "Проблема зупинки", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-halting-problem.md", status: "done" }], math: [{ file: "math-undecidability.md", status: "done" }], proj: [{ file: "proj-halting-in-code.md", status: "done" }] },
        { slug: "fault-tree-analysis", title: "Аналіз дерева відмов (FTA)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fta.md", status: "done" }], math: [{ file: "math-sharp-p-hardness.md", status: "done" }], proj: [{ file: "proj-fault-tree-eval.md", status: "done" }] },
        { slug: "asymptotic-complexity", title: "Асимптотична складність (нотація O великого)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bachmann-landau.md", status: "done" }], math: [{ file: "math-formal-bigo.md", status: "done" }], proj: [{ file: "proj-doubling-experiment.md", status: "done" }] },
        { slug: "np-completeness", title: "Класи P і NP та NP-повнота", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-classes.md", status: "done" }], proj: [{ file: "proj-verify-reduce.md", status: "done" }] },
        { slug: "amortized-analysis", title: "Амортизований аналіз", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-amortized.md", status: "done" }], math: [{ file: "math-potential-method.md", status: "done" }], proj: [{ file: "proj-dynamic-array.md", status: "done" }] },
        { slug: "sharp-p-counting", title: "Клас #P: складність підрахунку розв'язків", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-valiant.md", status: "done" }], math: [{ file: "math-permanent-determinant.md", status: "done" }], proj: [{ file: "proj-permanent-ryser.md", status: "done" }, { file: "proj-sharp-sat-counter.md", status: "done" }] },
        { slug: "master-theorem", title: "Основна теорема про рекурентні співвідношення (master theorem)", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-master-theorem.md", status: "done" }], proj: [{ file: "proj-master-classify.md", status: "done" }] },
        { slug: "polynomial-hierarchy", title: "Поліноміальна ієрархія (PH)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pp-probabilistic-polynomial", title: "Клас PP: ймовірнісний поліноміальний час", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "comparison-sort-lower-bound", title: "Нижня межа сортування порівняннями (Ω(n log n))", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "design-paradigms", title: "Парадигми", scope: "Загальні методи побудови алгоритмів — каркаси розв'язків для широких класів задач.",
      topics: [
        { slug: "backpressure", title: "Протитиск (backpressure)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-backpressure.md", status: "done" }], math: [{ file: "math-queue-stability.md", status: "done" }], proj: [{ file: "proj-backpressure-demo.md", status: "done" }] },
        { slug: "ransac", title: "RANSAC: згода на випадковій вибірці", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ransac.md", status: "done" }], math: [{ file: "math-iterations.md", status: "done" }], proj: [{ file: "proj-ransac-linefit.md", status: "done" }] },
        { slug: "divide-and-conquer", title: "Розділяй і володарюй", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-divide-and-conquer.md", status: "done" }], math: [{ file: "math-recurrence.md", status: "done" }], proj: [{ file: "proj-mergesort.md", status: "done" }] },
        { slug: "memoization", title: "Мемоізація", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-memo-functions.md", status: "done" }], math: [{ file: "math-subproblem-count.md", status: "done" }], proj: [{ file: "proj-edit-distance.md", status: "done" }] },
        { slug: "dynamic-programming", title: "Динамічне програмування", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-bellman.md", status: "done" }], math: [{ file: "math-optimal-substructure.md", status: "done" }], proj: [{ file: "proj-knapsack.md", status: "done" }] },
        { slug: "greedy-algorithms", title: "Жадібні алгоритми", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "data-structures", title: "Структури", scope: "Організація даних для доступу й оновлення (дерева, купи, хеш, персистентні) разом із упорядкуванням, селекцією та пошуком.",
      topics: [
        { slug: "bit-flips", title: "Перевернуті біти", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bit-flip-election.md", status: "done" }, { file: "hist-hamming.md", status: "done" }] },
        { slug: "wear-leveling", title: "Вирівнювання зносу флешу", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-wear-leveling.md", status: "done" }], math: [{ file: "math-endurance.md", status: "done" }], proj: [{ file: "proj-wear-leveling.md", status: "done" }] },
        { slug: "ftl-flash-translation", title: "Шар трансляції флешу (FTL)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ftl-birth.md", status: "done" }], proj: [{ file: "proj-ftl-sim-c.md", status: "done" }] },
        { slug: "np-hard-placement", title: "NP-важкість задачі розміщення", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-placement-annealing.md", status: "done" }], math: [{ file: "math-placement-nphard.md", status: "done" }], proj: [{ file: "proj-annealing-placer.md", status: "done" }] },
        { slug: "logic-synthesis", title: "Логічний синтез: від булевого виразу до LUT-дерева", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-bdd.md", status: "done" }], proj: [{ file: "proj-bdd-build.md", status: "done" }] },
        { slug: "cache-oblivious", title: "Кеш-незалежні алгоритми", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-birth.md", status: "done" }], math: [{ file: "math-ideal-cache.md", status: "done" }], proj: [{ file: "proj-matmul.md", status: "done" }] },
        { slug: "scatter-gather", title: "Scatter-gather DMA", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-scatter-gather-lineage.md", status: "done" }], proj: [{ file: "proj-sglist-c.md", status: "done" }] },
        { slug: "ring-buffer", title: "Кільцевий буфер", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-ring-buffer-indexing.md", status: "done" }], proj: [{ file: "proj-ring-buffer-c.md", status: "done" }] },
        { slug: "key-value-store", title: "Сховище «ключ — значення»", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-associative-to-dynamo.md", status: "done" }], math: [{ file: "math-load-factor.md", status: "done" }], proj: [{ file: "proj-hash-kv-store.md", status: "done" }] },
        { slug: "priority-queue", title: "Черга з пріоритетом (купа)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-heap-birth.md", status: "done" }], math: [{ file: "math-heap-analysis.md", status: "done" }], proj: [{ file: "proj-binary-heap.md", status: "done" }] },
        { slug: "ecc-memory", title: "ECC і виявлення помилок у пам'яті", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-syndrome-and-sizing.md", status: "done" }], proj: [{ file: "proj-syndrome-decoder.md", status: "done" }] },
        { slug: "copy-on-write", title: "Copy-on-write: принцип незмінних копій", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-cow-lineage.md", status: "done" }], math: [{ file: "math-path-copying.md", status: "done" }], proj: [{ file: "proj-persistent-bst.md", status: "done" }] },
        { slug: "queue-fifo", title: "Черга: FIFO і кільцевий буфер", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-queue-discipline.md", status: "done" }], proj: [{ file: "proj-two-stack-queue.md", status: "done" }] },
        { slug: "recursion", title: "Рекурсія", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-recursion.md", status: "done" }], math: [{ file: "math-recurrence.md", status: "done" }], proj: [{ file: "proj-recursion-to-iteration.md", status: "done" }] },
        { slug: "sorting-networks", title: "Сортувальні мережі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rolling-hash", title: "Ковзний хеш (rolling hash)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "over-provisioning", title: "Over-provisioning", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-wear-leveling", title: "Wear leveling у флеш-пам'яті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "binary-search", title: "Двійковий пошук", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "write-amplification", title: "Write Amplification Factor", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-garbage-collection", title: "Garbage collection у Flash-сховищах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "abstract-syntax-tree", title: "Абстрактне синтаксичне дерево (AST)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lsm-tree", title: "B-tree vs LSM-tree / log-structured", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "consistent-hashing", title: "Консистентне хешування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "merkle-tree", title: "Дерево Меркла", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bloom-filter", title: "Фільтр Блума", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "b-tree", title: "B-дерево", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "binary-decision-diagram", title: "Двійкова діаграма рішень (BDD)", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-model-checking.md", status: "done" }], math: [{ file: "math-canonicity.md", status: "done" }], proj: [{ file: "proj-apply.md", status: "done" }] },
        { slug: "hash-table", title: "Хеш-таблиця", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-hashing-birth.md", status: "done" }], math: [{ file: "math-open-addressing.md", status: "done" }], proj: [{ file: "proj-open-addressing.md", status: "done" }] },
        { slug: "binary-search-tree", title: "Двійкове дерево пошуку (BST)", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-bst-birth.md", status: "done" }], math: [{ file: "math-bst-height.md", status: "done" }], proj: [{ file: "proj-bst-operations.md", status: "done" }] },
        { slug: "union-find", title: "Система неперетинних множин (union-find)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "binary-tree", title: "Двійкове дерево", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "heapsort", title: "Сортування купою (heapsort)", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-heapsort.md", status: "done" }], math: [{ file: "math-heapsort.md", status: "done" }], proj: [{ file: "proj-heapsort.md", status: "done" }] },
        { slug: "fibonacci-heap", title: "Фібоначчієва купа", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-fredman-tarjan.md", status: "done" }], math: [{ file: "math-fibonacci-bound.md", status: "done" }], proj: [{ file: "proj-fib-heap.md", status: "done" }] },
        { slug: "deque", title: "Двобічна черга (deque)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "single-event-upset", title: "Одиничний збій від частинки (SEU і SEL)", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "array", title: "Масив", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "linked-list", title: "Зв'язаний список", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "tree-rotation", title: "Обертання дерева", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "avl-tree", title: "AVL-дерево", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "red-black-tree", title: "Червоно-чорне дерево", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quicksort", title: "Швидке сортування (quicksort)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "selection-sort", title: "Сортування вибором (selection sort)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "binomial-heap", title: "Біноміальна купа", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "spatial-index", title: "Просторовий індекс: R-дерево і квадродерево", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "graph-algorithms", title: "Графові", scope: "Обхід, шляхи, потоки, паросполучення та структурний аналіз графів і мереж.",
      topics: [
        { slug: "routing-algorithms", title: "Алгоритми маршрутизації", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "congestion-control", title: "Управління перевантаженням мережі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dijkstra", title: "Алгоритм Дейкстри", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-dijkstra.md", status: "done" }] },
        { slug: "topological-sort", title: "Топологічне сортування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "strongly-connected-components", title: "Сильно зв'язні компоненти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "register-allocation", title: "Розподіл регістрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bellman-ford", title: "Алгоритм Беллмана–Форда", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bipartite-matching", title: "Двочасткові графи й досконале паросполучення", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "breadth-first-search", title: "Пошук у ширину (BFS)", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "string-geometry-streaming", title: "Дискретні", scope: "Алгоритми над текстом, геометрією та потоками: пошук і вирівнювання рядків, оболонки й перетини фігур, онлайн-рішення та один прохід над масивними даними.",
      topics: [
        { slug: "regex-engine", title: "Рушій регулярних виразів", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "numerical-algorithms", title: "Числові", scope: "Арифметика великих чисел, лінійна алгебра, чисельні методи, точні та наближені обчислення.",
      topics: [
        { slug: "kahan-summation", title: "Компенсоване підсумовування (Кехен)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "newtons-method", title: "Метод Ньютона", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "automatic-differentiation", title: "Автоматичне диференціювання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "numerical-ode", title: "Числові методи розв'язку ОДУ", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "float-formats", title: "Формати чисел із рухомою комою (IEEE 754)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "symplectic-integrators", title: "Симплектичні інтегратори (Верле, leapfrog)", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "combinatorial-optimization", title: "Оптимізація", scope: "Пошук найкращого розв'язку в дискретних і неперервних просторах: лінійне, цілочисельне програмування, евристики.",
      topics: [
        { slug: "hungarian-algorithm", title: "Алгоритм Угорського методу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mean-shift", title: "Зсув до середнього", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "simulated-annealing", title: "Імітація відпалу (simulated annealing)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "set-cover", title: "Задача про покриття множини", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "cryptographic-algorithms", title: "Криптографія", scope: "Шифрування, хеш-функції, цифрові підписи, протоколи обміну ключами.",
      topics: [
        { slug: "berlekamp-massey", title: "Алгоритм Берлекампа–Мессі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rsa", title: "RSA", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "miller-rabin", title: "Тест простоти Міллера–Рабіна", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-miller-rabin.md", status: "done" }], math: [{ file: "math-liar-bound.md", status: "done" }], proj: [{ file: "proj-miller-rabin.md", status: "done" }] },
        { slug: "csprng", title: "Криптографічний генератор випадкових чисел (CSPRNG)", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-rng-disasters.md", status: "done" }], math: [{ file: "math-unpredictability.md", status: "done" }], proj: [{ file: "proj-fast-key-erasure.md", status: "done" }] },
        { slug: "fermat-primality-test", title: "Тест простоти Ферма", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "block-cipher", title: "Блоковий шифр", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "stream-cipher", title: "Потоковий шифр", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "entropy-source", title: "Джерело ентропії (TRNG)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "montgomery-multiplication", title: "Множення за Монтгомері", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "solovay-strassen", title: "Тест простоти Соловея–Штрассена", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "data-compression", title: "Стиснення", scope: "Скорочення даних без втрат і з втратами: ентропійне, словникове, трансформаційне кодування.",
      topics: [
        { slug: "why-compress", title: "Навіщо стискати", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-dct.md", status: "done" }] },
        { slug: "auditory-masking", title: "Психоакустичне маскування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "jpeg-intra", title: "JPEG", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-jpeg.md", status: "done" }], math: [{ file: "math-dct.md", status: "done" }], proj: [{ file: "proj-jpeg-encode.md", status: "done" }], api: [{ file: "api-markers.md", status: "done" }] },
        { slug: "inter-frame", title: "Міжкадрове стиснення", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-mpeg.md", status: "done" }], math: [{ file: "math-motion-estimation.md", status: "done" }] },
        { slug: "quality-bitrate", title: "Якість і бітрейт", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fpv-digital.md", status: "done" }] },
        { slug: "lossless-huffman-lz", title: "Стиснення без втрат", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "entropy", title: "Ентропія", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "huffman-coding", title: "Код Гаффмана", basic: { status: "done" }, detailed: { status: "done" }, proj: [{ file: "proj-huffman-c.md", status: "done" }] },
        { slug: "rle", title: "RLE (довжини серій)", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "arithmetic-coding", title: "Арифметичне кодування", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "shannon-fano", title: "Код Шеннона–Фано", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "lz77", title: "LZ77", basic: { status: "done" }, detailed: { status: "done" }, proj: [{ file: "proj-lz77-c.md", status: "done" }] },
        { slug: "lzw", title: "LZW", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "deflate", title: "DEFLATE", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-pkzip.md", status: "done" }] },
        { slug: "asymmetric-numeral-systems", title: "ANS: асиметричні системи числення", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "cabac", title: "CABAC", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "rate-distortion", title: "Rate-distortion оптимізація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "deblocking-filter", title: "Деблокінговий фільтр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "subpixel-interpolation", title: "Субпіксельна інтерполяція у відео", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "h265-hevc", title: "H.265 / HEVC", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "av1", title: "AV1", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "motion-estimation-search", title: "Пошук руху (motion estimation)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rate-control-algorithms", title: "Алгоритми керування бітрейтом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "psnr-ssim", title: "Метрики якості відео: PSNR і SSIM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hrd-buffer-model", title: "Модель HRD-буфера відеопотоку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "run-length-codes", title: "Коди довжин серій (Modified Huffman, MR)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "shannon-fano-elias", title: "Код Шеннона–Фано–Еліаса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "prefix-codes", title: "Префіксні коди та декодованість", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "kraft-inequality", title: "Нерівність Крафта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cobs-encoding", title: "Кодування COBS", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "crc-algorithm", title: "Алгоритм CRC: таблиця залишків і побітний метод", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "adaptive-bitrate", title: "Адаптивний бітрейт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "h264-nal-structure", title: "H.264: NAL-одиниці, SPS/PPS і ключові кадри", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "machine-learning", title: "Машинне навчання", scope: "Алгоритми, що будують моделі з даних: навчання з учителем і без, ансамблі, нейромережі, навчання з підкріпленням.",
      topics: [
        { slug: "what-is-ml", title: "Що таке ML", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ai-winters.md", status: "done" }] },
        { slug: "train-vs-inference", title: "Навчання vs вивід", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "neuron-layer", title: "Нейрон і шар", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "gradient-descent", title: "Градієнтний спуск", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "cnn", title: "Згорткові мережі", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-lecun-cnn.md", status: "done" }] },
        { slug: "overfitting", title: "Перенавчання", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "tinyml", title: "TinyML", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-tinyml-field.md", status: "done" }], proj: [{ file: "proj-arena-planner.md", status: "done" }], api: [{ file: "api-tflm.md", status: "done" }] },
        { slug: "ml-limits-ethics", title: "Межі й етика", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-shortcut-legends.md", status: "done" }], math: [{ file: "math-base-rate-threshold.md", status: "done" }], proj: [{ file: "proj-slice-audit.md", status: "done" }] },
        { slug: "transfer-learning", title: "Transfer learning (перенесення навчання)", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-transferable-features.md", status: "done" }] },
        { slug: "anchor-boxes", title: "Якорі та кодування рамок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "model-quantization", title: "Квантування нейромереж", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-int8-jacob.md", status: "done" }], math: [{ file: "math-affine-quant.md", status: "done" }], proj: [{ file: "proj-int8-inference.md", status: "done" }] },
        { slug: "backpropagation", title: "Зворотне поширення помилки", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-multiple-discovery.md", status: "done" }] },
        { slug: "activation-functions", title: "Функції активації", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-relu-triumph.md", status: "done" }], math: [{ file: "math-softmax.md", status: "done" }] },
        { slug: "sgd-optimizers", title: "Оптимізатори: SGD, моментум, Adam", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vanishing-gradient", title: "Затухаючий і вибуховий градієнт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "weight-initialization", title: "Ініціалізація ваг нейромережі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "perceptron", title: "Перцептрон Розенблатта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "regularization", title: "Регуляризація", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-regularization.md", status: "done" }], math: [{ file: "math-l1-sparsity.md", status: "done" }] },
        { slug: "data-augmentation", title: "Аугментація даних", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-alexnet-2012.md", status: "done" }], math: [{ file: "math-mixup.md", status: "done" }] },
        { slug: "cross-validation", title: "Крос-валідація", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-cross-validation.md", status: "done" }], proj: [{ file: "proj-kfold-c.md", status: "done" }] },
        { slug: "bias-variance-tradeoff", title: "Компроміс зміщення й дисперсії", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "knowledge-distillation", title: "Дистиляція знань", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-distillation-lineage.md", status: "done" }], math: [{ file: "math-distillation-loss.md", status: "done" }], proj: [{ file: "proj-distill-mnist-c.md", status: "done" }] },
        { slug: "weight-pruning", title: "Прорідження мережі", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-obd-lottery.md", status: "done" }], math: [{ file: "math-pruning-saliency.md", status: "done" }] },
        { slug: "loss-functions", title: "Функції втрат у машинному навчанні", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-mse-likelihood.md", status: "done" }] },
        { slug: "supervised-learning", title: "Навчання з учителем", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-nearest-neighbor.md", status: "done" }], math: [{ file: "math-loss-functions.md", status: "done" }] },
        { slug: "unsupervised-learning", title: "Навчання без учителя", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-kmeans-lineage.md", status: "done" }] },
        { slug: "reinforcement-learning", title: "Навчання з підкріпленням", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-rl-lineage.md", status: "done" }] },
        { slug: "edge-computing", title: "Edge computing", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "companion-computer", title: "Бортовий комп'ютер (companion)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "inference-latency", title: "Латентність інференсу", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-realtime-inference.md", status: "done" }] },
        { slug: "cosine-similarity", title: "Косинусна схожість", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "autoencoder", title: "Автокодер", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-birth.md", status: "done" }], math: [{ file: "math-linear-pca.md", status: "done" }], proj: [{ file: "proj-autoencoder-c.md", status: "done" }] },
        { slug: "dbscan", title: "DBSCAN: щільнісна кластеризація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pca", title: "Метод головних компонент (PCA)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "variational-autoencoder", title: "Варіаційний автокодер (VAE)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "restricted-boltzmann-machine", title: "Обмежена машина Больцмана (RBM)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "distribution-shift", title: "Зсув розподілу даних", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "confidence-calibration", title: "Калібрування впевненості моделі", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "model-explainability", title: "Пояснюваність моделей", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "fairness-criteria", title: "Критерії справедливості моделі та їхня несумісність", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "computer-vision", title: "Зір", scope: "Аналіз зображень і відео: фільтрація, ознаки, сегментація, відновлення геометрії сцени.",
      topics: [
        { slug: "bayer-demosaic", title: "Демозаїка", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-bryce-bayer.md", status: "done" }], proj: [{ file: "proj-demosaic-bilinear.md", status: "done" }] },
        { slug: "image-as-data", title: "Зображення як дані", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-summer-vision.md", status: "done" }, { file: "hist-maxwell-rgb.md", status: "done" }], math: [{ file: "math-color-spaces.md", status: "done" }], proj: [{ file: "proj-rgb-hsv-convert.md", status: "done" }] },
        { slug: "histogram", title: "Гістограма", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-hurter-driffield.md", status: "done" }], math: [{ file: "math-equalization.md", status: "done" }], proj: [{ file: "proj-histogram-lut.md", status: "done" }] },
        { slug: "convolution-filters", title: "Згортки й фільтри", basic: { status: "done" }, detailed: { status: "done" }, math: [{ file: "math-2d-convolution.md", status: "done" }], proj: [{ file: "proj-separable-blur.md", status: "done" }] },
        { slug: "edge-detection", title: "Виділення меж", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-sobel-feldman.md", status: "done" }], proj: [{ file: "proj-canny-c.md", status: "done" }] },
        { slug: "threshold-morphology", title: "Пороги й морфологія", basic: { status: "done" }, detailed: { status: "done" }, math: [{ file: "math-otsu-derivation.md", status: "done" }], proj: [{ file: "proj-threshold-morphology-pipeline.md", status: "done" }] },
        { slug: "object-detection", title: "Виявлення об'єктів", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-hough.md", status: "done" }], math: [{ file: "math-hough.md", status: "done" }], proj: [{ file: "proj-color-blob.md", status: "done" }] },
        { slug: "nn-detectors", title: "Нейродетектори", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-neural-nets.md", status: "done" }], math: [{ file: "math-iou-nms.md", status: "done" }], proj: [{ file: "proj-yolo-postprocess.md", status: "done" }] },
        { slug: "tracking", title: "Трекінг", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-tracking-history.md", status: "done" }], math: [{ file: "math-kf-tracking-state.md", status: "done" }], proj: [{ file: "proj-sort-tracker.md", status: "done" }] },
        { slug: "compute-cost", title: "Вартість обчислень", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-apollo-guidance.md", status: "done" }] },
        { slug: "edge-adaptive-demosaic", title: "Крайо-чутлива демозаїка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "raw-processing-pipeline", title: "Конвеєр обробки RAW", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "roofline-model", title: "Roofline-модель продуктивності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quantization-inference", title: "Квантування для інференсу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "separable-filters", title: "Розділювані фільтри", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bilateral-filter", title: "Білатеральний фільтр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "kernel-frequency-response", title: "Частотна характеристика ядер", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "corner-detection", title: "Детектори кутів: Гарріс, Ші–Томасі, FAST", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-corner-lineage.md", status: "done" }], math: [{ file: "math-second-moment.md", status: "done" }] },
        { slug: "scale-space", title: "Масштабний простір і піраміда Гауса", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "clahe", title: "CLAHE — локальна адаптивна еквалізація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tone-curve", title: "Тонова крива й гамма-корекція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "color-histogram", title: "Колірна гістограма і трекінг за кольором", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pixel-formats", title: "Формати пікселів і буферів зображення", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-chroma-subsampling.md", status: "done" }] },
        { slug: "nms-algorithm", title: "Non-Maximum Suppression", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "detection-architectures", title: "Архітектури детекторів: YOLO, SSD, R-CNN", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fiducial-markers", title: "Фідуційні мітки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "background-subtraction", title: "Відрахування фону", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "feature-matching", title: "Зіставлення ключових точок", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-sift-to-orb.md", status: "done" }], math: [{ file: "math-descriptor-distance.md", status: "done" }], proj: [{ file: "proj-orb-match-c.md", status: "done" }] },
        { slug: "otsu-method", title: "Метод Оцу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "adaptive-thresholding", title: "Адаптивний поріг", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hit-or-miss", title: "Перетворення влучання-промаху", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "watershed-segmentation", title: "Сегментація водорозділом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "optical-flow", title: "Оптичний потік", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-two-schools.md", status: "done" }], math: [{ file: "math-optical-flow-constraint.md", status: "done" }] },
        { slug: "data-association", title: "Прив'язка даних", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "white-balance", title: "Баланс білого", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-color-constancy.md", status: "done" }], math: [{ file: "math-von-kries-diagonal.md", status: "done" }], proj: [{ file: "proj-auto-white-balance.md", status: "done" }] },
        { slug: "color-filter-array-variants", title: "Альтернативні матриці кольорових фільтрів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "frequency-filtering", title: "Частотна фільтрація зображень", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "marr-hildreth-log", title: "Оператор Марра–Гілдрет (LoG)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "hough-transform", title: "Перетворення Хафа", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gamma-correction", title: "Гама-корекція", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nn-segmentation", title: "Сегментація зображень нейромережею", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "aruco-apriltag", title: "Фідуційні мітки ArUco та AprilTag", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fiducial-lineage.md", status: "done" }], proj: [{ file: "proj-aruco-decode.md", status: "done" }] },
        { slug: "blob-analysis", title: "Аналіз плям", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "template-matching", title: "Зіставлення з шаблоном", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "detection-metrics", title: "Метрики детектора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "color-spaces", title: "Кольорові простори", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "multi-object-tracking", title: "Трекінг багатьох цілей", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "depthwise-separable-conv", title: "Розділювана за глибиною згортка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "stereo-vision", title: "Стереозір", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tile-rendering", title: "Тайловий рендеринг", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "alpha-blending", title: "Альфа-змішування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pose-estimation", title: "Відновлення пози за точками (PnP)", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-pnp-lineage.md", status: "done" }], math: [{ file: "math-p3p-cosines.md", status: "done" }, { file: "math-reprojection-jacobian.md", status: "done" }], proj: [{ file: "proj-pnp-solver.md", status: "done" }] },
        { slug: "camera-model", title: "Модель камери-обскури й внутрішні параметри", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "camera-calibration", title: "Калібрування камери", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "homography", title: "Гомографія: перетворення площини в площину", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "bundle-adjustment", title: "Оптимізація пучком (bundle adjustment)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "absolute-orientation", title: "Абсолютна орієнтація (суміщення двох наборів точок)", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "signal-robotics", title: "Сигнали", scope: "Цифрова обробка сигналів (спектр, фільтрація, дискретизація) разом із плануванням руху, локалізацією та керуванням автономних агентів.",
      topics: [
        { slug: "signal-noise", title: "Шум у сигналі", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-snr.md", status: "done" }] },
        { slug: "moving-average", title: "Ковзне середнє", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "median-filter", title: "Медіанний фільтр", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "ema", title: "EMA", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-ema-c.md", status: "done" }] },
        { slug: "smoothing-vs-lag", title: "Згладжування й затримка", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "fft", title: "ШПФ", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-fft.md", status: "done" }] },
        { slug: "filter-as-spectrum-shaper", title: "Формувач спектра", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "fir-filter", title: "КІХ-фільтр", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-fir-c.md", status: "done" }] },
        { slug: "iir-filter", title: "БІХ-фільтр", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-biquad-c.md", status: "done" }] },
        { slug: "band-filters", title: "Смугові фільтри", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-type-transformations.md", status: "done" }] },
        { slug: "fixed-point-implementation", title: "Реалізація fixed-point", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "sensor-fusion", title: "Поєднання давачів", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "complementary-filter", title: "Комплементарний фільтр", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-complementary-c.md", status: "done" }] },
        { slug: "kalman-filter", title: "Фільтр Калмана", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-kalman.md", status: "done" }] },
        { slug: "discrete-pid", title: "Дискретний ПІД", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-pid-c.md", status: "done" }] },
        { slug: "sensor-insufficiency", title: "Недостатність давача", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-draper.md", status: "done" }] },
        { slug: "motion-model", title: "Модель руху", basic: { status: "done" }, detailed: { status: "done" }, math: [{ file: "math-cv-ca-models.md", status: "done" }] },
        { slug: "predict-vs-measure", title: "Передбачення vs вимір", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-recursive-estimation.md", status: "done" }], math: [{ file: "math-optimal-fusion.md", status: "done" }], proj: [{ file: "proj-predict-correct-tracker.md", status: "done" }] },
        { slug: "kalman-ekf", title: "Розширений фільтр Калмана (EKF)", basic: { status: "empty" }, detailed: { status: "done" }, proj: [{ file: "proj-fusion-in-flight.md", status: "done" }] },
        { slug: "latency-sync", title: "Затримки й синхро", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "odometry", title: "Одометрія", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "motion-profiles", title: "Профілі руху", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "roll-pitch-yaw-control", title: "Керування roll/pitch/yaw", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "motor-mixer", title: "Мікшер", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "instability-stabilization", title: "Потреба стабілізації", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "stabilization-cascade", title: "Каскад стабілізації", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "missions-waypoints", title: "Місії й точки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sense-decide-act-loop", title: "Контур offboard", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "one-stack-many-bodies", title: "Один стек", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rover-steering", title: "Ровер", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-ackermann.md", status: "done" }], proj: [{ file: "proj-pure-pursuit.md", status: "done" }] },
        { slug: "boat-underwater", title: "Човен і підводний", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-acoustic-positioning.md", status: "done" }], proj: [{ file: "proj-depth-hold-c.md", status: "done" }] },
        { slug: "pure-pursuit-navigation", title: "Навігація pure pursuit", basic: { status: "empty" }, detailed: { status: "done" }, math: [{ file: "math-pursuit-geometry.md", status: "done" }], proj: [{ file: "proj-pursuit-c.md", status: "done" }] },
        { slug: "platform-selection", title: "Вибір платформи", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mission-planning-map", title: "Планування на карті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "closing-the-loop", title: "Замкнути контур", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "where-next", title: "Куди далі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "jitter-buffer", title: "Буфер джитера", basic: { status: "empty" }, detailed: { status: "done" } },
        { slug: "adaptive-filter", title: "Адаптивний фільтр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "shelf-filter", title: "Поличковий фільтр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "all-pass-filter", title: "Всепропускний фільтр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "double-ema", title: "Подвійне EMA (DEMA) — компенсація тренду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "adaptive-ema", title: "Адаптивне EMA — змінний коефіцієнт згладжування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "goertzel", title: "Алгоритм Гертцеля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "parks-mcclellan", title: "Алгоритм Parks-McClellan", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "polyphase-fir", title: "Поліфазний КІХ і мультирейт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "filter-order-estimation", title: "Оцінка порядку фільтра", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "limit-cycles-iir", title: "Граничні цикли у БІХ-фільтрах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bilinear-transform", title: "Білінійне перетворення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "butterworth-filter", title: "Фільтр Баттерворта", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "chebyshev-filter", title: "Фільтр Чебишева", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "direct-form-iir", title: "Форми реалізації БІХ (Direct Form)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "packet-loss-concealment", title: "Приховування втрат пакетів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "audio-time-scaling", title: "Зміна темпу без зміни висоти тону", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-time-scaling.md", status: "done" }], proj: [{ file: "proj-wsola-c.md", status: "done" }] },
        { slug: "unscented-kalman-filter", title: "Несцентований фільтр Калмана (UKF)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "particle-filter", title: "Фільтр частинок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "innovation-gating", title: "Ворота несподіванки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sensor-timestamp-sync", title: "Синхронізація міток часу давачів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "trimmed-mean", title: "Усічене середнє", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ctrv-motion-model", title: "Модель CTRV: стала кутова швидкість і швидкість", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "imm-filter", title: "Фільтр IMM (взаємодіючі мультимоделі)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bicycle-kinematic-model", title: "Кінематична велосипедна модель", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "actuator-allocation", title: "Розподіл керування по приводах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "weighted-moving-average", title: "Зважене ковзне середнє", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cumulative-moving-average", title: "Кумулятивне ковзне середнє", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "innovation-gate", title: "Брама нової інформації (innovation gate)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "quaternion-attitude-control", title: "Кватерніонне керування орієнтацією", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-hamilton.md", status: "done" }], math: [{ file: "math-half-angle.md", status: "done" }], proj: [{ file: "proj-error-quaternion-c.md", status: "done" }] },
        { slug: "rate-angle-cascade", title: "Каскадний регулятор: кут і кутова швидкість", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ahrs", title: "AHRS — система відліку орієнтації й курсу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "madgwick-mahony", title: "Алгоритми Madgwick і Mahony", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "visual-inertial-odometry", title: "Візуально-інерціальна одометрія", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-msckf.md", status: "done" }] },
        { slug: "causal-filter", title: "Причинний фільтр і групова затримка", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "three-loop-cascade", title: "Трирівневий каскад (положення–швидкість–струм)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "real-time-systems", title: "Системи реального часу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dead-reckoning", title: "Інерціальне числення позиції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "phase-margin", title: "Запас по фазі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bumpless-transfer", title: "Безударне перемикання регулятора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "goertzel-algorithm", title: "Алгоритм Герцеля", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "overlap-add", title: "Overlap-add і потоковий спектр", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dithering", title: "Дізеринг", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "geofence-algorithm", title: "Алгоритм геозони", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rfid-anticollision", title: "Антиколізія RFID: кілька міток в одному полі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rtk-integer-ambiguity", title: "Розв'язання цілочислової неоднозначності RTK", basic: { status: "empty" }, detailed: { status: "done" }, hist: [{ file: "hist-lambda.md", status: "done" }], math: [{ file: "math-double-difference.md", status: "done" }] },
        { slug: "digital-filters", title: "Цифрові фільтри", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "acceleration-profile", title: "Профілі розгону привода", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cycle-counting-palmgren-miner", title: "Rainflow і правило Майнера", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "welford-online", title: "Онлайн-алгоритм Велфорда", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pole-zero-plot", title: "Площина полюсів-нулів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cic-filter", title: "CIC-фільтр (каскад інтегратор–гребінка)", basic: { status: "pending" }, detailed: { status: "pending" } },
        { slug: "survey-grid-coverage", title: "Покриття полігону галсами: планування зйомки", basic: { status: "empty" }, detailed: { status: "pending" } },

      ] },
    { slug: "parallel-distributed", title: "Паралельні", scope: "Одночасне виконання на багатьох процесорах зі спільною пам'яттю та системи незалежних вузлів з обміном повідомленнями: примітиви, синхронізація, консенсус, відмовостійкість.",
      topics: [
        { slug: "gesture-recognition", title: "Розпізнавання жестів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "edf-scheduling", title: "EDF-планування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "monitor-sync", title: "Монітори й умовні змінні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "amdahls-law", title: "Закон Амдала", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lamport-clocks", title: "Чому wall-clock бреше (дрейф, NTP-стрибки) і **годинник Лампорта**", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vector-clocks", title: "Векторні годинники й обходи розбіжності", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "consensus-problem", title: "Задача консенсусу і чому вона важка (FLP оглядово); коли потрібен консенсус, а коли ні (дорого)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "raft", title: "Raft", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "two-phase-commit", title: "Двофазний коміт і його страх", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "crdt", title: "Безконфліктні типи даних (CRDT)", basic: { status: "pending" }, detailed: { status: "done" }, hist: [{ file: "hist-crdt.md", status: "done" }], math: [{ file: "math-convergence.md", status: "done" }], proj: [{ file: "proj-or-set.md", status: "done" }] },
        { slug: "operational-transformation", title: "Операційні перетворення (OT)", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
  ]
});
