/* manifest — «Алгоритми» (тип "book"). Схема — AUTHORING.md §2. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "algorithms", title: "Алгоритми",
  sections: [
    { slug: "complexity-computability", title: "Складність", scope: "Теорія обчислюваності та складності: межі обчислюваного, класи задач, нижні оцінки.",
      topics: [
      ] },
    { slug: "design-paradigms", title: "Парадигми", scope: "Загальні методи побудови алгоритмів — каркаси розв'язків для широких класів задач.",
      topics: [
      ] },
    { slug: "data-structures", title: "Структури", scope: "Організація даних для доступу й оновлення (дерева, купи, хеш, персистентні) разом із упорядкуванням, селекцією та пошуком.",
      topics: [
        { slug: "bit-flips", title: "Перевернуті біти", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/error-correction#3.9.1", hist: [{ file: "hist-bit-flip-election.md", status: "done" }, { file: "hist-hamming.md", status: "done" }], math: [{ file: "math-seu-sel.md", status: "done" }] },
      ] },
    { slug: "graph-algorithms", title: "Графові", scope: "Обхід, шляхи, потоки, паросполучення та структурний аналіз графів і мереж.",
      topics: [
      ] },
    { slug: "string-geometry-streaming", title: "Дискретні", scope: "Алгоритми над текстом, геометрією та потоками: пошук і вирівнювання рядків, оболонки й перетини фігур, онлайн-рішення та один прохід над масивними даними.",
      topics: [
      ] },
    { slug: "numerical-algorithms", title: "Числові", scope: "Арифметика великих чисел, лінійна алгебра, чисельні методи, точні та наближені обчислення.",
      topics: [
      ] },
    { slug: "combinatorial-optimization", title: "Оптимізація", scope: "Пошук найкращого розв'язку в дискретних і неперервних просторах: лінійне, цілочисельне програмування, евристики.",
      topics: [
      ] },
    { slug: "cryptographic-algorithms", title: "Криптографія", scope: "Шифрування, хеш-функції, цифрові підписи, протоколи обміну ключами.",
      topics: [
      ] },
    { slug: "data-compression", title: "Стиснення", scope: "Скорочення даних без втрат і з втратами: ентропійне, словникове, трансформаційне кодування.",
      topics: [
        { slug: "why-compress", title: "Навіщо стискати", status: "deeper", levels: ["basic"], origin: "embedded/block-7-systems/video-signals-2#7.8.1", hist: [{ file: "hist-dct.md", status: "deeper" }] },
        { slug: "jpeg-intra", title: "JPEG", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/video-signals-2#7.8.2" },
        { slug: "inter-frame", title: "Міжкадрове стиснення", status: "deeper", levels: ["basic"], origin: "embedded/block-7-systems/video-signals-2#7.8.3" },
        { slug: "mjpeg-vs-h264", title: "MJPEG vs H.264", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/video-signals-2#7.8.4" },
        { slug: "quality-bitrate", title: "Якість і бітрейт", status: "recheck", origin: "embedded/block-7-systems/video-signals-2#7.8.5" },
        { slug: "lossless-huffman-lz", title: "Стиснення без втрат", status: "empty", origin: "embedded/block-7-systems/video-signals-2#7.8.8" },
      ] },
    { slug: "machine-learning", title: "Машинне навчання", scope: "Алгоритми, що будують моделі з даних: навчання з учителем і без, ансамблі, нейромережі, навчання з підкріпленням.",
      topics: [
        { slug: "what-is-ml", title: "Що таке ML", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.1", hist: [{ file: "hist-ai-winters.md", status: "done" }] },
        { slug: "train-vs-inference", title: "Навчання vs вивід", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.2" },
        { slug: "neuron-layer", title: "Нейрон і шар", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.3" },
        { slug: "gradient-descent", title: "Градієнтний спуск", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.4" },
        { slug: "cnn", title: "Згорткові мережі", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.5", hist: [{ file: "hist-lecun-cnn.md", status: "done" }] },
        { slug: "overfitting", title: "Перенавчання", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.6" },
        { slug: "tinyml", title: "TinyML", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.7" },
        { slug: "where-to-compute", title: "Де рахувати", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/machine-learning#7.10.8" },
        { slug: "ml-limits-ethics", title: "Межі й етика", status: "recheck", origin: "embedded/block-7-systems/machine-learning#7.10.9" },
      ] },
    { slug: "computer-vision", title: "Зір", scope: "Аналіз зображень і відео: фільтрація, ознаки, сегментація, відновлення геометрії сцени.",
      topics: [
        { slug: "bayer-demosaic", title: "Демозаїка", status: "recheck", origin: "embedded/block-7-systems/video-signals-1#7.7.3" },
        { slug: "image-as-data", title: "Зображення як дані", status: "recheck", origin: "embedded/block-7-systems/computer-vision#7.9.1", hist: [{ file: "hist-summer-vision.md", status: "recheck" }] },
        { slug: "histogram", title: "Гістограма", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/computer-vision#7.9.2" },
        { slug: "convolution-filters", title: "Згортки й фільтри", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/computer-vision#7.9.3" },
        { slug: "edge-detection", title: "Виділення меж", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/computer-vision#7.9.4" },
        { slug: "threshold-morphology", title: "Пороги й морфологія", status: "recheck", origin: "embedded/block-7-systems/computer-vision#7.9.5" },
        { slug: "object-detection", title: "Виявлення об'єктів", status: "recheck", origin: "embedded/block-7-systems/computer-vision#7.9.6" },
        { slug: "nn-detectors", title: "Нейродетектори", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/computer-vision#7.9.7", hist: [{ file: "hist-neural-nets.md", status: "done" }] },
        { slug: "tracking", title: "Трекінг", status: "recheck", origin: "embedded/block-7-systems/computer-vision#7.9.8" },
        { slug: "compute-cost", title: "Вартість обчислень", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/computer-vision#7.9.9" },
      ] },
    { slug: "signal-robotics", title: "Сигнали", scope: "Цифрова обробка сигналів (спектр, фільтрація, дискретизація) разом із плануванням руху, локалізацією та керуванням автономних агентів.",
      topics: [
        { slug: "signal-noise", title: "Шум у сигналі", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filtering#5.4.1" },
        { slug: "moving-average", title: "Ковзне середнє", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/digital-filtering#5.4.2" },
        { slug: "median-filter", title: "Медіанний фільтр", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/digital-filtering#5.4.3" },
        { slug: "ema", title: "EMA", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filtering#5.4.4" },
        { slug: "smoothing-vs-lag", title: "Згладжування й затримка", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filtering#5.4.5" },
        { slug: "choosing-a-filter", title: "Вибір фільтра", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filtering#5.4.6" },
        { slug: "fft", title: "ШПФ", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/spectrum-fourier#5.5.5", hist: [{ file: "hist-fft.md", status: "done" }] },
        { slug: "filter-as-spectrum-shaper", title: "Формувач спектра", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filters-mcu#5.6.1" },
        { slug: "fir-filter", title: "КІХ-фільтр", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filters-mcu#5.6.2" },
        { slug: "iir-filter", title: "БІХ-фільтр", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filters-mcu#5.6.3" },
        { slug: "band-filters", title: "Смугові фільтри", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filters-mcu#5.6.4" },
        { slug: "fixed-point-implementation", title: "Реалізація fixed-point", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filters-mcu#5.6.5" },
        { slug: "fir-vs-iir", title: "КІХ проти БІХ", status: "recheck", origin: "embedded/block-5-sensors-control/digital-filters-mcu#5.6.6" },
        { slug: "sensor-fusion", title: "Поєднання давачів", status: "recheck", origin: "embedded/block-5-sensors-control/imu-mems#5.7.6" },
        { slug: "complementary-filter", title: "Комплементарний фільтр", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.3" },
        { slug: "kalman-filter", title: "Фільтр Калмана", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.4", hist: [{ file: "hist-kalman.md", status: "recheck" }] },
        { slug: "discrete-pid", title: "Дискретний ПІД", status: "recheck", origin: "embedded/block-5-sensors-control/orientation-pid#5.8.9" },
        { slug: "sensor-insufficiency", title: "Недостатність давача", status: "recheck", origin: "embedded/block-7-systems/state-estimation-fusion#7.5.1", hist: [{ file: "hist-draper.md", status: "recheck" }] },
        { slug: "motion-model", title: "Модель руху", status: "recheck", origin: "embedded/block-7-systems/state-estimation-fusion#7.5.2" },
        { slug: "predict-vs-measure", title: "Передбачення vs вимір", status: "recheck", origin: "embedded/block-7-systems/state-estimation-fusion#7.5.3" },
        { slug: "kalman-ekf", title: "Фільтр Калмана", status: "recheck", origin: "embedded/block-7-systems/state-estimation-fusion#7.5.4" },
        { slug: "sensor-fusion-2", title: "Поєднання давачів у польоті", status: "recheck", origin: "embedded/block-7-systems/state-estimation-fusion#7.5.5" },
        { slug: "latency-sync", title: "Затримки й синхро", status: "recheck", origin: "embedded/block-7-systems/state-estimation-fusion#7.5.6" },
        { slug: "odometry", title: "Одометрія", status: "done", levels: ["basic"], origin: "embedded/undefined#5.3.7" },
        { slug: "motion-profiles", title: "Профілі руху", status: "empty", origin: "embedded/undefined#5.9.9" },
        { slug: "roll-pitch-yaw-control", title: "Керування roll/pitch/yaw", status: "done", levels: ["basic"], origin: "embedded/undefined#7.2.3" },
        { slug: "motor-mixer", title: "Мікшер", status: "done", levels: ["basic"], origin: "embedded/undefined#7.2.4" },
        { slug: "instability-stabilization", title: "Потреба стабілізації", status: "done", levels: ["basic"], origin: "embedded/undefined#7.2.5" },
        { slug: "stabilization-cascade", title: "Каскад стабілізації", status: "done", levels: ["basic"], origin: "embedded/undefined#7.2.8" },
        { slug: "missions-waypoints", title: "Місії й точки", status: "empty", origin: "embedded/undefined#7.6.4" },
        { slug: "sense-decide-act-loop", title: "Контур offboard", status: "empty", origin: "embedded/undefined#7.11.4" },
        { slug: "one-stack-many-bodies", title: "Один стек", status: "empty", origin: "embedded/undefined#7.12.1" },
        { slug: "rover-steering", title: "Ровер", status: "empty", origin: "embedded/undefined#7.12.2" },
        { slug: "boat-underwater", title: "Човен і підводний", status: "empty", origin: "embedded/undefined#7.12.5" },
        { slug: "pure-pursuit-navigation", title: "Навігація pure pursuit", status: "empty", origin: "embedded/undefined#7.12.7" },
        { slug: "platform-selection", title: "Вибір платформи", status: "empty", origin: "embedded/undefined#7.12.8" },
        { slug: "mission-planning-map", title: "Планування на карті", status: "empty", origin: "embedded/undefined#7.13.4" },
        { slug: "closing-the-loop", title: "Замкнути контур", status: "empty", origin: "embedded/undefined#7.14.5" },
        { slug: "where-next", title: "Куди далі", status: "empty", origin: "embedded/undefined#7.14.8" },
      ] },
    { slug: "parallel-distributed", title: "Паралельні", scope: "Одночасне виконання на багатьох процесорах зі спільною пам'яттю та системи незалежних вузлів з обміном повідомленнями: примітиви, синхронізація, консенсус, відмовостійкість.",
      topics: [
      ] },
  ]
});
