/* embedded/block-3-digital-processor/manifest.js — per-module маніфест Модуля 3. Складає scripts/bookbuild.js
   (histories[]/extras[] ВИВОДЯТЬСЯ з topics[]). Нумерація — М.Р.Т. */
(window.__MODREG__ = window.__MODREG__ || []).push({
  n: 3, slug: "block-3-digital-processor", title: "Цифрова електроніка й процесор",
  chapters: [
    { n: 1, title: "Логічні рівні: від аналога до цифри", dir: "block-3-digital-processor/logic-levels", main: "logic-levels.md", status: "done",
      scope: "Що таке «0» і «1» як діапазони напруг; завадостійкість і запас рівня; чому цифровий сигнал виживає в шумі; фронти й затримки.",
      topics: [
        { mrt: "3.1.1", title: "Навіщо цифра: аналог тоне в шумі, цифра виживає", status: "done" },
        { mrt: "3.1.2", title: "«0» і «1» — це діапазони напруг, а не точні числа", status: "done" },
        { mrt: "3.1.3", title: "Запас завадостійкості (noise margin)", status: "done" },
        { mrt: "3.1.4", title: "Логічні сімейства й рівні (TTL/CMOS; 5 В / 3.3 В)", status: "done" },
        { mrt: "3.1.5", title: "Фронти й час наростання: чому не миттєво", status: "done" },
        { mrt: "3.1.6", title: "Перетворення аналог→цифра на порозі (компаратор/Шмітт)", status: "done" },
        { kind: "hist", file: "hist-shannon.md", at: "chapter", status: "done", title: "Клод Шеннон: магістерська 1937, що зробила цифрову епоху" },
        { kind: "hist", file: "hist-5-volts.md", at: "3.1.4", status: "done", title: "Чому саме 5 вольтів: спадщина TTL і шлях до 3.3 і 1.8 В" },
        { kind: "math", file: "math-noise-margin.md", at: "3.1.3", status: "done", title: "Бюджет завадостійкості: VOH/VOL/VIH/VIL і noise margin з даташита" },
        { kind: "comp", file: "../../../components/active/logic-74-families/logic-74-families.md", at: "3.1.4", status: "done", title: "Серія 74: 74HC/74HCT/74LVC і чому HCT «розуміє» 5-вольтовий TTL" },
        { kind: "comp", file: "comp-series-termination.md", at: "3.1.5", status: "done", title: "Дзвін на фронті: послідовний резистор 22–33 Ом біля швидких ліній" },
        { kind: "math", file: "math-rise-time.md", at: "3.1.5", status: "done", title: "Фронт і смуга: BW ≈ 0.35/t_r, RC-модель фронту" },
        { kind: "comp", file: "../../../components/active/schmitt-74hc14/schmitt-74hc14.md", at: "3.1.6", status: "done", title: "74HC14: шість інверторів Шмітта — «чистильник» сигналів" },
        { kind: "proj", file: "proj-software-hysteresis.md", at: "3.1.6", status: "done", title: "Гістерезис у коді: програмний тригер Шмітта для зашумленого АЦП" }
      ] },
    { n: 2, title: "Логічні вентилі й комбінаційні схеми", dir: "block-3-digital-processor/logic-gates", main: "logic-gates.md", status: "done",
      scope: "Булева алгебра; базові вентилі; комбінаційна логіка; як зі простих вентилів складають суматори, мультиплексори тощо.",
      topics: [
        { mrt: "3.2.1", title: "Булева алгебра: логіка як математика", status: "done" },
        { mrt: "3.2.2", title: "Базові вентилі: AND, OR, NOT", status: "done" },
        { mrt: "3.2.3", title: "NAND і NOR: універсальні вентилі", status: "done" },
        { mrt: "3.2.4", title: "XOR і логіка порівняння", status: "done" },
        { mrt: "3.2.5", title: "Як із транзисторів роблять вентиль (CMOS)", status: "done" },
        { mrt: "3.2.6", title: "Комбінаційні схеми: суматор, мультиплексор, дешифратор", status: "done" },
        { mrt: "3.2.7", title: "Від вентилів до складних функцій", status: "done" },
        { kind: "hist", file: "hist-boole.md", at: "chapter", status: "done", title: "Джордж Буль: алгебра логіки за 90 років до комп'ютера (1847)" },
        { kind: "hist", file: "hist-apollo-nor.md", at: "3.2.3", status: "done", title: "Комп'ютер «Аполлона» з одного вентиля: NOR, що літав на Місяць" },
        { kind: "math", file: "../../../math/discrete-logic/boolean-algebra/boolean-algebra.md", at: "3.2.1", status: "done", title: "Булева алгебра формально: аксіоми, де Морган, доведення тотожностей" },
        { kind: "comp", file: "comp-74hc-breadboard.md", at: "3.2.2", status: "done", title: "74HC00/08/32 на макетці: розпіновка, живлення, невикористані входи" },
        { kind: "proj", file: "proj-bitwise-c.md", at: "3.2.2", status: "done", title: "Бітові операції в C: маски, set/clear/toggle — вентилі у коді" },
        { kind: "proj", file: "proj-xor-tricks.md", at: "3.2.4", status: "done", title: "XOR-трюки: парність слова, обмін без тимчасової, пошук відмінного біта" },
        { kind: "comp", file: "../../../components/interfaces/74hc138-decoder/74hc138-decoder.md", at: "3.2.6", status: "done", title: "74HC138: дешифратор як chip select — три піни обирають один із восьми" },
        { kind: "math", file: "../../../math/discrete-logic/karnaugh-maps/karnaugh-maps.md", at: "3.2.6", status: "done", title: "Карти Карно: мінімізація логіки руками" },
        { kind: "proj", file: "proj-gate-simulator.md", at: "3.2.6", status: "done", title: "Симулятор вентилів на 100 рядків: повний суматор і таблиця істинності" }
      ] },
    { n: 3, title: "Тригери, регістри й тактування", dir: "block-3-digital-processor/flip-flops-registers", main: "flip-flops-registers.md", status: "done",
      scope: "Засувки й тригери як пам'ять стану; регістр; синхронність і тактовий сигнал; чому потрібен спільний такт; скінченні автомати (Мур/Мілі).",
      topics: [
        { mrt: "3.3.1", title: "Пам'ять стану: схема, що «пам'ятає»", status: "done" },
        { mrt: "3.3.2", title: "Засувка (latch): SR-засувка", status: "done" },
        { mrt: "3.3.3", title: "Тактований D-тригер", status: "done" },
        { mrt: "3.3.4", title: "Фронт vs рівень: чому тактують по фронту", status: "done" },
        { mrt: "3.3.5", title: "Регістр: багато тригерів разом", status: "done" },
        { mrt: "3.3.6", title: "Тактовий сигнал: спільний ритм", status: "done" },
        { mrt: "3.3.7", title: "Лічильники (ділення такту; двійковий рахунок)", status: "done" },
        { mrt: "3.3.8", title: "Метастабільність і таймінг (setup/hold)", status: "done" },
        { mrt: "3.3.9", title: "Скінченні автомати: Мур і Мілі (стан + переходи)", status: "done" },
        { kind: "hist", file: "hist-flip-flop.md", at: "chapter", status: "done", title: "Тригер Екклза–Джордана, 1918 — перша електронна «комірка пам'яті»" },
        { kind: "hist", file: "hist-shift-register-ics.md", at: "3.3.5", status: "done", title: "Від ртутної труби до мікросхеми, що зсуває біти" },
        { kind: "hist", file: "hist-cmos-counters.md", at: "3.3.7", status: "done", title: "Лічильник, який рахує сам: звідки взялися 4017 і 4040" },
        { kind: "hist", file: "hist-metastability.md", at: "3.3.8", status: "done", title: "Метастабільність: явище, в яке інженери відмовлялися вірити (1973)" },
        { kind: "comp", file: "../../../components/interfaces/74hc165-piso/74hc165-piso.md", at: "3.3.5", status: "done", title: "74HC165: вісім кнопок в одну ніжку (паралельний вхід → послідовний)" },
        { kind: "comp", file: "../../../components/interfaces/74hc595-sipo/74hc595-sipo.md", at: "3.3.5", status: "done", title: "74HC595: три ніжки → вісім виходів (каскадування, латч, LED)" },
        { kind: "comp", file: "comp-clock-sources.md", at: "3.3.6", status: "done", title: "Звідки береться такт: кварц, кераміка, RC і MEMS-генератори (ppm)" },
        { kind: "comp", file: "comp-counter-ics.md", at: "3.3.7", status: "done", title: "Лічильники-мікросхеми 74HC4017/4040: біжучий вогник і дільник без МК" },
        { kind: "math", file: "math-timing-budget.md", at: "3.3.8", status: "done", title: "Бюджет таймінгу: t_setup, t_hold, t_clk-to-q — звідки межа частоти" },
        { kind: "proj", file: "proj-two-ff-synchronizer.md", at: "3.3.8", status: "done", title: "Двотригерний синхронізатор: безпечно завести асинхронний сигнал" },
        { kind: "math", file: "../../../math/discrete-logic/fsm-formal/fsm-formal.md", at: "3.3.9", status: "done", title: "Формалізм скінченних автоматів: стани, входи, діаграми переходів" },
        { kind: "proj", file: "proj-fsm-in-code.md", at: "3.3.9", status: "done", title: "Автомат у коді: switch проти таблиці переходів" }
      ] },
    { n: 4, title: "Представлення чисел", dir: "block-3-digital-processor/number-representation", main: "number-representation.md", status: "done",
      scope: "Двійкове й шістнадцяткове; знакові числа (доповняльний код); переповнення; фіксована й плаваюча кома; текст як числа (ASCII/UTF-8).",
      topics: [
        { mrt: "3.4.1", title: "Чому двійкова: два стани надійніші", status: "done" },
        { mrt: "3.4.2", title: "Позиційні системи: двійкова й шістнадцяткова", status: "done" },
        { mrt: "3.4.3", title: "Від'ємні числа: доповняльний код", status: "done" },
        { mrt: "3.4.4", title: "Переповнення (wrap-around; класичний баг)", status: "done" },
        { mrt: "3.4.5", title: "Дробові числа: фіксована кома", status: "done" },
        { mrt: "3.4.6", title: "Плаваюча кома (точність/діапазон)", status: "done" },
        { mrt: "3.4.7", title: "Біти, байти, слова й порядок байтів (endianness)", status: "done" },
        { mrt: "3.4.8", title: "Текст як числа: ASCII і UTF-8", status: "done" },
        { kind: "hist", file: "hist-leibniz.md", at: "chapter", status: "done", title: "Лейбніц і двійкова система (1703): математика задовго до машин" },
        { kind: "hist", file: "hist-modular-arithmetic.md", at: "3.4.3", status: "done", title: "Як годинник став наукою: лишки, конгруенції й доповняльний код" },
        { kind: "hist", file: "hist-ariane5.md", at: "3.4.4", status: "done", title: "Ariane 5 (1996): переповнення на сотні мільйонів доларів" },
        { kind: "hist", file: "hist-patriot.md", at: "3.4.5", status: "done", title: "Patriot у Дахрані (1991): 0.1 секунди, якої немає у двійковій" },
        { kind: "hist", file: "hist-ieee754.md", at: "3.4.6", status: "done", title: "Вільям Кехен і стандарт IEEE 754" },
        { kind: "hist", file: "hist-utf8-diner.md", at: "3.4.8", status: "done", title: "UTF-8 на паперовій підкладці в дайнері: Томпсон і Пайк, 1992" },
        { kind: "math", file: "../../../math/number-systems/modular-arithmetic/modular-arithmetic.md", at: "3.4.3", status: "done", title: "Арифметика за модулем: доповняльний код як залишки mod 2^n" },
        { kind: "proj", file: "proj-overflow-checks.md", at: "3.4.4", status: "done", title: "Ловимо переповнення в C: чому signed overflow — UB і як перевіряти" },
        { kind: "proj", file: "proj-cordic.md", at: "3.4.5", status: "done", title: "CORDIC: синус, косинус і atan2 без FPU — самі зсуви й додавання" },
        { kind: "proj", file: "proj-fixed-point.md", at: "3.4.5", status: "done", title: "Фіксована кома без FPU: Q-формати, множення зі зсувом, насичення" },
        { kind: "math", file: "../../../math/number-systems/ieee754/ieee754.md", at: "3.4.6", status: "done", title: "IEEE 754 докладно: знак, експонента, мантиса, subnormal, NaN та Inf" },
        { kind: "proj", file: "proj-float-compare.md", at: "3.4.6", status: "done", title: "Порівняння float: чому a == b не працює (epsilon, ULP)" },
        { kind: "comp", file: "comp-sensor-byte-order.md", at: "3.4.7", status: "done", title: "Endianness у даташитах давачів: 16-бітне значення двома регістрами" },
        { kind: "proj", file: "proj-serialization.md", at: "3.4.7", status: "done", title: "Серіалізація чисел: упакувати int32 і float у байти (union vs memcpy)" },
        { kind: "proj", file: "proj-utf8-decoder.md", at: "3.4.8", status: "done", title: "UTF-8 декодер вручну: біти-префікси й чому ASCII лишився сумісним" }
      ] },
    { n: 5, title: "Архітектура процесора", dir: "block-3-digital-processor/processor-architecture", main: "processor-architecture.md", status: "done",
      scope: "Лічильник команд, регістри, АЛП, внутрішня шина; цикл «вибірка → декодування → виконання»; конвеєр; що означає «частота» процесора.",
      topics: [
        { mrt: "3.5.1", title: "Що таке процесор: машина, що виконує інструкції", status: "done" },
        { mrt: "3.5.2", title: "Складові: регістри, АЛП, лічильник команд, шина", status: "done" },
        { mrt: "3.5.3", title: "Цикл «вибірка → декодування → виконання»", status: "done" },
        { mrt: "3.5.4", title: "Набір інструкцій (ISA): мова процесора", status: "done" },
        { mrt: "3.5.5", title: "Що означає «частота» процесора", status: "done" },
        { mrt: "3.5.6", title: "Конвеєр: робити кілька кроків водночас", status: "done" },
        { mrt: "3.5.7", title: "Фон Нейман vs Гарвард", status: "done" },
        { mrt: "3.5.8", title: "RISC vs CISC", status: "done" },
        { mrt: "3.5.9", title: "Кеш: чому пам'ять не встигає за ядром", status: "done" },
        { kind: "hist", file: "hist-von-neumann.md", at: "chapter", status: "done", title: "Фон Нейман і збережена програма — ідея, що визначила всі комп'ютери" },
        { kind: "hist", file: "hist-babbage-lovelace.md", at: "3.5.1", status: "done", title: "Беббідж і Ада Лавлейс — перший задуманий комп'ютер і перша програма" },
        { kind: "hist", file: "hist-riscv.md", at: "3.5.4", status: "done", title: "RISC-V: відкрита ISA з Берклі (2010) і чому вона змінила ринок" },
        { kind: "hist", file: "hist-megahertz-myth.md", at: "3.5.5", status: "done", title: "Війна одиниць: від «1 MIPS» (VAX-11/780) до «міфу мегагерців»" },
        { kind: "hist", file: "hist-harvard-architecture.md", at: "3.5.7", status: "done", title: "Звідки взялася «Гарвардська» архітектура" },
        { kind: "proj", file: "proj-toy-cpu-emulator.md", at: "3.5.3", status: "done", title: "Іграшковий процесор-емулятор: 8 інструкцій і цикл fetch–decode–execute" },
        { kind: "comp", file: "comp-isa-in-boards.md", at: "3.5.4", status: "done", title: "Які ISA живуть у хобі-платах: Xtensa, RISC-V, ARM Cortex-M" },
        { kind: "proj", file: "proj-reading-disassembly.md", at: "3.5.4", status: "done", title: "Читаємо дизасемблер: що компілятор зробив із вашим циклом" },
        { kind: "math", file: "math-performance-math.md", at: "3.5.5", status: "done", title: "Арифметика продуктивності: CPI, IPC, MIPS — чому МГц ≠ швидкість" },
        { kind: "math", file: "math-pipeline-hazards.md", at: "3.5.6", status: "done", title: "Конвеєр і хазарди: чому розгалуження ламає потік" },
        { kind: "comp", file: "comp-esp32-buses.md", at: "3.5.7", status: "done", title: "Гарвард на практиці: шини й пам'яті ESP32 (IRAM, DRAM, кеш Flash)" },
        { kind: "proj", file: "proj-cache-friendly-code.md", at: "3.5.9", status: "done", title: "Код, дружній до кешу: чому порядок обходу масиву міняє швидкість" }
      ] },
    { n: 6, title: "Пам'ять, адресація, стек і купа", dir: "block-3-digital-processor/memory-stack-heap", main: "memory-stack-heap.md", status: "done",
      scope: "Карта пам'яті; Flash проти RAM; адреси й покажчики; стек викликів і купа; що фізично відбувається при виклику функції; фізика комірок SRAM/DRAM/Flash.",
      topics: [
        { mrt: "3.6.1", title: "Пам'ять як масив комірок з адресами", status: "done" },
        { mrt: "3.6.2", title: "Карта пам'яті: де що лежить (регіони)", status: "done" },
        { mrt: "3.6.3", title: "Flash vs RAM: постійне й тимчасове", status: "done" },
        { mrt: "3.6.4", title: "Адреси й покажчики", status: "done" },
        { mrt: "3.6.5", title: "Стек: як працює виклик функції (LIFO)", status: "done" },
        { mrt: "3.6.6", title: "Купа й динамічна пам'ять (фрагментація)", status: "done" },
        { mrt: "3.6.7", title: "Переповнення стека й типові біди пам'яті", status: "done" },
        { mrt: "3.6.8", title: "Фізика комірок пам'яті: SRAM, DRAM, floating gate", status: "done" },
        { kind: "hist", file: "hist-core-memory.md", at: "chapter", status: "done", title: "Магнітна пам'ять на осердях (Форрестер, 1950-ті)" },
        { kind: "hist", file: "hist-heartbleed.md", at: "3.6.4", status: "done", title: "Heartbleed (2014): як один пропущений рядок «вицідив» пів інтернету" },
        { kind: "hist", file: "hist-stack-painting.md", at: "3.6.5", status: "done", title: "Звідки взялася «фарба на стеку»: вода, канарки й сторожові байти" },
        { kind: "hist", file: "comp-history-mpu.md", at: "3.6.7", status: "done", title: "Звідки взялися апаратні стіни в пам'яті: від «спільної кімнати» до MPU" },
        { kind: "hist", file: "hist-morris-worm.md", at: "3.6.7", status: "done", title: "Хробак Морріса (1988): переповнення буфера, що зупинило інтернет" },
        { kind: "hist", file: "hist-frohman-eprom.md", at: "3.6.8", status: "done", title: "Дов Фроман і EPROM (1971): пам'ять із кварцовим віконцем під УФ" },
        { kind: "math", file: "../../../math/number-systems/address-space/address-space.md", at: "3.6.1", status: "done", title: "Розрядність адреси: 2^n комірок і чому 32 біти бачать 4 ГіБ" },
        { kind: "comp", file: "comp-real-memory-map.md", at: "3.6.2", status: "done", title: "Карта пам'яті реального МК: SRAM, Flash, периферія у reference manual" },
        { kind: "comp", file: "comp-spi-flash-xip.md", at: "3.6.3", status: "done", title: "Чип W25Q-класу поруч із ESP32: чому прошивка живе в зовнішній флеші" },
        { kind: "proj", file: "proj-pointer-arithmetic.md", at: "3.6.4", status: "done", title: "Покажчики без паніки: арифметика, приведення типів і класичні помилки" },
        { kind: "proj", file: "proj-stack-watermark.md", at: "3.6.5", status: "done", title: "Скільки стека з'їдено: заповнення патерном і high-water mark" },
        { kind: "math", file: "math-fragmentation.md", at: "3.6.6", status: "done", title: "Фрагментація кількісно: зовнішня й внутрішня, чому embedded уникає free()" },
        { kind: "proj", file: "proj-block-pools.md", at: "3.6.6", status: "done", title: "Пули блоків: динамічна пам'ять без фрагментації (O(1) виділення)" },
        { kind: "proj", file: "proj-toy-allocator.md", at: "3.6.6", status: "done", title: "Іграшковий malloc: free list, виділення, злиття сусідніх блоків" },
        { kind: "comp", file: "comp-mpu.md", at: "3.6.7", status: "done", title: "MPU: апаратні стіни між задачами (регіони, права, чому стек не затопить сусіда)" },
        { kind: "comp", file: "../../../components/memory/psram/psram.md", at: "3.6.8", status: "done", title: "PSRAM: додаткові мегабайти по SPI (коли її вмикати)" },
        { kind: "math", file: "math-tunneling.md", at: "3.6.8", status: "done", title: "Тунелювання: електрон крізь ізолятор (Фаулер—Нордгайм, знос Flash)" }
      ] },
    { n: 7, title: "Програмована логіка: ПЛІС/FPGA", dir: "block-3-digital-processor/fpga", main: "fpga.md", status: "done",
      topics: [
        { mrt: "3.7.1", title: "Навіщо програмована логіка: паралельність у залізі", status: "done" },
        { mrt: "3.7.2", title: "Від PAL до FPGA: еволюція програмованих чипів", status: "done" },
        { mrt: "3.7.3", title: "LUT: таблиця істинності замість вентилів", status: "done" },
        { mrt: "3.7.4", title: "Усередині FPGA: логічні блоки, маршрутизація, блочна RAM, DSP", status: "done" },
        { mrt: "3.7.5", title: "HDL: описуємо залізо, а не пишемо програму", status: "done" },
        { mrt: "3.7.6", title: "Потік розробки: синтез → розміщення → трасування → бітстрім", status: "done" },
        { mrt: "3.7.7", title: "Таймінг у FPGA: критичний шлях і обмеження", status: "done" },
        { mrt: "3.7.8", title: "FPGA чи мікроконтролер: чесні критерії вибору", status: "done" },
        { mrt: "3.7.9", title: "М'яке ядро: процесор усередині FPGA", status: "done" },
        { kind: "hist", file: "hist-xilinx.md", at: "chapter", status: "done", title: "Фріман, Вондершмітт і Барнетт засновують Xilinx (1984–85)" },
        { kind: "hist", file: "hist-hdl.md", at: "3.7.5", status: "done", title: "Народження VHDL і Verilog: мова на замовлення Пентагону й мова стартапу" },
        { kind: "comp", file: "comp-fpga-in-the-wild.md", at: "3.7.1", status: "done", title: "Де ви вже зустрічали FPGA: осцилографи, аналізатори, SDR, ретро-консолі" },
        { kind: "comp", file: "comp-greenpak.md", at: "3.7.2", status: "done", title: "Клейова логіка сьогодні: GreenPAK-клас — програмована дрібнота між чіпами" },
        { kind: "math", file: "math-lut-math.md", at: "3.7.3", status: "done", title: "Скільки функцій уміщує LUT: 2^(2^n) і чому 4–6 входів — солодка точка" },
        { kind: "comp", file: "comp-hobby-fpga-boards.md", at: "3.7.4", status: "done", title: "Перші FPGA-плати хобіста: плати iCE40- і Gowin-класу" },
        { kind: "proj", file: "proj-verilog-first-projects.md", at: "3.7.5", status: "done", title: "Перші проєкти на Verilog: мигалка й UART-передавач" },
        { kind: "proj", file: "proj-open-toolchain.md", at: "3.7.6", status: "done", title: "Відкритий тулчейн: Yosys → nextpnr → бітстрім для iCE40" },
        { kind: "math", file: "math-critical-path.md", at: "3.7.7", status: "done", title: "Критичний шлях і slack: звідки береться максимальна частота дизайну" }
      ] },
    { n: 8, title: "Зовнішня пам'ять", dir: "block-3-digital-processor/external-memory", main: "external-memory.md", status: "done",
      topics: [
        { mrt: "3.8.1", title: "Коли вбудованої пам'яті мало: кадри дисплея, аудіо, логи", status: "done" },
        { mrt: "3.8.2", title: "DRAM: транзистор і конденсатор", status: "done" },
        { mrt: "3.8.3", title: "SDRAM і DDR якісно: синхронний інтерфейс, банки, подвійна швидкість", status: "done" },
        { mrt: "3.8.4", title: "Контролер пам'яті: таймінги, регенерація, ініціалізація", status: "done" },
        { mrt: "3.8.5", title: "NOR vs NAND: дві флеші для двох задач (XIP vs сховище)", status: "done" },
        { mrt: "3.8.6", title: "SD-картка зсередини: NAND + контролер", status: "done" },
        { mrt: "3.8.7", title: "eMMC і SSD якісно: FTL — прошарок, що вдає з себе диск", status: "done" },
        { mrt: "3.8.8", title: "EEPROM і FRAM: маленькі сховища налаштувань", status: "done" },
        { mrt: "3.8.9", title: "Як обрати пам'ять для проєкту", status: "done" },
        { kind: "hist", file: "hist-dennard-dram.md", at: "chapter", status: "done", title: "Роберт Деннард: DRAM з одного транзистора (IBM, 1966–68)" },
        { kind: "hist", file: "hist-sd-card-wars.md", at: "3.8.6", status: "done", title: "Війна карток пам'яті: CF, MMC, SD, Memory Stick — як SD перемогла" },
        { kind: "math", file: "math-dram-refresh.md", at: "3.8.2", status: "done", title: "Чому DRAM «тече»: RC-оцінка комірки й мілісекунди до втрати біта" },
        { kind: "comp", file: "comp-ddr-labels.md", at: "3.8.3", status: "done", title: "Читаємо маркування DDR-модуля: що означає DDR4-3200 CL22" },
        { kind: "math", file: "math-bandwidth.md", at: "3.8.3", status: "done", title: "Пропускна здатність пам'яті: такт × ширина × 2 — і де вузьке горло" },
        { kind: "comp", file: "comp-w25q-raw-commands.md", at: "3.8.5", status: "done", title: "NOR-флеш W25Q-класу зблизька: читання, стирання, посторінковий запис" },
        { kind: "proj", file: "proj-toy-ftl.md", at: "3.8.7", status: "done", title: "Іграшковий FTL: таблиця відображення і garbage collection у 100 рядків" }
      ] },
    { n: 9, title: "Коди виявлення й корекції помилок", dir: "block-3-digital-processor/error-correction", main: "error-correction.md", status: "done",
      topics: [
        { mrt: "3.9.1", title: "Звідки беруться перевернуті біти: шум, частинки, зношені комірки", status: "done" },
        { mrt: "3.9.2", title: "Біт парності: найпростіший детектор і його сліпа пляма", status: "done" },
        { mrt: "3.9.3", title: "Контрольні суми: проста сума, Флетчер", status: "done" },
        { mrt: "3.9.4", title: "CRC: чому він скрізь (ділення на многочлен)", status: "done" },
        { mrt: "3.9.5", title: "Відстань Геммінга: скільки помилок видно, а скільки виправно", status: "done" },
        { mrt: "3.9.6", title: "Код Геммінга (7,4): виправляємо один біт на пальцях", status: "done" },
        { mrt: "3.9.7", title: "ECC у RAM і Flash: SECDED у серверах, BCH у NAND", status: "done" },
        { mrt: "3.9.8", title: "Рід–Соломон якісно: символи замість бітів", status: "done" },
        { mrt: "3.9.9", title: "Інженерія надійності даних: що ставити де", status: "done" },
        { kind: "hist", file: "hist-hamming.md", at: "chapter", status: "done", title: "Річард Геммінг: «якщо машина бачить помилку — чому не виправить?»" },
        { kind: "hist", file: "hist-bit-flip-election.md", at: "3.9.1", status: "done", title: "4096 зайвих голосів: перевернутий біт на виборах у Бельгії (2003)" },
        { kind: "hist", file: "hist-voyager-codes.md", at: "3.9.8", status: "done", title: "Вояджери дзвонять додому: каскадні коди в далекому космосі" },
        { kind: "math", file: "math-seu-sel.md", at: "3.9.1", status: "done", title: "SEU/SEL: біт-фліпи від частинок (LET, переріз, чому в космосі гірше)" },
        { kind: "proj", file: "proj-checksums-in-code.md", at: "3.9.3", status: "done", title: "Контрольні суми на практиці: Internet checksum і Флетчер у коді" },
        { kind: "comp", file: "comp-hardware-crc.md", at: "3.9.4", status: "done", title: "Апаратний CRC: блок у МК і CRC усередині SD- та CAN-контролерів" },
        { kind: "math", file: "../../../math/linear-algebra/crc-cyclic-redundancy/crc-cyclic-redundancy.md", at: "3.9.4", status: "done", title: "Математика CRC: многочлени над GF(2), де XOR — і плюс, і мінус" },
        { kind: "proj", file: "proj-crc-implementation.md", at: "3.9.4", status: "done", title: "CRC у коді: бітовий цикл, таблична версія, вибір полінома" },
        { kind: "math", file: "../../../math/linear-algebra/hamming-distance/hamming-distance.md", at: "3.9.5", status: "done", title: "Відстань Геммінга формально: кулі, межі, ціна надлишковості" },
        { kind: "proj", file: "proj-hamming-codec.md", at: "3.9.6", status: "done", title: "Кодер і декодер Геммінга (7,4) у 30 рядків C" },
        { kind: "comp", file: "comp-ecc-hardware.md", at: "3.9.7", status: "done", title: "Де ECC у вашому залізі: 72-бітні серверні DIMM, контролери NAND" }
      ] },
    { n: 10, title: "Як народжується чіп: від піску до корпуса", dir: "block-3-digital-processor/chip-fabrication", main: "chip-fabrication.md", status: "done",
      topics: [
        { mrt: "3.10.1", title: "Кремній: від кварцового піску до монокристала (Чохральський)", status: "done" },
        { mrt: "3.10.2", title: "Фотолітографія: схему друкують світлом", status: "done" },
        { mrt: "3.10.3", title: "Шар за шаром: легування, травлення, метал", status: "done" },
        { mrt: "3.10.4", title: "«5 нанометрів» маркетингу: що насправді означає техпроцес", status: "done" },
        { mrt: "3.10.5", title: "Yield: дефекти як статистика", status: "done" },
        { mrt: "3.10.6", title: "Тестування й binning: один кристал — кілька продуктів", status: "done" },
        { mrt: "3.10.7", title: "Корпусування: wire bonding, flip-chip, QFN/BGA", status: "done" },
        { mrt: "3.10.8", title: "Фаби й fabless: економіка за мільярди", status: "done" },
        { kind: "hist", file: "hist-kilby-noyce.md", at: "chapter", status: "done", title: "Кілбі проти Нойса: хто винайшов інтегральну схему (і планарний процес Ерні)" },
        { kind: "hist", file: "hist-asml-euv.md", at: "3.10.2", status: "done", title: "ASML і EUV: світло з олов'яної плазми — найскладніша машина у виробництві" },
        { kind: "hist", file: "hist-tsmc.md", at: "3.10.8", status: "done", title: "Морріс Чанг і TSMC (1987): фабрика, що працює на всіх" },
        { kind: "proj", file: "proj-place-and-route.md", at: "3.10.2", status: "done", title: "Від схеми до маски: place & route і GDSII — що роблять EDA-алгоритми" },
        { kind: "math", file: "math-yield-math.md", at: "3.10.5", status: "done", title: "Математика yield: дефекти на см², модель Пуассона, чому чиплети рятують" },
        { kind: "comp", file: "comp-chip-markings.md", at: "3.10.6", status: "done", title: "Маркування чіпа: дата-код, ревізія кристала й чому errata прив'язані" },
        { kind: "proj", file: "proj-scan-chain.md", at: "3.10.6", status: "done", title: "Scan chain: як тестер перевіряє мільярд транзисторів через кілька ніжок" },
        { kind: "comp", file: "comp-package-guide.md", at: "3.10.7", status: "done", title: "Гід по корпусах на платі: DIP, SOIC, QFN, BGA — що реально паяти вдома" },
        { kind: "math", file: "math-moore-dennard.md", at: "3.10.8", status: "done", title: "Закон Мура як графік: експонента, її злами й кінець масштабування Деннарда" }
      ] }
  ]
});
