/* book/electronics/manifest.js — книга-предмет «Електроніка» (тип "book").
   Галузі → теми (плейсхолдери: status:"empty", origin = старе розташування для кроку 5).
   Схема: { type, slug, title, sections:[ {slug,title,scope, topics:[ {slug,title,status,origin} ]} ] } */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book",
  slug: "electronics",
  title: "Електроніка",
  sections: [
    { slug: "analog", title: "Аналогова", scope: "Безперервне оброблення сигналів на підсилювальних і пасивних елементах разом із математичним апаратом теорії кіл — законами, методами аналізу та реакцією кіл на сигнали.",
      topics: [
      { slug: "comparator", title: "Компаратор", status: "empty", origin: "components/active/comparator-ics/" },
      { slug: "opamp", title: "Оппідсилювач", status: "empty", origin: "components/active/rail-to-rail-opamp/" },
      { slug: "analog-mux", title: "Аналоговий мультиплексор", status: "empty", origin: "components/active/analog-mux/" },
      { slug: "instrumentation-amp", title: "Інструментальний підсилювач", status: "empty", origin: "components/sensors/undefined" },
      { slug: "ohms-law", title: "Закон Ома", status: "empty", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.2" },
      { slug: "nodes-branches-loops", title: "Вузли й контури", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.1" },
      { slug: "kcl", title: "Закон струмів Кірхгофа", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.2" },
      { slug: "kvl", title: "Закон напруг Кірхгофа", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.3" },
      { slug: "series-connection", title: "Послідовне з'єднання", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.4" },
      { slug: "parallel-connection", title: "Паралельне з'єднання", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.5" },
      { slug: "voltage-divider", title: "Дільник напруги", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.6" },
      { slug: "current-divider", title: "Дільник струму", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.7" },
      { slug: "circuit-analysis", title: "Аналіз кіл", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.8" },
      { slug: "wheatstone-bridge", title: "Міст Вітстона", status: "empty", origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.9" },
      { slug: "internal-resistance", title: "Внутрішній опір", status: "empty", origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.1" },
      { slug: "superposition", title: "Суперпозиція", status: "empty", origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.2" },
      { slug: "thevenin", title: "Теорема Тевеніна", status: "empty", origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.3" },
      { slug: "norton", title: "Теорема Нортона", status: "empty", origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.4" },
      { slug: "thevenin-equivalent", title: "Пошук еквівалента", status: "empty", origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.5" },
      { slug: "power-matching", title: "Узгодження потужності", status: "empty", origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.6" },
      { slug: "schematic-purpose", title: "Принципова схема", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.1" },
      { slug: "component-symbols", title: "Умовні позначення", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.2" },
      { slug: "nodes-connections", title: "Вузли й з'єднання", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.3" },
      { slug: "ground-power-rails", title: "Земля й шини", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.4" },
      { slug: "reading-schematics", title: "Читання схем", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.5" },
      { slug: "rc-time-constant", title: "Стала RC", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.4" },
      { slug: "rl-time-constant", title: "Стала RL", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.4" },
      { slug: "reactance", title: "Реактивність", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.1" },
      { slug: "capacitive-reactance", title: "Опір конденсатора", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.2" },
      { slug: "inductive-reactance", title: "Опір котушки", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.3" },
      { slug: "phase-shift", title: "Зсув фаз", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.4" },
      { slug: "lc-resonance", title: "LC-резонанс", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.5" },
      { slug: "quality-factor", title: "Добротність Q", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.6" },
      { slug: "rlc-selectivity", title: "RLC-вибірковість", status: "empty", origin: "embedded/block-2-components-analog/reactance-resonance#2.3.7" },
      { slug: "frequency-response", title: "Частотна характеристика", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.1" },
      { slug: "rc-low-pass", title: "RC-ФНЧ", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.2" },
      { slug: "rc-high-pass", title: "RC-ФВЧ", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.3" },
      { slug: "decibels", title: "Децибели", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.4" },
      { slug: "bode-plot", title: "Діаграма Боде", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.5" },
      { slug: "bandwidth-3db", title: "Смуга −3 дБ", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.6" },
      { slug: "lc-rlc-filters", title: "LC-фільтри", status: "empty", origin: "embedded/block-2-components-analog/frequency-response#2.4.7" },
      { slug: "transistor-idea", title: "Транзистор", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.1" },
      { slug: "bjt-operation", title: "Робота BJT", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.3" },
      { slug: "bjt-gain", title: "Підсилення β", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.4" },
      { slug: "bjt-regions", title: "Режими BJT", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.5" },
      { slug: "bjt-switch", title: "BJT-ключ", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.6" },
      { slug: "bjt-amplifier", title: "BJT-підсилювач", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.7" },
      { slug: "bjt-load-driving", title: "BJT: навантаження", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.8" },
      { slug: "field-control", title: "Керування полем", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.1" },
      { slug: "bjt-vs-mosfet", title: "BJT проти MOSFET", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.8" },
      { slug: "ideal-opamp", title: "Ідеальний ОП", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.1" },
      { slug: "negative-feedback", title: "Від'ємний ЗЗ", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.2" },
      { slug: "virtual-short", title: "Віртуальне коротке", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.3" },
      { slug: "inverting-noninverting", title: "Інвертуючий підсилювач", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.4" },
      { slug: "voltage-follower", title: "Повторювач", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.5" },
      { slug: "summing-difference-amp", title: "Суматор", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.6" },
      { slug: "comparator-2", title: "Компаратор", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.7" },
      { slug: "schmitt-trigger", title: "Тригер Шмітта", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.8" },
      { slug: "real-opamp-limits", title: "Реальний ОП", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.9" },
      { slug: "differential-pair", title: "Диференційна пара", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.10" },
      { slug: "reference-frequency", title: "Опорна частота", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.1" },
      { slug: "pierce-oscillator", title: "Генератор П'єрса", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.5" },
      { slug: "legendary-ics", title: "Легендарні ІМС", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.1" },
      { slug: "555-internals", title: "Таймер 555", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.2" },
      { slug: "555-astable", title: "555 астабільний", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.3" },
      { slug: "555-monostable", title: "555 моностабільний", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.4" },
      { slug: "voltage-reference", title: "Опорна напруга", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.5" },
      { slug: "analog-switches-mux", title: "Аналогові ключі", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.6" },
      { slug: "instrumentation-amp-2", title: "Інструментальний підсилювач", status: "empty", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.7" },
      { slug: "rc-filter", title: "RC-фільтр", status: "empty", origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.4" }
      ] },
    { slug: "digital", title: "Цифрова", scope: "Логічні схеми на дискретних рівнях і станах разом із цифровим обробленням сигналів — перетворенням дискретизованих сигналів алгоритмами.",
      topics: [
      { slug: "logic-74", title: "Логіка 74", status: "empty", origin: "components/active/logic-74-families/" },
      { slug: "schmitt-trigger", title: "Тригер Шмітта", status: "empty", origin: "components/active/schmitt-74hc14/" },
      { slug: "shift-register", title: "Зсувний регістр", status: "empty", origin: "components/interfaces/undefined" },
      { slug: "level-shifter", title: "Перетворювач рівнів", status: "empty", origin: "components/interfaces/undefined" },
      { slug: "74hc165", title: "74HC165", status: "empty", origin: "components/interfaces/74hc165-piso/" },
      { slug: "74hc595", title: "74HC595", status: "empty", origin: "components/interfaces/74hc595-sipo/" },
      { slug: "74hc138", title: "74HC138", status: "empty", origin: "components/interfaces/74hc138-decoder/" },
      { slug: "gpio-expander", title: "GPIO-розширювач", status: "empty", origin: "components/interfaces/gpio-expander/" },
      { slug: "why-digital", title: "Навіщо цифра", status: "empty", origin: "embedded/block-3-digital-processor/logic-levels#3.1.1" },
      { slug: "logic-levels-as-ranges", title: "Рівні «0» і «1»", status: "empty", origin: "embedded/block-3-digital-processor/logic-levels#3.1.2" },
      { slug: "noise-margin", title: "Запас завадостійкості", status: "empty", origin: "embedded/block-3-digital-processor/logic-levels#3.1.3" },
      { slug: "logic-families", title: "Логічні сімейства", status: "empty", origin: "embedded/block-3-digital-processor/logic-levels#3.1.4" },
      { slug: "edges-rise-time", title: "Фронти й час наростання", status: "empty", origin: "embedded/block-3-digital-processor/logic-levels#3.1.5" },
      { slug: "threshold-schmitt", title: "Поріг і Шмітт", status: "empty", origin: "embedded/block-3-digital-processor/logic-levels#3.1.6" },
      { slug: "basic-gates", title: "Базові вентилі", status: "empty", origin: "embedded/block-3-digital-processor/logic-gates#3.2.2" },
      { slug: "nand-nor", title: "NAND і NOR", status: "empty", origin: "embedded/block-3-digital-processor/logic-gates#3.2.3" },
      { slug: "xor-comparison", title: "XOR", status: "empty", origin: "embedded/block-3-digital-processor/logic-gates#3.2.4" },
      { slug: "cmos-gate", title: "CMOS-вентиль", status: "empty", origin: "embedded/block-3-digital-processor/logic-gates#3.2.5" },
      { slug: "combinational-circuits", title: "Комбінаційні схеми", status: "empty", origin: "embedded/block-3-digital-processor/logic-gates#3.2.6" },
      { slug: "gates-to-functions", title: "Складні функції", status: "empty", origin: "embedded/block-3-digital-processor/logic-gates#3.2.7" },
      { slug: "state-memory", title: "Пам'ять стану", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.1" },
      { slug: "sr-latch", title: "SR-засувка", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.2" },
      { slug: "d-flip-flop", title: "D-тригер", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.3" },
      { slug: "edge-vs-level", title: "Фронт і рівень", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.4" },
      { slug: "register", title: "Регістр", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.5" },
      { slug: "clock-signal", title: "Тактовий сигнал", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.6" },
      { slug: "counters", title: "Лічильники", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.7" },
      { slug: "metastability-timing", title: "Метастабільність", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.8" },
      { slug: "finite-state-machines", title: "Скінченні автомати", status: "empty", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.9" },
      { slug: "programmable-logic", title: "Програмована логіка", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.1" },
      { slug: "pal-to-fpga", title: "Від PAL до FPGA", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.2" },
      { slug: "lut", title: "LUT", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.3" },
      { slug: "inside-fpga", title: "Усередині FPGA", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.4" },
      { slug: "hdl", title: "HDL", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.5" },
      { slug: "fpga-flow", title: "Потік розробки", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.6" },
      { slug: "fpga-timing", title: "Таймінг FPGA", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.7" },
      { slug: "fpga-vs-mcu", title: "FPGA чи МК", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.8" },
      { slug: "soft-core", title: "М'яке ядро", status: "empty", origin: "embedded/block-3-digital-processor/fpga#3.7.9" },
      { slug: "when-memory-runs-out", title: "Коли пам'яті мало", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.1" },
      { slug: "sdram-ddr", title: "SDRAM і DDR", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.3" },
      { slug: "memory-controller", title: "Контролер пам'яті", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.4" },
      { slug: "sd-card", title: "SD-картка", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.6" },
      { slug: "emmc-ssd", title: "eMMC і SSD", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.7" },
      { slug: "choosing-memory", title: "Вибір пам'яті", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.9" },
      { slug: "push-pull-output", title: "Push-pull вихід", status: "empty", origin: "embedded/block-4-mcu-esp32/gpio#4.4.1" },
      { slug: "open-drain", title: "Open-drain", status: "empty", origin: "embedded/block-4-mcu-esp32/gpio#4.4.2" },
      { slug: "logic-thresholds", title: "Логічні пороги", status: "empty", origin: "embedded/block-4-mcu-esp32/gpio#4.4.3" },
      { slug: "floating-pullups", title: "Підтяжки", status: "empty", origin: "embedded/block-4-mcu-esp32/gpio#4.4.4" },
      { slug: "contact-debounce", title: "Дребезг контактів", status: "empty", origin: "embedded/block-4-mcu-esp32/gpio#4.4.5" },
      { slug: "pin-drive-limits", title: "Навантажувальна здатність", status: "empty", origin: "embedded/block-4-mcu-esp32/gpio#4.4.6" },
      { slug: "dac", title: "ЦАП", status: "empty", origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.6" },
      { slug: "adc", title: "АЦП", status: "empty", origin: "embedded/block-4-mcu-esp32/adc#4.8.1" },
      { slug: "sampling-quantization", title: "Дискретизація й квантування", status: "empty", origin: "embedded/block-4-mcu-esp32/adc#4.8.2" },
      { slug: "adc-resolution", title: "Роздільність АЦП", status: "empty", origin: "embedded/block-4-mcu-esp32/adc#4.8.3" },
      { slug: "adc-types", title: "Типи АЦП", status: "empty", origin: "embedded/block-4-mcu-esp32/adc#4.8.8" },
      { slug: "ttl-rs232", title: "TTL і RS-232", status: "empty", origin: "embedded/block-6-comms-radio/uart#6.1.4" },
      { slug: "open-collector", title: "Відкритий колектор", status: "empty", origin: "embedded/block-6-comms-radio/i2c#6.2.2" },
      { slug: "level-shifting", title: "Зсув рівнів", status: "empty", origin: "embedded/undefined#6.12.3" }
      ] },
    { slug: "power-electronics", title: "Силова", scope: "Перетворення й комутація великих потоків електроенергії ключовими приладами, а також формування і стабілізація напруг та струмів для живлення апаратури.",
      topics: [
      { slug: "darlington-uln", title: "Дарлінгтон ULN", status: "empty", origin: "components/active/darlington-uln/" },
      { slug: "gate-driver", title: "Gate driver", status: "empty", origin: "components/active/gate-driver/" },
      { slug: "logic-level-mosfet", title: "Logic-level MOSFET", status: "empty", origin: "components/active/logic-level-mosfet/" },
      { slug: "load-switch", title: "Load switch", status: "empty", origin: "components/active/pmos-load-switch/" },
      { slug: "ideal-diode", title: "Ideal diode", status: "empty", origin: "components/active/ideal-diode-ic/" },
      { slug: "ldo", title: "LDO", status: "empty", origin: "components/active/ldo-module/" },
      { slug: "bridge-rectifier", title: "Діодний міст", status: "empty", origin: "components/active/bridge-rectifier/" },
      { slug: "tl431", title: "TL431", status: "empty", origin: "components/active/tl431/" },
      { slug: "ssr", title: "Твердотільне реле", status: "empty", origin: "components/active/ssr/" },
      { slug: "dc-motor-driver", title: "Драйвер DC-моторів", status: "empty", origin: "components/actuators/undefined" },
      { slug: "stepper-driver", title: "Драйвер крокового", status: "empty", origin: "components/actuators/undefined" },
      { slug: "pwm-expander", title: "PWM-розширювач", status: "empty", origin: "components/actuators/undefined" },
      { slug: "backlight-driver", title: "Драйвер підсвічування", status: "empty", origin: "components/displays/backlight-driver/" },
      { slug: "linear-regulator", title: "Лінійний стабілізатор", status: "empty", origin: "components/power/undefined" },
      { slug: "buck", title: "Buck-перетворювач", status: "empty", origin: "components/power/undefined" },
      { slug: "boost", title: "Boost-перетворювач", status: "empty", origin: "components/power/undefined" },
      { slug: "li-ion-charger", title: "Зарядка Li-ion", status: "empty", origin: "components/power/undefined" },
      { slug: "tp4056", title: "TP4056", status: "empty", origin: "components/power/tp4056-charger/" },
      { slug: "fuel-gauge", title: "Fuel gauge", status: "empty", origin: "components/power/fuel-gauge/" },
      { slug: "cc-resistors", title: "CC-резистори", status: "empty", origin: "components/power/usb-cc-resistors/" },
      { slug: "usb-pd-sink", title: "USB PD sink", status: "empty", origin: "components/power/usb-pd-sink/" },
      { slug: "power-path", title: "Power-path", status: "empty", origin: "components/power/power-path/" },
      { slug: "sync-rectifier", title: "Синхронний випрямляч", status: "empty", origin: "components/power/sync-rectifier/" },
      { slug: "charge-pump", title: "Charge pump", status: "empty", origin: "components/power/charge-pump/" },
      { slug: "wall-adapter", title: "Мережевий адаптер", status: "empty", origin: "components/power/wall-adapter/" },
      { slug: "dc-dc-module", title: "DC-DC модуль", status: "empty", origin: "components/power/dc-dc-module/" },
      { slug: "reverse-polarity", title: "Захист переполюсування", status: "empty", origin: "components/protection/undefined" },
      { slug: "battery-protection", title: "Захист акумулятора", status: "empty", origin: "components/protection/battery-protection-ic/" },
      { slug: "crowbar", title: "Crowbar-захист", status: "empty", origin: "components/protection/crowbar/" },
      { slug: "rectification", title: "Випрямлення", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.6" },
      { slug: "mosfet-power-switch", title: "Силовий ключ", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.6" },
      { slug: "gate-capacitance", title: "Ємність затвора", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.7" },
      { slug: "h-bridge", title: "H-міст", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.10" },
      { slug: "high-side-switch", title: "Верхній ключ", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.11" },
      { slug: "ldo-internals", title: "LDO зсередини", status: "empty", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.11" },
      { slug: "ac-switch-need", title: "Ключі для мережі", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.1" },
      { slug: "thyristor-scr", title: "Тиристор", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.2" },
      { slug: "triac", title: "Симістор", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.3" },
      { slug: "phase-control-dimmer", title: "Фазове керування", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.4" },
      { slug: "zero-cross-switching", title: "Перехід через нуль", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.5" },
      { slug: "solid-state-relay", title: "Твердотільне реле", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.6" },
      { slug: "igbt", title: "IGBT", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.7" },
      { slug: "snubbers-dvdt", title: "Снабери", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.8" },
      { slug: "mains-safety", title: "Безпека з мережею", status: "empty", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.9" },
      { slug: "pwm-power-control", title: "Керування потужністю", status: "empty", origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.5" },
      { slug: "board-consumption", title: "Споживання плати", status: "empty", origin: "embedded/block-4-mcu-esp32/low-power#4.13.8" },
      { slug: "esc", title: "ESC-регулятор", status: "empty", origin: "embedded/block-7-systems/flight-components#7.3.5" },
      { slug: "linear-vs-switching", title: "Лінійний vs імпульсний", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.1" },
      { slug: "switching-converter", title: "Імпульсний перетворювач", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.2" },
      { slug: "power-rails", title: "Шини живлення", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.3" },
      { slug: "batteries", title: "Акумулятори", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.4" },
      { slug: "c-rate", title: "C-rate й опір", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.5" },
      { slug: "cc-cv-bms", title: "Заряд і BMS", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.6" },
      { slug: "energy-budget", title: "Бюджет енергії", status: "empty", origin: "embedded/block-7-systems/power-systems#7.4.7" },
      { slug: "h-bridge-2", title: "H-міст", status: "empty", origin: "embedded/undefined#5.9.2" },
      { slug: "module-power-supply", title: "Живлення модуля", status: "empty", origin: "embedded/undefined#6.12.4" },
      { slug: "companion-power-thermal", title: "Енергія й тепло", status: "empty", origin: "embedded/undefined#7.11.7" },
      { slug: "battery-to-controller", title: "Батарея до контролера", status: "empty", origin: "embedded/undefined#7.14.2" }
      ] },
    { slug: "radio", title: "Радіоелектроніка", scope: "Генерація, передавання й приймання електромагнітних коливань високих частот.",
      topics: [
      { slug: "rf-board-reading", title: "Читання ВЧ-плати", status: "empty", origin: "embedded/block-6-comms-radio/antennas#6.8.7" }
      ] },
    { slug: "microelectronics", title: "Мікроелектроніка", scope: "Фізика напівпровідників і провідності твердих тіл разом із проєктуванням інтегральних схем на кристалі — від принципів активних приладів до топології ІС.",
      topics: [
      { slug: "diodes", title: "Діоди", status: "empty", origin: "components/active/diode-families/" },
      { slug: "bjt", title: "BJT-транзистори", status: "empty", origin: "components/active/bjt-families/" },
      { slug: "body-diode", title: "Body-діод", status: "empty", origin: "components/active/mosfet-body-diode/" },
      { slug: "esd-damage", title: "ESD-пошкодження", status: "empty", origin: "embedded/block-1-circuits-physics/esd-static#1.10.5" },
      { slug: "bjt-structure", title: "Будова BJT", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.2" },
      { slug: "mosfet-structure", title: "Будова MOSFET", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.2" },
      { slug: "mosfet-threshold", title: "Поріг MOSFET", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.3" },
      { slug: "nmos-pmos", title: "NMOS/PMOS", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.4" },
      { slug: "cmos", title: "CMOS", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.9" },
      { slug: "dram-cell", title: "DRAM", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.2" },
      { slug: "nor-vs-nand", title: "NOR і NAND", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.5" },
      { slug: "eeprom-fram", title: "EEPROM і FRAM", status: "empty", origin: "embedded/block-3-digital-processor/external-memory#3.8.8" },
      { slug: "silicon-monocrystal", title: "Кремній і монокристал", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.1" },
      { slug: "photolithography", title: "Фотолітографія", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.2" },
      { slug: "doping-etching-metal", title: "Шар за шаром", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.3" },
      { slug: "process-node", title: "Техпроцес", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.4" },
      { slug: "yield", title: "Yield", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.5" },
      { slug: "testing-binning", title: "Тестування й binning", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.6" },
      { slug: "fabs-fabless", title: "Фаби й fabless", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.8" }
      ] },
    { slug: "components", title: "Компоненти", scope: "Пасивні елементи кіл, їхні параметри, неідеальності та конструкція.",
      topics: [
      { slug: "tvs-diode", title: "TVS-діод", status: "empty", origin: "components/active/tvs-diode/" },
      { slug: "mlcc", title: "MLCC", status: "empty", origin: "components/passive/mlcc/" },
      { slug: "electrolytic-cap", title: "Електролітичний конденсатор", status: "empty", origin: "components/passive/electrolytic/" },
      { slug: "capacitor-marking", title: "Маркування конденсаторів", status: "empty", origin: "components/passive/capacitor-marking/" },
      { slug: "bleeder", title: "Розрядний резистор", status: "empty", origin: "components/passive/bleeder/" },
      { slug: "decoupling", title: "Decoupling-конденсатор", status: "empty", origin: "components/passive/decoupling/" },
      { slug: "supercap", title: "Суперконденсатор", status: "empty", origin: "components/passive/supercap/" },
      { slug: "power-inductor", title: "Силовий дросель", status: "empty", origin: "components/passive/power-inductor/" },
      { slug: "transformer", title: "Трансформатор", status: "empty", origin: "components/passive/transformer/" },
      { slug: "resistor-marking", title: "Маркування резисторів", status: "empty", origin: "components/passive/resistor-marking/" },
      { slug: "wire-gauge", title: "Калібр проводу", status: "empty", origin: "components/passive/wire-gauge/" },
      { slug: "heatsink", title: "Радіатор", status: "empty", origin: "components/passive/heatsink/" },
      { slug: "peltier", title: "Елемент Пельтьє", status: "empty", origin: "components/passive/peltier/" },
      { slug: "magnet-grades", title: "Класи магнітів", status: "empty", origin: "components/passive/magnet-grades/" },
      { slug: "ferrite-bead", title: "Феритова намистина", status: "empty", origin: "components/passive/ferrite-bead/" },
      { slug: "crystal", title: "Кварц", status: "empty", origin: "components/passive/watch-crystal/" },
      { slug: "potentiometer", title: "Потенціометр", status: "empty", origin: "components/passive/potentiometer/" },
      { slug: "packages", title: "Корпуси", status: "empty", origin: "components/passive/packages/" },
      { slug: "smd-marking", title: "Маркування SMD", status: "empty", origin: "components/passive/smd-marking/" },
      { slug: "ptc-fuse", title: "Самовідновний запобіжник", status: "empty", origin: "components/protection/undefined" },
      { slug: "esd-protection", title: "ESD-захист", status: "empty", origin: "components/protection/undefined" },
      { slug: "gdt", title: "Газорозрядник", status: "empty", origin: "components/protection/gas-discharge-tube/" },
      { slug: "varistor", title: "Варистор", status: "empty", origin: "components/protection/mov-varistor/" },
      { slug: "inrush-ntc", title: "Inrush NTC", status: "empty", origin: "components/protection/inrush-ntc/" },
      { slug: "fuse-types", title: "Типи запобіжників", status: "empty", origin: "components/protection/fuse-types/" },
      { slug: "resistor", title: "Резистор", status: "empty", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.7" },
      { slug: "fuses-ptc", title: "Запобіжники", status: "empty", origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.8" },
      { slug: "capacitor", title: "Конденсатор", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.1" },
      { slug: "capacitance", title: "Ємність", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.2" },
      { slug: "capacitor-energy", title: "Енергія конденсатора", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.3" },
      { slug: "capacitor-parasitics", title: "Паразити конденсатора", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.5" },
      { slug: "capacitor-uses", title: "Застосування конденсаторів", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.6" },
      { slug: "capacitors-series-parallel", title: "Конденсатори: з'єднання", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.7" },
      { slug: "supercapacitor", title: "Суперконденсатор", status: "empty", origin: "embedded/block-2-components-analog/capacitor#2.1.8" },
      { slug: "inductor-coil", title: "Котушка", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.1" },
      { slug: "inductance", title: "Індуктивність", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.2" },
      { slug: "inductor-energy", title: "Енергія котушки", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.3" },
      { slug: "inductor-kickback", title: "Брикання котушки", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.5" },
      { slug: "mutual-inductance", title: "Взаємоіндукція", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.6" },
      { slug: "inductor-types", title: "Типи котушок", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.7" },
      { slug: "ferrite-beads", title: "Ферити", status: "empty", origin: "embedded/block-2-components-analog/inductor#2.2.9" },
      { slug: "diode-bias", title: "Зміщення діода", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.4" },
      { slug: "diode-iv-curve", title: "ВАХ діода", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.5" },
      { slug: "zener-schottky", title: "Діоди Зенера", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.8" },
      { slug: "flyback-protection", title: "Захист flyback", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.9" },
      { slug: "rds-on", title: "Опір Rds(on)", status: "empty", origin: "embedded/block-2-components-analog/mosfet#2.7.5" },
      { slug: "datasheet-structure", title: "Структура даташита", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.1" },
      { slug: "abs-max-ratings", title: "Граничні режими", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.2" },
      { slug: "datasheet-graphs", title: "Графіки даташита", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.4" },
      { slug: "packages-pinout", title: "Корпуси й розпіновка", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.5" },
      { slug: "datasheet-fine-print", title: "Дрібний шрифт", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.6" },
      { slug: "datasheet-practice", title: "Практикум даташитів", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.7" },
      { slug: "quartz-resonator", title: "Кварцовий резонатор", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.3" },
      { slug: "quartz-rlc-model", title: "RLC-модель кварцу", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.4" },
      { slug: "frequency-accuracy-ppm", title: "Точність ppm", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.6" },
      { slug: "watch-crystal-rtc", title: "Годинниковий кварц", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.7" },
      { slug: "ceramic-mems-resonators", title: "Керамічні резонатори", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.8" },
      { slug: "tcxo-ocxo", title: "TCXO та OCXO", status: "empty", origin: "embedded/block-2-components-analog/resonators-references#2.10.9" }
      ] },
    { slug: "metrology", title: "Вимірювання", scope: "Методи й засоби кількісного визначення електричних величин і похибок.",
      topics: [
      { slug: "kelvin-shunt", title: "Шунт Кельвіна", status: "empty", origin: "components/passive/kelvin-shunt/" },
      { slug: "electronic-load", title: "Електронне навантаження", status: "empty", origin: "components/power/electronic-load/" },
      { slug: "current-monitor", title: "Монітор струму", status: "empty", origin: "components/sensors/undefined" },
      { slug: "clamp-meter", title: "Струмові кліщі", status: "empty", origin: "components/sensors/clamp-meter/" },
      { slug: "multimeter", title: "Мультиметр", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.6" },
      { slug: "oscilloscope", title: "Осцилограф", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.7" },
      { slug: "measurement-errors", title: "Похибки вимірювань", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.8" },
      { slug: "logic-analyzer", title: "Логічний аналізатор", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.9" },
      { slug: "lab-power-supply", title: "Блок живлення", status: "empty", origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.10" },
      { slug: "sine-on-scope", title: "Синусоїда на осцилографі", status: "empty", origin: "embedded/block-1-circuits-physics/ac-signals#1.7.5" },
      { slug: "noise-hunting", title: "Полювання на заваду", status: "empty", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.9" },
      { slug: "min-typ-max", title: "Min/typ/max", status: "empty", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.3" },
      { slug: "voltage-reference", title: "Опорна напруга", status: "empty", origin: "embedded/block-4-mcu-esp32/adc#4.8.4" },
      { slug: "adc-errors", title: "Похибки АЦП", status: "empty", origin: "embedded/block-4-mcu-esp32/adc#4.8.6" },
      { slug: "measure-consumption", title: "Виміряти споживання", status: "empty", origin: "embedded/block-4-mcu-esp32/low-power#4.13.7" },
      { slug: "calibration", title: "Калібрування", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.6" },
      { slug: "current-voltage-measurement", title: "Вимірювання струму", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.8" },
      { slug: "first-power-up-check", title: "Перша перевірка", status: "empty", origin: "embedded/undefined#6.12.8" },
      { slug: "fault-finding", title: "Пошук несправності", status: "empty", origin: "embedded/undefined#6.12.10" }
      ] },
    { slug: "optoelectronics", title: "Оптоелектроніка", scope: "Прилади перетворення між світлом і електричним сигналом.",
      topics: [
      { slug: "optocoupler", title: "Оптопара", status: "empty", origin: "components/active/optocoupler/" },
      { slug: "led", title: "LED", status: "empty", origin: "components/active/led-practice/" },
      { slug: "oled", title: "OLED-дисплей", status: "empty", origin: "components/displays/ssd1306-oled/" },
      { slug: "tft", title: "TFT-дисплей", status: "empty", origin: "components/displays/spi-tft/" },
      { slug: "eink", title: "E-ink дисплей", status: "empty", origin: "components/displays/eink-module/" },
      { slug: "led-photodiode", title: "Світлодіод", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.7" },
      { slug: "optocoupler-2", title: "Оптопара", status: "empty", origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.10" },
      { slug: "addressable-leds", title: "Адресні світлодіоди", status: "empty", origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.7" },
      { slug: "image-sensor", title: "Сенсор зображення", status: "empty", origin: "embedded/block-7-systems/video-signals-1#7.7.1" },
      { slug: "cmos-matrix", title: "CMOS-матриця", status: "empty", origin: "embedded/block-7-systems/video-signals-1#7.7.2" },
      { slug: "dynamic-range-noise", title: "Динамічний діапазон", status: "empty", origin: "embedded/block-7-systems/video-signals-1#7.7.4" }
      ] },
    { slug: "electromechanics", title: "Електромеханіка", scope: "Перетворення між електричною та механічною енергією у приводах і виконавчих механізмах.",
      topics: [
      { slug: "gearmotor", title: "Мотор-редуктор", status: "empty", origin: "components/actuators/undefined" },
      { slug: "servo", title: "Серво", status: "empty", origin: "components/actuators/undefined" },
      { slug: "solenoid-relay", title: "Соленоїд реле", status: "empty", origin: "components/interfaces/solenoid-relay/" },
      { slug: "relay-driver", title: "Реле і драйвер", status: "empty", origin: "embedded/block-2-components-analog/bjt#2.6.9" },
      { slug: "microphone-speaker", title: "Мікрофон і динамік", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.10" },
      { slug: "bldc-motor", title: "BLDC-мотор", status: "empty", origin: "embedded/block-7-systems/flight-components#7.3.4" },
      { slug: "servo-2", title: "Серво", status: "empty", origin: "embedded/block-7-systems/flight-components#7.3.6" },
      { slug: "brushed-dc-motor", title: "DC-мотор", status: "empty", origin: "embedded/undefined#5.9.1" },
      { slug: "stepper-motor", title: "Кроковий мотор", status: "empty", origin: "embedded/undefined#5.9.3" },
      { slug: "hobby-servo", title: "Серво", status: "empty", origin: "embedded/undefined#5.9.4" },
      { slug: "solenoid-piezo-actuators", title: "Соленоїд і п'єзо", status: "empty", origin: "embedded/undefined#5.9.5" },
      { slug: "motor-current-stall-heat", title: "Заклинювання й нагрів", status: "empty", origin: "embedded/undefined#5.9.6" },
      { slug: "gears-transmission", title: "Редуктори", status: "empty", origin: "embedded/undefined#5.9.7" },
      { slug: "actuator-selection", title: "Вибір актуатора", status: "empty", origin: "embedded/undefined#5.9.8" }
      ] },
    { slug: "sensors", title: "Сенсорика", scope: "Прилади перетворення фізичних величин у вимірюваний електричний сигнал.",
      topics: [
      { slug: "touch-controller", title: "Сенсорний контролер", status: "empty", origin: "components/displays/touch-controller/" },
      { slug: "ntc-thermistor", title: "NTC-термістор", status: "empty", origin: "components/sensors/undefined" },
      { slug: "photo-sensors", title: "Фотодавачі", status: "empty", origin: "components/sensors/undefined" },
      { slug: "hall-current-sensor", title: "Холлівський давач струму", status: "empty", origin: "components/sensors/undefined" },
      { slug: "load-cell", title: "Тензодавач", status: "empty", origin: "components/sensors/undefined" },
      { slug: "ultrasonic-rangefinder", title: "Ультразвуковий далекомір", status: "empty", origin: "components/sensors/undefined" },
      { slug: "tof-sensor", title: "ToF-давач", status: "empty", origin: "components/sensors/undefined" },
      { slug: "imu", title: "IMU-давач", status: "empty", origin: "components/sensors/undefined" },
      { slug: "what-is-a-sensor", title: "Що таке давач", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.1" },
      { slug: "transducer-classes", title: "Класи перетворювачів", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.2" },
      { slug: "piezo-optical-semiconductor", title: "П'єзо й оптичні", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.3" },
      { slug: "sensor-characteristics", title: "Характеристики давача", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.4" },
      { slug: "drift-hysteresis-noise", title: "Дрейф і гістерезис", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.5" },
      { slug: "sensor-input-matching", title: "Узгодження давача", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.7" },
      { slug: "strain-gauges", title: "Тензодавачі", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.9" },
      { slug: "contactless-distance", title: "Безконтактна відстань", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.1" },
      { slug: "tof-ultrasonic", title: "ToF звук", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.2" },
      { slug: "tof-laser", title: "ToF лазер", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.3" },
      { slug: "triangulation", title: "Тріангуляція", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.4" },
      { slug: "reflection-absorption", title: "Відбиття IR", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.5" },
      { slug: "distance-errors", title: "Похибки відстані", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.6" },
      { slug: "environment-sensors", title: "Давачі оточення", status: "empty", origin: "embedded/block-5-sensors-control/distance-environment#5.2.7" },
      { slug: "mems", title: "MEMS", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.1" },
      { slug: "accelerometer", title: "Акселерометр", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.2" },
      { slug: "gyroscope", title: "Гіроскоп", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.3" },
      { slug: "magnetometer", title: "Магнітометр", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.4" },
      { slug: "imu-noise-bias-drift", title: "Шум і дрейф IMU", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.5" },
      { slug: "reading-imu-fifo", title: "Читання IMU", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.7" },
      { slug: "imu-vibration-isolation", title: "Розв'язка IMU", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.8" },
      { slug: "imu-calibration", title: "Калібрування IMU", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.9" },
      { slug: "onboard-sensors", title: "Давачі апарата", status: "empty", origin: "embedded/block-7-systems/flight-components#7.3.1" },
      { slug: "imu-barometer", title: "IMU й барометр", status: "empty", origin: "embedded/block-7-systems/flight-components#7.3.2" },
      { slug: "angle-rotation-sensing", title: "Вимір кута", status: "empty", origin: "embedded/undefined#5.3.1" },
      { slug: "potentiometer-angle-sensor", title: "Потенціометр кута", status: "empty", origin: "embedded/undefined#5.3.2" },
      { slug: "optical-incremental-encoder", title: "Оптичний енкодер", status: "empty", origin: "embedded/undefined#5.3.3" },
      { slug: "quadrature", title: "Квадратура", status: "empty", origin: "embedded/undefined#5.3.4" },
      { slug: "hall-magnetic-encoders", title: "Холл-енкодери", status: "empty", origin: "embedded/undefined#5.3.5" },
      { slug: "absolute-encoder-gray-code", title: "Абсолютний енкодер", status: "empty", origin: "embedded/undefined#5.3.6" },
      { slug: "mox-gas-sensor", title: "MOX-давач", status: "empty", origin: "embedded/undefined#5.10.1" },
      { slug: "ndir-co2", title: "NDIR CO2", status: "empty", origin: "embedded/undefined#5.10.2" },
      { slug: "electrochemical-cell", title: "Електрохімічна комірка", status: "empty", origin: "embedded/undefined#5.10.3" },
      { slug: "dust-aerosol-sensor", title: "Давач пилу", status: "empty", origin: "embedded/undefined#5.10.4" },
      { slug: "uv-light-sensor", title: "УФ-давач", status: "empty", origin: "embedded/undefined#5.10.5" },
      { slug: "geiger-muller-counter", title: "Лічильник Гейгера", status: "empty", origin: "embedded/undefined#5.10.6" },
      { slug: "barometric-altimeter", title: "Барометр-альтиметр", status: "empty", origin: "embedded/undefined#5.10.7" },
      { slug: "cross-sensitivity-compensation", title: "Перехресна чутливість", status: "empty", origin: "embedded/undefined#5.10.8" }
      ] },
    { slug: "pcb", title: "Плати", scope: "Конструювання й технологія друкованих плат і з'єднань разом з електромагнітною сумісністю — керуванням завадами, наведеннями й випромінюванням.",
      topics: [
      { slug: "shielded-cable", title: "Екранований кабель", status: "empty", origin: "components/comms/shielded-cable/" },
      { slug: "ferrite-clamp", title: "Феритова клема", status: "empty", origin: "components/passive/ferrite-clamp/" },
      { slug: "ground-loops", title: "Земляні петлі", status: "empty", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.6" },
      { slug: "shielding", title: "Екранування", status: "empty", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.7" },
      { slug: "twisted-pair", title: "Вита пара", status: "empty", origin: "embedded/block-1-circuits-physics/noise-interference#1.9.8" },
      { slug: "antistatic-workplace", title: "Антистатичне місце", status: "empty", origin: "embedded/block-1-circuits-physics/esd-static#1.10.6" },
      { slug: "esd-packaging", title: "ESD-пакування", status: "empty", origin: "embedded/block-1-circuits-physics/esd-static#1.10.7" },
      { slug: "packaging", title: "Корпусування", status: "empty", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.7" },
      { slug: "datasheet-pinout", title: "Розпіновка й даташит", status: "empty", origin: "embedded/undefined#6.12.1" },
      { slug: "common-ground", title: "Спільна земля", status: "empty", origin: "embedded/undefined#6.12.2" },
      { slug: "cables-connectors", title: "Кабелі й конектори", status: "empty", origin: "embedded/undefined#6.12.6" },
      { slug: "esd-hot-plug", title: "ESD і гаряче підключення", status: "empty", origin: "embedded/undefined#6.12.7" },
      { slug: "basic-soldering", title: "Мінімальна пайка", status: "empty", origin: "embedded/undefined#6.12.9" },
      { slug: "components-buses-on-frame", title: "Компоненти й шини", status: "empty", origin: "embedded/undefined#7.14.3" }
      ] }
  ]
});
