/* manifest — «Електроніка» (тип "book"). Схема — AUTHORING.md §2. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "electronics", title: "Електроніка",
  sections: [
    { slug: "analog", title: "Аналогова", scope: "Безперервне оброблення сигналів на підсилювальних і пасивних елементах разом із математичним апаратом теорії кіл — законами, методами аналізу та реакцією кіл на сигнали.",
      topics: [
        { slug: "comparator", title: "Компаратор", status: "done", origin: "components/active/comparator-ics/" },
        { slug: "opamp", title: "Оппідсилювач", status: "done", levels: ["basic"], origin: "components/active/rail-to-rail-opamp/" },
        { slug: "analog-mux", title: "Аналоговий мультиплексор", status: "recheck", origin: "components/active/analog-mux/" },
        { slug: "instrumentation-amp", title: "Інструментальний підсилювач", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "ohms-law", title: "Закон Ома", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.2" },
        { slug: "nodes-branches-loops", title: "Вузли й контури", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.1", hist: [{ file: "hist-euler-graphs.md", status: "done" }, { file: "hist-kirchhoff.md", status: "done" }], comp: [{ file: "comp-breadboard.md", status: "done" }], proj: [{ file: "proj-graph-traversal.md", status: "update" }] },
        { slug: "kcl", title: "Закон струмів Кірхгофа", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.2" },
        { slug: "kvl", title: "Закон напруг Кірхгофа", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.3" },
        { slug: "series-connection", title: "Послідовне з'єднання", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.4" },
        { slug: "parallel-connection", title: "Паралельне з'єднання", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.5" },
        { slug: "voltage-divider", title: "Дільник напруги", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.6", math: [{ file: "math-tolerance.md", status: "done" }], proj: [{ file: "proj-divider-search.md", status: "done" }] },
        { slug: "current-divider", title: "Дільник струму", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.7" },
        { slug: "circuit-analysis", title: "Аналіз кіл", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.8", hist: [{ file: "hist-maxwell-mesh.md", status: "deeper" }], proj: [{ file: "proj-circuit-sim.md", status: "deeper" }, { file: "proj-mna-spice.md", status: "deeper" }] },
        { slug: "wheatstone-bridge", title: "Міст Вітстона", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/kirchhoff-circuit-analysis#1.4.9", hist: [{ file: "hist-christie-wheatstone.md", status: "done" }], math: [{ file: "math-bridge-sensitivity.md", status: "done" }] },
        { slug: "internal-resistance", title: "Внутрішній опір", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.1", hist: [{ file: "hist-thevenin-norton.md", status: "done" }], comp: [{ file: "comp-source-impedances.md", status: "deeper" }], math: [{ file: "math-load-line.md", status: "deeper" }] },
        { slug: "superposition", title: "Суперпозиція", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.2" },
        { slug: "thevenin", title: "Теорема Тевеніна", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.3" },
        { slug: "norton", title: "Теорема Нортона", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.4" },
        { slug: "thevenin-equivalent", title: "Пошук еквівалента", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.5", proj: [{ file: "proj-two-load-method.md", status: "update" }] },
        { slug: "power-matching", title: "Узгодження потужності", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/equivalent-circuits#1.5.6", hist: [{ file: "hist-50-ohm.md", status: "done" }], comp: [{ file: "comp-terminator.md", status: "done" }], math: [{ file: "math-derivative-max.md", status: "done" }] },
        { slug: "schematic-purpose", title: "Принципова схема", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.1", hist: [{ file: "hist-instruments.md", status: "done" }], comp: [{ file: "comp-workbench.md", status: "done" }] },
        { slug: "component-symbols", title: "Умовні позначення", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.2" },
        { slug: "nodes-connections", title: "Вузли й з'єднання", status: "update", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.3", proj: [{ file: "proj-netlist-erc.md", status: "update" }] },
        { slug: "ground-power-rails", title: "Земля й шини", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.4", hist: [{ file: "hist-earth-return.md", status: "done" }] },
        { slug: "reading-schematics", title: "Читання схем", status: "deeper", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.5" },
        { slug: "rc-time-constant", title: "Стала RC", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.4", math: [{ file: "math-exponential-ode.md", status: "done" }], proj: [{ file: "proj-capacitance-meter.md", status: "done" }] },
        { slug: "rl-time-constant", title: "Стала RL", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.4", math: [{ file: "math-rl-ode.md", status: "done" }], proj: [{ file: "proj-inductance-meter.md", status: "done" }] },
        { slug: "reactance", title: "Реактивність", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.1", hist: [{ file: "hist-tuned-circuit.md", status: "done" }], math: [{ file: "math-complex-phasors.md", status: "done" }] },
        { slug: "capacitive-reactance", title: "Опір конденсатора", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.2", comp: [{ file: "comp-capacitive-dropper.md", status: "done" }] },
        { slug: "inductive-reactance", title: "Опір котушки", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.3", comp: [{ file: "comp-lc-supply-filter.md", status: "done" }] },
        { slug: "phase-shift", title: "Зсув фаз", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.4", math: [{ file: "math-impedance.md", status: "done" }, { file: "math-power-triangle.md", status: "done" }, { file: "math-sine-derivative.md", status: "done" }], proj: [{ file: "proj-lissajous.md", status: "done" }] },
        { slug: "lc-resonance", title: "LC-резонанс", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.5", math: [{ file: "math-thomson-formula.md", status: "done" }], proj: [{ file: "proj-resonance-sweep.md", status: "done" }] },
        { slug: "quality-factor", title: "Добротність Q", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.6", hist: [{ file: "hist-tacoma.md", status: "done" }], math: [{ file: "math-damping.md", status: "done" }, { file: "math-q-factor.md", status: "done" }] },
        { slug: "rlc-selectivity", title: "RLC-вибірковість", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reactance-resonance#2.3.7" },
        { slug: "frequency-response", title: "Частотна характеристика", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.1", hist: [{ file: "hist-bode.md", status: "done" }], comp: [{ file: "comp-breadboard-parasitics.md", status: "done" }, { file: "comp-scope-probe.md", status: "done" }] },
        { slug: "rc-low-pass", title: "RC-ФНЧ", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.2", comp: [{ file: "comp-input-rc.md", status: "done" }], math: [{ file: "math-transfer-function.md", status: "done" }] },
        { slug: "rc-high-pass", title: "RC-ФВЧ", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.3", comp: [{ file: "comp-coupling-cap.md", status: "done" }] },
        { slug: "decibels", title: "Децибели", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.4", hist: [{ file: "hist-decibel.md", status: "done" }], math: [{ file: "math-logarithms.md", status: "done" }] },
        { slug: "bode-plot", title: "Діаграма Боде", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.5", proj: [{ file: "proj-bode-measurement.md", status: "update" }] },
        { slug: "bandwidth-3db", title: "Смуга −3 дБ", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.6", math: [{ file: "math-half-power.md", status: "done" }, { file: "math-risetime-bandwidth.md", status: "done" }] },
        { slug: "lc-rlc-filters", title: "LC-фільтри", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/frequency-response#2.4.7", comp: [{ file: "comp-speaker-crossover.md", status: "done" }], math: [{ file: "math-cascading.md", status: "done" }] },
        { slug: "transistor-idea", title: "Транзистор", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.1", hist: [{ file: "hist-traitorous-eight.md", status: "done" }, { file: "hist-transistor.md", status: "done" }] },
        { slug: "bjt-operation", title: "Робота BJT", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.3" },
        { slug: "bjt-gain", title: "Підсилення β", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.4", proj: [{ file: "proj-measure-hfe.md", status: "done" }] },
        { slug: "bjt-regions", title: "Режими BJT", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.5" },
        { slug: "bjt-switch", title: "BJT-ключ", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.6", comp: [{ file: "comp-high-side-pnp.md", status: "deeper" }], math: [{ file: "math-base-resistor.md", status: "deeper" }] },
        { slug: "bjt-amplifier", title: "BJT-підсилювач", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.7", comp: [{ file: "comp-common-emitter.md", status: "done" }], math: [{ file: "math-load-line.md", status: "done" }] },
        { slug: "bjt-load-driving", title: "BJT: навантаження", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.8", hist: [{ file: "hist-tr1-sony.md", status: "done" }], comp: [{ file: "comp-darlington-uln.md", status: "done" }] },
        { slug: "field-control", title: "Керування полем", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.1", hist: [{ file: "hist-mosfet.md", status: "done" }] },
        { slug: "bjt-vs-mosfet", title: "BJT проти MOSFET", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.8" },
        { slug: "ideal-opamp", title: "Ідеальний ОП", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.1", hist: [{ file: "hist-opamp.md", status: "done" }] },
        { slug: "negative-feedback", title: "Від'ємний ЗЗ", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.2", hist: [{ file: "hist-harold-black.md", status: "done" }], math: [{ file: "math-feedback-formula.md", status: "done" }] },
        { slug: "virtual-short", title: "Віртуальне коротке", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.3" },
        { slug: "inverting-noninverting", title: "Інвертуючий підсилювач", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.4" },
        { slug: "voltage-follower", title: "Повторювач", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.5", comp: [{ file: "comp-buffer-divider.md", status: "done" }], math: [{ file: "math-cap-load.md", status: "done" }] },
        { slug: "summing-difference-amp", title: "Суматор", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.6", proj: [{ file: "proj-signal-scaling.md", status: "done" }] },
        { slug: "comparator-2", title: "Компаратор", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.7", comp: [{ file: "comp-comparator-ics.md", status: "done" }] },
        { slug: "schmitt-trigger", title: "Тригер Шмітта", status: "recheck", origin: "embedded/block-2-components-analog/opamp-comparator#2.8.8" },
        { slug: "real-opamp-limits", title: "Реальний ОП", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.9", math: [{ file: "math-gbw-slew.md", status: "done" }, { file: "math-noise-budget.md", status: "done" }] },
        { slug: "differential-pair", title: "Диференційна пара", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.10", math: [{ file: "math-current-mirror.md", status: "done" }] },
        { slug: "reference-frequency", title: "Опорна частота", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.1", hist: [{ file: "hist-pierce-ft243.md", status: "done" }], comp: [{ file: "comp-internal-rc.md", status: "done" }] },
        { slug: "pierce-oscillator", title: "Генератор П'єрса", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.5", comp: [{ file: "comp-crystal-layout.md", status: "done" }], proj: [{ file: "proj-oscillator-debug.md", status: "done" }] },
        { slug: "legendary-ics", title: "Легендарні ІМС", status: "recheck", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.1", hist: [{ file: "hist-camenzind-555.md", status: "recheck" }], comp: [{ file: "comp-ic-naming.md", status: "recheck" }] },
        { slug: "555-internals", title: "Таймер 555", status: "recheck", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.2", comp: [{ file: "comp-555-versions.md", status: "recheck" }] },
        { slug: "555-astable", title: "555 астабільний", status: "recheck", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.3", math: [{ file: "math-astable-formulas.md", status: "recheck" }] },
        { slug: "555-monostable", title: "555 моностабільний", status: "recheck", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.4", proj: [{ file: "proj-monostable.md", status: "recheck" }] },
        { slug: "voltage-reference", title: "Опорна напруга", status: "recheck", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.5" },
        { slug: "analog-switches-mux", title: "Аналогові ключі", status: "recheck", origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.6", proj: [{ file: "proj-mux-scanning.md", status: "recheck" }] },
        { slug: "instrumentation-amp-2", title: "Інструментальний підсилювач", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/legendary-analog-ics#2.12.7", comp: [{ file: "comp-inamp-bridge.md", status: "done" }], math: [{ file: "math-inamp-cmrr.md", status: "done" }] },
        { slug: "rc-filter", title: "RC-фільтр", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.4", math: [{ file: "math-rc-design.md", status: "done" }] },
      ] },
    { slug: "digital", title: "Цифрова", scope: "Логічні схеми на дискретних рівнях і станах разом із цифровим обробленням сигналів — перетворенням дискретизованих сигналів алгоритмами.",
      topics: [
        { slug: "logic-74", title: "Логіка 74", status: "recheck", origin: "components/active/logic-74-families/" },
        { slug: "schmitt-trigger", title: "Тригер Шмітта", status: "done", levels: ["basic"], origin: "components/active/schmitt-74hc14/", math: [{ file: "math-hysteresis-calc.md", status: "done" }], proj: [{ file: "proj-light-threshold.md", status: "done" }] },
        { slug: "shift-register", title: "Зсувний регістр", status: "done", levels: ["basic"], origin: "components/interfaces/undefined" },
        { slug: "level-shifter", title: "Перетворювач рівнів", status: "done", levels: ["basic"], origin: "components/interfaces/undefined" },
        { slug: "74hc165", title: "74HC165", status: "recheck", origin: "components/interfaces/74hc165-piso/" },
        { slug: "74hc595", title: "74HC595", status: "recheck", origin: "components/interfaces/74hc595-sipo/", comp: [{ file: "comp-74hc165.md", status: "empty" }] },
        { slug: "74hc138", title: "74HC138", status: "recheck", origin: "components/interfaces/74hc138-decoder/" },
        { slug: "gpio-expander", title: "GPIO-розширювач", status: "recheck", origin: "components/interfaces/gpio-expander/" },
        { slug: "why-digital", title: "Навіщо цифра", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-levels#3.1.1", hist: [{ file: "hist-shannon.md", status: "done" }] },
        { slug: "logic-levels-as-ranges", title: "Рівні «0» і «1»", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-levels#3.1.2" },
        { slug: "noise-margin", title: "Запас завадостійкості", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-levels#3.1.3", math: [{ file: "math-noise-margin.md", status: "done" }] },
        { slug: "logic-families", title: "Логічні сімейства", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-levels#3.1.4", hist: [{ file: "hist-5-volts.md", status: "done" }] },
        { slug: "edges-rise-time", title: "Фронти й час наростання", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-levels#3.1.5", comp: [{ file: "comp-series-termination.md", status: "done" }], math: [{ file: "math-rise-time.md", status: "done" }] },
        { slug: "threshold-schmitt", title: "Поріг і Шмітт", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-levels#3.1.6", proj: [{ file: "proj-software-hysteresis.md", status: "done" }] },
        { slug: "basic-gates", title: "Базові вентилі", status: "update", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-gates#3.2.2", comp: [{ file: "comp-74hc-breadboard.md", status: "done" }], proj: [{ file: "proj-bitwise-c.md", status: "done" }] },
        { slug: "nand-nor", title: "NAND і NOR", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-gates#3.2.3", hist: [{ file: "hist-apollo-nor.md", status: "done" }] },
        { slug: "xor-comparison", title: "XOR", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-gates#3.2.4", proj: [{ file: "proj-xor-tricks.md", status: "done" }] },
        { slug: "cmos-gate", title: "CMOS-вентиль", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-gates#3.2.5" },
        { slug: "combinational-circuits", title: "Комбінаційні схеми", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/logic-gates#3.2.6", proj: [{ file: "proj-gate-simulator.md", status: "done" }] },
        { slug: "gates-to-functions", title: "Складні функції", status: "recheck", origin: "embedded/block-3-digital-processor/logic-gates#3.2.7" },
        { slug: "state-memory", title: "Пам'ять стану", status: "recheck", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.1", hist: [{ file: "hist-flip-flop.md", status: "recheck" }] },
        { slug: "sr-latch", title: "SR-засувка", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.2" },
        { slug: "d-flip-flop", title: "D-тригер", status: "done", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.3" },
        { slug: "edge-vs-level", title: "Фронт і рівень", status: "recheck", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.4" },
        { slug: "register", title: "Регістр", status: "recheck", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.5", hist: [{ file: "hist-shift-register-ics.md", status: "recheck" }], comp: [{ file: "comp-74hc165.md", status: "done" }] },
        { slug: "clock-signal", title: "Тактовий сигнал", status: "recheck", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.6", comp: [{ file: "comp-clock-sources.md", status: "recheck" }] },
        { slug: "counters", title: "Лічильники", status: "recheck", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.7", hist: [{ file: "hist-cmos-counters.md", status: "recheck" }], comp: [{ file: "comp-counter-ics.md", status: "recheck" }] },
        { slug: "metastability-timing", title: "Метастабільність", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.8", hist: [{ file: "hist-metastability.md", status: "done" }], math: [{ file: "math-timing-budget.md", status: "done" }], proj: [{ file: "proj-two-ff-synchronizer.md", status: "done" }] },
        { slug: "finite-state-machines", title: "Скінченні автомати", status: "recheck", origin: "embedded/block-3-digital-processor/flip-flops-registers#3.3.9", proj: [{ file: "proj-fsm-in-code.md", status: "recheck" }] },
        { slug: "programmable-logic", title: "Програмована логіка", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.1", hist: [{ file: "hist-xilinx.md", status: "recheck" }], comp: [{ file: "comp-fpga-in-the-wild.md", status: "recheck" }] },
        { slug: "pal-to-fpga", title: "Від PAL до FPGA", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.2", comp: [{ file: "comp-greenpak.md", status: "recheck" }] },
        { slug: "lut", title: "LUT", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.3", math: [{ file: "math-lut-math.md", status: "recheck" }] },
        { slug: "inside-fpga", title: "Усередині FPGA", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.4", comp: [{ file: "comp-hobby-fpga-boards.md", status: "recheck" }] },
        { slug: "hdl", title: "HDL", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.5", hist: [{ file: "hist-hdl.md", status: "recheck" }], proj: [{ file: "proj-verilog-first-projects.md", status: "recheck" }] },
        { slug: "fpga-flow", title: "Потік розробки", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.6", proj: [{ file: "proj-open-toolchain.md", status: "recheck" }] },
        { slug: "fpga-timing", title: "Таймінг FPGA", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.7", math: [{ file: "math-critical-path.md", status: "recheck" }] },
        { slug: "fpga-vs-mcu", title: "FPGA чи МК", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.8" },
        { slug: "soft-core", title: "М'яке ядро", status: "recheck", origin: "embedded/block-3-digital-processor/fpga#3.7.9" },
        { slug: "when-memory-runs-out", title: "Коли пам'яті мало", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.1", hist: [{ file: "hist-dennard-dram.md", status: "recheck" }] },
        { slug: "sdram-ddr", title: "SDRAM і DDR", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.3", comp: [{ file: "comp-ddr-labels.md", status: "recheck" }], math: [{ file: "math-bandwidth.md", status: "recheck" }] },
        { slug: "memory-controller", title: "Контролер пам'яті", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.4" },
        { slug: "sd-card", title: "SD-картка", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.6", hist: [{ file: "hist-sd-card-wars.md", status: "recheck" }] },
        { slug: "emmc-ssd", title: "eMMC і SSD", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.7", proj: [{ file: "proj-toy-ftl.md", status: "recheck" }] },
        { slug: "choosing-memory", title: "Вибір пам'яті", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.9" },
        { slug: "push-pull-output", title: "Push-pull вихід", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/gpio#4.4.1" },
        { slug: "open-drain", title: "Open-drain", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/gpio#4.4.2" },
        { slug: "logic-thresholds", title: "Логічні пороги", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/gpio#4.4.3" },
        { slug: "floating-pullups", title: "Підтяжки", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/gpio#4.4.4", math: [{ file: "math-pullup-value.md", status: "done" }] },
        { slug: "contact-debounce", title: "Брязкіт контактів", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/gpio#4.4.5", hist: [{ file: "hist-relay-bounce.md", status: "done" }], comp: [{ file: "comp-tact-button.md", status: "done" }], proj: [{ file: "proj-debounce.md", status: "update" }] },
        { slug: "pin-drive-limits", title: "Навантажувальна здатність", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/gpio#4.4.6", math: [{ file: "math-pin-budget.md", status: "deeper" }] },
        { slug: "dac", title: "ЦАП", status: "done", origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.6", comp: [{ file: "comp-external-dac.md", status: "recheck" }] },
        { slug: "adc", title: "АЦП", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.1", hist: [{ file: "hist-sampling.md", status: "done" }] },
        { slug: "sampling-quantization", title: "Дискретизація й квантування", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.2", math: [{ file: "math-quantization-noise.md", status: "done" }, { file: "math-enob.md", status: "done" }] },
        { slug: "adc-resolution", title: "Роздільність АЦП", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.3", math: [{ file: "math-dithering.md", status: "done" }, { file: "math-enob.md", status: "done" }] },
        { slug: "adc-types", title: "Типи АЦП", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.8", hist: [{ file: "hist-delta-sigma.md", status: "done" }], proj: [{ file: "proj-sar-search.md", status: "done" }] },
        { slug: "ttl-rs232", title: "TTL і RS-232", status: "recheck", origin: "embedded/block-6-comms-radio/uart#6.1.4" },
        { slug: "open-collector", title: "Відкритий колектор", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/i2c#6.2.2" },
        { slug: "level-shifting", title: "Зсув рівнів", status: "done", levels: ["basic"], origin: "embedded/undefined#6.12.3" },
      ] },
    { slug: "power-electronics", title: "Силова", scope: "Перетворення й комутація великих потоків електроенергії ключовими приладами, а також формування і стабілізація напруг та струмів для живлення апаратури.",
      topics: [
        { slug: "darlington-uln", title: "Дарлінгтон ULN", status: "done", levels: ["basic"], origin: "components/active/darlington-uln/" },
        { slug: "gate-driver", title: "Gate driver", status: "recheck", origin: "components/active/gate-driver/" },
        { slug: "logic-level-mosfet", title: "Logic-level MOSFET", status: "done", levels: ["basic"], origin: "components/active/logic-level-mosfet/" },
        { slug: "load-switch", title: "Load switch", status: "recheck", origin: "components/active/pmos-load-switch/", comp: [{ file: "comp-body-diode.md", status: "done" }] },
        { slug: "ideal-diode", title: "Ideal diode", status: "done", levels: ["basic"], origin: "components/active/ideal-diode-ic/", comp: [{ file: "comp-body-diode.md", status: "done" }, { file: "comp-pmos-load-switch.md", status: "done" }, { file: "comp-logic-level.md", status: "done" }] },
        { slug: "ldo", title: "LDO", status: "done", origin: "components/active/ldo-module/" },
        { slug: "bridge-rectifier", title: "Діодний міст", status: "done", levels: ["basic"], origin: "components/active/bridge-rectifier/" },
        { slug: "tl431", title: "TL431", status: "done", levels: ["basic"], origin: "components/active/tl431/" },
        { slug: "ssr", title: "Твердотільне реле", status: "recheck", origin: "components/active/ssr/" },
        { slug: "dc-motor-driver", title: "Драйвер DC-моторів", status: "done", levels: ["basic"], origin: "components/actuators/undefined" },
        { slug: "stepper-driver", title: "Драйвер крокового", status: "empty", origin: "components/actuators/undefined" },
        { slug: "pwm-expander", title: "PWM-розширювач", status: "empty", origin: "components/actuators/undefined" },
        { slug: "backlight-driver", title: "Драйвер підсвічування", status: "recheck", origin: "components/displays/backlight-driver/" },
        { slug: "linear-regulator", title: "Лінійний стабілізатор", status: "recheck", origin: "embedded/block-10-power-energy/converter-topologies#10.1.1" },
        { slug: "buck", title: "Buck-перетворювач", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/converter-topologies#10.1.2", comp: [{ file: "comp-sync-vs-async.md", status: "done" }], math: [{ file: "math-inductor-ripple.md", status: "done" }, { file: "math-volt-second.md", status: "done" }] },
        { slug: "boost", title: "Boost-перетворювач", status: "done", origin: "embedded/block-10-power-energy/converter-topologies#10.1.3" },
        { slug: "buck-boost", title: "Buck-boost", status: "recheck", origin: "embedded/block-10-power-energy/converter-topologies#10.1.4" },
        { slug: "charge-pump-conv", title: "Заряд-помпа", status: "recheck", origin: "embedded/block-10-power-energy/converter-topologies#10.1.5", comp: [{ file: "comp-charge-pumps.md", status: "done" }] },
        { slug: "flyback-isolated", title: "Flyback", status: "recheck", origin: "embedded/block-10-power-energy/converter-topologies#10.1.6", comp: [{ file: "comp-wall-adapter.md", status: "done" }] },
        { slug: "topology-map", title: "Вибір топології", status: "recheck", origin: "embedded/block-10-power-energy/converter-topologies#10.1.7", math: [{ file: "math-efficiency-chain.md", status: "recheck" }] },
        { slug: "converter-spec", title: "ТЗ перетворювача", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/converter-design#10.2.1" },
        { slug: "controller-fsw", title: "Контролер і частота", status: "recheck", origin: "embedded/block-10-power-energy/converter-design#10.2.2", comp: [{ file: "comp-power-modules.md", status: "done" }] },
        { slug: "converter-inductor", title: "Котушка перетворювача", status: "recheck", origin: "embedded/block-10-power-energy/converter-design#10.2.3", math: [{ file: "math-inductor-selection.md", status: "recheck" }] },
        { slug: "converter-caps", title: "Конденсатори перетворювача", status: "recheck", origin: "embedded/block-10-power-energy/converter-design#10.2.4", math: [{ file: "math-ripple-esr.md", status: "recheck" }] },
        { slug: "feedback-stability", title: "Зворотний зв'язок", status: "recheck", origin: "embedded/block-10-power-energy/converter-design#10.2.5", math: [{ file: "math-load-step.md", status: "recheck" }] },
        { slug: "converter-layout", title: "Розведення перетворювача", status: "recheck", origin: "embedded/block-10-power-energy/converter-design#10.2.6" },
        { slug: "converter-measure", title: "Вимірювання перетворювача", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/converter-design#10.2.7", comp: [{ file: "comp-electronic-load.md", status: "done" }], proj: [{ file: "proj-efficiency-sweep.md", status: "update" }] },
        { slug: "converter-faults", title: "Хвороби перетворювача", status: "recheck", origin: "embedded/block-10-power-energy/converter-design#10.2.8" },
        { slug: "usb-power-map", title: "Живлення через USB", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.1", hist: [{ file: "hist-one-charger.md", status: "recheck" }] },
        { slug: "type-c-cc", title: "Type-C без PD", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.2", comp: [{ file: "comp-cc-resistors.md", status: "done" }] },
        { slug: "usb-pd", title: "USB Power Delivery", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.3" },
        { slug: "pd-sink-design", title: "PD у пристрої", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.4", proj: [{ file: "proj-pd-state-machine.md", status: "recheck" }] },
        { slug: "legacy-charging", title: "Легасі-зарядка", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.5" },
        { slug: "powerbank-source", title: "Свій павербанк", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.6" },
        { slug: "usb-cables-field", title: "Кабелі й сумісність", status: "recheck", origin: "embedded/block-10-power-energy/usb-power#10.3.7", math: [{ file: "math-cable-drop.md", status: "recheck" }] },
        { slug: "battery-chemistries", title: "Хімії батарей", status: "recheck", origin: "embedded/block-10-power-energy/batteries-charging#10.4.1", hist: [{ file: "hist-plante-jungner.md", status: "recheck" }] },
        { slug: "battery-sag", title: "Просадка під навантаженням", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/batteries-charging#10.4.2", math: [{ file: "math-sag-calc.md", status: "done" }] },
        { slug: "li-ion-charger", title: "Зарядка Li-ion", status: "done", origin: "embedded/block-10-power-energy/batteries-charging#10.4.3" },
        { slug: "state-of-charge", title: "Заряд, що лишився", status: "recheck", origin: "embedded/block-10-power-energy/batteries-charging#10.4.4", proj: [{ file: "proj-coulomb-counting.md", status: "recheck" }] },
        { slug: "battery-aging", title: "Старіння батарей", status: "recheck", origin: "embedded/block-10-power-energy/batteries-charging#10.4.5" },
        { slug: "bms", title: "Захист і BMS", status: "recheck", origin: "embedded/block-10-power-energy/batteries-charging#10.4.6" },
        { slug: "battery-mechanics", title: "Механіка й безпека", status: "recheck", origin: "embedded/block-10-power-energy/batteries-charging#10.4.7" },
        { slug: "photovoltaic-cell", title: "Фотоелемент", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/solar-mppt#10.5.1", hist: [{ file: "hist-bell-solar.md", status: "done" }] },
        { slug: "panel-iv-mpp", title: "ВАХ панелі", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/solar-mppt#10.5.2" },
        { slug: "real-sun-mppt", title: "Реальне сонце", status: "done", levels: ["basic"], origin: "embedded/block-10-power-energy/solar-mppt#10.5.3" },
        { slug: "tp4056", title: "TP4056", status: "recheck", origin: "components/power/tp4056-charger/" },
        { slug: "fuel-gauge", title: "Fuel gauge", status: "recheck", origin: "components/power/fuel-gauge/" },
        { slug: "cc-resistors", title: "CC-резистори", status: "recheck", origin: "components/power/usb-cc-resistors/" },
        { slug: "usb-pd-sink", title: "USB PD sink", status: "recheck", origin: "components/power/usb-pd-sink/" },
        { slug: "power-path", title: "Power-path", status: "recheck", origin: "components/power/power-path/" },
        { slug: "sync-rectifier", title: "Синхронний випрямляч", status: "recheck", origin: "components/power/sync-rectifier/" },
        { slug: "charge-pump", title: "Charge pump", status: "recheck", origin: "components/power/charge-pump/" },
        { slug: "wall-adapter", title: "Мережевий адаптер", status: "recheck", origin: "components/power/wall-adapter/" },
        { slug: "dc-dc-module", title: "DC-DC модуль", status: "recheck", origin: "components/power/dc-dc-module/" },
        { slug: "reverse-polarity", title: "Захист переполюсування", status: "done", levels: ["basic"], origin: "components/protection/undefined" },
        { slug: "battery-protection", title: "Захист акумулятора", status: "recheck", origin: "components/protection/battery-protection-ic/" },
        { slug: "crowbar", title: "Crowbar-захист", status: "recheck", origin: "components/protection/crowbar/" },
        { slug: "rectification", title: "Випрямлення", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.6", math: [{ file: "math-ripple-calc.md", status: "done" }] },
        { slug: "mosfet-power-switch", title: "Силовий ключ", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.6", proj: [{ file: "proj-thermal-calc.md", status: "done" }] },
        { slug: "gate-capacitance", title: "Ємність затвора", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.7", math: [{ file: "math-gate-charge.md", status: "done" }] },
        { slug: "h-bridge", title: "H-міст", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.10", comp: [{ file: "comp-h-bridge-board.md", status: "update" }], proj: [{ file: "proj-shoot-through.md", status: "update" }] },
        { slug: "high-side-switch", title: "Верхній ключ", status: "recheck", origin: "embedded/block-2-components-analog/mosfet#2.7.11", comp: [{ file: "comp-pmos-load-switch.md", status: "done" }] },
        { slug: "ldo-internals", title: "LDO зсередини", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/opamp-comparator#2.8.11", math: [{ file: "math-ldo-dissipation.md", status: "done" }] },
        { slug: "ac-switch-need", title: "Ключі для мережі", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.1", hist: [{ file: "hist-thyristor.md", status: "recheck" }] },
        { slug: "thyristor-scr", title: "Тиристор", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.2" },
        { slug: "triac", title: "Симістор", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.3", comp: [{ file: "comp-triac-driver.md", status: "recheck" }] },
        { slug: "phase-control-dimmer", title: "Фазове керування", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.4", math: [{ file: "math-phase-power.md", status: "recheck" }], proj: [{ file: "proj-dimmer-algorithm.md", status: "recheck" }] },
        { slug: "zero-cross-switching", title: "Перехід через нуль", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.5", comp: [{ file: "comp-zero-cross-module.md", status: "recheck" }], proj: [{ file: "proj-burst-control.md", status: "recheck" }] },
        { slug: "solid-state-relay", title: "Твердотільне реле", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/ac-power-switching#2.11.6", hist: [{ file: "hist-ssr.md", status: "done" }] },
        { slug: "igbt", title: "IGBT", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.7", hist: [{ file: "hist-igbt-baliga.md", status: "recheck" }] },
        { slug: "snubbers-dvdt", title: "Снабери", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/ac-power-switching#2.11.8", comp: [{ file: "comp-ssr.md", status: "done" }], math: [{ file: "math-snubber-calc.md", status: "done" }] },
        { slug: "mains-safety", title: "Безпека з мережею", status: "recheck", origin: "embedded/block-2-components-analog/ac-power-switching#2.11.9" },
        { slug: "pwm-power-control", title: "Керування потужністю", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.5", comp: [{ file: "comp-mosfet-module.md", status: "done" }], proj: [{ file: "proj-gamma.md", status: "done" }] },
        { slug: "board-consumption", title: "Споживання плати", status: "recheck", origin: "embedded/block-4-mcu-esp32/low-power#4.13.8", comp: [{ file: "comp-ldo-vs-buck.md", status: "recheck" }] },
        { slug: "esc", title: "ESC-регулятор", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/flight-components#7.3.5" },
        { slug: "linear-vs-switching", title: "Лінійний vs імпульсний", status: "recheck", origin: "embedded/block-7-systems/power-systems#7.4.1", hist: [{ file: "hist-lithium.md", status: "recheck" }] },
        { slug: "switching-converter", title: "Імпульсний перетворювач", status: "recheck", origin: "embedded/block-7-systems/power-systems#7.4.2", hist: [{ file: "hist-smps.md", status: "recheck" }] },
        { slug: "power-rails", title: "Шини живлення", status: "recheck", origin: "embedded/block-7-systems/power-systems#7.4.3" },
        { slug: "batteries", title: "Акумулятори", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/power-systems#7.4.4" },
        { slug: "c-rate", title: "C-rate й опір", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/power-systems#7.4.5" },
        { slug: "cc-cv-bms", title: "Заряд і BMS", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/power-systems#7.4.6" },
        { slug: "energy-budget", title: "Бюджет енергії", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/power-systems#7.4.7" },
        { slug: "h-bridge-2", title: "H-міст", status: "empty", origin: "embedded/undefined#5.9.2" },
        { slug: "module-power-supply", title: "Живлення модуля", status: "empty", origin: "embedded/undefined#6.12.4" },
        { slug: "companion-power-thermal", title: "Енергія й тепло", status: "empty", origin: "embedded/undefined#7.11.7" },
        { slug: "battery-to-controller", title: "Батарея до контролера", status: "empty", origin: "embedded/undefined#7.14.2" },
      ] },
    { slug: "radio", title: "Радіоелектроніка", scope: "Генерація, передавання й приймання електромагнітних коливань високих частот.",
      topics: [
        { slug: "rf-board-reading", title: "Читання ВЧ-плати", status: "recheck", origin: "embedded/block-6-comms-radio/antennas#6.8.7" },
      ] },
    { slug: "microelectronics", title: "Мікроелектроніка", scope: "Фізика напівпровідників і провідності твердих тіл разом із проєктуванням інтегральних схем на кристалі — від принципів активних приладів до топології ІС.",
      topics: [
        { slug: "diodes", title: "Діоди", status: "done", levels: ["basic"], origin: "components/active/diode-families/" },
        { slug: "bjt", title: "BJT-транзистори", status: "recheck", origin: "components/active/bjt-families/", comp: [{ file: "comp-darlington-uln.md", status: "done" }] },
        { slug: "body-diode", title: "Body-діод", status: "update", levels: ["basic"], origin: "components/active/mosfet-body-diode/" },
        { slug: "esd-damage", title: "ESD-пошкодження", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/esd-static#1.10.5", hist: [{ file: "hist-dust-explosions.md", status: "done" }], comp: [{ file: "comp-esd-gun.md", status: "done" }], math: [{ file: "math-spark-energy.md", status: "done" }] },
        { slug: "bjt-structure", title: "Будова BJT", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.2" },
        { slug: "mosfet-structure", title: "Будова MOSFET", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.2" },
        { slug: "mosfet-threshold", title: "Поріг MOSFET", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.3", math: [{ file: "math-square-law.md", status: "deeper" }] },
        { slug: "nmos-pmos", title: "NMOS/PMOS", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.4" },
        { slug: "cmos", title: "CMOS", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.9", hist: [{ file: "hist-cmos.md", status: "done" }] },
        { slug: "dram-cell", title: "DRAM", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.2", math: [{ file: "math-dram-refresh.md", status: "recheck" }] },
        { slug: "nor-vs-nand", title: "NOR і NAND", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.5", comp: [{ file: "comp-w25q-raw-commands.md", status: "recheck" }] },
        { slug: "eeprom-fram", title: "EEPROM і FRAM", status: "recheck", origin: "embedded/block-3-digital-processor/external-memory#3.8.8" },
        { slug: "silicon-monocrystal", title: "Кремній і монокристал", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.1", hist: [{ file: "hist-kilby-noyce.md", status: "recheck" }] },
        { slug: "photolithography", title: "Фотолітографія", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.2", hist: [{ file: "hist-asml-euv.md", status: "recheck" }], proj: [{ file: "proj-place-and-route.md", status: "recheck" }] },
        { slug: "doping-etching-metal", title: "Шар за шаром", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.3" },
        { slug: "process-node", title: "Техпроцес", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.4" },
        { slug: "yield", title: "Yield", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.5", math: [{ file: "math-yield-math.md", status: "recheck" }] },
        { slug: "testing-binning", title: "Тестування й binning", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.6", comp: [{ file: "comp-chip-markings.md", status: "recheck" }], proj: [{ file: "proj-scan-chain.md", status: "recheck" }] },
        { slug: "fabs-fabless", title: "Фаби й fabless", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.8", hist: [{ file: "hist-tsmc.md", status: "recheck" }], math: [{ file: "math-moore-dennard.md", status: "recheck" }] },
      ] },
    { slug: "components", title: "Компоненти", scope: "Пасивні елементи кіл, їхні параметри, неідеальності та конструкція.",
      topics: [
        { slug: "tvs-diode", title: "TVS-діод", status: "done", levels: ["basic"], origin: "components/active/tvs-diode/" },
        { slug: "mlcc", title: "MLCC", status: "done", levels: ["basic"], origin: "components/passive/mlcc/" },
        { slug: "electrolytic-cap", title: "Електролітичний конденсатор", status: "done", levels: ["basic"], origin: "components/passive/electrolytic/" },
        { slug: "capacitor-marking", title: "Маркування конденсаторів", status: "done", levels: ["basic"], origin: "components/passive/capacitor-marking/", comp: [{ file: "comp-electrolytic-tantalum.md", status: "done" }, { file: "comp-mlcc.md", status: "done" }] },
        { slug: "bleeder", title: "Розрядний резистор", status: "recheck", origin: "components/passive/bleeder/" },
        { slug: "decoupling", title: "Decoupling-конденсатор", status: "done", levels: ["basic"], origin: "components/passive/decoupling/", comp: [{ file: "comp-mlcc.md", status: "done" }] },
        { slug: "supercap", title: "Суперконденсатор", status: "done", levels: ["basic"], origin: "components/passive/supercap/" },
        { slug: "power-inductor", title: "Силовий дросель", status: "done", levels: ["basic"], origin: "components/passive/power-inductor/" },
        { slug: "transformer", title: "Трансформатор", status: "done", levels: ["basic"], origin: "components/passive/transformer/" },
        { slug: "resistor-marking", title: "Маркування резисторів", status: "done", levels: ["basic"], origin: "components/passive/resistor-marking/" },
        { slug: "wire-gauge", title: "Калібр проводу", status: "done", levels: ["basic"], origin: "components/passive/wire-gauge/" },
        { slug: "heatsink", title: "Радіатор", status: "done", levels: ["basic"], origin: "components/passive/heatsink/" },
        { slug: "peltier", title: "Елемент Пельтьє", status: "recheck", origin: "components/passive/peltier/" },
        { slug: "magnet-grades", title: "Класи магнітів", status: "done", origin: "components/passive/magnet-grades/" },
        { slug: "ferrite-bead", title: "Феритова намистина", status: "done", levels: ["basic"], origin: "components/passive/ferrite-bead/" },
        { slug: "crystal", title: "Кварц", status: "done", levels: ["basic"], origin: "components/passive/watch-crystal/" },
        { slug: "potentiometer", title: "Потенціометр", status: "done", levels: ["basic"], origin: "components/passive/potentiometer/", comp: [{ file: "comp-potentiometer.md", status: "done" }] },
        { slug: "packages", title: "Корпуси", status: "recheck", origin: "components/passive/packages/", comp: [{ file: "comp-packages.md", status: "recheck" }] },
        { slug: "smd-marking", title: "Маркування SMD", status: "recheck", origin: "components/passive/smd-marking/" },
        { slug: "ptc-fuse", title: "Самовідновний запобіжник", status: "empty", origin: "components/protection/undefined" },
        { slug: "esd-protection", title: "ESD-захист", status: "empty", origin: "components/protection/undefined" },
        { slug: "gdt", title: "Газорозрядник", status: "done", levels: ["basic"], origin: "components/protection/gas-discharge-tube/" },
        { slug: "varistor", title: "Варистор", status: "recheck", origin: "components/protection/mov-varistor/" },
        { slug: "inrush-ntc", title: "Inrush NTC", status: "done", levels: ["basic"], origin: "components/protection/inrush-ntc/" },
        { slug: "fuse-types", title: "Типи запобіжників", status: "done", levels: ["basic"], origin: "components/protection/fuse-types/" },
        { slug: "resistor", title: "Резистор", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.7" },
        { slug: "fuses-ptc", title: "Запобіжники", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/resistance-power-heat#1.3.8", hist: [{ file: "hist-fuse.md", status: "done" }] },
        { slug: "capacitor", title: "Конденсатор", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.1", hist: [{ file: "hist-leyden-jar.md", status: "done" }], comp: [{ file: "comp-mlcc.md", status: "done" }, { file: "comp-marking-sizes.md", status: "done" }] },
        { slug: "capacitor-dielectrics", title: "Діелектрики конденсаторів", status: "done", levels: ["basic"] },
        { slug: "capacitance", title: "Ємність", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.2", math: [{ file: "math-derivative-current.md", status: "done" }], proj: [{ file: "proj-touch-sensing.md", status: "done" }] },
        { slug: "capacitor-energy", title: "Енергія конденсатора", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.3" },
        { slug: "capacitor-parasitics", title: "Паразити конденсатора", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.5", hist: [{ file: "hist-capacitor-plague.md", status: "done" }] },
        { slug: "capacitor-uses", title: "Застосування конденсаторів", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.6" },
        { slug: "capacitors-series-parallel", title: "Конденсатори: з'єднання", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.7" },
        { slug: "supercapacitor", title: "Суперконденсатор", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/capacitor#2.1.8", hist: [{ file: "hist-supercap.md", status: "done" }] },
        { slug: "inductor-coil", title: "Котушка", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.1", hist: [{ file: "hist-oersted-ampere.md", status: "done" }, { file: "hist-induction.md", status: "done" }] },
        { slug: "inductance", title: "Індуктивність", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.2" },
        { slug: "inductor-energy", title: "Енергія котушки", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.3" },
        { slug: "inductor-kickback", title: "Брикання котушки", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.5", comp: [{ file: "comp-rc-snubber.md", status: "done" }] },
        { slug: "mutual-inductance", title: "Взаємоіндукція", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.6", hist: [{ file: "hist-transformer.md", status: "done" }], math: [{ file: "math-turns-ratio.md", status: "deeper" }] },
        { slug: "inductor-types", title: "Типи котушок", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.7" },
        { slug: "ferrite-beads", title: "Ферити", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/inductor#2.2.9" },
        { slug: "diode-bias", title: "Зміщення діода", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.4" },
        { slug: "diode-iv-curve", title: "ВАХ діода", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.5", math: [{ file: "math-shockley-equation.md", status: "done" }], proj: [{ file: "proj-diode-thermometer.md", status: "done" }] },
        { slug: "zener-schottky", title: "Діоди Зенера", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.8", hist: [{ file: "hist-zener.md", status: "done" }], math: [{ file: "math-reverse-recovery.md", status: "done" }] },
        { slug: "flyback-protection", title: "Захист flyback", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.9" },
        { slug: "rds-on", title: "Опір Rds(on)", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/mosfet#2.7.5", hist: [{ file: "hist-hexfet.md", status: "done" }] },
        { slug: "datasheet-structure", title: "Структура даташита", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/reading-datasheets#2.9.1", hist: [{ file: "hist-databooks.md", status: "done" }] },
        { slug: "abs-max-ratings", title: "Граничні режими", status: "recheck", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.2", comp: [{ file: "comp-abs-max-failures.md", status: "recheck" }] },
        { slug: "datasheet-graphs", title: "Графіки даташита", status: "recheck", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.4", math: [{ file: "math-derating.md", status: "recheck" }, { file: "math-thermal-resistance.md", status: "recheck" }], proj: [{ file: "proj-log-graph-reading.md", status: "recheck" }] },
        { slug: "packages-pinout", title: "Корпуси й розпіновка", status: "recheck", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.5" },
        { slug: "datasheet-fine-print", title: "Дрібний шрифт", status: "recheck", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.6", hist: [{ file: "hist-pentium-fdiv.md", status: "recheck" }] },
        { slug: "datasheet-practice", title: "Практикум даташитів", status: "update", levels: ["basic"], origin: "embedded/block-2-components-analog/reading-datasheets#2.9.7", comp: [{ file: "comp-component-tester.md", status: "done" }], proj: [{ file: "proj-selection-checklist.md", status: "done" }] },
        { slug: "quartz-resonator", title: "Кварцовий резонатор", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.3", math: [{ file: "math-q-stability.md", status: "done" }] },
        { slug: "quartz-rlc-model", title: "RLC-модель кварцу", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.4" },
        { slug: "frequency-accuracy-ppm", title: "Точність ppm", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.6", math: [{ file: "math-ppm-math.md", status: "done" }], proj: [{ file: "proj-measure-drift.md", status: "done" }] },
        { slug: "watch-crystal-rtc", title: "Годинниковий кварц", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.7", hist: [{ file: "hist-quartz-crisis.md", status: "done" }] },
        { slug: "ceramic-mems-resonators", title: "Керамічні резонатори", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.8", comp: [{ file: "comp-mems-vs-quartz.md", status: "done" }] },
        { slug: "tcxo-ocxo", title: "TCXO та OCXO", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/resonators-references#2.10.9", comp: [{ file: "comp-tcxo.md", status: "done" }] },
      ] },
    { slug: "metrology", title: "Вимірювання", scope: "Методи й засоби кількісного визначення електричних величин і похибок.",
      topics: [
        { slug: "kelvin-shunt", title: "Шунт Кельвіна", status: "done", levels: ["basic"], origin: "components/passive/kelvin-shunt/" },
        { slug: "electronic-load", title: "Електронне навантаження", status: "recheck", origin: "components/power/electronic-load/" },
        { slug: "current-monitor", title: "Монітор струму", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "clamp-meter", title: "Струмові кліщі", status: "done", levels: ["basic"], origin: "components/sensors/clamp-meter/" },
        { slug: "multimeter", title: "Мультиметр", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.6", hist: [{ file: "hist-weston.md", status: "done" }], comp: [{ file: "comp-multimeter.md", status: "deeper" }] },
        { slug: "oscilloscope", title: "Осцилограф", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.7", hist: [{ file: "hist-crt.md", status: "done" }, { file: "hist-tektronix.md", status: "done" }], comp: [{ file: "comp-oscilloscope.md", status: "done" }, { file: "comp-probe.md", status: "done" }], proj: [{ file: "proj-trigger.md", status: "done" }] },
        { slug: "measurement-errors", title: "Похибки вимірювань", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.8", comp: [{ file: "comp-cat-ratings.md", status: "done" }, { file: "comp-probe-ground.md", status: "done" }], math: [{ file: "math-accuracy.md", status: "done" }] },
        { slug: "logic-analyzer", title: "Логічний аналізатор", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.9" },
        { slug: "lab-power-supply", title: "Блок живлення", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/schematics-measurement#1.6.10" },
        { slug: "sine-on-scope", title: "Синусоїда на осцилографі", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/ac-signals#1.7.5" },
        { slug: "noise-hunting", title: "Полювання на заваду", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/noise-interference#1.9.9", math: [{ file: "math-averaging.md", status: "done" }] },
        { slug: "min-typ-max", title: "Min/typ/max", status: "recheck", origin: "embedded/block-2-components-analog/reading-datasheets#2.9.3", math: [{ file: "math-tolerance-statistics.md", status: "recheck" }] },
        { slug: "voltage-reference", title: "Опорна напруга", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/adc#4.8.4", hist: [{ file: "hist-bandgap.md", status: "done" }], comp: [{ file: "comp-voltage-reference.md", status: "done" }, { file: "comp-tl431.md", status: "done" }], math: [{ file: "math-bandgap-math.md", status: "done" }] },
        { slug: "adc-errors", title: "Похибки АЦП", status: "done", origin: "embedded/block-4-mcu-esp32/adc#4.8.6", comp: [{ file: "comp-ads1115.md", status: "recheck" }], proj: [{ file: "proj-two-point-cal.md", status: "recheck" }] },
        { slug: "measure-consumption", title: "Виміряти споживання", status: "recheck", origin: "embedded/block-4-mcu-esp32/low-power#4.13.7", comp: [{ file: "comp-current-profiler.md", status: "recheck" }], math: [{ file: "math-dynamic-range.md", status: "recheck" }] },
        { slug: "calibration", title: "Калібрування", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/sensor-physics#5.1.6" },
        { slug: "current-voltage-measurement", title: "Вимірювання струму", status: "empty", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.8" },
        { slug: "first-power-up-check", title: "Перша перевірка", status: "empty", origin: "embedded/undefined#6.12.8" },
        { slug: "fault-finding", title: "Пошук несправності", status: "empty", origin: "embedded/undefined#6.12.10" },
      ] },
    { slug: "optoelectronics", title: "Оптоелектроніка", scope: "Прилади перетворення між світлом і електричним сигналом.",
      topics: [
        { slug: "optocoupler", title: "Оптопара", status: "done", origin: "components/active/optocoupler/" },
        { slug: "led", title: "LED", status: "done", levels: ["basic"], origin: "components/active/led-practice/" },
        { slug: "oled", title: "OLED-дисплей", status: "recheck", origin: "components/displays/ssd1306-oled/" },
        { slug: "tft", title: "TFT-дисплей", status: "recheck", origin: "components/displays/spi-tft/" },
        { slug: "eink", title: "E-ink дисплей", status: "recheck", origin: "components/displays/eink-module/" },
        { slug: "led-photodiode", title: "Світлодіод", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.7", hist: [{ file: "hist-blue-led.md", status: "done" }, { file: "hist-led.md", status: "done" }], math: [{ file: "math-photon-energy.md", status: "done" }], proj: [{ file: "proj-charlieplexing.md", status: "done" }] },
        { slug: "optocoupler-2", title: "Оптопара", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/diode-pn-junction#2.5.10" },
        { slug: "addressable-leds", title: "Адресні світлодіоди", status: "recheck", origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.7", comp: [{ file: "comp-ws2812-strip.md", status: "recheck" }], proj: [{ file: "proj-ws2812-timing.md", status: "recheck" }] },
        { slug: "image-sensor", title: "Сенсор зображення", status: "recheck", origin: "embedded/block-7-systems/video-signals-1#7.7.1", hist: [{ file: "hist-farnsworth.md", status: "recheck" }] },
        { slug: "cmos-matrix", title: "CMOS-матриця", status: "recheck", origin: "embedded/block-7-systems/video-signals-1#7.7.2", hist: [{ file: "hist-ccd.md", status: "recheck" }] },
        { slug: "dynamic-range-noise", title: "Динамічний діапазон", status: "recheck", origin: "embedded/block-7-systems/video-signals-1#7.7.4" },
      ] },
    { slug: "displays", title: "Дисплеї", scope: "Засоби візуального відображення інформації — панелі, їхні інтерфейси й сенсорний ввід, разом із програмним конвеєром формування зображення в пам'яті.",
      topics: [
        { slug: "display-classes", title: "Класи дисплеїв", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.1", hist: [{ file: "hist-lcd.md", status: "recheck" }] },
        { slug: "panel-parameters", title: "Параметри панелі", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.2" },
        { slug: "panel-interfaces", title: "Інтерфейси панелей", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.3", math: [{ file: "math-bandwidth-budget.md", status: "recheck" }] },
        { slug: "display-controller", title: "Контролер дисплея", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.4" },
        { slug: "backlight-dimming", title: "Підсвітка", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.5" },
        { slug: "touch-tech", title: "Сенсорний ввід", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.6" },
        { slug: "eink-refresh", title: "E-ink оновлення", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.7", hist: [{ file: "hist-eink.md", status: "recheck" }, { file: "hist-lcd.md", status: "done" }] },
        { slug: "display-selection", title: "Вибір дисплея", status: "recheck", origin: "embedded/block-13-ui-hmi/displays-touch#13.1.8" },
        { slug: "framebuffer", title: "Кадровий буфер", status: "recheck", origin: "embedded/block-13-ui-hmi/graphics-pipeline#13.2.1", hist: [{ file: "hist-alto.md", status: "recheck" }] },
        { slug: "color-formats", title: "Колір у пам'яті", status: "recheck", origin: "embedded/block-13-ui-hmi/graphics-pipeline#13.2.2" },
        { slug: "primitives-raster", title: "Растеризація", status: "recheck", origin: "embedded/block-13-ui-hmi/graphics-pipeline#13.2.3" },
        { slug: "fonts", title: "Шрифти", status: "recheck", origin: "embedded/block-13-ui-hmi/graphics-pipeline#13.2.4" },
        { slug: "double-buffering", title: "Подвійна буферизація", status: "recheck", origin: "embedded/block-13-ui-hmi/graphics-pipeline#13.2.5" },
      ] },
    { slug: "electromechanics", title: "Електромеханіка", scope: "Перетворення між електричною та механічною енергією у приводах і виконавчих механізмах.",
      topics: [
        { slug: "gearmotor", title: "Мотор-редуктор", status: "done", levels: ["basic"], origin: "components/actuators/undefined" },
        { slug: "servo", title: "Серво", status: "done", levels: ["basic"], origin: "components/actuators/undefined" },
        { slug: "solenoid-relay", title: "Соленоїд реле", status: "done", levels: ["basic"], origin: "components/interfaces/solenoid-relay/" },
        { slug: "relay-driver", title: "Реле і драйвер", status: "done", levels: ["basic"], origin: "embedded/block-2-components-analog/bjt#2.6.9", comp: [{ file: "comp-relay-inside.md", status: "done" }, { file: "comp-relay-module.md", status: "done" }] },
        { slug: "microphone-speaker", title: "Мікрофон і динамік", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/sensor-physics#5.1.10" },
        { slug: "bldc-motor", title: "BLDC-мотор", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/flight-components#7.3.4" },
        { slug: "servo-2", title: "Серво", status: "recheck", origin: "embedded/block-7-systems/flight-components#7.3.6" },
        { slug: "brushed-dc-motor", title: "DC-мотор", status: "done", levels: ["basic"], origin: "embedded/undefined#5.9.1" },
        { slug: "stepper-motor", title: "Кроковий мотор", status: "done", levels: ["basic"], origin: "embedded/undefined#5.9.3" },
        { slug: "hobby-servo", title: "Серво", status: "done", levels: ["basic"], origin: "embedded/undefined#5.9.4" },
        { slug: "solenoid-piezo-actuators", title: "Соленоїд і п'єзо", status: "empty", origin: "embedded/undefined#5.9.5" },
        { slug: "motor-current-stall-heat", title: "Заклинювання й нагрів", status: "done", levels: ["basic"], origin: "embedded/undefined#5.9.6" },
        { slug: "gears-transmission", title: "Редуктори", status: "done", levels: ["basic"], origin: "embedded/undefined#5.9.7" },
        { slug: "actuator-selection", title: "Вибір актуатора", status: "empty", origin: "embedded/undefined#5.9.8" },
      ] },
    { slug: "sensors", title: "Сенсорика", scope: "Прилади перетворення фізичних величин у вимірюваний електричний сигнал.",
      topics: [
        { slug: "touch-controller", title: "Сенсорний контролер", status: "recheck", origin: "components/displays/touch-controller/" },
        { slug: "ntc-thermistor", title: "NTC-термістор", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "photo-sensors", title: "Фотодавачі", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "hall-current-sensor", title: "Холлівський давач струму", status: "empty", origin: "components/sensors/undefined" },
        { slug: "load-cell", title: "Тензодавач", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "ultrasonic-rangefinder", title: "Ультразвуковий далекомір", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "tof-sensor", title: "ToF-давач", status: "empty", origin: "components/sensors/undefined" },
        { slug: "imu", title: "IMU-давач", status: "done", levels: ["basic"], origin: "components/sensors/undefined" },
        { slug: "what-is-a-sensor", title: "Що таке давач", status: "done", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.1", hist: [{ file: "hist-seebeck.md", status: "recheck" }] },
        { slug: "transducer-classes", title: "Класи перетворювачів", status: "done", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.2" },
        { slug: "piezo-optical-semiconductor", title: "П'єзо й оптичні", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/sensor-physics#5.1.3" },
        { slug: "sensor-characteristics", title: "Характеристики давача", status: "recheck", origin: "embedded/block-5-sensors-control/sensor-physics#5.1.4" },
        { slug: "drift-hysteresis-noise", title: "Дрейф і гістерезис", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/sensor-physics#5.1.5" },
        { slug: "sensor-input-matching", title: "Узгодження давача", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/sensor-physics#5.1.7" },
        { slug: "strain-gauges", title: "Тензодавачі", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/sensor-physics#5.1.9", hist: [{ file: "hist-strain-gauge.md", status: "recheck" }], comp: [{ file: "comp-loadcell-hx711.md", status: "done" }], math: [{ file: "math-wheatstone-bridge.md", status: "done" }] },
        { slug: "contactless-distance", title: "Безконтактна відстань", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/distance-environment#5.2.1", hist: [{ file: "hist-sonar.md", status: "done" }] },
        { slug: "tof-ultrasonic", title: "ToF звук", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/distance-environment#5.2.2" },
        { slug: "tof-laser", title: "ToF лазер", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/distance-environment#5.2.3" },
        { slug: "triangulation", title: "Тріангуляція", status: "recheck", origin: "embedded/block-5-sensors-control/distance-environment#5.2.4" },
        { slug: "reflection-absorption", title: "Відбиття IR", status: "recheck", origin: "embedded/block-5-sensors-control/distance-environment#5.2.5" },
        { slug: "distance-errors", title: "Похибки відстані", status: "recheck", origin: "embedded/block-5-sensors-control/distance-environment#5.2.6" },
        { slug: "environment-sensors", title: "Давачі оточення", status: "recheck", origin: "embedded/block-5-sensors-control/distance-environment#5.2.7" },
        { slug: "mems", title: "MEMS", status: "recheck", origin: "embedded/block-5-sensors-control/imu-mems#5.7.1", hist: [{ file: "hist-mems-airbag.md", status: "recheck" }] },
        { slug: "accelerometer", title: "Акселерометр", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/imu-mems#5.7.2" },
        { slug: "gyroscope", title: "Гіроскоп", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/imu-mems#5.7.3" },
        { slug: "magnetometer", title: "Магнітометр", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/imu-mems#5.7.4" },
        { slug: "imu-noise-bias-drift", title: "Шум і дрейф IMU", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/imu-mems#5.7.5" },
        { slug: "reading-imu-fifo", title: "Читання IMU", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.7" },
        { slug: "imu-vibration-isolation", title: "Розв'язка IMU", status: "done", levels: ["basic"], origin: "embedded/block-5-sensors-control/imu-mems#5.7.8" },
        { slug: "imu-calibration", title: "Калібрування IMU", status: "empty", origin: "embedded/block-5-sensors-control/imu-mems#5.7.9" },
        { slug: "onboard-sensors", title: "Давачі апарата", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/flight-components#7.3.1", hist: [{ file: "hist-gps.md", status: "done" }] },
        { slug: "imu-barometer", title: "IMU й барометр", status: "recheck", origin: "embedded/block-7-systems/flight-components#7.3.2" },
        { slug: "angle-rotation-sensing", title: "Вимір кута", status: "empty", origin: "embedded/undefined#5.3.1" },
        { slug: "potentiometer-angle-sensor", title: "Потенціометр кута", status: "empty", origin: "embedded/undefined#5.3.2" },
        { slug: "optical-incremental-encoder", title: "Оптичний енкодер", status: "done", levels: ["basic"], origin: "embedded/undefined#5.3.3" },
        { slug: "quadrature", title: "Квадратура", status: "empty", origin: "embedded/undefined#5.3.4" },
        { slug: "hall-magnetic-encoders", title: "Холл-енкодери", status: "empty", origin: "embedded/undefined#5.3.5" },
        { slug: "absolute-encoder-gray-code", title: "Абсолютний енкодер", status: "empty", origin: "embedded/undefined#5.3.6" },
        { slug: "mox-gas-sensor", title: "MOX-давач", status: "empty", origin: "embedded/undefined#5.10.1" },
        { slug: "ndir-co2", title: "NDIR CO2", status: "empty", origin: "embedded/undefined#5.10.2" },
        { slug: "electrochemical-cell", title: "Електрохімічна комірка", status: "empty", origin: "embedded/undefined#5.10.3" },
        { slug: "dust-aerosol-sensor", title: "Давач пилу", status: "empty", origin: "embedded/undefined#5.10.4" },
        { slug: "uv-light-sensor", title: "УФ-давач", status: "empty", origin: "embedded/undefined#5.10.5" },
        { slug: "geiger-muller-counter", title: "Лічильник Гейгера", status: "empty", origin: "embedded/undefined#5.10.6" },
        { slug: "barometric-altimeter", title: "Барометр-альтиметр", status: "done", levels: ["basic"], origin: "embedded/undefined#5.10.7" },
        { slug: "cross-sensitivity-compensation", title: "Перехресна чутливість", status: "empty", origin: "embedded/undefined#5.10.8" },
      ] },
    { slug: "pcb", title: "Плати", scope: "Конструювання й технологія друкованих плат і з'єднань разом з електромагнітною сумісністю — керуванням завадами, наведеннями й випромінюванням.",
      topics: [
        { slug: "shielded-cable", title: "Екранований кабель", status: "done", levels: ["basic"], origin: "components/comms/shielded-cable/" },
        { slug: "ferrite-clamp", title: "Феритова клема", status: "done", origin: "components/passive/ferrite-clamp/" },
        { slug: "ground-loops", title: "Земляні петлі", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/noise-interference#1.9.6", comp: [{ file: "comp-star-ground.md", status: "done" }] },
        { slug: "shielding", title: "Екранування", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/noise-interference#1.9.7" },
        { slug: "twisted-pair", title: "Вита пара", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/noise-interference#1.9.8", hist: [{ file: "hist-twisted-pair.md", status: "done" }] },
        { slug: "antistatic-workplace", title: "Антистатичне місце", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/esd-static#1.10.6", comp: [{ file: "comp-wrist-strap.md", status: "done" }] },
        { slug: "esd-packaging", title: "ESD-пакування", status: "done", levels: ["basic"], origin: "embedded/block-1-circuits-physics/esd-static#1.10.7", comp: [{ file: "comp-ionizer.md", status: "deeper" }] },
        { slug: "packaging", title: "Корпусування", status: "recheck", origin: "embedded/block-3-digital-processor/chip-fabrication#3.10.7", comp: [{ file: "comp-package-guide.md", status: "recheck" }] },
        { slug: "datasheet-pinout", title: "Розпіновка й даташит", status: "empty", origin: "embedded/undefined#6.12.1" },
        { slug: "common-ground", title: "Спільна земля", status: "done", levels: ["basic"], origin: "embedded/undefined#6.12.2" },
        { slug: "cables-connectors", title: "Кабелі й конектори", status: "empty", origin: "embedded/undefined#6.12.6" },
        { slug: "esd-hot-plug", title: "ESD і гаряче підключення", status: "empty", origin: "embedded/undefined#6.12.7" },
        { slug: "basic-soldering", title: "Мінімальна пайка", status: "empty", origin: "embedded/undefined#6.12.9" },
        { slug: "components-buses-on-frame", title: "Компоненти й шини", status: "empty", origin: "embedded/undefined#7.14.3" },
      ] },
  ]
});
