/* manifest — «Програмування» (тип "book"). Схема — AUTHORING.md §2. */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "programming", title: "Програмування",
  sections: [
    { slug: "computer-architecture", title: "Архітектура", scope: "Будова обчислювальної машини: модель фон Неймана й Гарвардська, набори інструкцій, конвеєр, ієрархія пам'яті, переривання.",
      topics: [
        { slug: "overflow-wraparound", title: "Переповнення", status: "done", origin: "embedded/block-3-digital-processor/number-representation#3.4.4", hist: [{ file: "hist-ariane5.md", status: "done" }], proj: [{ file: "proj-overflow-checks.md", status: "done" }] },
        { slug: "fixed-point", title: "Фіксована кома", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/number-representation#3.4.5", hist: [{ file: "hist-patriot.md", status: "done" }], proj: [{ file: "proj-cordic.md", status: "done" }, { file: "proj-fixed-point.md", status: "done" }] },
        { slug: "floating-point", title: "Плаваюча кома", status: "done", origin: "embedded/block-3-digital-processor/number-representation#3.4.6", hist: [{ file: "hist-ieee754.md", status: "done" }], proj: [{ file: "proj-float-compare.md", status: "done" }] },
        { slug: "bits-bytes-endianness", title: "Біти й порядок байтів", status: "done", origin: "embedded/block-3-digital-processor/number-representation#3.4.7", comp: [{ file: "comp-sensor-byte-order.md", status: "done" }], proj: [{ file: "proj-serialization.md", status: "done" }] },
        { slug: "ascii-utf8", title: "ASCII і UTF-8", status: "recheck", origin: "embedded/block-3-digital-processor/number-representation#3.4.8", hist: [{ file: "hist-utf8-diner.md", status: "recheck" }], proj: [{ file: "proj-utf8-decoder.md", status: "recheck" }] },
        { slug: "what-is-processor", title: "Що таке процесор", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.1", hist: [{ file: "hist-babbage-lovelace.md", status: "done" }, { file: "hist-von-neumann.md", status: "done" }] },
        { slug: "processor-parts", title: "Складові процесора", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.2" },
        { slug: "fetch-decode-execute", title: "Цикл виконання", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.3", proj: [{ file: "proj-toy-cpu-emulator.md", status: "done" }] },
        { slug: "isa", title: "Набір інструкцій", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.4", hist: [{ file: "hist-riscv.md", status: "done" }], comp: [{ file: "comp-isa-in-boards.md", status: "done" }], proj: [{ file: "proj-reading-disassembly.md", status: "done" }] },
        { slug: "clock-frequency", title: "Частота процесора", status: "done", levels: ["basic"], origin: "embedded/block-3-digital-processor/processor-architecture#3.5.5", hist: [{ file: "hist-megahertz-myth.md", status: "done" }], math: [{ file: "math-performance-math.md", status: "done" }] },
        { slug: "pipeline", title: "Конвеєр", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.6", math: [{ file: "math-pipeline-hazards.md", status: "done" }] },
        { slug: "von-neumann-harvard", title: "Фон Нейман і Гарвард", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.7", hist: [{ file: "hist-harvard-architecture.md", status: "done" }], comp: [{ file: "comp-esp32-buses.md", status: "done" }] },
        { slug: "risc-cisc", title: "RISC і CISC", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.8", hist: [{ file: "hist-risc-revolution.md", status: "done" }] },
        { slug: "cache", title: "Кеш", status: "done", origin: "embedded/block-3-digital-processor/processor-architecture#3.5.9", proj: [{ file: "proj-cache-friendly-code.md", status: "done" }] },
        { slug: "mcu-blocks", title: "Складові МК", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.2", proj: [{ file: "proj-offload-to-peripheral.md", status: "done" }] },
        { slug: "interrupt-vector", title: "Контролер і вектор", status: "done", origin: "embedded/block-4-mcu-esp32/interrupts#4.5.2", comp: [{ file: "comp-int-controllers.md", status: "done" }] },
        { slug: "dma-problem", title: "Проблема потоку даних", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.1", hist: [{ file: "hist-dma-channels.md", status: "done" }], math: [{ file: "math-throughput.md", status: "done" }] },
        { slug: "dma-controller", title: "DMA-контролер", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.2", proj: [{ file: "proj-memcpy-vs-dma.md", status: "done" }] },
        { slug: "dma-channels", title: "Канали й дескриптори", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.3", proj: [{ file: "proj-descriptors.md", status: "done" }] },
      ] },
    { slug: "languages", title: "Мови", scope: "Парадигми, дизайн і трансляція мов: імперативна/об'єктна/функційна/логічна/реактивна моделі, синтаксис, системи типів, метапрограмування, лексика, парсинг, IR, оптимізація, генерація коду, рантайми.",
      topics: [
        { slug: "compilation", title: "Компіляція", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.1", hist: [{ file: "hist-grace-hopper.md", status: "done" }] },
        { slug: "compiler-stages", title: "Стадії компілятора", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.2", hist: [{ file: "hist-gcc.md", status: "done" }], proj: [{ file: "proj-optimizer.md", status: "done" }] },
        { slug: "linking", title: "Лінкування", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.3", proj: [{ file: "proj-linker-errors.md", status: "done" }] },
        { slug: "volatile", title: "volatile", status: "done", origin: "embedded/block-4-mcu-esp32/interrupts#4.5.5", proj: [{ file: "proj-volatile-asm.md", status: "done" }] },
      ] },
    { slug: "systems", title: "Системи", scope: "Керування ресурсами й виконанням: процеси, планування, віртуальна й фізична пам'ять (стек, купа, алокатори, GC, покажчики), файлові системи, драйвери, потоки, синхронізація, моделі пам'яті, неблокувальність.",
      topics: [
        { slug: "memory-as-array", title: "Пам'ять як масив", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.1", hist: [{ file: "hist-core-memory.md", status: "done" }] },
        { slug: "memory-map", title: "Карта пам'яті", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.2", comp: [{ file: "comp-real-memory-map.md", status: "done" }] },
        { slug: "flash-vs-ram", title: "Flash і RAM", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.3", comp: [{ file: "comp-spi-flash-xip.md", status: "done" }] },
        { slug: "addresses-pointers", title: "Адреси й покажчики", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.4", hist: [{ file: "hist-heartbleed.md", status: "done" }], proj: [{ file: "proj-pointer-arithmetic.md", status: "done" }] },
        { slug: "stack-lifo", title: "Стек", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.5", hist: [{ file: "hist-stack-painting.md", status: "done" }], proj: [{ file: "proj-stack-watermark.md", status: "done" }] },
        { slug: "heap-dynamic-memory", title: "Купа", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.6", math: [{ file: "math-fragmentation.md", status: "done" }], proj: [{ file: "proj-block-pools.md", status: "done" }, { file: "proj-toy-allocator.md", status: "done" }] },
        { slug: "stack-overflow", title: "Переповнення стека", status: "done", origin: "embedded/block-3-digital-processor/memory-stack-heap#3.6.7", hist: [{ file: "comp-history-mpu.md", status: "done" }, { file: "hist-morris-worm.md", status: "done" }], comp: [{ file: "comp-mpu.md", status: "done" }] },
        { slug: "firmware-image", title: "Образ прошивки", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.4", math: [{ file: "math-image-checksums.md", status: "done" }], proj: [{ file: "proj-firmware-version.md", status: "done" }, { file: "proj-map-file.md", status: "done" }, { file: "proj-size-opt.md", status: "done" }] },
        { slug: "c-runtime", title: "C-рантайм", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.11", proj: [{ file: "proj-newlib-syscalls.md", status: "done" }] },
        { slug: "flash-filesystems", title: "Файлові системи Flash", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.6", hist: [{ file: "hist-fat.md", status: "done" }] },
        { slug: "atomicity-races", title: "Атомарність і гонки", status: "done", origin: "embedded/block-4-mcu-esp32/interrupts#4.5.6", hist: [{ file: "hist-therac25.md", status: "done" }], proj: [{ file: "proj-atomics-barriers.md", status: "done" }, { file: "proj-critical-sections.md", status: "done" }] },
        { slug: "dma-cache-races", title: "Пастки DMA", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.7", proj: [{ file: "proj-cache-dma.md", status: "done" }] },
        { slug: "tasks", title: "Задачі", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.3", proj: [{ file: "proj-fsm-instead.md", status: "done" }] },
        { slug: "scheduler", title: "Планувальник", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.4", math: [{ file: "math-tick-latency.md", status: "done" }], proj: [{ file: "proj-clz-bitmap.md", status: "done" }, { file: "proj-context-switch.md", status: "done" }] },
        { slug: "task-ipc", title: "Черги й семафори", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.6", hist: [{ file: "hist-pathfinder.md", status: "done" }], proj: [{ file: "proj-deadlock.md", status: "done" }, { file: "proj-priority-inheritance.md", status: "done" }, { file: "proj-queue-pattern.md", status: "done" }] },
        { slug: "task-stacks", title: "Стеки задач", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.7", proj: [{ file: "proj-no-free.md", status: "done" }, { file: "proj-stack-overflow.md", status: "done" }] },
        { slug: "persistent-storage", title: "Енергонезалежне зберігання", status: "empty" },
      ] },
    { slug: "peripherals", title: "Периферія", scope: "Порти, шини й контролери материнської плати та підключення зовнішніх пристроїв: PCIe, USB, BIOS/UEFI, ввід-вивід.",
      topics: [
        { slug: "spi-flash", title: "SPI-флеш", status: "done", levels: ["basic"], origin: "components/memory/undefined" },
        { slug: "eeprom", title: "EEPROM", status: "empty", origin: "components/memory/undefined" },
        { slug: "microsd", title: "microSD", status: "empty", origin: "components/memory/undefined" },
        { slug: "psram", title: "PSRAM", status: "done", origin: "components/memory/psram/", proj: [{ file: "proj-esp32-psram.md", status: "done" }] },
        { slug: "usb-overview", title: "USB огляд", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.1", hist: [{ file: "hist-usb-birth.md", status: "done" }] },
        { slug: "usb-physical", title: "USB фізично", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.2", math: [{ file: "math-nrzi.md", status: "done" }] },
        { slug: "usb-enumeration", title: "Енумерація USB", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.3", proj: [{ file: "proj-descriptors.md", status: "done" }] },
        { slug: "usb-endpoints", title: "Кінцеві точки USB", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.4", proj: [{ file: "proj-frames.md", status: "done" }] },
        { slug: "usb-device-classes", title: "Класи USB", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.5", hist: [{ file: "hist-badusb.md", status: "done" }], proj: [{ file: "proj-hid-reports.md", status: "done" }] },
        { slug: "esp32-usb", title: "USB в ESP32", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.6" },
        { slug: "usb-power", title: "Живлення з USB", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.7" },
        { slug: "usb-host", title: "МК як USB-host", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/usb-mcu#4.12.8", comp: [{ file: "comp-otg.md", status: "done" }] },
        { slug: "tinyusb-device", title: "TinyUSB: пристрій", status: "done", levels: ["basic", "detailed"], origin: "expansion-2026-06-22" },
      ] },
    { slug: "networking", title: "Мережі", scope: "Мережеве програмування: сокети, стек протоколів у коді, клієнт-сервер, RPC, прикладні сервіси.",
      topics: [
        { slug: "web-server-mcu", title: "Веб-сервер на МК", status: "empty", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.11" },
        { slug: "pymavlink", title: "pymavlink", status: "done", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.7" },
        { slug: "sockets-tcp-udp", title: "Сокети TCP/UDP", status: "empty", origin: "embedded/undefined#6.10.7" },
        { slug: "mavlink-stream-processing", title: "Обробка потоку", status: "empty", origin: "embedded/undefined#6.11.8" },
        { slug: "mavlink-channel", title: "Канал MAVLink", status: "empty", origin: "embedded/undefined#7.11.2" },
        { slug: "mavlink-routing", title: "Роутинг MAVLink", status: "empty", origin: "embedded/undefined#7.11.3" },
        { slug: "multi-vehicle-one-station", title: "Кілька апаратів", status: "empty", origin: "embedded/undefined#7.13.7" },
        { slug: "esp-hosted", title: "ESP-Hosted", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
      ] },
    { slug: "databases", title: "Бази даних", scope: "Зберігання й запити даних: реляційна й нереляційні моделі, транзакції, індекси, рушії та оптимізатори.",
      topics: [
      ] },
    { slug: "graphics", title: "Графіка", scope: "Програмний синтез зображень та інтерфейси: растеризація, трасування, шейдери, GPU, віконні системи, UI.",
      topics: [
        { slug: "operator-ergonomics", title: "Ергономіка оператора", status: "empty", origin: "embedded/undefined#7.13.5" },
      ] },
    { slug: "security", title: "Безпека", scope: "Захист програм від атак: класи вразливостей, ізоляція, криптографія в коді, моделі загроз, аудит.",
      topics: [
        { slug: "secure-boot", title: "Secure boot", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.9", math: [{ file: "math-hash-signature.md", status: "done" }] },
      ] },
    { slug: "software-engineering", title: "Інженерія", scope: "Проєктування, супровід і верифікація систем: архітектурні патерни, модульність, рефакторинг, процеси розробки, види тестів, фаззинг, формальні методи, неперервна інтеграція.",
      topics: [
        { slug: "firmware-testing", title: "Тестування прошивки", status: "recheck", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.9", proj: [{ file: "proj-emulators.md", status: "recheck" }] },
        { slug: "static-analysis", title: "Статичний аналіз", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/toolchain#4.2.10", proj: [{ file: "proj-sanitizers.md", status: "done" }] },
        { slug: "profiling", title: "Профілювання", status: "recheck", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.9" },
        { slug: "error-handling", title: "Жодна помилка не мовчить", status: "done", origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.1", hist: [{ file: "hist-ariane5.md", status: "done" }] },
        { slug: "assert-panic", title: "Assert і паніка", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.2" },
        { slug: "defensive-programming", title: "Захисне програмування", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.3" },
        { slug: "sitl-simulation", title: "SITL", status: "empty", origin: "embedded/undefined#7.11.6" },
        { slug: "gcs-as-system", title: "GCS як система", status: "empty", origin: "embedded/undefined#7.13.1" },
        { slug: "preflight-checklists", title: "Передпольотні чеклисти", status: "empty", origin: "embedded/undefined#7.13.6" },
        { slug: "ground-station-logs", title: "Записи станції", status: "empty", origin: "embedded/undefined#7.13.8" },
        { slug: "fuzzing", title: "Фаззинг", status: "done", levels: ["basic", "detailed"], origin: "expansion-2026-06-22" },
        { slug: "code-review", title: "Рев'ю коду", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
        { slug: "formal-verification", title: "Формальна верифікація", status: "done", levels: ["basic", "detailed"], origin: "expansion-2026-06-22" },
        { slug: "design-by-contract", title: "Проєктування за контрактом", status: "done", levels: ["basic", "detailed"], origin: "expansion-2026-06-22" },
        { slug: "error-codes-vs-exceptions", title: "Коди помилок проти винятків", status: "done", levels: ["basic", "detailed"], origin: "expansion-2026-06-22" },
        { slug: "loop-invariants", title: "Інваріанти циклу", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
        { slug: "behavioral-subtyping", title: "Поведінкова підтипізація", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
      ] },
    { slug: "embedded-systems", title: "Вбудовані системи", scope: "Програмування мікроконтролерів і прошивок: периферія МК, реального часу (RTOS), тулчейни, драйвери, апаратна взаємодія.",
      topics: [
        { slug: "microcontroller", title: "Мікроконтролер", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.1", hist: [{ file: "hist-first-mcu.md", status: "done" }] },
        { slug: "memory-mapped-io", title: "Memory-mapped IO", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.3", proj: [{ file: "proj-reg-access.md", status: "done" }] },
        { slug: "clock-power", title: "Тактування й живлення", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.4", comp: [{ file: "comp-crystal.md", status: "done" }], math: [{ file: "math-clock-tree.md", status: "done" }] },
        { slug: "esp32-architecture", title: "Архітектура ESP32", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.5", hist: [{ file: "hist-esp.md", status: "done" }], comp: [{ file: "comp-devkit.md", status: "done" }] },
        { slug: "esp32-vs-8bit", title: "ESP32 проти 8-біт", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.6", hist: [{ file: "hist-8051.md", status: "done" }], math: [{ file: "math-benchmarks.md", status: "done" }] },
        { slug: "esp32-family", title: "Сімейство ESP32", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.7", hist: [{ file: "hist-riscv.md", status: "done" }] },
        { slug: "reset-causes", title: "Причини reset", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-esp32#4.1.8", comp: [{ file: "comp-brownout.md", status: "done" }] },
        { slug: "flashing", title: "Прошивка у Flash", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.5", proj: [{ file: "proj-flash-protocol.md", status: "done" }] },
        { slug: "bootloader", title: "Bootloader", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.6", comp: [{ file: "comp-strapping.md", status: "done" }] },
        { slug: "baremetal-vs-framework", title: "Голе залізо vs фреймворк", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.7", hist: [{ file: "hist-arduino.md", status: "done" }] },
        { slug: "jtag-swd-tools", title: "Serial, JTAG/SWD", status: "done", origin: "embedded/block-4-mcu-esp32/toolchain#4.2.8", comp: [{ file: "comp-debug-probes.md", status: "done" }], proj: [{ file: "proj-binary-logging.md", status: "done" }, { file: "proj-logging.md", status: "done" }] },
        { slug: "why-persist", title: "Навіщо зберігати", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.1", hist: [{ file: "hist-flash.md", status: "done" }], proj: [{ file: "proj-flash-ring-log.md", status: "done" }] },
        { slug: "flash-internals", title: "Flash зсередини", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.2" },
        { slug: "wear-leveling", title: "Wear leveling", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.3", math: [{ file: "math-endurance.md", status: "done" }] },
        { slug: "partition-table", title: "Таблиця розділів", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.4", proj: [{ file: "proj-partition-table.md", status: "done" }] },
        { slug: "nvs", title: "NVS", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.5", proj: [{ file: "proj-nvs-internals.md", status: "done" }] },
        { slug: "write-integrity", title: "Цілісність запису", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.7", proj: [{ file: "proj-atomic-config.md", status: "done" }] },
        { slug: "ota-slots", title: "OTA-слоти", status: "done", origin: "embedded/block-4-mcu-esp32/persistent-storage#4.3.8" },
        { slug: "gpio-registers", title: "GPIO-регістри", status: "done", origin: "embedded/block-4-mcu-esp32/gpio#4.4.7", proj: [{ file: "proj-bitbang.md", status: "done" }] },
        { slug: "module-model", title: "Модель модуля", status: "done", origin: "embedded/block-4-mcu-esp32/gpio#4.4.8", proj: [{ file: "proj-key-matrix.md", status: "done" }] },
        { slug: "interrupts", title: "Переривання", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/interrupts#4.5.1", hist: [{ file: "hist-interrupt.md", status: "done" }], comp: [{ file: "comp-int-pin.md", status: "done" }], proj: [{ file: "proj-spsc-ring.md", status: "done" }] },
        { slug: "isr", title: "ISR", status: "done", origin: "embedded/block-4-mcu-esp32/interrupts#4.5.3", proj: [{ file: "proj-deferred-work.md", status: "done" }, { file: "proj-reentrancy.md", status: "done" }] },
        { slug: "interrupt-priorities", title: "Пріоритети переривань", status: "done", origin: "embedded/block-4-mcu-esp32/interrupts#4.5.4", hist: [{ file: "hist-apollo.md", status: "done" }], math: [{ file: "math-latency.md", status: "done" }] },
        { slug: "polling-vs-interrupts", title: "Polling vs переривання", status: "done", origin: "embedded/block-4-mcu-esp32/interrupts#4.5.7", math: [{ file: "math-isr-budget.md", status: "done" }] },
        { slug: "timer-counter", title: "Таймер-лічильник", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/timers#4.6.1", hist: [{ file: "hist-quartz.md", status: "done" }], math: [{ file: "math-prescaler.md", status: "done" }] },
        { slug: "timer-overflow", title: "Період і переповнення", status: "done", origin: "embedded/block-4-mcu-esp32/timers#4.6.2", math: [{ file: "math-unsigned-wrap.md", status: "done" }] },
        { slug: "capture-compare", title: "Захоплення й порівняння", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/timers#4.6.3", proj: [{ file: "proj-input-capture.md", status: "done" }] },
        { slug: "millis-micros", title: "Точний час", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/timers#4.6.4", proj: [{ file: "proj-millis-patterns.md", status: "done" }] },
        { slug: "nonblocking-time", title: "Неблокуючий час", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/timers#4.6.5", proj: [{ file: "proj-coop-scheduler.md", status: "done" }] },
        { slug: "periodic-scheduling", title: "Періодичні події", status: "done", origin: "embedded/block-4-mcu-esp32/timers#4.6.6", proj: [{ file: "proj-timer-wheel.md", status: "done" }] },
        { slug: "watchdog", title: "Watchdog", status: "done", origin: "embedded/block-4-mcu-esp32/timers#4.6.7", comp: [{ file: "comp-esp32-watchdogs.md", status: "done" }], proj: [{ file: "proj-watchdog-feed.md", status: "done" }] },
        { slug: "rtc", title: "RTC", status: "done", origin: "embedded/block-4-mcu-esp32/timers#4.6.8", hist: [{ file: "hist-y2k-2038.md", status: "done" }], comp: [{ file: "comp-rtc-module.md", status: "done" }], math: [{ file: "math-calendar-math.md", status: "done" }] },
        { slug: "pwm", title: "ШІМ", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.1", hist: [{ file: "hist-dimmer.md", status: "done" }], comp: [{ file: "comp-buzzer.md", status: "done" }], math: [{ file: "math-pwm-spectrum.md", status: "done" }] },
        { slug: "hardware-pwm", title: "Апаратний PWM", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.2", proj: [{ file: "proj-pwm-alignment.md", status: "done" }] },
        { slug: "pwm-resolution", title: "Шпаруватість і роздільність", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/pwm-dac#4.7.3", math: [{ file: "math-freq-resolution.md", status: "done" }] },
        { slug: "double-buffering", title: "Подвійна буферизація", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.4", math: [{ file: "math-buffer-sizing.md", status: "done" }], proj: [{ file: "proj-ring-buffer.md", status: "done" }] },
        { slug: "dma-adc", title: "DMA + АЦП", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.5" },
        { slug: "dma-spi-i2s", title: "DMA + SPI/I2S", status: "done", origin: "embedded/block-4-mcu-esp32/dma#4.9.6", hist: [{ file: "hist-soundblaster.md", status: "done" }], comp: [{ file: "comp-i2s-mic.md", status: "done" }, { file: "comp-spi-display.md", status: "done" }] },
        { slug: "super-loop", title: "Super-loop", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.1", hist: [{ file: "hist-time-sharing.md", status: "done" }], proj: [{ file: "proj-cooperative-loop.md", status: "done" }] },
        { slug: "super-loop-limits", title: "Межі super-loop", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.2" },
        { slug: "freertos", title: "FreeRTOS", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.5", hist: [{ file: "hist-freertos.md", status: "done" }], comp: [{ file: "comp-dual-core.md", status: "done" }] },
        { slug: "realtime-determinism", title: "Детермінованість", status: "done", origin: "embedded/block-4-mcu-esp32/execution-rtos#4.10.8", math: [{ file: "math-rate-monotonic.md", status: "done" }] },
        { slug: "mcu-selection", title: "Вибір МК", status: "recheck", origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.1", hist: [{ file: "hist-arm.md", status: "recheck" }] },
        { slug: "avr", title: "AVR-клас", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.2", hist: [{ file: "hist-avr.md", status: "done" }], comp: [{ file: "comp-uno-nano.md", status: "done" }] },
        { slug: "cortex-m", title: "ARM Cortex-M", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.3" },
        { slug: "stm32", title: "STM32-клас", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.4", comp: [{ file: "comp-stm32-boards.md", status: "done" }] },
        { slug: "rp2040-pio", title: "RP2040 і PIO", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.5", hist: [{ file: "hist-rp2040.md", status: "done" }], comp: [{ file: "comp-pico-board.md", status: "done" }], proj: [{ file: "proj-pio.md", status: "done" }] },
        { slug: "nrf-radio-mcu", title: "nRF-клас", status: "done", origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.6", comp: [{ file: "comp-nrf-modules.md", status: "done" }] },
        { slug: "mcu-ecosystem", title: "Екосистема МК", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.7", proj: [{ file: "proj-portability.md", status: "done" }] },
        { slug: "mcu-checklist", title: "Чеклист вибору МК", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/mcu-landscape#4.11.8", math: [{ file: "math-decision-matrix.md", status: "done" }] },
        { slug: "battery-budget", title: "Бюджет батареї", status: "done", origin: "embedded/block-4-mcu-esp32/low-power#4.13.1", hist: [{ file: "hist-pacemaker.md", status: "done" }], math: [{ file: "math-battery-math.md", status: "done" }] },
        { slug: "current-paths", title: "Куди тече струм", status: "done", origin: "embedded/block-4-mcu-esp32/low-power#4.13.2", hist: [{ file: "hist-voyager.md", status: "done" }], comp: [{ file: "comp-sensor-standby.md", status: "done" }] },
        { slug: "sleep-modes", title: "Режими сну", status: "done", levels: ["basic"], origin: "embedded/block-4-mcu-esp32/low-power#4.13.3" },
        { slug: "wakeup-sources", title: "Джерела пробудження", status: "done", origin: "embedded/block-4-mcu-esp32/low-power#4.13.4", comp: [{ file: "comp-wake-hw.md", status: "done" }] },
        { slug: "ulp-coprocessor", title: "ULP-співпроцесор", status: "done", origin: "embedded/block-4-mcu-esp32/low-power#4.13.5", proj: [{ file: "proj-ulp-program.md", status: "done" }] },
        { slug: "duty-cycle-current", title: "Цикл і середній струм", status: "done", origin: "embedded/block-4-mcu-esp32/low-power#4.13.6", proj: [{ file: "proj-energy-budget-table.md", status: "done" }] },
        { slug: "rtc-memory", title: "RTC-память", status: "done", origin: "embedded/block-4-mcu-esp32/low-power#4.13.9" },
        { slug: "why-debugger", title: "Навіщо відлагоджувач", status: "done", origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.1", hist: [{ file: "hist-jtag.md", status: "done" }] },
        { slug: "swd-jtag-internals", title: "SWD і JTAG зсередини", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.2" },
        { slug: "breakpoints-watchpoints", title: "Брейкпоінти й вотчпоінти", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.3" },
        { slug: "openocd-gdb", title: "OpenOCD і GDB", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.4" },
        { slug: "step-debugging", title: "Кроком по коду", status: "recheck", origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.5" },
        { slug: "hardfault", title: "Розбір HardFault", status: "done", origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.6" },
        { slug: "core-dump", title: "Посмертний аналіз", status: "done", origin: "embedded/block-4-mcu-esp32/debug-deep#4.14.7", proj: [{ file: "proj-coredump-workflow.md", status: "done" }] },
        { slug: "safe-mode", title: "Безпечний стан", status: "done", origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.4", hist: [{ file: "hist-fail-safe.md", status: "done" }] },
        { slug: "reboot-strategy", title: "Перезавантаження", status: "done", origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.5", hist: [{ file: "hist-restart-recovery.md", status: "done" }] },
        { slug: "reboot-counter", title: "Лічильник перезавантажень", status: "done", origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.6", proj: [{ file: "proj-robust-counter.md", status: "done" }] },
        { slug: "brownout", title: "Brown-out", status: "done", origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.7" },
        { slug: "graceful-degradation", title: "Деградація з гідністю", status: "done", origin: "embedded/block-4-mcu-esp32/fault-tolerant#4.15.8", proj: [{ file: "proj-health-aggregator.md", status: "done" }] },
        { slug: "stream-parser", title: "Розбір потоку", status: "done", origin: "embedded/block-6-comms-radio/uart#6.1.7" },
        { slug: "ota-update", title: "OTA-оновлення", status: "done", levels: ["basic"], origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.9" },
        { slug: "ble-gatt-practice", title: "BLE-практика", status: "empty", origin: "embedded/block-6-comms-radio/wifi-bluetooth#6.5.12" },
        { slug: "mavlink-commands", title: "Команди MAVLink", status: "done", origin: "embedded/block-6-comms-radio/telemetry-mavlink#6.9.6", proj: [{ file: "proj-command-ack-loop.md", status: "done" }] },
        { slug: "autonomous-system", title: "Автономна система", status: "done", origin: "embedded/block-7-systems/architecture-flight-controller#7.1.1", hist: [{ file: "hist-ardupilot.md", status: "done" }], proj: [{ file: "proj-control-loop.md", status: "done" }] },
        { slug: "flight-controller", title: "Політний контролер", status: "done", levels: ["basic"], origin: "embedded/block-7-systems/architecture-flight-controller#7.1.2" },
        { slug: "ardupilot-layers", title: "Шари ArduPilot", status: "done", origin: "embedded/block-7-systems/architecture-flight-controller#7.1.3", proj: [{ file: "proj-hal-backend.md", status: "done" }] },
        { slug: "params-gcs", title: "Параметри й GCS", status: "done", origin: "embedded/block-7-systems/architecture-flight-controller#7.1.4", proj: [{ file: "proj-param-protocol.md", status: "done" }] },
        { slug: "fc-vs-companion", title: "Контролер vs комп'ютер", status: "recheck", origin: "embedded/block-7-systems/architecture-flight-controller#7.1.5" },
        { slug: "redundancy", title: "Надлишковість", status: "done", origin: "embedded/block-7-systems/flight-components#7.3.7", hist: [{ file: "hist-tmr.md", status: "done" }] },
        { slug: "video-latency", title: "Затримка відео", status: "done", levels: ["basic", "detailed"], origin: "embedded/block-7-systems/video-signals-1#7.7.7" },
        { slug: "ethernet-on-mcu", title: "Ethernet на МК", status: "empty", origin: "embedded/undefined#6.10.9" },
        { slug: "manual-stabilized-modes", title: "Ручні режими", status: "empty", origin: "embedded/undefined#7.6.1" },
        { slug: "position-modes", title: "Режими з позицією", status: "empty", origin: "embedded/undefined#7.6.2" },
        { slug: "arming-checks", title: "Arming-перевірки", status: "empty", origin: "embedded/undefined#7.6.3" },
        { slug: "failsafe", title: "Failsafe", status: "done", levels: ["basic"], origin: "embedded/undefined#7.6.5" },
        { slug: "failure-priorities", title: "Пріоритети відмов", status: "empty", origin: "embedded/undefined#7.6.6" },
        { slug: "mode-state-machine", title: "Автомат режимів", status: "empty", origin: "embedded/undefined#7.6.7" },
        { slug: "first-bringup", title: "Перший запуск", status: "empty", origin: "embedded/undefined#7.6.8" },
        { slug: "realtime-vs-compute", title: "Дві ролі на борту", status: "empty", origin: "embedded/undefined#7.11.1" },
        { slug: "trust-boundaries-failsafe", title: "Межі довіри", status: "empty", origin: "embedded/undefined#7.11.5" },
        { slug: "dynamics-dependent-failsafe", title: "Failsafe за динамікою", status: "empty", origin: "embedded/undefined#7.12.6" },
        { slug: "capstone-task", title: "Капстоун", status: "empty", origin: "embedded/undefined#7.14.1" },
        { slug: "firmware-realtime-loop", title: "Прошивка реального часу", status: "empty", origin: "embedded/undefined#7.14.4" },
        { slug: "preflight-safety", title: "Безпека до польоту", status: "empty", origin: "embedded/undefined#7.14.6" },
        { slug: "end-to-end-mission", title: "Місія від початку до кінця", status: "empty", origin: "embedded/undefined#7.14.7" },
        { slug: "toolchain", title: "Тулчейн", status: "empty" },
        { slug: "timers", title: "Таймери", status: "empty" },
        { slug: "trace-itm-swo", title: "Трасування: ITM, SWO, ETM", status: "done", levels: ["basic", "detailed"], origin: "expansion-2026-06-22" },
        { slug: "semihosting", title: "Семіхостинг", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
        { slug: "debug-vscode", title: "Налагодження у VS Code", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
        { slug: "esp32-p4", title: "ESP32-P4", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
        { slug: "rtt", title: "RTT (Real-Time Transfer)", status: "done", levels: ["basic"], origin: "expansion-2026-06-22" },
      ] },
  ]
});
