/* manifest — «Програмування» (тип "book"). Схема — AUTHORING.md §2 (v4). */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "programming", title: "Програмування",
  sections: [
    { slug: "computer-architecture", title: "Архітектура", scope: "Будова обчислювальної машини: модель фон Неймана й Гарвардська, набори інструкцій, конвеєр, ієрархія пам'яті, переривання.",
      topics: [
        { slug: "overflow-wraparound", title: "Переповнення", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-ariane5.md", status: "done" }], proj: [{ file: "proj-overflow-checks.md", status: "done" }] },
        { slug: "fixed-point", title: "Фіксована кома", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-patriot.md", status: "done" }], proj: [{ file: "proj-cordic.md", status: "done" }, { file: "proj-fixed-point.md", status: "done" }] },
        { slug: "floating-point", title: "Плаваюча кома", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-ieee754.md", status: "done" }], proj: [{ file: "proj-float-compare.md", status: "done" }] },
        { slug: "bits-bytes-endianness", title: "Біти й порядок байтів", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-sensor-byte-order.md", status: "done" }], proj: [{ file: "proj-serialization.md", status: "done" }] },
        { slug: "ascii-utf8", title: "ASCII і UTF-8", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-utf8-diner.md", status: "done" }], proj: [{ file: "proj-utf8-decoder.md", status: "done" }] },
        { slug: "what-is-processor", title: "Що таке процесор", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-babbage-lovelace.md", status: "done" }, { file: "hist-von-neumann.md", status: "done" }] },
        { slug: "processor-parts", title: "Складові процесора", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "fetch-decode-execute", title: "Цикл виконання", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-toy-cpu-emulator.md", status: "done" }] },
        { slug: "isa", title: "Набір інструкцій", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-riscv.md", status: "done" }], comp: [{ file: "comp-isa-in-boards.md", status: "done" }], proj: [{ file: "proj-reading-disassembly.md", status: "done" }] },
        { slug: "clock-frequency", title: "Частота процесора", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-megahertz-myth.md", status: "done" }], math: [{ file: "math-performance-math.md", status: "done" }] },
        { slug: "pipeline", title: "Конвеєр", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-pipeline-hazards.md", status: "done" }] },
        { slug: "cache", title: "Кеш", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-cache-friendly-code.md", status: "done" }] },
        { slug: "mcu-blocks", title: "Складові МК", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-offload-to-peripheral.md", status: "done" }] },
        { slug: "interrupt-vector", title: "Контролер і вектор", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-int-controllers.md", status: "done" }] },
        { slug: "dma-problem", title: "Проблема потоку даних", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-dma-channels.md", status: "done" }], math: [{ file: "math-throughput.md", status: "done" }] },
        { slug: "dma-controller", title: "DMA-контролер", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-memcpy-vs-dma.md", status: "done" }] },
        { slug: "dma-channels", title: "Канали й дескриптори", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-descriptors.md", status: "done" }] },
        { slug: "sign-extension", title: "Знакове розширення", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "integer-types-c", title: "Цілі типи в C/C++", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "cache-coherence", title: "Когерентність кешів", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-illinois-mesi.md", status: "done" }], proj: [{ file: "proj-false-sharing.md", status: "done" }] },
        { slug: "tlb", title: "TLB — кеш адресного перекладу", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-atlas.md", status: "done" }] },
        { slug: "power-wall", title: "Стіна потужності й темний кремній", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-power-wall-2004.md", status: "done" }], math: [{ file: "math-dennard-scaling.md", status: "done" }] },
        { slug: "dvfs", title: "Динамічне масштабування напруги і частоти (DVFS)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-speedstep-powernow.md", status: "done" }] },
        { slug: "dma-channels-gdma", title: "GDMA: загальний пул каналів", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "bus-arbitration", title: "Арбітраж шини", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-daisy-chain.md", status: "done" }], math: [{ file: "math-metastability.md", status: "done" }] },
        { slug: "cache-coherency-dma", title: "Когерентність кеша і DMA", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-dma-origins.md", status: "done" }] },
        { slug: "control-unit", title: "Пристрій керування", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-microprogramming.md", status: "done" }], proj: [{ file: "proj-control-decoder.md", status: "done" }] },
        { slug: "cpu-exception-handling", title: "Обробка виключень у процесорі", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "fpu", title: "Блок дробових чисел (FPU)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-fpu.md", status: "done" }] },
        { slug: "half-precision", title: "Напівточність: float16 і bfloat16", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-half-precision.md", status: "done" }], proj: [{ file: "proj-half-precision-convert.md", status: "done" }] },
        { slug: "calling-convention", title: "Угода про виклик (ABI)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-abi-wars.md", status: "done" }] },
        { slug: "microcode", title: "Мікрокод", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "ahb-apb-bus", title: "Шинна ієрархія AHB/APB у Cortex-M", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-amba.md", status: "done" }] },
        { slug: "integer-promotion", title: "Просування цілих типів у C/C++", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "saturating-arithmetic", title: "Насичувальна арифметика", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-mmx-dsp.md", status: "done" }], proj: [{ file: "proj-saturate-clamp.md", status: "done" }] },
        { slug: "out-of-order-execution", title: "Позачергове виконання", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-spectre-meltdown.md", status: "done" }] },
        { slug: "superscalar", title: "Суперскалярна архітектура", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-superscalar.md", status: "done" }] },
        { slug: "forwarding-bypassing", title: "Forwarding і bypassing", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-forwarding.md", status: "done" }] },
        { slug: "multicore", title: "Багатоядерні процесори", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-multicore-turn.md", status: "done" }] },
        { slug: "control-unit-design", title: "Пристрій керування: hardwired і мікропрограмний", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-microcode-family.md", status: "done" }] },
        { slug: "branch-prediction", title: "Передбачення переходів", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-branch-prediction.md", status: "done" }, { file: "hist-spectre.md", status: "done" }], proj: [{ file: "proj-branchless.md", status: "done" }] },
        { slug: "dsp-architecture", title: "Архітектура DSP-процесора", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-first-dsp.md", status: "done" }], proj: [{ file: "proj-fir-mac.md", status: "done" }] },
        { slug: "address-space-separation", title: "Розділення адресних просторів", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-harvard-mark.md", status: "done" }] },
        { slug: "bus-matrix", title: "Матриця шин (bus matrix)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-amba.md", status: "done" }] },
        { slug: "instruction-cycle-detail", title: "Цикл виконання інструкції: стадії та конвеєр", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-risc-pipeline.md", status: "done" }], proj: [{ file: "proj-pipeline-sim.md", status: "done" }] },
        { slug: "isa-encoding", title: "Кодування інструкцій: як команда стає числом", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-thumb.md", status: "done" }], math: [{ file: "math-immediate-split.md", status: "done" }] },
        { slug: "port-mapped-io", title: "Port-mapped IO (IN/OUT)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-io-instructions.md", status: "done" }] },
        { slug: "memory-barriers", title: "Memory barriers (DMB/DSB/ISB)", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-flash-barriers.md", status: "done" }] },
        { slug: "mmu-address-window", title: "MMU і вікна зовнішньої пам'яті", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-bank-switching-mmu.md", status: "done" }], proj: [{ file: "proj-bank-window.md", status: "done" }] },
        { slug: "cache-coherence-protocol", title: "Протокол когерентності кешу", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-moesi-mesif.md", status: "done" }] },
        { slug: "xip-memory-mapped-flash", title: "XIP: виконання коду з флеші на місці", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "virtual-memory", title: "Віртуальна пам'ять", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-atlas.md", status: "done" }] },
        { slug: "memory-alignment", title: "Вирівнювання даних у пам'яті", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-alignment-hardware.md", status: "done" }] },
      ] },
    { slug: "languages", title: "Мови", scope: "Парадигми, дизайн і трансляція мов: імперативна/об'єктна/функційна/логічна/реактивна моделі, синтаксис, системи типів, метапрограмування, лексика, парсинг, IR, оптимізація, генерація коду, рантайми.",
      topics: [
        { slug: "compilation", title: "Компіляція", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-grace-hopper.md", status: "done" }] },
        { slug: "compiler-stages", title: "Стадії компілятора", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-gcc.md", status: "done" }], proj: [{ file: "proj-optimizer.md", status: "done" }] },
        { slug: "linking", title: "Лінкування", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-linker-errors.md", status: "done" }] },
        { slug: "volatile", title: "volatile", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-volatile-asm.md", status: "done" }] },
        { slug: "strict-aliasing", title: "Суворе аліасування (strict aliasing)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-gcc-strict-aliasing.md", status: "done" }], proj: [{ file: "proj-restrict.md", status: "done" }] },
        { slug: "bytecode-vm", title: "Байткод і віртуальна машина", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-pcode-jvm.md", status: "done" }] },
        { slug: "zero-cost-abstractions", title: "Абстракції без витрат: шаблони й inline", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-zero-overhead.md", status: "done" }], proj: [{ file: "proj-monomorphization.md", status: "done" }] },
        { slug: "intermediate-representation", title: "Проміжне представлення (IR)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-uncol.md", status: "done" }] },
        { slug: "compiler-optimizations", title: "Оптимізації компілятора", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-frances-allen.md", status: "done" }] },
        { slug: "undefined-behavior", title: "Невизначена поведінка (UB)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-nasal-demons.md", status: "done" }], proj: [{ file: "proj-null-check-removal.md", status: "done" }] },
        { slug: "elf-format", title: "ELF-формат прошивки", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-elf-origin.md", status: "done" }], comp: [{ file: "comp-dwarf.md", status: "done" }] },
        { slug: "abi-calling-convention", title: "ABI та calling convention", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-cpp-abi.md", status: "done" }], proj: [{ file: "proj-struct-packing.md", status: "done" }] },
        { slug: "llvm-clang", title: "LLVM і Clang", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-llvm-clang.md", status: "done" }] },
        { slug: "compiler-bootstrapping", title: "Самопідняття компілятора (bootstrapping)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-bootstrap-origins.md", status: "done" }, { file: "hist-trusting-trust.md", status: "done" }], proj: [{ file: "proj-gcc-bootstrap.md", status: "done" }], comp: [{ file: "comp-cross-compiler.md", status: "done" }, { file: "comp-reproducible-builds.md", status: "done" }] },
        { slug: "weak-symbols", title: "Слабкі символи", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "as-if-rule", title: "Правило «ніби» (as-if rule)", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-as-if.md", status: "done" }], proj: [{ file: "proj-as-if-defeat.md", status: "done" }] },
        { slug: "std-atomic", title: "std::atomic і порядок пам'яті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rust-ownership", title: "Модель власності Rust", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "unsigned-overflow", title: "Беззнакове переповнення і модульна арифметика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lexer-design", title: "Лексичний аналіз", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "tcl", title: "Tcl", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "systems", title: "Системи", scope: "Керування ресурсами й виконанням: процеси, планування, віртуальна й фізична пам'ять (стек, купа, алокатори, GC, покажчики), файлові системи, драйвери, потоки, синхронізація, моделі пам'яті, неблокувальність.",
      topics: [
        { slug: "memory-as-array", title: "Пам'ять як масив", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-core-memory.md", status: "done" }] },
        { slug: "memory-map", title: "Карта пам'яті", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-real-memory-map.md", status: "done" }] },
        { slug: "flash-vs-ram", title: "Flash і RAM", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-spi-flash-xip.md", status: "done" }] },
        { slug: "addresses-pointers", title: "Адреси й покажчики", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-heartbleed.md", status: "done" }], proj: [{ file: "proj-pointer-arithmetic.md", status: "done" }] },
        { slug: "stack-lifo", title: "Стек", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-stack-painting.md", status: "done" }], proj: [{ file: "proj-stack-watermark.md", status: "done" }] },
        { slug: "heap-dynamic-memory", title: "Купа", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-fragmentation.md", status: "done" }], proj: [{ file: "proj-block-pools.md", status: "done" }, { file: "proj-toy-allocator.md", status: "done" }] },
        { slug: "stack-overflow", title: "Переповнення стека", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "comp-history-mpu.md", status: "done" }, { file: "hist-morris-worm.md", status: "done" }], comp: [{ file: "comp-mpu.md", status: "done" }] },
        { slug: "firmware-image", title: "Образ прошивки", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-image-checksums.md", status: "done" }], proj: [{ file: "proj-firmware-version.md", status: "done" }, { file: "proj-map-file.md", status: "done" }, { file: "proj-size-opt.md", status: "done" }] },
        { slug: "c-runtime", title: "C-рантайм", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-newlib-syscalls.md", status: "done" }] },
        { slug: "flash-filesystems", title: "Файлові системи Flash", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-fat.md", status: "done" }] },
        { slug: "atomicity-races", title: "Атомарність і гонки", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-therac25.md", status: "done" }], proj: [{ file: "proj-atomics-barriers.md", status: "done" }, { file: "proj-critical-sections.md", status: "done" }] },
        { slug: "dma-cache-races", title: "Пастки DMA", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-cache-dma.md", status: "done" }] },
        { slug: "tasks", title: "Задачі", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-fsm-instead.md", status: "done" }] },
        { slug: "scheduler", title: "Планувальник", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-tick-latency.md", status: "done" }], proj: [{ file: "proj-clz-bitmap.md", status: "done" }, { file: "proj-context-switch.md", status: "done" }] },
        { slug: "task-ipc", title: "Черги й семафори", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-pathfinder.md", status: "done" }], proj: [{ file: "proj-deadlock.md", status: "done" }, { file: "proj-priority-inheritance.md", status: "done" }, { file: "proj-queue-pattern.md", status: "done" }] },
        { slug: "task-stacks", title: "Стеки задач", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-no-free.md", status: "done" }, { file: "proj-stack-overflow.md", status: "done" }] },
        { slug: "persistent-storage", title: "Енергонезалежне зберігання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "alignment-hardware", title: "Вирівнювання даних: апаратні вимоги", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "context-switch", title: "Перемикання контексту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "priority-inversion", title: "Інверсія пріоритетів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "memory-ordering-barriers", title: "Упорядкування пам'яті та бар'єри", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "log-structured-storage", title: "Журнальне і log-structured сховище", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dynamic-linking", title: "Динамічне лінкування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "function-pointers", title: "Покажчики на функції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pointer-aliasing", title: "Аліасинг покажчиків і UB", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "volatile-qualifier", title: "Квалiфікатор volatile в C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "alignment", title: "Вирівнювання даних у пам'яті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "memory-ordering", title: "Упорядкованість пам'яті та барʼєри", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "torn-reads", title: "Розривне читання (torn read)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "weak-symbol", title: "Слабкий символ і перевизначення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "newlib", title: "newlib — libc для вбудованих систем", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cpp-static-init-order", title: "Static initialization order fiasco", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "startup-code", title: "Стартовий код (crt0)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "memory-allocator-internals", title: "Внутрішня будова алокатора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "garbage-collection", title: "Збирання сміття", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "volatile-keyword", title: "Ключове слово volatile і модель пам'яті компілятора", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "smp-scheduling", title: "SMP-планування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "event-groups", title: "Групи подій (event groups)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "task-notification", title: "Сповіщення задачі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "message-buffer", title: "Потокові буфери й буфери повідомлень", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "task-priorities", title: "Пріоритети задач", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "coroutines", title: "Корутини", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "peripherals", title: "Периферія", scope: "Порти, шини й контролери материнської плати та підключення зовнішніх пристроїв: PCIe, USB, BIOS/UEFI, ввід-вивід.",
      topics: [
        { slug: "spi-flash", title: "SPI-флеш", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "eeprom", title: "EEPROM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "microsd", title: "microSD", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "psram", title: "PSRAM", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-esp32-psram.md", status: "done" }] },
        { slug: "usb-overview", title: "USB огляд", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "hist-usb-birth.md", status: "done" }] },
        { slug: "usb-physical", title: "USB фізично", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-nrzi.md", status: "done" }] },
        { slug: "usb-enumeration", title: "Енумерація USB", basic: { status: "done" }, detailed: { status: "done" }, proj: [{ file: "proj-descriptors.md", status: "done" }] },
        { slug: "usb-endpoints", title: "Кінцеві точки USB", basic: { status: "done" }, detailed: { status: "done" }, proj: [{ file: "proj-frames.md", status: "done" }] },
        { slug: "usb-device-classes", title: "Класи USB", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-badusb.md", status: "done" }], proj: [{ file: "proj-hid-reports.md", status: "done" }] },
        { slug: "esp32-usb", title: "USB в ESP32", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "usb-power", title: "Живлення з USB", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "usb-host", title: "МК як USB-host", basic: { status: "done" }, detailed: { status: "done" }, comp: [{ file: "comp-otg.md", status: "done" }] },
        { slug: "tinyusb-device", title: "TinyUSB: пристрій", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "sfdp", title: "SFDP — автовиявлення флеші", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-hub", title: "USB-хаб: архітектура й топологія", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-otg", title: "USB OTG: зміна ролей", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-protocol-layer", title: "Протокольний рівень USB: пакети, токени, транзакції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "usb-suspend-resume", title: "USB Suspend і Resume: управління живленням шини", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "interrupt-driven-io", title: "Переривання від зовнішніх подій: EXTI і INT-входи", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "networking", title: "Мережі", scope: "Мережеве програмування: сокети, стек протоколів у коді, клієнт-сервер, RPC, прикладні сервіси.",
      topics: [
        { slug: "web-server-mcu", title: "Веб-сервер на МК", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "sockets-tcp-udp", title: "Сокети TCP/UDP", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "mavlink-stream-processing", title: "Обробка потоку", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-channel", title: "Канал MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mavlink-routing", title: "Роутинг MAVLink", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "multi-vehicle-one-station", title: "Кілька апаратів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "esp-hosted", title: "ESP-Hosted", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "socket-api", title: "API сокетів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lwip-internals", title: "Архітектура lwIP", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "databases", title: "Бази даних", scope: "Зберігання й запити даних: реляційна й нереляційні моделі, транзакції, індекси, рушії та оптимізатори.",
      topics: [
        { slug: "fat-filesystem", title: "Файлова система FAT", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "endianness", title: "Порядок байтів (endianness)", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "graphics", title: "Графіка", scope: "Програмний синтез зображень та інтерфейси: растеризація, трасування, шейдери, GPU, віконні системи, UI.",
      topics: [
        { slug: "operator-ergonomics", title: "Ергономіка оператора", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "security", title: "Безпека", scope: "Захист програм від атак: класи вразливостей, ізоляція, криптографія в коді, моделі загроз, аудит.",
      topics: [
        { slug: "secure-boot", title: "Secure boot", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-hash-signature.md", status: "done" }] },
        { slug: "aes-xts", title: "AES-XTS: шифрування блокових пристроїв", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "buffer-overflow-security", title: "Переповнення буфера як вразливість", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "software-engineering", title: "Інженерія", scope: "Проєктування, супровід і верифікація систем: архітектурні патерни, модульність, рефакторинг, процеси розробки, види тестів, фаззинг, формальні методи, неперервна інтеграція.",
      topics: [
        { slug: "static-analysis", title: "Статичний аналіз", basic: { status: "done" }, detailed: { status: "done" }, proj: [{ file: "proj-sanitizers.md", status: "done" }] },
        { slug: "profiling", title: "Профілювання", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "error-handling", title: "Жодна помилка не мовчить", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-ariane5.md", status: "done" }] },
        { slug: "assert-panic", title: "Assert і паніка", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "defensive-programming", title: "Захисне програмування", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "sitl-simulation", title: "SITL", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "gcs-as-system", title: "GCS як система", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "preflight-checklists", title: "Передпольотні чеклисти", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ground-station-logs", title: "Записи станції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fuzzing", title: "Фаззинг", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "code-review", title: "Рев'ю коду", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "formal-verification", title: "Формальна верифікація", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "design-by-contract", title: "Проєктування за контрактом", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "loop-invariants", title: "Інваріанти циклу", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "behavioral-subtyping", title: "Поведінкова підтипізація", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "hardware-abstraction-layer", title: "Шар абстрагування заліза (HAL)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "abstraction-principle", title: "Принцип абстракції в програмуванні", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "information-hiding", title: "Приховування інформації", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "covariance-contravariance", title: "Коваріантність і контраваріантність", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "interface-segregation", title: "Принцип розділення інтерфейсів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fagan-inspection", title: "Формальна інспекція (метод Фагана)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "code-metrics", title: "Метрики якості коду", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pair-programming", title: "Парне програмування", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "errno", title: "errno та POSIX-коди помилок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "weakest-precondition", title: "Найслабша передумова", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "address-sanitizer", title: "Санітайзери пам'яті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "lookup-table", title: "Таблиця замін (LUT)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "heisenbug", title: "Гейзенбаги та спостережницький ефект", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "code", title: "Код", scope: "Робота з кодом як артефактом: контроль версій, репозиторії, гілки, злиття, історія змін, спільна розробка.",
      topics: [
        { slug: "version-control", title: "Контроль версій і git", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
    { slug: "embedded-systems", title: "Вбудовані системи", scope: "Програмування мікроконтролерів і прошивок: периферія МК, реального часу (RTOS), тулчейни, драйвери, апаратна взаємодія.",
      topics: [
        { slug: "microcontroller", title: "Мікроконтролер", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-first-mcu.md", status: "done" }] },
        { slug: "memory-mapped-io", title: "Memory-mapped IO", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-reg-access.md", status: "done" }] },
        { slug: "clock-power", title: "Тактування й живлення", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-crystal.md", status: "done" }], math: [{ file: "math-clock-tree.md", status: "done" }] },
        { slug: "esp32-architecture", title: "Архітектура ESP32", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-esp.md", status: "done" }], comp: [{ file: "comp-devkit.md", status: "done" }] },
        { slug: "reset-causes", title: "Причини reset", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-brownout.md", status: "done" }] },
        { slug: "flashing", title: "Прошивка у Flash", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-flash-protocol.md", status: "done" }] },
        { slug: "bootloader", title: "Bootloader", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-strapping.md", status: "done" }] },
        { slug: "why-persist", title: "Навіщо зберігати", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-flash.md", status: "done" }], proj: [{ file: "proj-flash-ring-log.md", status: "done" }] },
        { slug: "flash-internals", title: "Flash зсередини", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "wear-leveling", title: "Wear leveling", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-endurance.md", status: "done" }] },
        { slug: "partition-table", title: "Таблиця розділів", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-partition-table.md", status: "done" }] },
        { slug: "nvs", title: "NVS", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-nvs-internals.md", status: "done" }] },
        { slug: "write-integrity", title: "Цілісність запису", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-atomic-config.md", status: "done" }] },
        { slug: "ota-slots", title: "OTA-слоти", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "gpio-registers", title: "GPIO-регістри", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-bitbang.md", status: "done" }] },
        { slug: "module-model", title: "Модель модуля", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-key-matrix.md", status: "done" }] },
        { slug: "interrupts", title: "Переривання", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-interrupt.md", status: "done" }], comp: [{ file: "comp-int-pin.md", status: "done" }], proj: [{ file: "proj-spsc-ring.md", status: "done" }] },
        { slug: "isr", title: "ISR", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-deferred-work.md", status: "done" }, { file: "proj-reentrancy.md", status: "done" }] },
        { slug: "interrupt-priorities", title: "Пріоритети переривань", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-apollo.md", status: "done" }], math: [{ file: "math-latency.md", status: "done" }] },
        { slug: "timer-counter", title: "Таймер-лічильник", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-quartz.md", status: "done" }], math: [{ file: "math-prescaler.md", status: "done" }] },
        { slug: "timer-overflow", title: "Період і переповнення", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-unsigned-wrap.md", status: "done" }] },
        { slug: "capture-compare", title: "Захоплення й порівняння", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-input-capture.md", status: "done" }] },
        { slug: "millis-micros", title: "Точний час", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-millis-patterns.md", status: "done" }] },
        { slug: "nonblocking-time", title: "Неблокуючий час", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-coop-scheduler.md", status: "done" }] },
        { slug: "periodic-scheduling", title: "Періодичні події", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-timer-wheel.md", status: "done" }] },
        { slug: "watchdog", title: "Watchdog", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-esp32-watchdogs.md", status: "done" }], proj: [{ file: "proj-watchdog-feed.md", status: "done" }] },
        { slug: "rtc", title: "RTC", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-y2k-2038.md", status: "done" }], comp: [{ file: "comp-rtc-module.md", status: "done" }], math: [{ file: "math-calendar-math.md", status: "done" }] },
        { slug: "pwm", title: "ШІМ", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-dimmer.md", status: "done" }], comp: [{ file: "comp-buzzer.md", status: "done" }], math: [{ file: "math-pwm-spectrum.md", status: "done" }] },
        { slug: "hardware-pwm", title: "Апаратний PWM", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-pwm-alignment.md", status: "done" }] },
        { slug: "pwm-resolution", title: "Шпаруватість і роздільність", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-freq-resolution.md", status: "done" }] },
        { slug: "double-buffering", title: "Подвійна буферизація", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-buffer-sizing.md", status: "done" }], proj: [{ file: "proj-ring-buffer.md", status: "done" }] },
        { slug: "super-loop", title: "Super-loop", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-time-sharing.md", status: "done" }], proj: [{ file: "proj-cooperative-loop.md", status: "done" }] },
        { slug: "freertos", title: "FreeRTOS", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-freertos.md", status: "done" }], comp: [{ file: "comp-dual-core.md", status: "done" }] },
        { slug: "realtime-determinism", title: "Детермінованість", basic: { status: "done" }, detailed: { status: "pending" }, math: [{ file: "math-rate-monotonic.md", status: "done" }] },
        { slug: "avr", title: "AVR-клас", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-avr.md", status: "done" }], comp: [{ file: "comp-uno-nano.md", status: "done" }] },
        { slug: "cortex-m", title: "ARM Cortex-M", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "stm32", title: "STM32-клас", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-stm32-boards.md", status: "done" }] },
        { slug: "rp2040-pio", title: "RP2040 і PIO", basic: { status: "done" }, detailed: { status: "done" }, hist: [{ file: "hist-rp2040.md", status: "done" }], comp: [{ file: "comp-pico-board.md", status: "done" }], proj: [{ file: "proj-pio.md", status: "done" }] },
        { slug: "nrf-radio-mcu", title: "nRF-клас", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-nrf-modules.md", status: "done" }] },
        { slug: "mcu-ecosystem", title: "Екосистема МК", basic: { status: "done" }, detailed: { status: "empty" }, proj: [{ file: "proj-portability.md", status: "done" }] },
        { slug: "battery-budget", title: "Бюджет батареї", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-pacemaker.md", status: "done" }], math: [{ file: "math-battery-math.md", status: "done" }] },
        { slug: "current-paths", title: "Куди тече струм", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-voyager.md", status: "done" }], comp: [{ file: "comp-sensor-standby.md", status: "done" }] },
        { slug: "sleep-modes", title: "Режими сну", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "wakeup-sources", title: "Джерела пробудження", basic: { status: "done" }, detailed: { status: "pending" }, comp: [{ file: "comp-wake-hw.md", status: "done" }] },
        { slug: "ulp-coprocessor", title: "ULP-співпроцесор", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-ulp-program.md", status: "done" }] },
        { slug: "rtc-memory", title: "RTC-память", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "why-debugger", title: "Навіщо відлагоджувач", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-jtag.md", status: "done" }] },
        { slug: "swd-jtag-internals", title: "SWD і JTAG зсередини", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "breakpoints-watchpoints", title: "Брейкпоінти й вотчпоінти", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "step-debugging", title: "Кроком по коду", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "hardfault", title: "Розбір HardFault", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "safe-mode", title: "Безпечний стан", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-fail-safe.md", status: "done" }] },
        { slug: "reboot-strategy", title: "Перезавантаження", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-restart-recovery.md", status: "done" }] },
        { slug: "reboot-counter", title: "Лічильник перезавантажень", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-robust-counter.md", status: "done" }] },
        { slug: "brownout", title: "Brown-out", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "graceful-degradation", title: "Деградація з гідністю", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-health-aggregator.md", status: "done" }] },
        { slug: "stream-parser", title: "Розбір потоку", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "ota-update", title: "OTA-оновлення", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "ble-gatt-practice", title: "BLE-практика", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flight-controller", title: "Політний контролер", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "ardupilot-layers", title: "Шари ArduPilot", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-hal-backend.md", status: "done" }] },
        { slug: "params-gcs", title: "Параметри й GCS", basic: { status: "done" }, detailed: { status: "pending" }, proj: [{ file: "proj-param-protocol.md", status: "done" }] },
        { slug: "fc-vs-companion", title: "Контролер vs комп'ютер", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "redundancy", title: "Надлишковість", basic: { status: "done" }, detailed: { status: "pending" }, hist: [{ file: "hist-tmr.md", status: "done" }] },
        { slug: "video-latency", title: "Затримка відео", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "ethernet-on-mcu", title: "Ethernet на МК", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "manual-stabilized-modes", title: "Ручні режими", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "position-modes", title: "Режими з позицією", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "arming-checks", title: "Arming-перевірки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "failsafe", title: "Failsafe", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "failure-priorities", title: "Пріоритети відмов", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mode-state-machine", title: "Автомат режимів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "first-bringup", title: "Перший запуск", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "realtime-vs-compute", title: "Дві ролі на борту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "trust-boundaries-failsafe", title: "Межі довіри", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dynamics-dependent-failsafe", title: "Failsafe за динамікою", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "capstone-task", title: "Капстоун", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "firmware-realtime-loop", title: "Прошивка реального часу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "preflight-safety", title: "Безпека до польоту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "end-to-end-mission", title: "Місія від початку до кінця", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "toolchain", title: "Тулчейн", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "timers", title: "Таймери", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "trace-itm-swo", title: "Трасування: ITM, SWO, ETM", basic: { status: "done" }, detailed: { status: "done" } },
        { slug: "semihosting", title: "Семіхостинг", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "debug-vscode", title: "Налагодження у VS Code", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "esp32-p4", title: "ESP32-P4", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "rtt", title: "RTT (Real-Time Transfer)", basic: { status: "done" }, detailed: { status: "pending" } },
        { slug: "interrupt-affinity", title: "Прив'язка переривань до ядер", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nmi-exceptions", title: "NMI та апаратні винятки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pin-multiplexing", title: "Мультиплексування виводів МК", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "peripheral-clock-enable", title: "Тактування периферії: ввімкнення й тактові домени", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "sitl-simulator", title: "SITL: симулятор у контурі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ardupilot-mavlink-dispatch", title: "MAVLink: диспетчер і шари", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "virtual-dispatch-cpp", title: "Таблиця віртуальних методів C++", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "waypoint-navigation", title: "Навігація за маршрутними точками", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "avr-fuses", title: "Fuse-біти AVR", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "isp-programming", title: "ISP-програмування мікроконтролерів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bitbang-protocol", title: "Bit-bang протоколи на GPIO", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "elf-image", title: "ELF-образ", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "linker-script", title: "Лінкер-скрипт", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vector-table", title: "Таблиця векторів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pcnt-pulse-counter", title: "PCNT — апаратний лічильник імпульсів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rmt-peripheral", title: "RMT — периферія точних імпульсних послідовностей", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mcpwm-peripheral", title: "MCPWM — мотор-контрольний ШІМ ESP32", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dynamic-voltage-frequency-scaling", title: "Масштабування напруги й частоти (DVFS)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-domains", title: "Домени живлення в мікроконтролері", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "panic-handler-arch", title: "Архітектура обробника паніки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "stack-walking", title: "Розмотування стека: frame pointer і DWARF", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "heap-layout", title: "Структура динамічної пам'яті на MCU", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dap-protocol", title: "Debug Adapter Protocol", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "svd-format", title: "Формат SVD (System View Description)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rtos-debug-awareness", title: "Відлагодження RTOS: видимість задач", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "triple-buffering", title: "Потрійна буферизація", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "peak-current-budgeting", title: "Пікові струми та просідання живлення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wi-fi-power-modes", title: "Режими енергоощадності Wi-Fi", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "esp32-memory-map", title: "Карта пам'яті ESP32", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "gpio-matrix-internals", title: "GPIO matrix ESP32: внутрішня схема", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "esp32-s3-ai", title: "AI-прискорення в ESP32-S3: вектори й inference на краю мережі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "spiram-psram", title: "SPIRAM / PSRAM в мікроконтролерах: зовнішня RAM через SPI", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "risc-v-vector", title: "RISC-V векторні розширення", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mcu-power-modes", title: "Режими сну мікроконтролерів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "geofence", title: "Геозона (geofence) в автопілоті", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "limp-mode", title: "Кульгавий режим (limp mode)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-filesystem", title: "Файлові системи у Flash", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nor-flash-spi-protocol", title: "Протокол SPI NOR Flash", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-cell-types", title: "SLC, MLC, TLC, QLC: типи Flash-комірок", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "common-mode-failure", title: "Спільна за причиною відмова", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "freertos-heap", title: "Алокатори пам'яті FreeRTOS (heap_1–heap_5)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "task-states", title: "Автомат станів задачі", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "volatile-register", title: "volatile і компілятор в embedded C", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "health-monitor", title: "Монітор здоров'я пристрою", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dwt-etm-debug", title: "DWT і ETM: трасування Cortex-M", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pwm-deadtime", title: "Мертвий час і комплементарні виходи ШІМ", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pwm-phase-shift", title: "Зсув фаз між каналами ШІМ", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nvic-cortex-m", title: "NVIC Cortex-M", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "critical-sections", title: "Критичні секції", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "interrupt-latency", title: "Затримка переривання", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "fpu-context-isr", title: "FPU-стан у ISR", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "advanced-timer-deadtime", title: "Мертвий час у таймері: advanced-timer і захист від наскрізного струму", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "platformio", title: "PlatformIO: збірка під будь-який МК", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "vendor-lock-in", title: "Прив'язка до платформи (vendor lock-in)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "dma-arbitration", title: "Арбітраж DMA і конкуренція шини", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "harvard-vs-vonneumann", title: "Гарвардська і фон Нейманнівська архітектури", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "mcu-startup-sequence", title: "Boot-послідовність мікроконтролера: від скидання до main()", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "risc-vs-cisc-mcu", title: "RISC і CISC у мікроконтролерах", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "uptime-clock-sync", title: "Синхронізація uptime з реальним часом", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "driver-pattern", title: "Шаблон драйвера периферії", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "state-machine-embedded", title: "Автомат станів у прошивці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "nvs-encryption", title: "Шифрування NVS на ESP32", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ota-image-signing", title: "Підписування OTA-образу", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "delta-ota", title: "Дельта-оновлення прошивки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ap-param-storage", title: "Зберігання параметрів у флеші: AP_Param", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-encryption", title: "Шифрування Flash (Flash Encryption)", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wcrt-analysis", title: "Аналіз найгіршого часу відповіді", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "time-sharing-history", title: "Розподіл часу: від мейнфреймів до мікроконтролерів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wcet-analysis", title: "WCET-аналіз", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "priority-protocols", title: "Протоколи пріоритету", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ota-rollback", title: "Відкат OTA-прошивки", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "common-cause-failure", title: "Відмова від спільної причини", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "exception-handling-mcu", title: "Обробка винятків на МК", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "wake-stub", title: "Wake-stub: мінімальний код до повної ініціалізації", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "stm32-clock-tree", title: "Дерево тактування STM32", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "advanced-control-timer", title: "Advanced-control таймер", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "state-machine", title: "Машина станів", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "context-switching", title: "Перемикання контексту", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "clock-tree", title: "Тактове дерево MCU", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "timer-modes", title: "Режими лічення таймера", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "ulp-fsm-assembly", title: "ULP-FSM: асемблер і макро-DSL для класичного ESP32", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "power-domains-mcu", title: "Острівці живлення в мікроконтролері", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rtc-slow-fast-memory", title: "RTC-пам'ять: slow і fast, shared-symbols, карта адресного простору", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "rtc-gpio-domain", title: "RTC-GPIO домен", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "bad-block-management", title: "Управління бракованими блоками NAND", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "data-serialization", title: "Серіалізація даних", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "flash-wear-model", title: "Модель зношування Flash", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "backlash-compensation", title: "Компенсація люфту в прошивці", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "pwm-hardware-timer", title: "Апаратний таймер для PWM", basic: { status: "pending" }, detailed: { status: "empty" } },
        { slug: "cmsis", title: "CMSIS: стандартний інтерфейс ПЗ для Cortex-M", basic: { status: "pending" }, detailed: { status: "pending" } },
      ] },
  ]
});
