/* manifest — «Хімія» (тип "book"). Схема — AUTHORING.md §2 (v4). */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "book", slug: "chemistry", title: "Хімія",
  sections: [
    { slug: "inorganic-chemistry", title: "Неорганічна хімія", scope: "Будова, властивості й реакції елементів та сполук без вуглець-водневого скелета — від солей до координаційних комплексів.",
      topics: [
        { slug: "element", title: "Елемент", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "periodic-table", title: "Періодична таблиця", basic: { status: "done" }, detailed: { status: "empty" }, hist: [{ file: "periodic-table-h-mendeleev.md", status: "done" }] },
        { slug: "element-families", title: "Родини елементів", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "formulas", title: "Формули", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "valence", title: "Валентність", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "acids", title: "Кислоти", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "bases", title: "Основи", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "oxides", title: "Оксиди", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "salts", title: "Солі", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "inorganic-map", title: "Карта неорганіки", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "activity-corrosion", title: "Активність і іржа", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "elements-tour", title: "Елементи навколо", basic: { status: "done" }, detailed: { status: "empty" } },
      ] },
    { slug: "organic-chemistry", title: "Органічна хімія", scope: "Хімія сполук вуглецю: класи, функційні групи, механізми та методи синтезу молекул.",
      topics: [
        { slug: "carbon", title: "Карбон", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "hydrocarbons", title: "Вуглеводні", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "alcohols-acids", title: "Спирти і кислоти", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "esters-fats", title: "Естери і жири", basic: { status: "done" }, detailed: { status: "empty" } },
      ] },
    { slug: "physical-chemistry", title: "Фізична хімія", scope: "Фізичні закони, що керують речовиною й перетвореннями: термодинаміка, кінетика, рівновага та електрохімія.",
      topics: [
        { slug: "substances", title: "Речовини", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "mole", title: "Моль", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "reaction", title: "Реакція", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "equations", title: "Рівняння", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "reaction-types", title: "Типи реакцій", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "reaction-energy", title: "Енергія реакцій", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "combustion", title: "Горіння", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "reaction-rate", title: "Швидкість реакції", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "catalysts", title: "Каталізатори", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "equilibrium", title: "Рівновага", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "dissolution", title: "Розчинення", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "solubility", title: "Розчинність", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "ions-solution", title: "Іони в розчині", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "fixed-ratios", title: "Сталі відношення", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "mole-formulas", title: "Формули моля", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "mole-proportion", title: "Пропорція в молях", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "stoichiometry", title: "Стехіометрія", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "gas-volume", title: "Об'єм газу", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "excess-limiting", title: "Надлишок і нестача", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "product-yield", title: "Вихід продукту", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "electrode-potential", title: "Стандартний електродний потенціал і ряд активності", basic: { status: "pending" }, detailed: { status: "empty" } },
      ] },
    { slug: "theoretical-chemistry", title: "Теоретична хімія", scope: "Квантовий і обчислювальний опис атомів і молекул: рівняння, моделі та симуляції структури й реакційності.",
      topics: [
        { slug: "atoms-molecules", title: "Атоми й молекули", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "inside-atom", title: "Будова атома", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "why-bond", title: "Хімічний зв'язок", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "ionic-covalent", title: "Іонний і ковалентний", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "metallic-bond", title: "Металічний зв'язок", basic: { status: "done" }, detailed: { status: "empty" } },
      ] },
    { slug: "analytical-chemistry", title: "Аналітична хімія", scope: "Методи виявлення, ідентифікації та вимірювання кількості речовин у зразках.",
      topics: [
        { slug: "mixtures", title: "Суміші", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "ph-indicators", title: "pH та індикатори", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "mass-fraction", title: "Масова частка", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "element-fraction", title: "Частка елемента", basic: { status: "done" }, detailed: { status: "empty" } },
      ] },
    { slug: "biochemistry", title: "Біохімія", scope: "Хімічні процеси й молекули живих систем: метаболізм, ферменти та біополімери.",
      topics: [
        { slug: "carbohydrates", title: "Вуглеводи", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "fats-proteins", title: "Жири і білки", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "kitchen-chemistry", title: "Кухонна хімія", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "epilogue", title: "Куди далі", basic: { status: "update" }, detailed: { status: "empty" } },
      ] },
    { slug: "polymer-chemistry", title: "Полімери", scope: "Синтез, структура та властивості макромолекул і пластиків, побудованих із повторюваних ланок.",
      topics: [
        { slug: "polymers", title: "Полімери", basic: { status: "done" }, detailed: { status: "empty" } },
      ] },
    { slug: "solid-state-chemistry", title: "Твердотільна хімія", scope: "Хімія протяжних твердих тіл: структура кристалів, дефекти та функційні неорганічні матеріали.",
      topics: [
        { slug: "molecules-lattice", title: "Молекули чи ґратка", basic: { status: "done" }, detailed: { status: "empty" } },
        { slug: "structure-properties", title: "Структура і властивості", basic: { status: "done" }, detailed: { status: "empty" } },
      ] },
    { slug: "supramolecular-chemistry", title: "Супрамолекулярна хімія", scope: "Нековалентні взаємодії та самозбірка, що утримують молекули разом у більші ансамблі.",
      topics: [
      ] },
    { slug: "radiochemistry", title: "Радіохімія", scope: "Хімія радіоактивних елементів, ядерних перетворень та поведінки ізотопів.",
      topics: [
      ] },
    { slug: "geochemistry", title: "Геохімія", scope: "Розподіл і кругообіг хімічних елементів у Землі, її водах, атмосфері та породах.",
      topics: [
      ] },
  ]
});
