/* manifest */
(window.__BOOKS__ = window.__BOOKS__ || []).push({
  type: "reference", slug: "python", title: "Python",
  sections: [
    { slug: "objects", title: "Об'єкти й типи", scope: "Що таке значення в Python, як ім'я з ним пов'язане і які типи мова дає з коробки.",
      topics: [
        { slug: "everything-is-object", title: "Усе є об'єктом", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "names-and-binding", title: "Імена, прив'язка й посилання", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mutable-and-immutable", title: "Змінювані й незмінні об'єкти", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "is-operator", title: "Оператор is і тотожність об'єктів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "hashable-objects", title: "Хешовність об'єкта", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "truthiness", title: "Істинність об'єкта", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "int-arbitrary-precision", title: "Ціле необмеженої розрядності", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "float-precision", title: "float і межі його точності", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "str-unicode-model", title: "Рядок як послідовність код-пойнтів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "string-formatting", title: "f-рядки й специфікатори формату", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "bytes-and-memoryview", title: "bytes, bytearray і memoryview", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "list-type", title: "Список і ціна його операцій", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tuple-type", title: "Кортеж і розпакування", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dict-type", title: "Словник і його впорядкованість", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "set-type", title: "Множини set і frozenset", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "slicing", title: "Зрізи й від'ємні індекси", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "sorting-with-key", title: "Сортування з key і стабільність", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "copy-module", title: "Поверхнева й глибока копія", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "collections-module", title: "Контейнери з collections", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "datetime-and-timezones", title: "Дата, час і часові пояси", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "numeric-arrays", title: "Масиви чисел array і numpy", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "control-flow", title: "Потік виконання й винятки", scope: "Як виконується код і що відбувається, коли він відмовляється виконуватися далі.",
      topics: [
        { slug: "loops-and-else", title: "Цикли, break і else при циклі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "iteration-protocol", title: "Протокол ітерації", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "range-enumerate-zip", title: "range, enumerate і zip", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "comprehensions", title: "Спискові, словникові й множинні включення", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "unpacking-and-star", title: "Розпакування й зірочка", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "raising-and-catching", title: "Підняття й перехоплення винятків", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "exception-hierarchy", title: "Ієрархія вбудованих винятків", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "custom-exceptions", title: "Власні класи винятків", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "finally-and-cleanup", title: "finally й гарантоване прибирання", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "exception-chaining", title: "Ланцюг винятків і raise from", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "exception-groups", title: "Групи винятків і except*", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "context-managers", title: "Менеджери контексту й with", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "contextlib", title: "Контекст із генератора", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "match-statement", title: "match і зіставлення зі зразком", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "assert-statement", title: "assert і прапорець -O", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "eafp-vs-lbyl", title: "EAFP і LBYL", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "functions", title: "Функції й генератори", scope: "Як оголошується виклик, що він захоплює з собою і як одна функція перетворює іншу.",
      topics: [
        { slug: "function-definition", title: "Означення функції та її об'єкт", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "arguments-and-defaults", title: "Аргументи й значення за замовчуванням", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "star-args-kwargs", title: "*args і **kwargs", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "positional-only-keyword-only", title: "Позиційні-лише й іменовані-лише параметри", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "scopes-legb", title: "Області видимості, global і nonlocal", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "closure-cells", title: "Замикання й комірки", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "lambda-expression", title: "lambda і межі виразу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "decorators", title: "Декоратори", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "decorators-with-arguments", title: "Декоратори з аргументами й functools.wraps", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "functools-partial", title: "partial і зафіксовані аргументи", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "lru-cache", title: "Кешування виклику", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "generators", title: "Генератори й yield", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "generator-send-close", title: "send, throw і закриття генератора", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "yield-from", title: "yield from і делегування", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "genexpr", title: "Генераторні вирази й лінива обробка", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "recursion-limit", title: "Рекурсія й межа глибини", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "classes", title: "Класи й об'єктна модель", scope: "",
      topics: [
        { slug: "class-definition", title: "Оголошення класу й простір його імен", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "instance-vs-class-attributes", title: "Атрибути примірника й атрибути класу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "init-and-new", title: "\\_\\_init\\_\\_ і \\_\\_new\\_\\_", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "classmethod-staticmethod", title: "classmethod і staticmethod", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dunder-protocols", title: "Дандер-методи як протоколи мови", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "repr-and-str", title: "\\_\\_repr\\_\\_ і \\_\\_str\\_\\_", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "property-decorator", title: "Властивість замість гетера", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "descriptor-protocol", title: "Протокол дескриптора", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dunder-slots", title: "\\_\\_slots\\_\\_ і розмір примірника", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "inheritance-and-mro", title: "Спадкування й порядок розв'язання методів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "super-call", title: "super() і кооперативний виклик", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "abstract-base-classes", title: "Абстрактні базові класи", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "duck-typing", title: "Качина типізація", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dataclasses", title: "Класи-дані", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "enum-classes", title: "Enum, IntEnum і Flag", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "metaclasses", title: "Метакласи", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dynamic-attributes", title: "\\_\\_getattr\\_\\_ і динамічні атрибути", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "typing", title: "Підказки типів", scope: "",
      topics: [
        { slug: "annotations-basics", title: "Анотації і що з ними робить рантайм", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "builtin-generics", title: "Узагальнення вбудованих типів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "optional-and-union", title: "Optional, Union і оператор \\|", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "special-types", title: "Any, object і Never", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "typing-protocol", title: "Protocol і структурна типізація", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "typevar-and-generics", title: "TypeVar і власні узагальнені типи", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "callable-and-paramspec", title: "Callable і ParamSpec", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "typeddict-and-literal", title: "TypedDict, Literal і NewType", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mypy-checking", title: "Перевірка типів mypy", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "gradual-typing", title: "Поступова типізація наявного коду", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "runtime-annotations", title: "Анотації під час виконання", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pydantic-validation", title: "Валідація даних за анотаціями", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "interpreter", title: "Інтерпретатор CPython", scope: "Що насправді робить CPython, виконуючи код, і чим Python платить за свою зручність.",
      topics: [
        { slug: "cpython-execution-model", title: "Шлях від тексту до байткоду", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "bytecode-and-dis", title: "Байткод і модуль dis", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "object-layout", title: "Устрій об'єкта в пам'яті", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "refcount-and-cycle-gc", title: "Підрахунок посилань і збирач циклів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pymalloc-arenas", title: "Аллокатор pymalloc і повернення пам'яті", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "cpython-gil", title: "GIL у CPython", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "free-threaded-python", title: "Збірка без GIL", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "interpreter-startup", title: "Запуск інтерпретатора й час старту", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "attribute-lookup", title: "Ціна пошуку атрибута", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "performance-model", title: "Чому Python повільний і де саме", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "adaptive-interpreter-jit", title: "Спеціалізація й JIT у сучасному CPython", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "c-extensions", title: "Розширення на C і Python/C API", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ctypes-and-cffi", title: "ctypes і cffi", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "alternative-implementations", title: "PyPy, GraalPy та інші реалізації", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "python-versions-eol", title: "Версії Python, сумісність і кінець підтримки", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "files", title: "Файли й формати", scope: "",
      topics: [
        { slug: "open-and-file-objects", title: "open, режими й файловий об'єкт", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "text-vs-binary-mode", title: "Текстовий і бінарний режим", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "encodings-and-utf8", title: "Кодування, UTF-8 і помилки декодування", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pathlib", title: "Шлях як об'єкт", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "directory-walking", title: "Обхід дерева каталогів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "temp-files", title: "Тимчасові файли й каталоги", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "atomic-write", title: "Атомний запис і збереження на диск", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "shutil-operations", title: "Копіювання, переміщення й видалення дерев", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "large-file-streaming", title: "Читання великого файлу потоком", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "json-module", title: "Модуль json", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "json-custom-types", title: "Власні типи в JSON", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "csv-module", title: "CSV, діалекти й заголовок", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "toml-and-ini", title: "Конфігураційні формати TOML та INI", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "yaml-safety", title: "YAML і безпечне завантаження", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pickle-danger", title: "pickle і його небезпека", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "sqlite3-module", title: "Локальна база sqlite3", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "archives-zip-tar", title: "Архіви zip і tar", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "regex-module", title: "Регулярні вирази", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "xml-parsing", title: "Розбір XML з ElementTree", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tabular-analysis", title: "Таблиці й графіки для аналізу даних", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "binary", title: "Бінарні дані й послідовний порт", scope: "Байти, а не текст: як зібрати й розібрати пакет і як говорити з пристроєм на дроті.",
      topics: [
        { slug: "struct-module", title: "struct і пакування чисел у байти", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "endianness-in-struct", title: "Порядок байтів і вирівнювання у struct", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "bit-operations", title: "Бітові операції над цілими", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "int-bytes-conversion", title: "to_bytes і from_bytes", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "frame-parsing", title: "Кадрування байтового потоку", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "checksums-crc", title: "Контрольні суми й CRC", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pyserial-basics", title: "pyserial і параметри порту", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "serial-timeouts", title: "Таймаути й неповні кадри на порту", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "serial-port-discovery", title: "Пошук потрібного порту", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pymavlink", title: "pymavlink і діалекти MAVLink", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "telemetry-log-parsing", title: "Розбір журналів телеметрії", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "linux-gpio-i2c-spi", title: "GPIO, I²C і SPI з Python на одноплатнику", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "python-can", title: "CAN-шина з python-can", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "network", title: "Мережа й HTTP", scope: "",
      topics: [
        { slug: "socket-module", title: "Модуль socket і TCP-з'єднання", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "udp-datagrams", title: "UDP-датаграми й втрати", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "socket-timeouts", title: "Таймаути й неблокувальний сокет", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "requests-client", title: "HTTP-клієнт requests", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "sessions-and-pooling", title: "Сесія, пул з'єднань і keep-alive", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "retries-and-backoff", title: "Повтори й експоненційна витримка", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "auth-tokens", title: "Токени й заголовки автентифікації", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tls-certificates", title: "TLS і перевірка сертифікатів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "streaming-bodies", title: "Потокове передавання великих тіл", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "http-server-minimal", title: "Найпростіший HTTP-сервер", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "flask-and-fastapi", title: "Flask і FastAPI", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "websockets-python", title: "WebSocket-клієнт і сервер", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mqtt-paho", title: "MQTT з paho-mqtt", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "url-parsing", title: "Розбір URL і кодування параметрів", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "concurrency", title: "Паралельність і асинхронність", scope: "",
      topics: [
        { slug: "threading-basics", title: "Потоки в threading", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "when-threads-help", title: "Коли потоки прискорюють, а коли ні", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "locks-and-conditions", title: "Замки, RLock і умовні змінні", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "queue-module", title: "Черга між потоками", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "concurrent-futures", title: "Пули в concurrent.futures", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "multiprocessing-module", title: "Процеси замість потоків", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "ipc-between-processes", title: "Обмін даними між процесами", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "asyncio-event-loop", title: "Цикл подій asyncio", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "coroutines-and-await", title: "Корутини й await", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tasks-and-taskgroup", title: "Задачі, gather і TaskGroup", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "asyncio-cancellation", title: "Скасування задач і таймаути", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "blocking-in-async", title: "Блокувальний виклик у циклі подій", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "asyncio-streams", title: "Асинхронні сокети й сервери", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "subprocess-module", title: "Запуск чужої програми", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "subprocess-pipes", title: "Труби, буфери й затики", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "signals-and-shutdown", title: "Сигнали й коректне завершення", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "micropython", title: "MicroPython і CircuitPython", scope: "",
      topics: [
        { slug: "micropython-overview", title: "Що таке MicroPython", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-vs-cpython", title: "Чим MicroPython відрізняється від CPython", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-memory", title: "Пам'ять і купа на мікроконтролері", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-gc-pauses", title: "Збирач сміття й паузи", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-repl-flashing", title: "REPL, прошивання й файли на платі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-machine-module", title: "Піни, АЦП і ШІМ у модулі machine", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-buses", title: "I²C, SPI і UART у MicroPython", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-interrupts", title: "Переривання й обробники", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-ticks", title: "Час, затримки й переповнення ticks", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-network", title: "Мережа на ESP32", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-asyncio", title: "Асинхронність на мікроконтролері", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-power", title: "Сон і споживання", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "circuitpython", title: "CircuitPython і його модель", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "micropython-limits", title: "Де MicroPython не годиться", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "testing", title: "Тестування й налагодження", scope: "Як переконатися, що скрипт робить обіцяне, і як з'ясувати, чому не робить.* **16 тем*",
      topics: [
        { slug: "pytest-basics", title: "Тест як звичайна функція", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pytest-fixtures", title: "Фікстури й області їхньої дії", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pytest-parametrize", title: "Параметризовані тести", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mock-and-patch", title: "Мок і підміна залежності", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "fake-hardware-in-tests", title: "Фейковий порт і фейковий пристрій", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "test-isolation", title: "Ізоляція тесту від середовища", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "testing-async-code", title: "Тестування асинхронного коду", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "coverage-measurement", title: "Покриття коду й що воно не міряє", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "hypothesis-testing", title: "Тестування властивостями", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tests-in-ci", title: "Розкладка тестів і запуск у CI", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "logging-module", title: "Модуль logging", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "traceback-reading", title: "Читання трейсбека", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pdb-debugger", title: "Відлагоджувач pdb", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "profiling-cprofile", title: "Профілювання cProfile і timeit", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "tracemalloc-leaks", title: "tracemalloc і витік пам'яті", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "hang-diagnosis", title: "Діагностика зависання", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "packaging", title: "Модулі, пакети й середовища", scope: "Як код стає імпортовним, встановлюваним і відтворюваним на чужій машині.* **18 тем*",
      topics: [
        { slug: "module-object", title: "Модуль як об'єкт", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "import-machinery", title: "Механіка імпорту", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "sys-path", title: "sys.path і звідки він береться", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "packages-and-init", title: "Пакети й \\_\\_init\\_\\_.py", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "relative-imports", title: "Відносні імпорти", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "circular-imports", title: "Циклічні імпорти", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "main-and-dash-m", title: "\\_\\_main\\_\\_, -m і точка входу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "venv", title: "Віртуальне середовище", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pip-install", title: "pip і джерела пакетів", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "requirements-pinning", title: "requirements.txt і закріплення версій", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pyproject-toml", title: "Метадані проєкту в pyproject.toml", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "wheels-and-sdist", title: "sdist, wheel і бінарні колеса", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "dependency-conflicts", title: "Конфлікти версій залежностей", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "lock-files", title: "Замки залежностей і сучасні менеджери", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "linters-and-formatters", title: "Лінтер і форматувальник у проєкті", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "pyinstaller-freeze", title: "Заморожування застосунку в один файл", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "python-on-device", title: "Python на цільовому пристрої", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "system-python", title: "Системний Python і чому його не чіпають", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
    { slug: "pitfalls", title: "Пастки", scope: "Місця, де код робить не те, що очевидно з тексту, і де інтуїція з C систематично бреше.",
      topics: [
        { slug: "mutable-default-argument", title: "Змінюваний аргумент за замовчуванням", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "late-binding-in-loops", title: "Пізнє зв'язування замикань у циклі", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "mutating-while-iterating", title: "Зміна колекції під час обходу", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "float-equality", title: "Порівняння дробових чисел", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "interning-and-caching", title: "Кешування малих цілих і інтернування рядків", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "shadowing-stdlib-modules", title: "Файл з іменем стандартного модуля", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "broad-except", title: "Перехоплення всіх винятків", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "atomicity-and-races", title: "Що атомарне, а що ні", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "shell-injection-subprocess", title: "shell=True і лапки в аргументах", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "naive-datetime", title: "Наївний час без пояса", basic: { status: "empty" }, detailed: { status: "pending" } },
        { slug: "eval-untrusted-input", title: "eval, exec і чужі дані", basic: { status: "empty" }, detailed: { status: "pending" } },
      ] },
  ]
});
